const fs = require('fs');

const lmx_ta = {
  "screenTitle": "க்ஷேத்ர நேரலை",
  "liveNow": "தற்போது {{count}} நேரலையில்",
  "liveNow_one": "தற்போது {{count}} நேரலையில்",
  "liveNow_other": "தற்போது {{count}} நேரலையில்",
  "aiEnrichmentOff": "AI மேம்படுத்தல் முடக்கப்பட்டுள்ளது",
  "aiEnrichmentOn": "AI மேம்படுத்தல் செயலில் உள்ளது",
  "goLive": "நேரலை தொடங்கு",
  "filters": {
    "all": "அனைத்தும்",
    "liveNow": "தற்போதைய நேரலை",
    "replays": "மறு ஒளிபரப்புகள்",
    "verified": "சரிபார்க்கப்பட்டவை"
  },
  "empty": {
    "title": "உங்கள் வடிகட்டிகளுடன் எந்த நேரலையும் பொருந்தவில்லை",
    "subtitle": "நீங்களே முதல் நபராக இருங்கள் — இங்கிருந்து ஒளிபரப்ப நேரலை தொடங்கு என்பதை அழுத்தவும்."
  },
  "goLiveScreen": {
    "title": "நேரலை தொடங்கு",
    "detectingLocation": "இடத்தைக் கண்டறிகிறது…",
    "locationLocked": "இடம் பூட்டப்பட்டது — {{district}}, {{state}}",
    "approxLocation": "தோராயமான இடத்தைப் பயன்படுத்துகிறது",
    "camera": "கேமரா",
    "recordClip": "காணொளியை பதிவு செய்",
    "reRecord": "மீண்டும் பதிவு செய்",
    "clipRecorded": "காணொளி பதிவு செய்யப்பட்டது",
    "broadcastingAs": "இவ்வாறு ஒளிபரப்பப்படுகிறது",
    "independent": "சுயேச்சை",
    "neutralWatermark": "நடுநிலையான க்ஷேத்ர வாட்டர்மார்க்",
    "visibility": "பார்வைக்குட்பட்டவை",
    "alertDepartment": "அரசு துறைக்கு எச்சரிக்கை செய்",
    "alertDepartmentDesc": "உங்கள் நேரலை ஒளிபரப்பு தேர்ந்தெடுக்கப்பட்ட துறைகளுக்கு நேரடியாக அனுப்பப்படும்.",
    "category": "வகை",
    "tags": "குறியீடுகள் (காற்புள்ளியால் பிரிக்கப்பட்டவை)",
    "tagsPlaceholder": "எ.கா. சாலை, மேம்பாலம், சிக்னல்",
    "moderationBuffer": "மதிப்பாய்வு இடைவெளி: ~{{seconds}}வி",
    "startBroadcasting": "ஒளிபரப்பைத் தொடங்கு",
    "locating": "கண்டறிகிறது…",
    "kycRequired": "நேரலைக்கு அடையாள சரிபார்ப்பு தேவை",
    "kycPending": "உங்கள் சரிபார்ப்பு இன்னும் மதிப்பாய்வில் உள்ளது",
    "credibilityLow": "உங்கள் நம்பகத்தன்மை மதிப்பெண் மிகக் குறைவாக உள்ளது. துறை எச்சரிக்கை தடைசெய்யப்பட்டுள்ளது.",
    "cosignRequired": "நீங்கள் ஒளிபரப்புவதற்கு முன் மதிப்பீட்டாளரின் ஒப்புதல் தேவை.",
    "prePollSilence": "48 மணிநேர தேர்தல் மௌன காலத்தில் ஒளிபரப்பு தடைசெய்யப்பட்டுள்ளது.",
    "prePollSilenceDesc": "மக்கள் பிரதிநிதித்துவ சட்டம் 1951 இன் படி, நேரலை ஒளிபரப்புகள் {{startTime}} முதல் {{endTime}} வரை நிறுத்தப்பட்டுள்ளன."
  },
  "player": {
    "streamNotFound": "ஒளிபரப்பு காணவில்லை",
    "goBack": "திரும்பிச் செல்",
    "provisioning": "ஒளிபரப்பை வழங்குகிறது…",
    "replayUnavailable": "மறு ஒளிபரப்பு கிடைக்கவில்லை",
    "live": "நேரலை",
    "replay": "மறு ஒளிபரப்பு",
    "viewers": "{{count}} பார்வையாளர்கள்",
    "viewers_one": "{{count}} பார்வையாளர்",
    "viewers_other": "{{count}} பார்வையாளர்கள்",
    "aiEnrichment": "AI மேம்படுத்தல்",
    "aiEnrichmentInactive": "இந்த ஒளிபரப்பிற்கு AI மேம்படுத்தல் செயலில் இல்லை.",
    "transcript": "உரை",
    "summary": "சுருக்கம்",
    "autoHeadline": "AI தலைப்பு",
    "emergency": "அவசரநிலை",
    "crowd": "கூட்டம்",
    "authenticity": "உண்மைத்தன்மை",
    "deepfakeDetected": "டீப்ஃபேக் எச்சரிக்கை",
    "violenceDetected": "வன்முறை கண்டறியப்பட்டது",
    "weaponDetected": "ஆயுதம் கண்டறியப்பட்டது",
    "departmentAlerts": "துறை எச்சரிக்கைகள்",
    "dispatched": "அனுப்பப்பட்டது",
    "delivered": "வழங்கப்பட்டது",
    "awaitingAck": "ஒப்புதலுக்காக காத்திருக்கிறது",
    "failed": "தோல்வியடைந்தது",
    "endBroadcast": "ஒளிபரப்பை முடி",
    "endBroadcastConfirm": "இந்த ஒளிபரப்பை நிச்சயமாக முடிக்க விரும்புகிறீர்களா?",
    "bufferState": "இடைவெளி நிலை",
    "streamId": "ஒளிபரப்பு ஐடி",
    "startedAt": "தொடங்கிய நேரம்",
    "endedAt": "முடிந்த நேரம்",
    "peakViewers": "அதிகபட்ச பார்வையாளர்கள்",
    "contentHash": "உள்ளடக்க ஹாஷ்"
  },
  "distribution": {
    "title": "விநியோகம்",
    "selectStream": "விநியோகிக்க ஒளிபரப்பைத் தேர்ந்தெடுக்கவும்",
    "noActiveStreams": "விநியோகத்திற்கு எந்த நேரலை ஒளிபரப்பும் இல்லை.",
    "youtubeRelay": "யூடியூப் / டிஜிட்டல் ரிலே",
    "youtubeRelayDesc": "உங்கள் க்ஷேத்ர ஒளிபரப்பை நேரடியாக யூடியூப் நேரலைக்கு அனுப்பவும்.",
    "embeddablePlayer": "உட்பொதிக்கக்கூடிய பிளேயர்",
    "embeddablePlayerDesc": "நேரலை க்ஷேத்ர பிளேயரை எந்த வலைத்தளத்திலும் உட்பொதிக்கவும்.",
    "srtEndpoint": "SRT எண்ட்பாயிண்ட்",
    "srtEndpointDesc": "தொலைக்காட்சி செய்தி அறைகளுக்கான ஒளிபரப்பு-தர SRT.",
    "webReceiver": "யுனிவர்சல் வெப் ரிசீவர்",
    "webReceiverDesc": "எந்த திரையிலும் திறக்கவும்.",
    "streamKey": "ஸ்ட்ரீம் கீ",
    "streamKeyPlaceholder": "உங்கள் யூடியூப் ஸ்ட்ரீம் கீயை ஒட்டவும்",
    "addRelay": "ரிலே அவுட்புட்டைச் சேர்",
    "relayAdded": "ரிலே சேர்க்கப்பட்டது ✓",
    "copySnippet": "ஸ்னிப்பெட்டை நகலெடு",
    "copyEndpoint": "எண்ட்பாயிண்டை நகலெடு",
    "copied": "கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது",
    "openReceiver": "ரிசீவரைத் திற"
  },
  "moderation": {
    "title": "மதிப்பாய்வு வரிசை",
    "streamsInBuffer": "இடைவெளியில் {{count}} ஒளிபரப்பு(கள்).",
    "streamsInBuffer_one": "இடைவெளியில் {{count}} ஒளிபரப்பு.",
    "streamsInBuffer_other": "இடைவெளியில் {{count}} ஒளிபரப்புகள்.",
    "aiScreeningActive": "AI திரையிடல் செயலில் உள்ளது.",
    "aiScreeningOff": "AI திரையிடல் முடக்கப்பட்டுள்ளது — மனித மதிப்பாய்வு மட்டுமே.",
    "queueClear": "வரிசை காலியாக உள்ளது",
    "allow": "அனுமதி",
    "mute": "ஒலி முடக்கு",
    "cut": "துண்டி",
    "escalate": "மேல்முறையீடு செய்",
    "previewFeed": "முன்னோட்டம் காண்",
    "riskFlags": "AI ஆபத்து எச்சரிக்கைகள்",
    "bufferTime": "இடைவெளி: {{seconds}}வி",
    "moderatedBy": "{{name}} ஆல் மதிப்பாய்வு செய்யப்பட்டது",
    "escalatedTo": "மூத்த மதிப்பாய்வுக்கு அனுப்பப்பட்டது",
    "streamCut": "ஒளிபரப்பு துண்டிக்கப்பட்டது",
    "streamMuted": "ஒலி முடக்கப்பட்டது"
  },
  "categories": {
    "emergency": "அவசரநிலை",
    "breakingNews": "முக்கிய செய்திகள்",
    "traffic": "போக்குவரத்து",
    "weather": "வானிலை",
    "civic": "குடிமை / உள்கட்டமைப்பு",
    "general": "பொதுவானவை"
  },
  "visibility": {
    "public": "பொது",
    "publicShort": "பொது",
    "publicDesc": "க்ஷேத்ர நேரலை தாவலில் தோன்றும்.",
    "exclusivePartner": "பங்குதாரருக்கு மட்டுமே",
    "exclusivePartnerShort": "பிரத்தியேகமானவை",
    "exclusivePartnerDesc": "உங்கள் இணைக்கப்பட்ட நிறுவனம் மட்டுமே இதைப் பெறும்.",
    "confidentialDirect": "இரகசியம் / நேரடி",
    "confidentialDirectShort": "இரகசியம்",
    "confidentialDirectDesc": "எப்போதும் பொதுவில் வராது. எச்சரிக்கப்பட்ட துறைகள் மட்டுமே பார்க்க முடியும்."
  },
  "departments": {
    "police": "காவல்துறை",
    "fire": "தீயணைப்பு துறை",
    "hospital": "மருத்துவமனை / மருத்துவம்",
    "disasterManagement": "பேரிடர் மேலாண்மை",
    "antiCorruption": "ஊழல் தடுப்பு / கண்காணிப்பு",
    "trafficPolice": "போக்குவரத்து காவல்துறை",
    "municipal": "நகராட்சி / குடிமை",
    "collectorate": "மாவட்ட ஆட்சியரகம்",
    "electricityBoard": "மின்சார வாரியம்",
    "waterBoard": "குடிநீர் வாரியம்",
    "womenChildHelpline": "பெண்கள் & குழந்தைகள் உதவி மையம்",
    "forest": "வனத்துறை"
  },
  "tiers": {
    "citizen": "குடிமகன்",
    "stringer": "ஸ்ட்ரிங்கர்",
    "accredited": "அங்கீகரிக்கப்பட்டவர்",
    "senior": "மூத்தவர்",
    "editor": "ஆசிரியர்",
    "organization": "நிறுவனம்"
  },
  "ack": {
    "genuine": "உண்மையானவை",
    "falseAlert": "தவறான எச்சரிக்கை",
    "unableToVerify": "சரிபார்க்க முடியவில்லை"
  },
  "bufferStates": {
    "buffering": "பஃபரிங் ஆகிறது",
    "cleared": "அனுமதிக்கப்பட்டது",
    "held": "மதிப்பாய்வுக்காக நிறுத்திவைக்கப்பட்டுள்ளது",
    "cut": "துண்டிக்கப்பட்டது",
    "bypassed": "தவிர்க்கப்பட்டது"
  },
  "card": {
    "live": "நேரலை",
    "replay": "மறு ஒளிபரப்பு",
    "viewers": "{{count}} பார்வையாளர்கள்",
    "viewers_one": "{{count}} பார்வையாளர்",
    "viewers_other": "{{count}} பார்வையாளர்கள்",
    "priority": "முன்னுரிமை: {{score}}",
    "aiHeadline": "AI தலைப்பு",
    "noLocation": "இடம் கிடைக்கவில்லை"
  },
  "broadcaster": {
    "endBroadcast": "ஒளிபரப்பை முடி",
    "connecting": "இணைக்கிறது…",
    "live": "நேரலை",
    "reconnecting": "மீண்டும் இணைக்கிறது…",
    "connectionFailed": "இணைப்பு தோல்வியடைந்தது",
    "cameraPermission": "கேமரா அனுமதி தேவை",
    "micPermission": "மைக்ரோஃபோன் அனுமதி தேவை",
    "notSupported": "இந்தச் சாதனத்தில் நேரலை ஒளிபரப்பு ஆதரிக்கப்படவில்லை.",
    "switchCamera": "கேமராவை மாற்று",
    "muteAudio": "ஒலி முடக்கு",
    "unmuteAudio": "ஒலியை இயக்கு"
  },
  "hlsPlayer": {
    "loading": "ஒளிபரப்பு ஏற்றப்படுகிறது…",
    "error": "ஒளிபரப்பு பிழை",
    "retry": "மீண்டும் முயற்சிக்க தட்டவும்",
    "offline": "ஒளிபரப்பு ஆஃப்லைனில் உள்ளது"
  }
};

const lmx_ml = {
  "screenTitle": "ക്ഷേത്ര ലൈവ്",
  "liveNow": "ഇപ്പോൾ {{count}} ലൈവ്",
  "liveNow_one": "ഇപ്പോൾ {{count}} ലൈവ്",
  "liveNow_other": "ഇപ്പോൾ {{count}} ലൈവ്",
  "aiEnrichmentOff": "AI മെച്ചപ്പെടുത്തൽ ഓഫാണ്",
  "aiEnrichmentOn": "AI മെച്ചപ്പെടുത്തൽ സജീവമാണ്",
  "goLive": "ലൈവ് ആരംഭിക്കുക",
  "filters": {
    "all": "എല്ലാം",
    "liveNow": "ഇപ്പോൾ ലൈവ്",
    "replays": "റീപ്ലേകൾ",
    "verified": "സ്ഥിരീകരിച്ചവ"
  },
  "empty": {
    "title": "നിങ്ങളുടെ ഫിൽട്ടറുകൾക്ക് അനുയോജ്യമായ ലൈവുകൾ ഇല്ല",
    "subtitle": "ആദ്യത്തെയാളാകൂ — ഇവിടെ നിന്ന് സംപ്രേക്ഷണം ചെയ്യാൻ ലൈവ് ആരംഭിക്കുക എന്നത് അമർത്തുക."
  },
  "goLiveScreen": {
    "title": "ലൈവ് ആരംഭിക്കുക",
    "detectingLocation": "സ്ഥലം കണ്ടെത്തുന്നു…",
    "locationLocked": "സ്ഥലം ഉറപ്പിച്ചു — {{district}}, {{state}}",
    "approxLocation": "ഏകദേശ സ്ഥലം ഉപയോഗിക്കുന്നു",
    "camera": "ക്യാമറ",
    "recordClip": "ഒരു വീഡിയോ റെക്കോർഡ് ചെയ്യുക",
    "reRecord": "വീണ്ടും റെക്കോർഡ് ചെയ്യുക",
    "clipRecorded": "വീഡിയോ റെക്കോർഡ് ചെയ്തു",
    "broadcastingAs": "സംപ്രേക്ഷണം ചെയ്യുന്നത്",
    "independent": "സ്വതന്ത്രം",
    "neutralWatermark": "ന്യൂട്രൽ ക്ഷേത്ര വാട്ടർമാർക്ക്",
    "visibility": "കാണാവുന്നത്",
    "alertDepartment": "ഒരു സർക്കാർ വകുപ്പിനെ അറിയിക്കുക",
    "alertDepartmentDesc": "നിങ്ങളുടെ ലൈവ് ഫീഡ് നേരിട്ട് തിരഞ്ഞെടുത്ത വകുപ്പുകളിലേക്ക് അയയ്ക്കും.",
    "category": "വിഭാഗം",
    "tags": "ടാഗുകൾ (കോമ ഉപയോഗിച്ച് വേർതിരിക്കുക)",
    "tagsPlaceholder": "ഉദാ. റോഡ്, മേൽപ്പാലം, സിഗ്നൽ",
    "moderationBuffer": "മോഡറേഷൻ ബഫർ: ~{{seconds}}സെ",
    "startBroadcasting": "സംപ്രേക്ഷണം ആരംഭിക്കുക",
    "locating": "കണ്ടെത്തുന്നു…",
    "kycRequired": "ലൈവ് പോകാൻ വ്യക്തിത്വം സ്ഥിരീകരിക്കേണ്ടതുണ്ട്",
    "kycPending": "നിങ്ങളുടെ സ്ഥിരീകരണം ഇപ്പോഴും അവലോകനത്തിലാണ്",
    "credibilityLow": "നിങ്ങളുടെ വിശ്വാസ്യത സ്കോർ വളരെ കുറവാണ്. വകുപ്പുകളെ അറിയിക്കുന്നത് തടഞ്ഞിരിക്കുന്നു.",
    "cosignRequired": "സംപ്രേക്ഷണം ചെയ്യുന്നതിന് മുമ്പ് മോഡറേറ്ററുടെ അനുമതി ആവശ്യമാണ്.",
    "prePollSilence": "തിരഞ്ഞെടുപ്പിന് മുമ്പുള്ള 48 മണിക്കൂർ സമയത്ത് സംപ്രേക്ഷണം നിയന്ത്രിച്ചിരിക്കുന്നു.",
    "prePollSilenceDesc": "1951 ലെ ജനപ്രാതിനിധ്യ നിയമപ്രകാരം, {{startTime}} മുതൽ {{endTime}} വരെ ലൈവ് സംപ്രേക്ഷണം നിർത്തിവച്ചിരിക്കുന്നു."
  },
  "player": {
    "streamNotFound": "സ്ട്രീം കണ്ടെത്തിയില്ല",
    "goBack": "മടങ്ങുക",
    "provisioning": "സ്ട്രീം നൽകുന്നു…",
    "replayUnavailable": "റീപ്ലേ ലഭ്യമല്ല",
    "live": "ലൈവ്",
    "replay": "റീപ്ലേ",
    "viewers": "{{count}} കാഴ്ചക്കാർ",
    "viewers_one": "{{count}} കാഴ്ചക്കാരൻ",
    "viewers_other": "{{count}} കാഴ്ചക്കാർ",
    "aiEnrichment": "AI മെച്ചപ്പെടുത്തൽ",
    "aiEnrichmentInactive": "ഈ സ്ട്രീമിന് AI മെച്ചപ്പെടുത്തൽ സജീവമല്ല.",
    "transcript": "ട്രാൻസ്ക്രിപ്റ്റ്",
    "summary": "സംഗ്രഹം",
    "autoHeadline": "AI തലക്കെട്ട്",
    "emergency": "അടിയന്തരാവസ്ഥ",
    "crowd": "കൂട്ടം",
    "authenticity": "ആധികാരികത",
    "deepfakeDetected": "ഡീപ്പ്ഫേക്ക് കണ്ടെത്തി",
    "violenceDetected": "അക്രമം കണ്ടെത്തി",
    "weaponDetected": "ആയുധം കണ്ടെത്തി",
    "departmentAlerts": "വകുപ്പ് അറിയിപ്പുകൾ",
    "dispatched": "അയച്ചു",
    "delivered": "നൽകി",
    "awaitingAck": "മറുപടിക്കായി കാത്തിരിക്കുന്നു",
    "failed": "പരാജയപ്പെട്ടു",
    "endBroadcast": "സംപ്രേക്ഷണം അവസാനിപ്പിക്കുക",
    "endBroadcastConfirm": "ഈ സംപ്രേക്ഷണം അവസാനിപ്പിക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?",
    "bufferState": "ബഫർ അവസ്ഥ",
    "streamId": "സ്ട്രീം ഐഡി",
    "startedAt": "ആരംഭിച്ചത്",
    "endedAt": "അവസാനിച്ചത്",
    "peakViewers": "ഏറ്റവും കൂടുതൽ കാഴ്ചക്കാർ",
    "contentHash": "കണ്ടെൻ്റ് ഹാഷ്"
  },
  "distribution": {
    "title": "വിതരണം",
    "selectStream": "വിതരണം ചെയ്യാൻ ഒരു സ്ട്രീം തിരഞ്ഞെടുക്കുക",
    "noActiveStreams": "വിതരണത്തിന് ലൈവ് സ്ട്രീമുകളൊന്നും ലഭ്യമല്ല.",
    "youtubeRelay": "യൂട്യൂബ് / ഡിജിറ്റൽ റിലേ",
    "youtubeRelayDesc": "നിങ്ങളുടെ ക്ഷേത്ര സ്ട്രീം നേരിട്ട് യൂട്യൂബ് ലൈവിലേക്ക് അയയ്ക്കുക.",
    "embeddablePlayer": "എംബഡബിൾ പ്ലെയർ",
    "embeddablePlayerDesc": "ഏതെങ്കിലും വെബ്സൈറ്റിൽ ലൈവ് ക്ഷേത്ര പ്ലെയർ എംബഡ് ചെയ്യുക.",
    "srtEndpoint": "SRT എൻഡ്‌പോയിന്റ്",
    "srtEndpointDesc": "ടിവി ന്യൂസ് റൂമുകൾക്കുള്ള ബ്രോഡ്കാസ്റ്റ് ഗ്രേഡ് SRT.",
    "webReceiver": "യൂണിവേഴ്സൽ വെബ് റിസീവർ",
    "webReceiverDesc": "ഏത് സ്ക്രീനിലും തുറക്കുക.",
    "streamKey": "സ്ട്രീം കീ",
    "streamKeyPlaceholder": "നിങ്ങളുടെ യൂട്യൂബ് സ്ട്രീം കീ ഇവിടെ നൽകുക",
    "addRelay": "റിലേ ഔട്ട്പുട്ട് ചേർക്കുക",
    "relayAdded": "റിലേ ചേർത്തു ✓",
    "copySnippet": "സ്നിപ്പെറ്റ് പകർത്തുക",
    "copyEndpoint": "എൻഡ്‌പോയിന്റ് പകർത്തുക",
    "copied": "ക്ലിപ്പ്ബോർഡിലേക്ക് പകർത്തി",
    "openReceiver": "റിസീവർ തുറക്കുക"
  },
  "moderation": {
    "title": "മോഡറേഷൻ ക്യൂ",
    "streamsInBuffer": "ബഫറിൽ {{count}} സ്ട്രീം(കൾ).",
    "streamsInBuffer_one": "ബഫറിൽ {{count}} സ്ട്രീം.",
    "streamsInBuffer_other": "ബഫറിൽ {{count}} സ്ട്രീമുകൾ.",
    "aiScreeningActive": "AI സ്ക്രീനിംഗ് സജീവമാണ്.",
    "aiScreeningOff": "AI സ്ക്രീനിംഗ് ഓഫാണ് — മാനുവൽ അവലോകനം മാത്രം.",
    "queueClear": "ക്യൂ ശൂന്യമാണ്",
    "allow": "അനുവദിക്കുക",
    "mute": "മ്യൂട്ട് ചെയ്യുക",
    "cut": "മുറിക്കുക",
    "escalate": "മുകളിലേക്ക് അയക്കുക",
    "previewFeed": "പ്രിവ്യൂ കാണുക",
    "riskFlags": "AI റിസ്ക് ഫ്ലാഗുകൾ",
    "bufferTime": "ബഫർ: {{seconds}}സെ",
    "moderatedBy": "{{name}} മോഡറേറ്റ് ചെയ്തു",
    "escalatedTo": "സീനിയർ അവലോകനത്തിന് അയച്ചു",
    "streamCut": "സ്ട്രീം അവസാനിപ്പിച്ചു",
    "streamMuted": "ഓഡിയോ മ്യൂട്ട് ചെയ്തു"
  },
  "categories": {
    "emergency": "അടിയന്തരാവസ്ഥ",
    "breakingNews": "ബ്രേക്കിംഗ് ന്യൂസ്",
    "traffic": "ട്രാഫിക്",
    "weather": "കാലാവസ്ഥ",
    "civic": "സിവിക് / ഇൻഫ്രാ",
    "general": "പൊതുവായവ"
  },
  "visibility": {
    "public": "പബ്ലിക്",
    "publicShort": "പബ്ലിക്",
    "publicDesc": "ക്ഷേത്ര ലൈവ് ടാബിൽ കാണിക്കും.",
    "exclusivePartner": "പങ്കാളിക്ക് മാത്രം",
    "exclusivePartnerShort": "എക്സ്ക്ലൂസീവ്",
    "exclusivePartnerDesc": "നിങ്ങളുടെ ബന്ധപ്പെട്ട സ്ഥാപനത്തിന് മാത്രം ലഭിക്കും.",
    "confidentialDirect": "രഹസ്യം / നേരിട്ട്",
    "confidentialDirectShort": "രഹസ്യം",
    "confidentialDirectDesc": "ഒരിക്കലും പരസ്യമാകില്ല. അറിയിപ്പ് ലഭിച്ച വകുപ്പുകൾക്ക് മാത്രമേ കാണാൻ കഴിയൂ."
  },
  "departments": {
    "police": "പോലീസ്",
    "fire": "ഫയർ സർവീസ്",
    "hospital": "ആശുപത്രി / മെഡിക്കൽ",
    "disasterManagement": "ദുരന്ത നിവാരണം",
    "antiCorruption": "അഴിമതി വിരുദ്ധം / വിജിലൻസ്",
    "trafficPolice": "ട്രാഫിക് പോലീസ്",
    "municipal": "മുനിസിപ്പൽ / സിവിക്",
    "collectorate": "കളക്ടറേറ്റ്",
    "electricityBoard": "വൈദ്യുതി ബോർഡ്",
    "waterBoard": "വാട്ടർ ബോർഡ്",
    "womenChildHelpline": "വനിതാ ശിശു ഹെൽപ്പ്‌ലൈൻ",
    "forest": "വനം വകുപ്പ്"
  },
  "tiers": {
    "citizen": "പൗരൻ",
    "stringer": "സ്ട്രിംഗർ",
    "accredited": "അംഗീകൃതമായത്",
    "senior": "സീനിയർ",
    "editor": "എഡിറ്റർ",
    "organization": "സ്ഥാപനം"
  },
  "ack": {
    "genuine": "യഥാർത്ഥം",
    "falseAlert": "തെറ്റായ മുന്നറിയിപ്പ്",
    "unableToVerify": "സ്ഥിരീകരിക്കാൻ കഴിഞ്ഞില്ല"
  },
  "bufferStates": {
    "buffering": "ബഫറിംഗ്",
    "cleared": "അനുവദിച്ചു",
    "held": "അവലോകനത്തിനായി നിർത്തിവച്ചിരിക്കുന്നു",
    "cut": "മുറിച്ചു",
    "bypassed": "ബൈപാസ് ചെയ്തു"
  },
  "card": {
    "live": "ലൈവ്",
    "replay": "റീപ്ലേ",
    "viewers": "{{count}} കാഴ്ചക്കാർ",
    "viewers_one": "{{count}} കാഴ്ചക്കാരൻ",
    "viewers_other": "{{count}} കാഴ്ചക്കാർ",
    "priority": "മുൻഗണന: {{score}}",
    "aiHeadline": "AI തലക്കെട്ട്",
    "noLocation": "സ്ഥലം ലഭ്യമല്ല"
  },
  "broadcaster": {
    "endBroadcast": "സംപ്രേക്ഷണം അവസാനിപ്പിക്കുക",
    "connecting": "ബന്ധിപ്പിക്കുന്നു…",
    "live": "ലൈവ്",
    "reconnecting": "വീണ്ടും ബന്ധിപ്പിക്കുന്നു…",
    "connectionFailed": "ബന്ധിപ്പിക്കൽ പരാജയപ്പെട്ടു",
    "cameraPermission": "ക്യാമറ അനുമതി ആവശ്യമാണ്",
    "micPermission": "മൈക്രോഫോൺ അനുമതി ആവശ്യമാണ്",
    "notSupported": "ഈ ഉപകരണത്തിൽ ലൈവ് സംപ്രേക്ഷണം പിന്തുണയ്ക്കുന്നില്ല.",
    "switchCamera": "ക്യാമറ മാറ്റുക",
    "muteAudio": "മ്യൂട്ട് ചെയ്യുക",
    "unmuteAudio": "അൺമ്യൂട്ട് ചെയ്യുക"
  },
  "hlsPlayer": {
    "loading": "സ്ട്രീം ലോഡുചെയ്യുന്നു…",
    "error": "സ്ട്രീം പ്ലേബാക്ക് പിശക്",
    "retry": "വീണ്ടും ശ്രമിക്കാൻ ടാപ്പുചെയ്യുക",
    "offline": "സ്ട്രീം ഓഫ്‌ലൈനിലാണ്"
  }
};

const lmx_bn = {
  "screenTitle": "ক্ষেত্র লাইভ",
  "liveNow": "এখন {{count}} লাইভ",
  "liveNow_one": "এখন {{count}} লাইভ",
  "liveNow_other": "এখন {{count}} লাইভ",
  "aiEnrichmentOff": "AI সমৃদ্ধি বন্ধ আছে",
  "aiEnrichmentOn": "AI সমৃদ্ধি সক্রিয় আছে",
  "goLive": "লাইভ শুরু করুন",
  "filters": {
    "all": "সব",
    "liveNow": "এখন লাইভ",
    "replays": "রিপ্লে",
    "verified": "যাচাইকৃত"
  },
  "empty": {
    "title": "আপনার ফিল্টারের সাথে মিলে এমন কোনো লাইভ নেই",
    "subtitle": "প্রথম হন — এখান থেকে সম্প্রচার করতে লাইভ শুরু করুন-এ ট্যাপ করুন।"
  },
  "goLiveScreen": {
    "title": "লাইভ শুরু করুন",
    "detectingLocation": "অবস্থান শনাক্ত করা হচ্ছে…",
    "locationLocked": "অবস্থান লক করা হয়েছে — {{district}}, {{state}}",
    "approxLocation": "আনুমানিক অবস্থান ব্যবহার করা হচ্ছে",
    "camera": "ক্যামেরা",
    "recordClip": "একটি ভিডিও রেকর্ড করুন",
    "reRecord": "আবার রেকর্ড করুন",
    "clipRecorded": "ভিডিও রেকর্ড করা হয়েছে",
    "broadcastingAs": "সম্প্রচার করা হচ্ছে",
    "independent": "স্বতন্ত্র",
    "neutralWatermark": "নিরপেক্ষ ক্ষেত্র জলছাপ",
    "visibility": "দৃশ্যমানতা",
    "alertDepartment": "সরকারি বিভাগকে সতর্ক করুন",
    "alertDepartmentDesc": "আপনার লাইভ ফিড সরাসরি নির্বাচিত বিভাগে পাঠানো হবে।",
    "category": "বিভাগ",
    "tags": "ট্যাগ (কমা দ্বারা আলাদা করা)",
    "tagsPlaceholder": "যেমন রাস্তা, ফ্লাইওভার, সিগন্যাল",
    "moderationBuffer": "মডারেশন বাফার: ~{{seconds}}সে",
    "startBroadcasting": "সম্প্রচার শুরু করুন",
    "locating": "শনাক্ত করা হচ্ছে…",
    "kycRequired": "লাইভে যেতে পরিচয় যাচাইকরণ প্রয়োজন",
    "kycPending": "আপনার যাচাইকরণ এখনও পর্যালোচনা করা হচ্ছে",
    "credibilityLow": "আপনার বিশ্বাসযোগ্যতা স্কোর খুব কম। বিভাগকে সতর্ক করা সীমাবদ্ধ।",
    "cosignRequired": "সম্প্রচারের আগে একজন মডারেটরের অনুমোদন প্রয়োজন।",
    "prePollSilence": "নির্বাচনের আগের ৪৮ ঘন্টা নীরবতা সময়কালে সম্প্রচার সীমাবদ্ধ।",
    "prePollSilenceDesc": "জনপ্রতিনিধিত্ব আইন ১৯৫১ অনুসারে, {{startTime}} থেকে {{endTime}} পর্যন্ত লাইভ সম্প্রচার বন্ধ রয়েছে।"
  },
  "player": {
    "streamNotFound": "স্ট্রিম পাওয়া যায়নি",
    "goBack": "ফিরে যান",
    "provisioning": "স্ট্রিম প্রস্তুত করা হচ্ছে…",
    "replayUnavailable": "রিপ্লে উপলব্ধ নয়",
    "live": "লাইভ",
    "replay": "রিপ্লে",
    "viewers": "{{count}} দর্শক",
    "viewers_one": "{{count}} দর্শক",
    "viewers_other": "{{count}} দর্শক",
    "aiEnrichment": "AI সমৃদ্ধি",
    "aiEnrichmentInactive": "এই স্ট্রিমের জন্য AI সমৃদ্ধি সক্রিয় নয়।",
    "transcript": "ট্রান্সক্রিপ্ট",
    "summary": "সারাংশ",
    "autoHeadline": "AI শিরোনাম",
    "emergency": "জরুরি অবস্থা",
    "crowd": "ভিড়",
    "authenticity": "সত্যতা",
    "deepfakeDetected": "ডিপফেক শনাক্ত করা হয়েছে",
    "violenceDetected": "সহিংসতা শনাক্ত করা হয়েছে",
    "weaponDetected": "অস্ত্র শনাক্ত করা হয়েছে",
    "departmentAlerts": "বিভাগীয় সতর্কতা",
    "dispatched": "পাঠানো হয়েছে",
    "delivered": "বিতরণ করা হয়েছে",
    "awaitingAck": "উত্তরের অপেক্ষায়",
    "failed": "ব্যর্থ হয়েছে",
    "endBroadcast": "সম্প্রচার শেষ করুন",
    "endBroadcastConfirm": "আপনি কি নিশ্চিত যে আপনি এই সম্প্রচারটি শেষ করতে চান?",
    "bufferState": "বাফার অবস্থা",
    "streamId": "স্ট্রিম আইডি",
    "startedAt": "শুরু হয়েছে",
    "endedAt": "শেষ হয়েছে",
    "peakViewers": "সর্বোচ্চ দর্শক",
    "contentHash": "কন্টেন্ট হ্যাশ"
  },
  "distribution": {
    "title": "বিতরণ",
    "selectStream": "বিতরণ করার জন্য একটি স্ট্রিম নির্বাচন করুন",
    "noActiveStreams": "বিতরণের জন্য কোনো সক্রিয় স্ট্রিম নেই।",
    "youtubeRelay": "ইউটিউব / ডিজিটাল রিলে",
    "youtubeRelayDesc": "আপনার ক্ষেত্র স্ট্রিম সরাসরি ইউটিউব লাইভে পাঠান।",
    "embeddablePlayer": "এমবেডেবল প্লেয়ার",
    "embeddablePlayerDesc": "যেকোনো ওয়েবসাইটে লাইভ ক্ষেত্র প্লেয়ার এমবেড করুন।",
    "srtEndpoint": "SRT এন্ডপয়েন্ট",
    "srtEndpointDesc": "টিভি নিউজরুমের জন্য ব্রডকাস্ট-গ্রেড SRT।",
    "webReceiver": "ইউনিভার্সাল ওয়েব রিসিভার",
    "webReceiverDesc": "যেকোনো স্ক্রিনে খুলুন।",
    "streamKey": "স্ট্রিম কী",
    "streamKeyPlaceholder": "আপনার ইউটিউব স্ট্রিম কী পেস্ট করুন",
    "addRelay": "রিলে আউটপুট যোগ করুন",
    "relayAdded": "রিলে যোগ করা হয়েছে ✓",
    "copySnippet": "স্নিপেট অনুলিপি করুন",
    "copyEndpoint": "এন্ডপয়েন্ট অনুলিপি করুন",
    "copied": "ক্লিপবোর্ডে অনুলিপি করা হয়েছে",
    "openReceiver": "রিসিভার খুলুন"
  },
  "moderation": {
    "title": "মডারেশন সারি",
    "streamsInBuffer": "বাফারে {{count}}টি স্ট্রিম আছে।",
    "streamsInBuffer_one": "বাফারে {{count}}টি স্ট্রিম আছে।",
    "streamsInBuffer_other": "বাফারে {{count}}টি স্ট্রিম আছে।",
    "aiScreeningActive": "AI স্ক্রীনিং সক্রিয় আছে।",
    "aiScreeningOff": "AI স্ক্রীনিং বন্ধ আছে — শুধুমাত্র ম্যানুয়াল পর্যালোচনা।",
    "queueClear": "সারি পরিষ্কার — পর্যালোচনার জন্য কিছু নেই",
    "allow": "অনুমতি দিন",
    "mute": "মিউট করুন",
    "cut": "কাটুন",
    "escalate": "ঊর্ধ্বতনকে জানান",
    "previewFeed": "প্রিভিউ দেখুন",
    "riskFlags": "AI ঝুঁকির সতর্কতা",
    "bufferTime": "বাফার: {{seconds}}সে",
    "moderatedBy": "{{name}} দ্বারা মডারেট করা হয়েছে",
    "escalatedTo": "সিনিয়র পর্যালোচনার জন্য পাঠানো হয়েছে",
    "streamCut": "স্ট্রিম বন্ধ করা হয়েছে",
    "streamMuted": "অডিও মিউট করা হয়েছে"
  },
  "categories": {
    "emergency": "জরুরি অবস্থা",
    "breakingNews": "ব্রেকিং নিউজ",
    "traffic": "ট্রাফিক",
    "weather": "আবহাওয়া",
    "civic": "নাগরিক / পরিকাঠামো",
    "general": "সাধারণ"
  },
  "visibility": {
    "public": "পাবলিক",
    "publicShort": "পাবলিক",
    "publicDesc": "ক্ষেত্র লাইভ ট্যাবে প্রদর্শিত হবে।",
    "exclusivePartner": "শুধুমাত্র অংশীদারের জন্য",
    "exclusivePartnerShort": "এক্সক্লুসিভ",
    "exclusivePartnerDesc": "শুধুমাত্র আপনার অনুমোদিত সংস্থা এটি পাবে।",
    "confidentialDirect": "গোপনীয় / সরাসরি",
    "confidentialDirectShort": "গোপনীয়",
    "confidentialDirectDesc": "কখনই সর্বজনীন হবে না। শুধুমাত্র সতর্ক করা বিভাগগুলো দেখতে পাবে।"
  },
  "departments": {
    "police": "পুলিশ",
    "fire": "ফায়ার সার্ভিস",
    "hospital": "হাসপাতাল / চিকিৎসা",
    "disasterManagement": "দুর্যোগ ব্যবস্থাপনা",
    "antiCorruption": "দুর্নীতি দমন / ভিজিল্যান্স",
    "trafficPolice": "ট্রাফিক পুলিশ",
    "municipal": "পৌরসভা / নাগরিক",
    "collectorate": "জেলা প্রশাসকের কার্যালয়",
    "electricityBoard": "বিদ্যুৎ বোর্ড",
    "waterBoard": "পানি উন্নয়ন বোর্ড",
    "womenChildHelpline": "নারী ও শিশু হেল্পলাইন",
    "forest": "বন বিভাগ"
  },
  "tiers": {
    "citizen": "নাগরিক",
    "stringer": "স্ট্রিংগার",
    "accredited": "স্বীকৃত",
    "senior": "সিনিয়র",
    "editor": "সম্পাদক",
    "organization": "সংস্থা"
  },
  "ack": {
    "genuine": "প্রকৃত",
    "falseAlert": "মিথ্যা সতর্কতা",
    "unableToVerify": "যাচাই করতে অক্ষম"
  },
  "bufferStates": {
    "buffering": "বাফারিং হচ্ছে",
    "cleared": "অনুমোদিত",
    "held": "পর্যালোচনার জন্য আটকে রাখা হয়েছে",
    "cut": "কাটা হয়েছে",
    "bypassed": "বাইপাস করা হয়েছে"
  },
  "card": {
    "live": "লাইভ",
    "replay": "রিপ্লে",
    "viewers": "{{count}} দর্শক",
    "viewers_one": "{{count}} দর্শক",
    "viewers_other": "{{count}} দর্শক",
    "priority": "অগ্রাধিকার: {{score}}",
    "aiHeadline": "AI শিরোনাম",
    "noLocation": "অবস্থান উপলব্ধ নয়"
  },
  "broadcaster": {
    "endBroadcast": "সম্প্রচার শেষ করুন",
    "connecting": "সংযুক্ত করা হচ্ছে…",
    "live": "লাইভ",
    "reconnecting": "পুনরায় সংযুক্ত করা হচ্ছে…",
    "connectionFailed": "সংযোগ ব্যর্থ হয়েছে",
    "cameraPermission": "ক্যামেরার অনুমতি প্রয়োজন",
    "micPermission": "মাইক্রোফোনের অনুমতি প্রয়োজন",
    "notSupported": "এই ডিভাইসে লাইভ সম্প্রচার সমর্থিত নয়।",
    "switchCamera": "ক্যামেরা পরিবর্তন করুন",
    "muteAudio": "মিউট করুন",
    "unmuteAudio": "আনমিউট করুন"
  },
  "hlsPlayer": {
    "loading": "স্ট্রিম লোড হচ্ছে…",
    "error": "স্ট্রিম প্লেব্যাক ত্রুটি",
    "retry": "পুনরায় চেষ্টা করতে ট্যাপ করুন",
    "offline": "স্ট্রিম অফলাইনে আছে"
  }
};

const lmx_gu = {
  "screenTitle": "ક્ષેત્ર લાઇવ",
  "liveNow": "હવે {{count}} લાઇવ",
  "liveNow_one": "હવે {{count}} લાઇવ",
  "liveNow_other": "હવે {{count}} લાઇવ",
  "aiEnrichmentOff": "AI એન્હાન્સમેન્ટ બંધ છે",
  "aiEnrichmentOn": "AI એન્હાન્સમેન્ટ સક્રિય છે",
  "goLive": "લાઇવ શરૂ કરો",
  "filters": {
    "all": "બધા",
    "liveNow": "હવે લાઇવ",
    "replays": "રીપ્લે",
    "verified": "ચકાસાયેલ"
  },
  "empty": {
    "title": "તમારા ફિલ્ટર સાથે કોઈ લાઇવ મળતું નથી",
    "subtitle": "પ્રથમ બનો — અહીંથી પ્રસારણ કરવા માટે લાઇવ શરૂ કરો પર ટેપ કરો."
  },
  "goLiveScreen": {
    "title": "લાઇવ શરૂ કરો",
    "detectingLocation": "સ્થાન શોધી રહ્યું છે…",
    "locationLocked": "સ્થાન લોક થયું — {{district}}, {{state}}",
    "approxLocation": "અંદાજિત સ્થાનનો ઉપયોગ કરી રહ્યાં છે",
    "camera": "કેમેરા",
    "recordClip": "વિડિઓ રેકોર્ડ કરો",
    "reRecord": "ફરીથી રેકોર્ડ કરો",
    "clipRecorded": "વિડિઓ રેકોર્ડ થયો",
    "broadcastingAs": "તરીકે પ્રસારણ કરી રહ્યાં છે",
    "independent": "સ્વતંત્ર",
    "neutralWatermark": "તટસ્થ ક્ષેત્ર વોટરમાર્ક",
    "visibility": "દૃશ્યતા",
    "alertDepartment": "સરકારી વિભાગને ચેતવણી આપો",
    "alertDepartmentDesc": "તમારી લાઇવ ફીડ સીધી પસંદ કરેલા વિભાગોને મોકલવામાં આવશે.",
    "category": "કેટેગરી",
    "tags": "ટેગ્સ (અલ્પવિરામથી અલગ)",
    "tagsPlaceholder": "દા.ત. રસ્તો, ફ્લાયઓવર, સિગ્નલ",
    "moderationBuffer": "મોડરેશન બફર: ~{{seconds}}સે",
    "startBroadcasting": "પ્રસારણ શરૂ કરો",
    "locating": "શોધી રહ્યું છે…",
    "kycRequired": "લાઇવ જવા માટે ઓળખ ચકાસણી જરૂરી છે",
    "kycPending": "તમારી ચકાસણી હજુ સમીક્ષા હેઠળ છે",
    "credibilityLow": "તમારો વિશ્વસનીયતા સ્કોર ખૂબ ઓછો છે. વિભાગને ચેતવણી આપવી મર્યાદિત છે.",
    "cosignRequired": "પ્રસારણ કરતા પહેલા મોડરેટરની મંજૂરી જરૂરી છે.",
    "prePollSilence": "ચૂંટણી પહેલાના 48-કલાકના મૌન સમયગાળા દરમિયાન પ્રસારણ મર્યાદિત છે.",
    "prePollSilenceDesc": "લોકપ્રતિનિધિત્વ ધારો 1951 મુજબ, લાઇવ પ્રસારણ {{startTime}} થી {{endTime}} સુધી બંધ છે."
  },
  "player": {
    "streamNotFound": "સ્ટ્રીમ મળ્યું નથી",
    "goBack": "પાછા જાઓ",
    "provisioning": "સ્ટ્રીમ તૈયાર કરી રહ્યાં છે…",
    "replayUnavailable": "રીપ્લે ઉપલબ્ધ નથી",
    "live": "લાઇવ",
    "replay": "રીપ્લે",
    "viewers": "{{count}} દર્શકો",
    "viewers_one": "{{count}} દર્શક",
    "viewers_other": "{{count}} દર્શકો",
    "aiEnrichment": "AI એન્હાન્સમેન્ટ",
    "aiEnrichmentInactive": "આ સ્ટ્રીમ માટે AI એન્હાન્સમેન્ટ સક્રિય નથી.",
    "transcript": "ટ્રાન્સક્રિપ્ટ",
    "summary": "સારાંશ",
    "autoHeadline": "AI હેડલાઇન",
    "emergency": "કટોકટી",
    "crowd": "ભીડ",
    "authenticity": "પ્રમાણિકતા",
    "deepfakeDetected": "ડીપફેક મળી આવ્યું",
    "violenceDetected": "હિંસા મળી આવી",
    "weaponDetected": "હથિયાર મળ્યું",
    "departmentAlerts": "વિભાગની ચેતવણીઓ",
    "dispatched": "મોકલવામાં આવ્યું",
    "delivered": "વિતરિત થયું",
    "awaitingAck": "જવાબની રાહ જોઈ રહ્યાં છે",
    "failed": "નિષ્ફળ",
    "endBroadcast": "પ્રસારણ સમાપ્ત કરો",
    "endBroadcastConfirm": "શું તમે ખરેખર આ પ્રસારણ સમાપ્ત કરવા માંગો છો?",
    "bufferState": "બફર સ્થિતિ",
    "streamId": "સ્ટ્રીમ ID",
    "startedAt": "શરૂ થયું",
    "endedAt": "સમાપ્ત થયું",
    "peakViewers": "મહત્તમ દર્શકો",
    "contentHash": "કન્ટેન્ટ હેશ"
  },
  "distribution": {
    "title": "વિતરણ",
    "selectStream": "વિતરિત કરવા માટે સ્ટ્રીમ પસંદ કરો",
    "noActiveStreams": "વિતરણ માટે કોઈ સક્રિય સ્ટ્રીમ ઉપલબ્ધ નથી.",
    "youtubeRelay": "યુટ્યુબ / ડિજિટલ રિલે",
    "youtubeRelayDesc": "તમારી ક્ષેત્ર સ્ટ્રીમ સીધી યુટ્યુબ લાઇવ પર મોકલો.",
    "embeddablePlayer": "એમ્બેડેબલ પ્લેયર",
    "embeddablePlayerDesc": "કોઈપણ વેબસાઇટ પર લાઇવ ક્ષેત્ર પ્લેયર એમ્બેડ કરો.",
    "srtEndpoint": "SRT એન્ડપોઇન્ટ",
    "srtEndpointDesc": "ટીવી ન્યૂઝરૂમ માટે બ્રોડકાસ્ટ-ગ્રેડ SRT.",
    "webReceiver": "યુનિવર્સલ વેબ રિસીવર",
    "webReceiverDesc": "કોઈપણ સ્ક્રીન પર ખોલો.",
    "streamKey": "સ્ટ્રીમ કી",
    "streamKeyPlaceholder": "તમારી યુટ્યુબ સ્ટ્રીમ કી પેસ્ટ કરો",
    "addRelay": "રિલે આઉટપુટ ઉમેરો",
    "relayAdded": "રિલે ઉમેર્યું ✓",
    "copySnippet": "સ્નિપેટ કૉપિ કરો",
    "copyEndpoint": "એન્ડપોઇન્ટ કૉપિ કરો",
    "copied": "ક્લિપબોર્ડ પર કૉપિ કર્યું",
    "openReceiver": "રિસીવર ખોલો"
  },
  "moderation": {
    "title": "મોડરેશન કતાર",
    "streamsInBuffer": "બફરમાં {{count}} સ્ટ્રીમ(ઓ).",
    "streamsInBuffer_one": "બફરમાં {{count}} સ્ટ્રીમ.",
    "streamsInBuffer_other": "બફરમાં {{count}} સ્ટ્રીમ્સ.",
    "aiScreeningActive": "AI સ્ક્રીનિંગ સક્રિય છે.",
    "aiScreeningOff": "AI સ્ક્રીનિંગ બંધ છે — માત્ર મેન્યુઅલ સમીક્ષા.",
    "queueClear": "કતાર ખાલી છે",
    "allow": "મંજૂરી આપો",
    "mute": "મ્યૂટ કરો",
    "cut": "કાપો",
    "escalate": "ઉચ્ચ સ્તરે મોકલો",
    "previewFeed": "પ્રિવ્યૂ જુઓ",
    "riskFlags": "AI જોખમની ચેતવણીઓ",
    "bufferTime": "બફર: {{seconds}}સે",
    "moderatedBy": "{{name}} દ્વારા મોડરેટ કરાયેલ",
    "escalatedTo": "સિનિયર સમીક્ષા માટે મોકલ્યું",
    "streamCut": "સ્ટ્રીમ સમાપ્ત કરી",
    "streamMuted": "ઓડિયો મ્યૂટ કર્યો"
  },
  "categories": {
    "emergency": "કટોકટી",
    "breakingNews": "બ્રેકિંગ ન્યૂઝ",
    "traffic": "ટ્રાફિક",
    "weather": "હવામાન",
    "civic": "નાગરિક / ઇન્ફ્રા",
    "general": "સામાન્ય"
  },
  "visibility": {
    "public": "જાહેર",
    "publicShort": "જાહેર",
    "publicDesc": "ક્ષેત્ર લાઇવ ટેબ પર દેખાશે.",
    "exclusivePartner": "માત્ર પાર્ટનર માટે",
    "exclusivePartnerShort": "એક્સક્લુઝિવ",
    "exclusivePartnerDesc": "માત્ર તમારી સંલગ્ન સંસ્થાને જ મળશે.",
    "confidentialDirect": "ગોપનીય / સીધું",
    "confidentialDirectShort": "ગોપનીય",
    "confidentialDirectDesc": "ક્યારેય જાહેર થશે નહીં. માત્ર ચેતવણી આપેલા વિભાગો જ જોઈ શકશે."
  },
  "departments": {
    "police": "પોલીસ",
    "fire": "ફાયર સર્વિસ",
    "hospital": "હોસ્પિટલ / મેડિકલ",
    "disasterManagement": "આપત્તિ વ્યવસ્થાપન",
    "antiCorruption": "ભ્રષ્ટાચાર વિરોધી / વિજિલન્સ",
    "trafficPolice": "ટ્રાફિક પોલીસ",
    "municipal": "મ્યુનિસિપલ / સિવિક",
    "collectorate": "કલેક્ટર કચેરી",
    "electricityBoard": "વિદ્યુત બોર્ડ",
    "waterBoard": "વોટર બોર્ડ",
    "womenChildHelpline": "મહિલા અને બાળ હેલ્પલાઇન",
    "forest": "વન વિભાગ"
  },
  "tiers": {
    "citizen": "નાગરિક",
    "stringer": "સ્ટ્રિંગર",
    "accredited": "માન્યતાપ્રાપ્ત",
    "senior": "સિનિયર",
    "editor": "સંપાદક",
    "organization": "સંસ્થા"
  },
  "ack": {
    "genuine": "અસલી",
    "falseAlert": "ખોટી ચેતવણી",
    "unableToVerify": "ચકાસવામાં અસમર્થ"
  },
  "bufferStates": {
    "buffering": "બફરિંગ",
    "cleared": "મંજૂર",
    "held": "સમીક્ષા માટે અટકાવેલ",
    "cut": "કાપેલ",
    "bypassed": "બાયપાસ કરેલ"
  },
  "card": {
    "live": "લાઇવ",
    "replay": "રીપ્લે",
    "viewers": "{{count}} દર્શકો",
    "viewers_one": "{{count}} દર્શક",
    "viewers_other": "{{count}} દર્શકો",
    "priority": "પ્રાથમિકતા: {{score}}",
    "aiHeadline": "AI હેડલાઇન",
    "noLocation": "સ્થાન ઉપલબ્ધ નથી"
  },
  "broadcaster": {
    "endBroadcast": "પ્રસારણ સમાપ્ત કરો",
    "connecting": "જોડાઈ રહ્યું છે…",
    "live": "લાઇવ",
    "reconnecting": "ફરી જોડાઈ રહ્યું છે…",
    "connectionFailed": "જોડાણ નિષ્ફળ",
    "cameraPermission": "કેમેરાની પરવાનગી જરૂરી છે",
    "micPermission": "માઇક્રોફોનની પરવાનગી જરૂરી છે",
    "notSupported": "આ ઉપકરણ પર લાઇવ પ્રસારણ સમર્થિત નથી.",
    "switchCamera": "કેમેરા બદલો",
    "muteAudio": "મ્યૂટ કરો",
    "unmuteAudio": "અનમ્યૂટ કરો"
  },
  "hlsPlayer": {
    "loading": "સ્ટ્રીમ લોડ થઈ રહ્યું છે…",
    "error": "સ્ટ્રીમ પ્લેબેક ભૂલ",
    "retry": "ફરી પ્રયાસ કરવા ટેપ કરો",
    "offline": "સ્ટ્રીમ ઑફલાઇન છે"
  }
};

const fs = require('fs');

const insertLmx = (filePath, lmxObj) => {
  let content = fs.readFileSync(filePath, 'utf8');
  
  if (content.includes('"liveElection": {')) {
    content = content.replace(/"liveElection":\s*\{/, `"lmx": ${JSON.stringify(lmxObj, null, 4)},\n  "liveElection": {`);
  } else if (content.includes('"constituencyExtended": {')) {
    content = content.replace(/"constituencyExtended":\s*\{/, `"lmx": ${JSON.stringify(lmxObj, null, 4)},\n  "constituencyExtended": {`);
  } else {
    content = content.replace(/\n\};\s*$/, `,\n  "lmx": ${JSON.stringify(lmxObj, null, 4)}\n};`);
  }
  
  content = content.replace(/"lmx": \{/g, '  "lmx": {');
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
};

const basePath = 'c:\\\\Users\\\\Laven\\\\OneDrive\\\\Desktop\\\\Kshetra\\\\apps\\\\mobile\\\\i18n\\\\locales\\\\';
insertLmx(basePath + 'ta.ts', lmx_ta);
insertLmx(basePath + 'ml.ts', lmx_ml);
insertLmx(basePath + 'bn.ts', lmx_bn);
insertLmx(basePath + 'gu.ts', lmx_gu);
