import type { PartyCode } from '../types/constituency';

export interface PartyInfo {
  code: PartyCode;
  name: string;
  shortName: string;
  color: string;
  secondaryColor: string;
}

export const PARTY_CONFIG: Record<PartyCode, PartyInfo> = {
  BJP: {
    code: 'BJP',
    name: 'Bharatiya Janata Party',
    shortName: 'BJP',
    color: '#FF6B00',
    secondaryColor: '#FF9A45',
  },
  INC: {
    code: 'INC',
    name: 'Indian National Congress',
    shortName: 'Congress',
    color: '#19AAED',
    secondaryColor: '#5DC4F5',
  },
  BRS: {
    code: 'BRS',
    name: 'Bharat Rashtra Samithi',
    shortName: 'BRS',
    color: '#E91E7B',
    secondaryColor: '#F06DAB',
  },
  TDP: {
    code: 'TDP',
    name: 'Telugu Desam Party',
    shortName: 'TDP',
    color: '#FFCD00',
    secondaryColor: '#FFE066',
  },
  AIMIM: {
    code: 'AIMIM',
    name: 'All India Majlis-e-Ittehadul Muslimeen',
    shortName: 'AIMIM',
    color: '#008000',
    secondaryColor: '#33B333',
  },
  YSRCP: {
    code: 'YSRCP',
    name: 'YSR Congress Party',
    shortName: 'YSRCP',
    color: '#0066CC',
    secondaryColor: '#4D99E6',
  },
  AAP: {
    code: 'AAP',
    name: 'Aam Aadmi Party',
    shortName: 'AAP',
    color: '#0080DD',
    secondaryColor: '#45A3E8',
  },
  DMK: {
    code: 'DMK',
    name: 'Dravida Munnetra Kazhagam',
    shortName: 'DMK',
    color: '#E30613',
    secondaryColor: '#F04D57',
  },
  AITC: {
    code: 'AITC',
    name: 'All India Trinamool Congress',
    shortName: 'TMC',
    color: '#20C646',
    secondaryColor: '#5DD97A',
  },
  CPI: {
    code: 'CPI',
    name: 'Communist Party of India',
    shortName: 'CPI',
    color: '#CC0000',
    secondaryColor: '#E64D4D',
  },
  CPIM: {
    code: 'CPIM',
    name: 'Communist Party of India (Marxist)',
    shortName: 'CPI(M)',
    color: '#CC0000',
    secondaryColor: '#E64D4D',
  },
  NCP: {
    code: 'NCP',
    name: 'Nationalist Congress Party',
    shortName: 'NCP',
    color: '#00BFFF',
    secondaryColor: '#4DD4FF',
  },
  SHS: {
    code: 'SHS',
    name: 'Shiv Sena',
    shortName: 'SHS',
    color: '#FF6600',
    secondaryColor: '#FF944D',
  },
  JDU: {
    code: 'JDU',
    name: 'Janata Dal (United)',
    shortName: 'JD(U)',
    color: '#006400',
    secondaryColor: '#009700',
  },
  RJD: {
    code: 'RJD',
    name: 'Rashtriya Janata Dal',
    shortName: 'RJD',
    color: '#008000',
    secondaryColor: '#33B333',
  },
  BSP: {
    code: 'BSP',
    name: 'Bahujan Samaj Party',
    shortName: 'BSP',
    color: '#22409A',
    secondaryColor: '#4D6BC4',
  },
  SP: {
    code: 'SP',
    name: 'Samajwadi Party',
    shortName: 'SP',
    color: '#FF2222',
    secondaryColor: '#FF6666',
  },
  JSP: {
    code: 'JSP',
    name: 'Jana Sena Party',
    shortName: 'JSP',
    color: '#FF0000',
    secondaryColor: '#FF4D4D',
  },
  JDS: {
    code: 'JDS',
    name: 'Janata Dal (Secular)',
    shortName: 'JD(S)',
    color: '#006633',
    secondaryColor: '#009944',
  },
  JMM: {
    code: 'JMM',
    name: 'Jharkhand Mukti Morcha',
    shortName: 'JMM',
    color: '#2E8B57',
    secondaryColor: '#5CB88A',
  },
  JKNC: {
    code: 'JKNC',
    name: 'Jammu & Kashmir National Conference',
    shortName: 'JKNC',
    color: '#FF0000',
    secondaryColor: '#FF4D4D',
  },
  SHSUBT: {
    code: 'SHSUBT',
    name: 'Shiv Sena (Uddhav Balasaheb Thackeray)',
    shortName: 'SHS(UBT)',
    color: '#FF6600',
    secondaryColor: '#FF944D',
  },
  NCPSP: {
    code: 'NCPSP',
    name: 'Nationalist Congress Party (Sharad Pawar)',
    shortName: 'NCP(SP)',
    color: '#00BFFF',
    secondaryColor: '#4DD4FF',
  },
  NPP: {
    code: 'NPP',
    name: 'National People\'s Party',
    shortName: 'NPP',
    color: '#E8B004',
    secondaryColor: '#F0C84D',
  },
  ZPM: {
    code: 'ZPM',
    name: 'Zoram People\'s Movement',
    shortName: 'ZPM',
    color: '#1E90FF',
    secondaryColor: '#63B3FF',
  },
  NDPP: {
    code: 'NDPP',
    name: 'Nationalist Democratic Progressive Party',
    shortName: 'NDPP',
    color: '#2E8B57',
    secondaryColor: '#5CB88A',
  },
  SKM: {
    code: 'SKM',
    name: 'Sikkim Krantikari Morcha',
    shortName: 'SKM',
    color: '#DC143C',
    secondaryColor: '#E85D75',
  },
  TVK: {
    code: 'TVK',
    name: 'Tamilaga Vettri Kazhagam',
    shortName: 'TVK',
    color: '#8B008B',
    secondaryColor: '#B040B0',
  },
  AGP: {
    code: 'AGP',
    name: 'Asom Gana Parishad',
    shortName: 'AGP',
    color: '#228B22',
    secondaryColor: '#5CB85C',
  },
  BPF: {
    code: 'BPF',
    name: 'Bodoland People\'s Front',
    shortName: 'BPF',
    color: '#FF8C00',
    secondaryColor: '#FFB347',
  },
  BJD: {
    code: 'BJD',
    name: 'Biju Janata Dal',
    shortName: 'BJD',
    color: '#006B3F',
    secondaryColor: '#009E5C',
  },
  SAD: {
    code: 'SAD',
    name: 'Shiromani Akali Dal',
    shortName: 'SAD',
    color: '#0F5132',
    secondaryColor: '#1A7A4C',
  },
  AJSU: {
    code: 'AJSU',
    name: 'All Jharkhand Students Union',
    shortName: 'AJSU',
    color: '#FF8C00',
    secondaryColor: '#FFB347',
  },
  'ADSL': {
    code: 'ADSL',
    name: 'Azad Samaj Party (Kanshi Ram)',
    shortName: 'ASP',
    color: '#0F52BA',
    secondaryColor: '#4D85D6',
  },
  'AIADMK': {
    code: 'AIADMK',
    name: 'All India Anna Dravida Munnetra Kazhagam',
    shortName: 'AIADMK',
    color: '#009933',
    secondaryColor: '#33B35C',
  },
  'AIFB': {
    code: 'AIFB',
    name: 'All India Forward Bloc',
    shortName: 'AIFB',
    color: '#E32636',
    secondaryColor: '#EB6B76',
  },
  'AIMM': {
    code: 'AIMM',
    name: 'All India Majlis-e-Ittehadul Muslimeen',
    shortName: 'AIMIM',
    color: '#008000',
    secondaryColor: '#33B333',
  },
  'AINRC': {
    code: 'AINRC',
    name: 'All India N.R. Congress',
    shortName: 'AINRC',
    color: '#FFB300',
    secondaryColor: '#FFC94D',
  },
  'AJU': {
    code: 'AJU',
    name: 'regional (West Bengal)',
    shortName: 'AJU',
    color: '#7B68EE',
    secondaryColor: '#A293F2',
  },
  'AMMK': {
    code: 'AMMK',
    name: 'Amma Makkal Munnetra Kazhagam',
    shortName: 'AMMK',
    color: '#1B998B',
    secondaryColor: '#4DBFB3',
  },
  'AP': {
    code: 'AP',
    name: 'regional (Jharkhand)',
    shortName: 'AP',
    color: '#7E5109',
    secondaryColor: '#A87A33',
  },
  'BAP': {
    code: 'BAP',
    name: 'Bharat Adivasi Party',
    shortName: 'BAP',
    color: '#1E7D34',
    secondaryColor: '#4DA864',
  },
  'CMP(J)': {
    code: 'CMP(J)',
    name: 'Communist Marxist Party (John)',
    shortName: 'CMP(J)',
    color: '#B22222',
    secondaryColor: '#D45D5D',
  },
  'CONS': {
    code: 'CONS',
    name: 'Conservative / regional',
    shortName: 'CONS',
    color: '#5D6D7E',
    secondaryColor: '#869AAB',
  },
  'CPI(M)': {
    code: 'CPI(M)',
    name: 'Communist Party of India (Marxist)',
    shortName: 'CPI(M)',
    color: '#CC0000',
    secondaryColor: '#E64D4D',
  },
  'CPI(ML': {
    code: 'CPI(ML',
    name: 'CPI (Marxist-Leninist) Liberation',
    shortName: 'CPI(ML)',
    color: '#D2122E',
    secondaryColor: '#E0596B',
  },
  'GFP': {
    code: 'GFP',
    name: 'Goa Forward Party',
    shortName: 'GFP',
    color: '#FF6700',
    secondaryColor: '#FF9447',
  },
  'GGP': {
    code: 'GGP',
    name: 'Gondwana Gantantra Party',
    shortName: 'GGP',
    color: '#1E5631',
    secondaryColor: '#4D8366',
  },
  'GNC': {
    code: 'GNC',
    name: 'Garo National Council',
    shortName: 'GNC',
    color: '#2E8B57',
    secondaryColor: '#5CB88A',
  },
  'HAMS': {
    code: 'HAMS',
    name: 'Hindustani Awam Morcha (Secular)',
    shortName: 'HAM(S)',
    color: '#7A3E9D',
    secondaryColor: '#A06BC0',
  },
  'HSPDP': {
    code: 'HSPDP',
    name: 'Hill State People\'s Democratic Party',
    shortName: 'HSPDP',
    color: '#8B4513',
    secondaryColor: '#B5703A',
  },
  'INL': {
    code: 'INL',
    name: 'Indian National League',
    shortName: 'INL',
    color: '#1B7A3D',
    secondaryColor: '#4D9E68',
  },
  'INLD': {
    code: 'INLD',
    name: 'Indian National Lok Dal',
    shortName: 'INLD',
    color: '#138808',
    secondaryColor: '#4DAE4D',
  },
  'IPFT': {
    code: 'IPFT',
    name: 'Indigenous People\'s Front of Tripura',
    shortName: 'IPFT',
    color: '#FF7F00',
    secondaryColor: '#FFA64D',
  },
  'ISF': {
    code: 'ISF',
    name: 'Indian Secular Front',
    shortName: 'ISF',
    color: '#1C6EA4',
    secondaryColor: '#4D97C4',
  },
  'IUML': {
    code: 'IUML',
    name: 'Indian Union Muslim League',
    shortName: 'IUML',
    color: '#138808',
    secondaryColor: '#4DAE4D',
  },
  'JD(U)': {
    code: 'JD(U)',
    name: 'Janata Dal (United)',
    shortName: 'JD(U)',
    color: '#006400',
    secondaryColor: '#009700',
  },
  'JKC': {
    code: 'JKC',
    name: 'J&K regional',
    shortName: 'JKC',
    color: '#3A7CA5',
    secondaryColor: '#6FA3C4',
  },
  'JKNPP': {
    code: 'JKNPP',
    name: 'J&K National Panthers Party',
    shortName: 'JKNPP',
    color: '#FFD700',
    secondaryColor: '#FFE34D',
  },
  'JKPC': {
    code: 'JKPC',
    name: 'J&K People\'s Conference',
    shortName: 'JKPC',
    color: '#2E8B57',
    secondaryColor: '#5CB88A',
  },
  'JKPDP': {
    code: 'JKPDP',
    name: 'J&K Peoples Democratic Party',
    shortName: 'PDP',
    color: '#1B7A3D',
    secondaryColor: '#4D9E68',
  },
  'KC': {
    code: 'KC',
    name: 'Kerala Congress',
    shortName: 'KC',
    color: '#0B6E4F',
    secondaryColor: '#3E9374',
  },
  'KC(B)': {
    code: 'KC(B)',
    name: 'Kerala Congress (B)',
    shortName: 'KC(B)',
    color: '#0B6E4F',
    secondaryColor: '#3E9374',
  },
  'KC(M)': {
    code: 'KC(M)',
    name: 'Kerala Congress (M)',
    shortName: 'KC(M)',
    color: '#0B6E4F',
    secondaryColor: '#3E9374',
  },
  'KCJ': {
    code: 'KCJ',
    name: 'Kerala Congress (Jacob)',
    shortName: 'KCJ',
    color: '#0B6E4F',
    secondaryColor: '#3E9374',
  },
  'KCM': {
    code: 'KCM',
    name: 'Kerala Congress (M)',
    shortName: 'KC(M)',
    color: '#0B6E4F',
    secondaryColor: '#3E9374',
  },
  'KPA': {
    code: 'KPA',
    name: 'Kuki People\'s Alliance',
    shortName: 'KPA',
    color: '#B8860B',
    secondaryColor: '#D4AA3A',
  },
  'LJD': {
    code: 'LJD',
    name: 'Loktantrik Janata Dal',
    shortName: 'LJD',
    color: '#138808',
    secondaryColor: '#4DAE4D',
  },
  'LJK': {
    code: 'LJK',
    name: 'Lok Jananayaga Katchi',
    shortName: 'LJK',
    color: '#C71585',
    secondaryColor: '#D957A5',
  },
  'LJPRV': {
    code: 'LJPRV',
    name: 'Lok Janshakti Party (Ram Vilas)',
    shortName: 'LJP(RV)',
    color: '#6A0DAD',
    secondaryColor: '#9B4DD6',
  },
  'LJPV': {
    code: 'LJPV',
    name: 'Lok Janshakti Party (Ram Vilas)',
    shortName: 'LJP(RV)',
    color: '#6A0DAD',
    secondaryColor: '#9B4DD6',
  },
  'MG': {
    code: 'MG',
    name: 'Maharashtrawadi Gomantak Party',
    shortName: 'MGP',
    color: '#1F6FB2',
    secondaryColor: '#4D95C9',
  },
  'MNF': {
    code: 'MNF',
    name: 'Mizo National Front',
    shortName: 'MNF',
    color: '#006400',
    secondaryColor: '#2E8B2E',
  },
  'MNM': {
    code: 'MNM',
    name: 'Makkal Needhi Maiam',
    shortName: 'MNM',
    color: '#D81E5B',
    secondaryColor: '#E55D8A',
  },
  'NISHAD': {
    code: 'NISHAD',
    name: 'Nishad Party',
    shortName: 'NISHAD',
    color: '#1CA9C9',
    secondaryColor: '#5DC4D9',
  },
  'NMK': {
    code: 'NMK',
    name: 'Nam Tamilar / regional (Puducherry)',
    shortName: 'NMK',
    color: '#9932CC',
    secondaryColor: '#B566D6',
  },
  'NPF': {
    code: 'NPF',
    name: 'Naga People\'s Front',
    shortName: 'NPF',
    color: '#1B5E20',
    secondaryColor: '#4D8453',
  },
  'NSC': {
    code: 'NSC',
    name: 'Nationalist Party (Kerala)',
    shortName: 'NSC',
    color: '#4682B4',
    secondaryColor: '#79A6CC',
  },
  'PDF': {
    code: 'PDF',
    name: 'People\'s Democratic Front',
    shortName: 'PDF',
    color: '#607D8B',
    secondaryColor: '#8AA1AC',
  },
  'PMK': {
    code: 'PMK',
    name: 'Pattali Makkal Katchi',
    shortName: 'PMK',
    color: '#FFE135',
    secondaryColor: '#FFEB6B',
  },
  'PPA': {
    code: 'PPA',
    name: 'People\'s Party of Arunachal',
    shortName: 'PPA',
    color: '#FF8C00',
    secondaryColor: '#FFB347',
  },
  'RD': {
    code: 'RD',
    name: 'Raijor Dal',
    shortName: 'RD',
    color: '#C8102E',
    secondaryColor: '#D9536B',
  },
  'RGP': {
    code: 'RGP',
    name: 'Revolutionary Goans Party',
    shortName: 'RGP',
    color: '#8B0000',
    secondaryColor: '#B33A3A',
  },
  'RLD': {
    code: 'RLD',
    name: 'Rashtriya Lok Dal',
    shortName: 'RLD',
    color: '#007A33',
    secondaryColor: '#33A05C',
  },
  'RMPI': {
    code: 'RMPI',
    name: 'Revolutionary Marxist Party of India',
    shortName: 'RMPI',
    color: '#CC0000',
    secondaryColor: '#E64D4D',
  },
  'RPIA': {
    code: 'RPIA',
    name: 'Republican Party of India (Athawale)',
    shortName: 'RPI(A)',
    color: '#0000CD',
    secondaryColor: '#4D4DDB',
  },
  'RSP': {
    code: 'RSP',
    name: 'Revolutionary Socialist Party',
    shortName: 'RSP',
    color: '#D2122E',
    secondaryColor: '#E0596B',
  },
  'SBSP': {
    code: 'SBSP',
    name: 'Suheldev Bharatiya Samaj Party',
    shortName: 'SBSP',
    color: '#FFA500',
    secondaryColor: '#FFC04D',
  },
  'SDF': {
    code: 'SDF',
    name: 'Sikkim Democratic Front',
    shortName: 'SDF',
    color: '#20B2AA',
    secondaryColor: '#5CC7C1',
  },
  'TMP': {
    code: 'TMP',
    name: 'Tipra Motha Party',
    shortName: 'TMP',
    color: '#2F4FAF',
    secondaryColor: '#5E77C5',
  },
  'UDP': {
    code: 'UDP',
    name: 'United Democratic Party',
    shortName: 'UDP',
    color: '#00688B',
    secondaryColor: '#3A8FAC',
  },
  'UJP': {
    code: 'UJP',
    name: 'Uttarakhand Janata Party',
    shortName: 'UJP',
    color: '#556B2F',
    secondaryColor: '#7E9152',
  },
  'UKD': {
    code: 'UKD',
    name: 'Uttarakhand Kranti Dal',
    shortName: 'UKD',
    color: '#228B22',
    secondaryColor: '#52A852',
  },
  'VCK': {
    code: 'VCK',
    name: 'Viduthalai Chiruthaigal Katchi',
    shortName: 'VCK',
    color: '#D32F2F',
    secondaryColor: '#E06B6B',
  },
  'VIP': {
    code: 'VIP',
    name: 'Vikassheel Insaan Party',
    shortName: 'VIP',
    color: '#1E88E5',
    secondaryColor: '#5BA8ED',
  },
  'VPP': {
    code: 'VPP',
    name: 'Voice of the People Party',
    shortName: 'VPP',
    color: '#1565C0',
    secondaryColor: '#4D8AD0',
  },
  NDA: {
    code: 'NDA',
    name: 'National Democratic Alliance',
    shortName: 'NDA',
    color: '#FF6B00',
    secondaryColor: '#FF9A45',
  },
  NOTA: {
    code: 'NOTA',
    name: 'None of the Above',
    shortName: 'NOTA',
    color: '#808080',
    secondaryColor: '#A6A6A6',
  },
  IND: {
    code: 'IND',
    name: 'Independent',
    shortName: 'IND',
    color: '#999999',
    secondaryColor: '#BFBFBF',
  },
  OTH: {
    code: 'OTH',
    name: 'Other',
    shortName: 'Other',
    color: '#666666',
    secondaryColor: '#999999',
  },
};

export const getPartyColor = (party: PartyCode): string =>
  PARTY_CONFIG[party]?.color ?? '#666666';

export const getPartyName = (party: PartyCode): string =>
  PARTY_CONFIG[party]?.shortName ?? party;
