import type { StateInfo } from '../types/constituency';

export const STATES: Record<string, StateInfo> = {
  TS: {
    code: 'TS',
    name: 'Telangana',
    assemblySeats: 119,
    parliamentarySeats: 17,
    rulingParty: 'INC',
    centroid: { latitude: 17.8495, longitude: 79.1151 },
    zoom: 7,
  },
  AP: {
    code: 'AP',
    name: 'Andhra Pradesh',
    assemblySeats: 175,
    parliamentarySeats: 25,
    rulingParty: 'TDP',
    centroid: { latitude: 15.9129, longitude: 79.7400 },
    zoom: 7,
  },
  KA: {
    code: 'KA',
    name: 'Karnataka',
    assemblySeats: 224,
    parliamentarySeats: 28,
    rulingParty: 'INC',
    centroid: { latitude: 15.3173, longitude: 75.7139 },
    zoom: 6.5,
  },
  MH: {
    code: 'MH',
    name: 'Maharashtra',
    assemblySeats: 288,
    parliamentarySeats: 48,
    rulingParty: 'BJP',
    centroid: { latitude: 19.7515, longitude: 75.7139 },
    zoom: 6,
  },
  TN: {
    code: 'TN',
    name: 'Tamil Nadu',
    assemblySeats: 234,
    parliamentarySeats: 39,
    rulingParty: 'DMK',
    centroid: { latitude: 11.1271, longitude: 78.6569 },
    zoom: 6.5,
  },
  KL: {
    code: 'KL',
    name: 'Kerala',
    assemblySeats: 140,
    parliamentarySeats: 20,
    rulingParty: 'CPIM',
    centroid: { latitude: 10.8505, longitude: 76.2711 },
    zoom: 7,
  },
  WB: {
    code: 'WB',
    name: 'West Bengal',
    assemblySeats: 294,
    parliamentarySeats: 42,
    rulingParty: 'AITC',
    centroid: { latitude: 22.9868, longitude: 87.8550 },
    zoom: 6.5,
  },
  UP: {
    code: 'UP',
    name: 'Uttar Pradesh',
    assemblySeats: 403,
    parliamentarySeats: 80,
    rulingParty: 'BJP',
    centroid: { latitude: 26.8467, longitude: 80.9462 },
    zoom: 6,
  },
  RJ: {
    code: 'RJ',
    name: 'Rajasthan',
    assemblySeats: 200,
    parliamentarySeats: 25,
    rulingParty: 'BJP',
    centroid: { latitude: 27.0238, longitude: 74.2179 },
    zoom: 6,
  },
  GJ: {
    code: 'GJ',
    name: 'Gujarat',
    assemblySeats: 182,
    parliamentarySeats: 26,
    rulingParty: 'BJP',
    centroid: { latitude: 22.2587, longitude: 71.1924 },
    zoom: 6.5,
  },
  DL: {
    code: 'DL',
    name: 'Delhi',
    assemblySeats: 70,
    parliamentarySeats: 7,
    rulingParty: 'AAP',
    centroid: { latitude: 28.7041, longitude: 77.1025 },
    zoom: 10,
  },
  OD: {
    code: 'OD',
    name: 'Odisha',
    assemblySeats: 147,
    parliamentarySeats: 21,
    rulingParty: 'BJP',
    centroid: { latitude: 20.9517, longitude: 85.0985 },
    zoom: 6.5,
  },
  JH: {
    code: 'JH',
    name: 'Jharkhand',
    assemblySeats: 81,
    parliamentarySeats: 14,
    rulingParty: 'JMM',
    centroid: { latitude: 23.6102, longitude: 85.2799 },
    zoom: 7,
  },
  BR: {
    code: 'BR',
    name: 'Bihar',
    assemblySeats: 243,
    parliamentarySeats: 40,
    rulingParty: 'JDU',
    centroid: { latitude: 25.0961, longitude: 85.3131 },
    zoom: 6.5,
  },
  PB: {
    code: 'PB',
    name: 'Punjab',
    assemblySeats: 117,
    parliamentarySeats: 13,
    rulingParty: 'AAP',
    centroid: { latitude: 31.1471, longitude: 75.3412 },
    zoom: 7.5,
  },
  HR: {
    code: 'HR',
    name: 'Haryana',
    assemblySeats: 90,
    parliamentarySeats: 10,
    rulingParty: 'BJP',
    centroid: { latitude: 29.0588, longitude: 76.0856 },
    zoom: 7.5,
  },
  UK: {
    code: 'UK',
    name: 'Uttarakhand',
    assemblySeats: 70,
    parliamentarySeats: 5,
    rulingParty: 'BJP',
    centroid: { latitude: 30.0668, longitude: 79.0193 },
    zoom: 7.5,
  },
  CG: {
    code: 'CG',
    name: 'Chhattisgarh',
    assemblySeats: 90,
    parliamentarySeats: 11,
    rulingParty: 'BJP',
    centroid: { latitude: 21.2787, longitude: 81.8661 },
    zoom: 6.5,
  },
  MP: {
    code: 'MP',
    name: 'Madhya Pradesh',
    assemblySeats: 230,
    parliamentarySeats: 29,
    rulingParty: 'BJP',
    centroid: { latitude: 22.9734, longitude: 78.6569 },
    zoom: 6,
  },
  AS: {
    code: 'AS',
    name: 'Assam',
    assemblySeats: 126,
    parliamentarySeats: 14,
    rulingParty: 'BJP',
    centroid: { latitude: 26.2006, longitude: 92.9376 },
    zoom: 7,
  },
  GA: {
    code: 'GA',
    name: 'Goa',
    assemblySeats: 40,
    parliamentarySeats: 2,
    rulingParty: 'BJP',
    centroid: { latitude: 15.2993, longitude: 74.1240 },
    zoom: 9.5,
  },
  HP: {
    code: 'HP',
    name: 'Himachal Pradesh',
    assemblySeats: 68,
    parliamentarySeats: 4,
    rulingParty: 'INC',
    centroid: { latitude: 31.1048, longitude: 77.1734 },
    zoom: 7.5,
  },
  JK: {
    code: 'JK',
    name: 'Jammu & Kashmir',
    assemblySeats: 90,
    parliamentarySeats: 5,
    rulingParty: 'JKNC',
    centroid: { latitude: 33.7782, longitude: 76.5762 },
    zoom: 7,
  },
};

/** States that have full constituency data available */
export const FULLY_SUPPORTED_STATES = ['TS', 'AP', 'KA', 'MH'] as const;
export type FullySupportedStateCode = (typeof FULLY_SUPPORTED_STATES)[number];

/** States that have at least stub/partial data available */
export const SUPPORTED_STATES = ['TS', 'AP', 'KA', 'MH', 'TN', 'KL', 'WB', 'UP', 'RJ', 'GJ', 'DL', 'OD', 'JH', 'BR', 'PB', 'HR', 'UK', 'CG', 'MP', 'AS', 'GA', 'HP', 'JK'] as const;
export type SupportedStateCode = (typeof SUPPORTED_STATES)[number];

export const INDIA_CENTER = { latitude: 22.5937, longitude: 78.9629 };
export const INDIA_ZOOM = 4;
