/**
 * Candidate Photo Service — 4-Tier Pipeline
 * ─────────────────────────────────────────────────────────────────────
 * Priority:
 *  1. Static scraped map (MyNeta + Official Legislature sites) — bundled JSON, instant
 *  2. Wikipedia REST API — runtime fetch for ~100 notable politicians, cached
 *  3. Initials with party-colored background — last resort
 *
 * The static map is populated by running:
 *   npx ts-node scripts/scrape-candidate-photos.ts
 *
 * This generates data/candidate-photo-map.json which is bundled with the app.
 */

// ── Static photo map (generated by scraper, bundled at build time) ────
// Falls back to empty object if file hasn't been generated yet
let STATIC_PHOTO_MAP: Record<string, string> = {};
try {
  STATIC_PHOTO_MAP = require('@/data/candidate-photo-map.json');
} catch {
  // File not generated yet — scraper hasn't been run
}

/**
 * Normalise a candidate name for lookup: lowercase, collapse whitespace,
 * strip dots/commas, trim.
 */
function normaliseName(name: string): string {
  return name.toLowerCase().replace(/[.,]/g, '').replace(/\s+/g, ' ').trim();
}

/**
 * Curated mapping: Candidate Name → Wikipedia Article Title
 * Only notable politicians with Wikipedia articles are included.
 */
export const WIKIPEDIA_ARTICLES: Record<string, string> = {
  // ── National ──
  'Narendra Modi': 'Narendra_Modi',
  'Amit Shah': 'Amit_Shah',
  'Rajnath Singh': 'Rajnath_Singh',
  'Nitin Gadkari': 'Nitin_Gadkari',
  'Nirmala Sitharaman': 'Nirmala_Sitharaman',
  'S. Jaishankar': 'S._Jaishankar',
  'Smriti Irani': 'Smriti_Irani',
  'Rahul Gandhi': 'Rahul_Gandhi',
  'Sonia Gandhi': 'Sonia_Gandhi',
  'Mallikarjun Kharge': 'Mallikarjun_Kharge',

  // ── Telangana ──
  'A. Revanth Reddy': 'Anumula_Revanth_Reddy',
  'Revanth Reddy': 'Anumula_Revanth_Reddy',
  'K. Chandrashekar Rao': 'K._Chandrashekar_Rao',
  'K.T. Rama Rao': 'K._T._Rama_Rao',
  'T. Harish Rao': 'T._Harish_Rao',
  'Bhatti Vikramarka': 'Bhatti_Vikramarka',
  'Eatala Rajender': 'Eatala_Rajender',
  'Asaduddin Owaisi': 'Asaduddin_Owaisi',
  'G. Kishan Reddy': 'G._Kishan_Reddy',
  'Bandi Sanjay Kumar': 'Bandi_Sanjay_Kumar',
  'D. Sridhar Babu': 'D._Sridhar_Babu',
  'Konda Surekha': 'Konda_Surekha',
  'Nama Nageswara Rao': 'Nama_Nageswara_Rao',

  // ── Andhra Pradesh ──
  'N. Chandrababu Naidu': 'N._Chandrababu_Naidu',
  'Chandrababu Naidu': 'N._Chandrababu_Naidu',
  'Y.S. Jagan Mohan Reddy': 'Y._S._Jagan_Mohan_Reddy',
  'Jagan Mohan Reddy': 'Y._S._Jagan_Mohan_Reddy',
  'Pawan Kalyan': 'Pawan_Kalyan',
  'Nara Lokesh': 'Nara_Lokesh',
  'K. Atchannaidu': 'Kinjarapu_Atchannaidu',
  'Botcha Satyanarayana': 'Botcha_Satyanarayana',

  // ── Karnataka ──
  'Siddaramaiah': 'Siddaramaiah',
  'D.K. Shivakumar': 'D._K._Shivakumar',
  'B.S. Yediyurappa': 'B._S._Yediyurappa',
  'H.D. Kumaraswamy': 'H._D._Kumaraswamy',
  'B.Y. Raghavendra': 'B._Y._Raghavendra',
  'R. Ashoka': 'R._Ashok',
  'Pralhad Joshi': 'Pralhad_Joshi',
  'Basavaraj Bommai': 'Basavaraj_Bommai',

  // ── Maharashtra ──
  'Devendra Fadnavis': 'Devendra_Fadnavis',
  'Eknath Shinde': 'Eknath_Shinde',
  'Ajit Pawar': 'Ajit_Pawar',
  'Uddhav Thackeray': 'Uddhav_Thackeray',
  'Aaditya Thackeray': 'Aaditya_Thackeray',
  'Sharad Pawar': 'Sharad_Pawar',
  'Supriya Sule': 'Supriya_Sule',

  // ── Tamil Nadu ──
  'M.K. Stalin': 'M._K._Stalin',
  'Edappadi K. Palaniswami': 'Edappadi_K._Palaniswami',
  'K. Annamalai': 'K._Annamalai',
  'Udhayanidhi Stalin': 'Udhayanidhi_Stalin',
  'O. Panneerselvam': 'O._Panneerselvam',
  'T.R. Baalu': 'T._R._Baalu',
  'Kanimozhi': 'Kanimozhi',
  'Dayanidhi Maran': 'Dayanidhi_Maran',

  // ── Kerala ──
  'Pinarayi Vijayan': 'Pinarayi_Vijayan',
  'V.D. Satheesan': 'V._D._Satheesan',
  'K. Sudhakaran': 'K._Sudhakaran',
  'Shashi Tharoor': 'Shashi_Tharoor',
  'E. Sreedharan': 'E._Sreedharan',

  // ── West Bengal ──
  'Mamata Banerjee': 'Mamata_Banerjee',
  'Suvendu Adhikari': 'Suvendu_Adhikari',
  'Dilip Ghosh': 'Dilip_Ghosh',
  'Abhishek Banerjee': 'Abhishek_Banerjee_(politician)',

  // ── Uttar Pradesh ──
  'Yogi Adityanath': 'Yogi_Adityanath',
  'Akhilesh Yadav': 'Akhilesh_Yadav',
  'Mayawati': 'Mayawati',
  'Keshav Prasad Maurya': 'Keshav_Prasad_Maurya',
  'Brajesh Pathak': 'Brajesh_Pathak',
  'Azam Khan': 'Azam_Khan_(politician)',
};

// ── In-memory caches ─────────────────────────────────────────────────
const photoCache = new Map<string, string>();
const failedNames = new Set<string>();
let pendingCount = 0;
const MAX_CONCURRENT = 4;
const requestQueue: (() => void)[] = [];

function processQueue() {
  while (pendingCount < MAX_CONCURRENT && requestQueue.length > 0) {
    const next = requestQueue.shift();
    if (next) next();
  }
}

/**
 * Look up a photo from the static scraped map (MyNeta + Legislature).
 * Returns the photo URL or undefined if not found.
 */
export function getStaticPhoto(name: string): string | undefined {
  // Try exact key first, then normalised key
  return STATIC_PHOTO_MAP[name] ?? STATIC_PHOTO_MAP[normaliseName(name)];
}

/**
 * Fetch the Wikipedia thumbnail for a known politician.
 * Returns the direct image URL or null if unavailable.
 * Results are cached; failed lookups are not retried.
 */
export async function fetchWikipediaPhoto(name: string): Promise<string | null> {
  if (photoCache.has(name)) return photoCache.get(name) ?? null;
  if (failedNames.has(name)) return null;

  const article = WIKIPEDIA_ARTICLES[name];
  if (!article) return null;

  return new Promise<string | null>((resolve) => {
    const doFetch = async () => {
      pendingCount++;
      try {
        const resp = await fetch(
          `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(article)}`,
          { headers: { 'Accept': 'application/json' } },
        );
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        const data = await resp.json();
        const url = data?.thumbnail?.source;
        if (url) {
          const hiRes = url.replace(/\/\d+px-/, '/300px-');
          photoCache.set(name, hiRes);
          resolve(hiRes);
        } else {
          failedNames.add(name);
          resolve(null);
        }
      } catch {
        failedNames.add(name);
        resolve(null);
      } finally {
        pendingCount--;
        processQueue();
      }
    };

    if (pendingCount < MAX_CONCURRENT) {
      doFetch();
    } else {
      requestQueue.push(doFetch);
    }
  });
}

/**
 * Full candidate photo lookup — 4-tier pipeline.
 * Returns the best available photo URL, or null (= show initials).
 *
 * Priority:
 *  1. Explicit photoUrl passed in (from seed data)
 *  2. Static scraped map (MyNeta / Legislature)
 *  3. Wikipedia REST API (async, cached)
 *  4. null → component shows initials
 */
export async function getCandidatePhoto(
  name: string,
  photoUrl?: string,
): Promise<string | null> {
  // Tier 1: explicit photoUrl from seed data
  if (photoUrl) return photoUrl;

  // Tier 2: static scraped map (instant, bundled)
  const scraped = getStaticPhoto(name);
  if (scraped) return scraped;

  // Tier 3: Wikipedia runtime fetch
  const wiki = await fetchWikipediaPhoto(name);
  if (wiki) return wiki;

  // Tier 4: null — component renders initials
  return null;
}

/**
 * Check if a candidate has any known photo source (static map OR Wikipedia article).
 */
export function hasKnownPhoto(name: string): boolean {
  return (
    name in WIKIPEDIA_ARTICLES ||
    name in STATIC_PHOTO_MAP ||
    normaliseName(name) in STATIC_PHOTO_MAP
  );
}

/**
 * Get cached photo URL (synchronous, no fetch).
 * Checks static map first, then in-memory Wikipedia cache.
 */
export function getCachedPhoto(name: string): string | undefined {
  return getStaticPhoto(name) ?? photoCache.get(name);
}
