import { StyleSheet } from 'react-native';

/**
 * Styles for the map screen (app/(tabs)/index.tsx).
 *
 * IMPORTANT: this file lives in lib/ (NOT in app/) on purpose. Expo Router
 * treats every file inside app/ as a navigable route, so a styles module placed
 * there (e.g. app/(tabs)/index.styles.ts) shows up as a broken phantom tab.
 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF6EE',
  },
  map: {
    flex: 1,
  },
  header: {
    position: 'absolute',
    left: 14,
    right: 14,
    zIndex: 60,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 2.5,
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FCD34D',
    marginTop: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  actionButtons: {
    position: 'absolute',
    right: 14,
    gap: 8,
    alignItems: 'center',
    zIndex: 50,
  },
  actionItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
  },
  actionButton: {
    backgroundColor: '#0F172A',
    borderRadius: 22,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#C5A059',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 6,
  },
  actionButtonLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 2,
    textAlign: 'center',
    letterSpacing: 0.2,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  locateButton: {
    backgroundColor: '#991B1B',
    borderColor: '#EF4444',
  },
  compareButton: {
    backgroundColor: '#0F172A',
    borderColor: '#A78BFA',
  },
  searchButton: {
    backgroundColor: '#0F172A',
    borderColor: '#60A5FA',
  },
  resetButton: {
    backgroundColor: '#0F172A',
    borderColor: '#94A3B8',
  },
  activeButton: {
    backgroundColor: '#B45309',
    borderColor: '#FCD34D',
    borderWidth: 2,
  },
  delimButtonActive: {
    backgroundColor: '#065F46',
    borderColor: '#34D399',
    borderWidth: 2,
  },
  homeIndicator: {
    position: 'absolute',
    bottom: 20,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 92, 104, 0.15)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(20, 92, 104, 0.3)',
  },
  homeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#145C68',
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  userMarker: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(168, 32, 26, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userMarkerInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#A8201A',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  // ─── Bottom Sheet ───
  sheetBackground: {
    backgroundColor: '#FAF6EE',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: '#D8BC7E',
  },
  sheetHandle: {
    backgroundColor: '#C5A059',
    width: 40,
  },
  sheetContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  partyBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 14,
  },
  partyBadgeText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  sheetTitleGroup: {
    flex: 1,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#241814',
  },
  sheetSubtitle: {
    fontSize: 13,
    color: '#6D5549',
    marginTop: 2,
  },
  resultSection: {
    marginBottom: 14,
  },
  resultLabel: {
    fontSize: 12,
    color: '#988275',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  resultWinnerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 6,
  },
  sheetAvatarWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    overflow: 'hidden',
    backgroundColor: '#F5EFE4',
  },
  sheetAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  resultValue: {
    fontSize: 16,
    color: '#241814',
    fontWeight: '600',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8DED1',
  },
  statValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#241814',
  },
  statLabel: {
    fontSize: 11,
    color: '#988275',
    marginTop: 4,
  },
  defectionRow: {
    marginBottom: 14,
  },
  triviaRow: {
    marginBottom: 14,
  },
  colorToggleContainer: {
    position: 'absolute',
    left: 16,
  },
  bottomDashboardContainer: {
    position: 'absolute',
    bottom: 24,
    left: 12,
    right: 12,
    gap: 8,
    alignItems: 'center',
    zIndex: 10,
  },
  homeIndicatorUnified: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 92, 104, 0.15)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(20, 92, 104, 0.3)',
    alignSelf: 'center',
  },
  homeTextUnified: {
    fontSize: 11,
    fontWeight: '700',
    color: '#145C68',
  },
  detailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A8201A',
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
  },
  detailButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // ─── Historical mini-cards ───
  histRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
  },
  histMiniCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8DED1',
  },
  histMiniCardCurrent: {
    borderWidth: 1.5,
    borderColor: '#C5A059',
  },
  histMiniYear: {
    fontSize: 10,
    fontWeight: '700',
    color: '#988275',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  histMiniParty: {
    fontSize: 13,
    fontWeight: '800',
    color: '#241814',
    marginTop: 2,
  },
  // ─── Delimitation overlay ───
  delimBar: {
    position: 'absolute',
    bottom: 80,
    left: 10,
    right: 10,
    backgroundColor: '#1C1917F0',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#FCD34D40',
    elevation: 5,
  },
  delimBarTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  delimBarTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FCD34D',
    flex: 1,
  },
  delimBarBadge: {
    fontSize: 9,
    fontWeight: '800',
    color: '#F59E0B',
    backgroundColor: '#78350F50',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  delimBarLegend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 6,
  },
  delimDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  delimBarLbl: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  delimBarSpacer: {
    flex: 1,
  },
  delimBarStat: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  delimBarLink: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FCD34D',
    textAlign: 'center',
  },
  timeSliderWrapper: {
    width: '100%',
    alignItems: 'center',
  },
  idleTriviaWrapper: {
    width: '100%',
  },
  sheetCompareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#C5A05925',
    borderWidth: 1,
    borderColor: '#C5A05950',
    borderRadius: 12,
    paddingVertical: 10,
    gap: 6,
    marginBottom: 10,
  },
  sheetCompareText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#A8201A',
  },
  compareCard: {
    position: 'absolute',
    bottom: 20,
    left: 12,
    right: 12,
    backgroundColor: '#FAF6EE',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#D8BC7E',
    shadowColor: '#2C1810',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  compareHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DED1',
    paddingBottom: 6,
  },
  compareTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#241814',
    letterSpacing: 1,
  },
  compareClose: {
    padding: 4,
  },
  compareBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  compareCol: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E8DED1',
  },
  compareColLeft: {
    borderLeftWidth: 3,
    borderLeftColor: '#C5A059',
  },
  compareColRight: {
    borderLeftWidth: 3,
    borderLeftColor: '#145C68',
  },
  compareSeatName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#241814',
    marginBottom: 4,
  },
  compareParty: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6D5549',
  },
  compareStatLabel: {
    fontSize: 10,
    color: '#988275',
    marginTop: 6,
  },
  compareStatValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#241814',
  },
  // ─── Spatial Hub (Map-Only Mode) ───
  spatialHub: {
    position: 'absolute',
    bottom: 24,
    left: 12,
    right: 12,
    backgroundColor: '#FAF6EE',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#D8BC7E',
    maxHeight: 280,
    shadowColor: '#2C1810',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  spatialHubTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E8DED1',
    paddingBottom: 8,
    marginBottom: 10,
    gap: 16,
  },
  spatialHubTab: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  spatialHubTabActive: {
    backgroundColor: '#A8201A20',
  },
  spatialHubTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#988275',
  },
  spatialHubTabTextActive: {
    color: '#A8201A',
  },
  spatialHubScroll: {
    maxHeight: 200,
  },
  spatialHubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E8DED1',
  },
  spatialHubRowInfo: {
    flex: 1,
  },
  spatialHubRowTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#241814',
  },
  spatialHubRowSubtitle: {
    fontSize: 11,
    color: '#6D5549',
    marginTop: 2,
  },
  spatialHubDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 10,
  },
  spatialHubBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#F5EFE4',
  },
  spatialHubBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#241814',
  },
  spatialHubEmpty: {
    textAlign: 'center',
    color: '#988275',
    fontSize: 12,
    fontStyle: 'italic',
    paddingVertical: 20,
  },
  geoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(36, 24, 20, 0.45)',
    gap: 10,
  },
  geoOverlayText: {
    color: '#FAF6EE',
    fontSize: 13,
    fontWeight: '600',
  },
  geoRetryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#C5A059',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    marginTop: 4,
  },
  geoRetryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
});
