/**
 * Andhra Pradesh Assembly Constituencies — 2024 General Election (175 seats)
 *
 * SOURCE: English Wikipedia, "2024 Andhra Pradesh Legislative Assembly election",
 *         section "Results by constituency" (ECI-sourced). Auto-generated by
 *         scripts/build-ap-seed.mjs — do not hand-edit.
 *
 * Winner/runner-up names, parties, vote counts and margins are from the ECI
 * results as compiled on Wikipedia. Reservation status (GEN/SC/ST) is derived
 * from the official constituency-name suffix (e.g. "(SC)"). Telugu names are
 * carried over from prior data, matched by constituency name where available.
 *
 * PARTY TALLY 2024: TDP 135 | JSP 21 | BJP 8 | YSRCP 11 = 175
 */

export interface APConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in Telugu script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2024: string;
  winnerName2024: string;
  winnerVotes2024: number;
  /** Runner-up party code */
  runnerUp2024: string;
  margin2024: number;
  currentParty: string;
}

export const AP_CONSTITUENCIES: APConstituencySeed[] = [
  { acNo: 1, name: 'Ichchapuram', localName: 'ఇచ్చాపురం', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bendalam Ashok', winnerVotes2024: 110612, runnerUp2024: 'YSRCP', margin2024: 39783, currentParty: 'TDP' },
  { acNo: 2, name: 'Palasa', localName: 'పలాస', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gouthu Sireesha', winnerVotes2024: 101560, runnerUp2024: 'YSRCP', margin2024: 40350, currentParty: 'TDP' },
  { acNo: 3, name: 'Tekkali', localName: 'టెక్కలి', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kinjarapu Atchannaidu', winnerVotes2024: 107923, runnerUp2024: 'YSRCP', margin2024: 34435, currentParty: 'TDP' },
  { acNo: 4, name: 'Pathapatnam', localName: 'పాతపట్నం', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Mamidi Govinda Rao', winnerVotes2024: 89452, runnerUp2024: 'YSRCP', margin2024: 26527, currentParty: 'TDP' },
  { acNo: 5, name: 'Srikakulam', localName: 'శ్రీకాకుళం', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gondu Shankar', winnerVotes2024: 117091, runnerUp2024: 'YSRCP', margin2024: 52521, currentParty: 'TDP' },
  { acNo: 6, name: 'Amadalavalasa', localName: 'ఆమదాలవలస', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Koona Ravi Kumar', winnerVotes2024: 88003, runnerUp2024: 'YSRCP', margin2024: 35032, currentParty: 'TDP' },
  { acNo: 7, name: 'Etcherla', localName: 'ఎచ్చెర్ల', district: 'Srikakulam', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Nadukuditi Eswara Rao', winnerVotes2024: 112770, runnerUp2024: 'YSRCP', margin2024: 29089, currentParty: 'BJP' },
  { acNo: 8, name: 'Narasannapeta', localName: 'నరసన్నపేట', district: 'Srikakulam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Baggu Ramanamurthy', winnerVotes2024: 99951, runnerUp2024: 'YSRCP', margin2024: 29371, currentParty: 'TDP' },
  { acNo: 9, name: 'Rajam', localName: 'రాజాం', district: 'Vizianagaram', type: 'SC', winner2024: 'TDP', winnerName2024: 'Kondru Murali Mohan', winnerVotes2024: 94385, runnerUp2024: 'YSRCP', margin2024: 20722, currentParty: 'TDP' },
  { acNo: 10, name: 'Palakonda', district: 'Parvathipuram Manyam', type: 'ST', winner2024: 'JSP', winnerName2024: 'Nimmaka Jaya Krishna', winnerVotes2024: 75208, runnerUp2024: 'YSRCP', margin2024: 13291, currentParty: 'JSP' },
  { acNo: 11, name: 'Kurupam', localName: 'కురుపాం', district: 'Parvathipuram Manyam', type: 'ST', winner2024: 'TDP', winnerName2024: 'Jagadeeswari Thoyaka', winnerVotes2024: 83355, runnerUp2024: 'YSRCP', margin2024: 23500, currentParty: 'TDP' },
  { acNo: 12, name: 'Parvathipuram', localName: 'పార్వతీపురం', district: 'Parvathipuram Manyam', type: 'SC', winner2024: 'TDP', winnerName2024: 'Bonela Vijaya Chandra', winnerVotes2024: 83905, runnerUp2024: 'YSRCP', margin2024: 24414, currentParty: 'TDP' },
  { acNo: 13, name: 'Salur', localName: 'సాలూరు', district: 'Parvathipuram Manyam', type: 'ST', winner2024: 'TDP', winnerName2024: 'Gummidi Sandhyarani', winnerVotes2024: 80211, runnerUp2024: 'YSRCP', margin2024: 13733, currentParty: 'TDP' },
  { acNo: 14, name: 'Bobbili', localName: 'బొబ్బిలి', district: 'Vizianagaram', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Ravu Venkata Swetha Kumara Krishna Ranga Rao (BabyNayana)', winnerVotes2024: 112366, runnerUp2024: 'YSRCP', margin2024: 44648, currentParty: 'TDP' },
  { acNo: 15, name: 'Cheepurupalli', localName: 'చీపురుపల్లి', district: 'Vizianagaram', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kimidi Kalavenkata Rao', winnerVotes2024: 88225, runnerUp2024: 'YSRCP', margin2024: 11971, currentParty: 'TDP' },
  { acNo: 16, name: 'Gajapathinagaram', localName: 'గజపతినగరం', district: 'Vizianagaram', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kondapalli Srinivas', winnerVotes2024: 98051, runnerUp2024: 'YSRCP', margin2024: 25301, currentParty: 'TDP' },
  { acNo: 17, name: 'Nellimarla', localName: 'నెల్లిమర్ల', district: 'Vizianagaram', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Lokam Naga Madhavi', winnerVotes2024: 109915, runnerUp2024: 'YSRCP', margin2024: 39829, currentParty: 'JSP' },
  { acNo: 18, name: 'Vizianagaram', localName: 'విజయనగరం', district: 'Vizianagaram', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Pusapati Aditi Vijayalakshmi', winnerVotes2024: 121241, runnerUp2024: 'YSRCP', margin2024: 60609, currentParty: 'TDP' },
  { acNo: 19, name: 'Srungavarapukota', district: 'Vizianagaram', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kolla Lalitha Kumari', winnerVotes2024: 111026, runnerUp2024: 'YSRCP', margin2024: 38790, currentParty: 'TDP' },
  { acNo: 20, name: 'Bhimili', localName: 'భీమిలి', district: 'Visakhapatnam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Ganta Srinivasa Rao', winnerVotes2024: 176230, runnerUp2024: 'YSRCP', margin2024: 92401, currentParty: 'TDP' },
  { acNo: 21, name: 'Visakhapatnam East', localName: 'విశాఖపట్నం తూర్పు', district: 'Visakhapatnam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Velagapudi Ramakrishna Babu', winnerVotes2024: 132047, runnerUp2024: 'YSRCP', margin2024: 70877, currentParty: 'TDP' },
  { acNo: 22, name: 'Visakhapatnam South', localName: 'విశాఖపట్నం దక్షిణం', district: 'Visakhapatnam', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Vamsi Krishna Srinivasa Yadav', winnerVotes2024: 97868, runnerUp2024: 'YSRCP', margin2024: 64594, currentParty: 'JSP' },
  { acNo: 23, name: 'Visakhapatnam North', localName: 'విశాఖపట్నం ఉత్తరం', district: 'Visakhapatnam', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Penmetsa Vishnu Kumar Raju', winnerVotes2024: 108801, runnerUp2024: 'YSRCP', margin2024: 47534, currentParty: 'BJP' },
  { acNo: 24, name: 'Visakhapatnam West', localName: 'విశాఖపట్నం పశ్చిమ', district: 'Visakhapatnam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'P. G. V. R. Naidu', winnerVotes2024: 90805, runnerUp2024: 'YSRCP', margin2024: 35184, currentParty: 'TDP' },
  { acNo: 25, name: 'Gajuwaka', localName: 'గాజువాక', district: 'Visakhapatnam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Palla Srinivas Rao Yadav', winnerVotes2024: 157703, runnerUp2024: 'YSRCP', margin2024: 95235, currentParty: 'TDP' },
  { acNo: 26, name: 'Chodavaram', localName: 'చోడవరం', district: 'Anakapalli', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kalidindi Suryana Naga Sanyasi Raju', winnerVotes2024: 109651, runnerUp2024: 'YSRCP', margin2024: 42189, currentParty: 'TDP' },
  { acNo: 27, name: 'Madugula', localName: 'మాడుగుల', district: 'Anakapalli', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bandaru Satyanarayana Murthy', winnerVotes2024: 91869, runnerUp2024: 'YSRCP', margin2024: 28026, currentParty: 'TDP' },
  { acNo: 28, name: 'Araku Valley', localName: 'అరకు వ్యాలీ', district: 'Alluri Sitharama Raju', type: 'ST', winner2024: 'YSRCP', winnerName2024: 'Regam Matyalingam', winnerVotes2024: 65658, runnerUp2024: 'BJP', margin2024: 31877, currentParty: 'YSRCP' },
  { acNo: 29, name: 'Paderu', localName: 'పాడేరు', district: 'Alluri Sitharama Raju', type: 'ST', winner2024: 'YSRCP', winnerName2024: 'Matsyarasa Visweswara Raju', winnerVotes2024: 68170, runnerUp2024: 'TDP', margin2024: 19338, currentParty: 'YSRCP' },
  { acNo: 30, name: 'Anakapalle', district: 'Anakapalli', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Konathala Ramakrishna', winnerVotes2024: 115126, runnerUp2024: 'YSRCP', margin2024: 65764, currentParty: 'JSP' },
  { acNo: 31, name: 'Pendurthi', localName: 'పెందుర్తి', district: 'Visakhapatnam', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Panchakarla Ramesh Babu', winnerVotes2024: 149611, runnerUp2024: 'YSRCP', margin2024: 81870, currentParty: 'JSP' },
  { acNo: 32, name: 'Elamanchili', district: 'Anakapalli', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Sundarapu Vijay Kumar', winnerVotes2024: 109443, runnerUp2024: 'YSRCP', margin2024: 48956, currentParty: 'JSP' },
  { acNo: 33, name: 'Payakaraopet', district: 'Anakapalli', type: 'SC', winner2024: 'TDP', winnerName2024: 'Vangalapudi Anitha', winnerVotes2024: 120042, runnerUp2024: 'YSRCP', margin2024: 43727, currentParty: 'TDP' },
  { acNo: 34, name: 'Narsipatnam', localName: 'నర్సీపట్నం', district: 'Anakapalli', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Chintakayala Ayyanna Patrudu', winnerVotes2024: 99849, runnerUp2024: 'YSRCP', margin2024: 24676, currentParty: 'TDP' },
  { acNo: 35, name: 'Tuni', localName: 'తుని', district: 'Kakinada', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Yanamala Divya', winnerVotes2024: 97206, runnerUp2024: 'YSRCP', margin2024: 15177, currentParty: 'TDP' },
  { acNo: 36, name: 'Prathipadu (Kakinada)', district: 'Kakinada', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Varupula Satya Prabha', winnerVotes2024: 103002, runnerUp2024: 'YSRCP', margin2024: 38768, currentParty: 'TDP' },
  { acNo: 37, name: 'Pithapuram', localName: 'పిఠాపురం', district: 'Kakinada', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Pawan Kalyan', winnerVotes2024: 134394, runnerUp2024: 'YSRCP', margin2024: 70279, currentParty: 'JSP' },
  { acNo: 38, name: 'Kakinada Rural', localName: 'కాకినాడ రూరల్', district: 'Kakinada', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Pantham Venkateswara Rao', winnerVotes2024: 134414, runnerUp2024: 'YSRCP', margin2024: 72040, currentParty: 'JSP' },
  { acNo: 39, name: 'Peddapuram', localName: 'పెద్దాపురం', district: 'Kakinada', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nimmakayala Chinarajappa', winnerVotes2024: 105685, runnerUp2024: 'YSRCP', margin2024: 40451, currentParty: 'TDP' },
  { acNo: 40, name: 'Anaparthy', localName: 'అనపర్తి', district: 'East Godavari', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Nallamilli Ramakrishna Reddy', winnerVotes2024: 105720, runnerUp2024: 'YSRCP', margin2024: 20850, currentParty: 'BJP' },
  { acNo: 41, name: 'Kakinada City', localName: 'కాకినాడ సిటీ', district: 'Kakinada', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Vanamadi Venkateswara Rao', winnerVotes2024: 113014, runnerUp2024: 'YSRCP', margin2024: 56572, currentParty: 'TDP' },
  { acNo: 42, name: 'Ramachandrapuram', district: 'Konaseema', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Vasamsetti Subhash', winnerVotes2024: 97652, runnerUp2024: 'YSRCP', margin2024: 26291, currentParty: 'TDP' },
  { acNo: 43, name: 'Mummidivaram', district: 'Konaseema', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Datla Subbaraju', winnerVotes2024: 118687, runnerUp2024: 'YSRCP', margin2024: 38736, currentParty: 'TDP' },
  { acNo: 44, name: 'Amalapuram', localName: 'అమలాపురం', district: 'Konaseema', type: 'SC', winner2024: 'TDP', winnerName2024: 'Aithabathula Anandarao', winnerVotes2024: 104022, runnerUp2024: 'YSRCP', margin2024: 38628, currentParty: 'TDP' },
  { acNo: 45, name: 'Razole', localName: 'రాజోలు', district: 'Konaseema', type: 'SC', winner2024: 'JSP', winnerName2024: 'Deva Varaprasad', winnerVotes2024: 95514, runnerUp2024: 'YSRCP', margin2024: 39011, currentParty: 'JSP' },
  { acNo: 46, name: 'Gannavaram (Konaseema)', district: 'Konaseema', type: 'SC', winner2024: 'JSP', winnerName2024: 'Giddi Satyanarayana', winnerVotes2024: 96108, runnerUp2024: 'YSRCP', margin2024: 33367, currentParty: 'JSP' },
  { acNo: 47, name: 'Kothapeta', localName: 'కొత్తపేట', district: 'Konaseema', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bandaru Satyananda Rao', winnerVotes2024: 134286, runnerUp2024: 'YSRCP', margin2024: 56479, currentParty: 'TDP' },
  { acNo: 48, name: 'Mandapeta', localName: 'మండపేట', district: 'Konaseema', type: 'GEN', winner2024: 'TDP', winnerName2024: 'V. Jogeswara Rao', winnerVotes2024: 116309, runnerUp2024: 'YSRCP', margin2024: 44435, currentParty: 'TDP' },
  { acNo: 49, name: 'Rajanagaram', localName: 'రాజానగరం', district: 'East Godavari', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Bathula Balaramakrishna', winnerVotes2024: 105995, runnerUp2024: 'YSRCP', margin2024: 34049, currentParty: 'JSP' },
  { acNo: 50, name: 'Rajahmundry City', localName: 'రాజమండ్రి సిటీ', district: 'East Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Adireddy Srinivas', winnerVotes2024: 123291, runnerUp2024: 'YSRCP', margin2024: 71404, currentParty: 'TDP' },
  { acNo: 51, name: 'Rajahmundry Rural', localName: 'రాజమండ్రి రూరల్', district: 'East Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gorantla Butchaiah Chowdary', winnerVotes2024: 129060, runnerUp2024: 'YSRCP', margin2024: 64090, currentParty: 'TDP' },
  { acNo: 52, name: 'Jaggampeta', district: 'Kakinada', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Jyothula Nehru', winnerVotes2024: 113593, runnerUp2024: 'YSRCP', margin2024: 52676, currentParty: 'TDP' },
  { acNo: 53, name: 'Rampachodavaram', localName: 'రంపచోడవరం', district: 'Alluri Sitharama Raju', type: 'ST', winner2024: 'TDP', winnerName2024: 'Miryala Sirisha Devi', winnerVotes2024: 90087, runnerUp2024: 'YSRCP', margin2024: 9139, currentParty: 'TDP' },
  { acNo: 54, name: 'Kovvur', localName: 'కొవ్వూరు', district: 'East Godavari', type: 'SC', winner2024: 'TDP', winnerName2024: 'Muppidi Venkateswara Rao', winnerVotes2024: 92743, runnerUp2024: 'YSRCP', margin2024: 33946, currentParty: 'TDP' },
  { acNo: 55, name: 'Nidadavole', district: 'East Godavari', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Kandula Durgesh', winnerVotes2024: 102699, runnerUp2024: 'YSRCP', margin2024: 33304, currentParty: 'JSP' },
  { acNo: 56, name: 'Achanta', district: 'West Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Satyanarayana Pithani', winnerVotes2024: 85402, runnerUp2024: 'YSRCP', margin2024: 26554, currentParty: 'TDP' },
  { acNo: 57, name: 'Palakollu', district: 'West Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nimmala Ramanaidu', winnerVotes2024: 111471, runnerUp2024: 'YSRCP', margin2024: 66881, currentParty: 'TDP' },
  { acNo: 58, name: 'Narasapuram', localName: 'నరసాపురం', district: 'West Godavari', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Bommidi Narayana Nayakar', winnerVotes2024: 94116, runnerUp2024: 'YSRCP', margin2024: 49738, currentParty: 'JSP' },
  { acNo: 59, name: 'Bhimavaram', localName: 'భీమవరం', district: 'West Godavari', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Pulaparthi Ramanjaneyulu', winnerVotes2024: 130424, runnerUp2024: 'YSRCP', margin2024: 66974, currentParty: 'JSP' },
  { acNo: 60, name: 'Undi', localName: 'ఉండి', district: 'West Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kanumuru Raghu Rama Krishna Raju', winnerVotes2024: 116902, runnerUp2024: 'YSRCP', margin2024: 56777, currentParty: 'TDP' },
  { acNo: 61, name: 'Tanuku', localName: 'తణుకు', district: 'West Godavari', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Arimilli Radha Krishna', winnerVotes2024: 129547, runnerUp2024: 'YSRCP', margin2024: 72121, currentParty: 'TDP' },
  { acNo: 62, name: 'Tadepalligudem', localName: 'తాడేపల్లిగూడెం', district: 'West Godavari', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Bolisetti Srinivas', winnerVotes2024: 116443, runnerUp2024: 'YSRCP', margin2024: 62492, currentParty: 'JSP' },
  { acNo: 63, name: 'Unguturu', localName: 'ఉంగుటూరు', district: 'Eluru', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Dharmaraju Patsamatla', winnerVotes2024: 108894, runnerUp2024: 'YSRCP', margin2024: 44945, currentParty: 'JSP' },
  { acNo: 64, name: 'Denduluru', localName: 'దెందులూరు', district: 'Eluru', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Chintamaneni Prabhakar', winnerVotes2024: 107287, runnerUp2024: 'YSRCP', margin2024: 26266, currentParty: 'TDP' },
  { acNo: 65, name: 'Eluru', localName: 'ఏలూరు', district: 'Eluru', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Radha Krishnayya Badeti', winnerVotes2024: 111562, runnerUp2024: 'YSRCP', margin2024: 62388, currentParty: 'TDP' },
  { acNo: 66, name: 'Gopalapuram', localName: 'గోపాలపురం', district: 'East Godavari', type: 'SC', winner2024: 'TDP', winnerName2024: 'Maddipati Venkata Raju', winnerVotes2024: 114420, runnerUp2024: 'YSRCP', margin2024: 26784, currentParty: 'TDP' },
  { acNo: 67, name: 'Polavaram', localName: 'పోలవరం', district: 'Eluru', type: 'ST', winner2024: 'JSP', winnerName2024: 'Chirri Balaraju', winnerVotes2024: 101453, runnerUp2024: 'YSRCP', margin2024: 7935, currentParty: 'JSP' },
  { acNo: 68, name: 'Chintalapudi', localName: 'చింతలపూడి', district: 'Eluru', type: 'SC', winner2024: 'TDP', winnerName2024: 'Roshan Kumar Songa', winnerVotes2024: 120126, runnerUp2024: 'YSRCP', margin2024: 27766, currentParty: 'TDP' },
  { acNo: 69, name: 'Tiruvuru', localName: 'తిరువూరు', district: 'NTR', type: 'SC', winner2024: 'TDP', winnerName2024: 'Kolikapudi Srinivasa Rao', winnerVotes2024: 100719, runnerUp2024: 'YSRCP', margin2024: 21874, currentParty: 'TDP' },
  { acNo: 70, name: 'Nuzvid', localName: 'నూజివీడు', district: 'Eluru', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kolusu Parthasarathy', winnerVotes2024: 108229, runnerUp2024: 'YSRCP', margin2024: 12378, currentParty: 'TDP' },
  { acNo: 71, name: 'Gannavaram (Krishna)', district: 'Krishna', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Yarlagadda Venkata Rao', winnerVotes2024: 135552, runnerUp2024: 'YSRCP', margin2024: 37628, currentParty: 'TDP' },
  { acNo: 72, name: 'Gudivada', localName: 'గుడివాడ', district: 'Krishna', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Venigandla Ramu', winnerVotes2024: 109980, runnerUp2024: 'YSRCP', margin2024: 53040, currentParty: 'TDP' },
  { acNo: 73, name: 'Kaikalur', localName: 'కైకలూరు', district: 'Eluru', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Kamineni Srinivas', winnerVotes2024: 109280, runnerUp2024: 'YSRCP', margin2024: 45273, currentParty: 'BJP' },
  { acNo: 74, name: 'Pedana', localName: 'పెడన', district: 'Krishna', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kagitha Krishna Prasad', winnerVotes2024: 91394, runnerUp2024: 'YSRCP', margin2024: 38123, currentParty: 'TDP' },
  { acNo: 75, name: 'Machilipatnam', localName: 'మచిలీపట్నం', district: 'Krishna', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kollu Ravindra', winnerVotes2024: 105044, runnerUp2024: 'YSRCP', margin2024: 50242, currentParty: 'TDP' },
  { acNo: 76, name: 'Avanigadda', localName: 'అవనిగడ్డ', district: 'Krishna', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Mandali Buddha Prasad', winnerVotes2024: 113460, runnerUp2024: 'YSRCP', margin2024: 46434, currentParty: 'JSP' },
  { acNo: 77, name: 'Pamarru', localName: 'పామర్రు', district: 'Krishna', type: 'SC', winner2024: 'TDP', winnerName2024: 'Varla Kumar Raja', winnerVotes2024: 94189, runnerUp2024: 'YSRCP', margin2024: 29690, currentParty: 'TDP' },
  { acNo: 78, name: 'Penamaluru', district: 'Krishna', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bode Prasad', winnerVotes2024: 144912, runnerUp2024: 'YSRCP', margin2024: 59915, currentParty: 'TDP' },
  { acNo: 79, name: 'Vijayawada West', localName: 'విజయవాడ పశ్చిమ', district: 'NTR', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Sujana Chowdary', winnerVotes2024: 105669, runnerUp2024: 'YSRCP', margin2024: 47032, currentParty: 'BJP' },
  { acNo: 80, name: 'Vijayawada Central', localName: 'విజయవాడ సెంట్రల్', district: 'NTR', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bonda Umamaheswara Rao', winnerVotes2024: 130034, runnerUp2024: 'YSRCP', margin2024: 68886, currentParty: 'TDP' },
  { acNo: 81, name: 'Vijayawada East', localName: 'విజయవాడ తూర్పు', district: 'NTR', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gadde Rama Mohan', winnerVotes2024: 118841, runnerUp2024: 'YSRCP', margin2024: 49640, currentParty: 'TDP' },
  { acNo: 82, name: 'Mylavaram', localName: 'మైలవరం', district: 'NTR', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Vasantha Venkata Krishna Prasad', winnerVotes2024: 137338, runnerUp2024: 'YSRCP', margin2024: 42829, currentParty: 'TDP' },
  { acNo: 83, name: 'Nandigama', localName: 'నందిగామ', district: 'NTR', type: 'SC', winner2024: 'TDP', winnerName2024: 'Tangirala Sowmya', winnerVotes2024: 102201, runnerUp2024: 'YSRCP', margin2024: 27395, currentParty: 'TDP' },
  { acNo: 84, name: 'Jaggayyapeta', district: 'NTR', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Rajagopal Sreeram (Tataiah)', winnerVotes2024: 98479, runnerUp2024: 'YSRCP', margin2024: 15977, currentParty: 'TDP' },
  { acNo: 85, name: 'Pedakurapadu', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bhashyam Praveen', winnerVotes2024: 112957, runnerUp2024: 'YSRCP', margin2024: 21089, currentParty: 'TDP' },
  { acNo: 86, name: 'Tadikonda', localName: 'తాడికొండ', district: 'Guntur', type: 'SC', winner2024: 'TDP', winnerName2024: 'Tenali Sravan Kumar', winnerVotes2024: 109585, runnerUp2024: 'YSRCP', margin2024: 39606, currentParty: 'TDP' },
  { acNo: 87, name: 'Mangalagiri', localName: 'మంగళగిరి', district: 'Guntur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nara Lokesh', winnerVotes2024: 167710, runnerUp2024: 'YSRCP', margin2024: 91413, currentParty: 'TDP' },
  { acNo: 88, name: 'Ponnuru', district: 'Guntur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Dhulipalla Narendra Kumar', winnerVotes2024: 110410, runnerUp2024: 'YSRCP', margin2024: 32915, currentParty: 'TDP' },
  { acNo: 89, name: 'Vemuru', localName: 'వేమూరు', district: 'Bapatla', type: 'SC', winner2024: 'TDP', winnerName2024: 'Nakka Ananda Babu', winnerVotes2024: 94922, runnerUp2024: 'YSRCP', margin2024: 22021, currentParty: 'TDP' },
  { acNo: 90, name: 'Repalle', localName: 'రేపల్లె', district: 'Bapatla', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Anagani Satya Prasad', winnerVotes2024: 111129, runnerUp2024: 'YSRCP', margin2024: 39947, currentParty: 'TDP' },
  { acNo: 91, name: 'Tenali', localName: 'తెనాలి', district: 'Guntur', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Nadendla Manohar', winnerVotes2024: 123961, runnerUp2024: 'YSRCP', margin2024: 48112, currentParty: 'JSP' },
  { acNo: 92, name: 'Bapatla', localName: 'బాపట్ల', district: 'Bapatla', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Vegesana Narendra Varma Raju', winnerVotes2024: 90626, runnerUp2024: 'YSRCP', margin2024: 27768, currentParty: 'TDP' },
  { acNo: 93, name: 'Prathipadu (Guntur)', district: 'Guntur', type: 'SC', winner2024: 'TDP', winnerName2024: 'Burla Ramanjaneyulu', winnerVotes2024: 128665, runnerUp2024: 'YSRCP', margin2024: 42015, currentParty: 'TDP' },
  { acNo: 94, name: 'Guntur West', localName: 'గుంటూరు పశ్చిమ', district: 'Guntur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Galla Madhavi', winnerVotes2024: 116067, runnerUp2024: 'YSRCP', margin2024: 51150, currentParty: 'TDP' },
  { acNo: 95, name: 'Guntur East', localName: 'గుంటూరు తూర్పు', district: 'Guntur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Mohammed Naseer Ahmed', winnerVotes2024: 100815, runnerUp2024: 'YSRCP', margin2024: 31962, currentParty: 'TDP' },
  { acNo: 96, name: 'Chilakaluripet', localName: 'చిలకలూరిపేట', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Prathipati Pulla Rao', winnerVotes2024: 111062, runnerUp2024: 'YSRCP', margin2024: 33262, currentParty: 'TDP' },
  { acNo: 97, name: 'Narasaraopet', localName: 'నరసరావుపేట', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Chadalavada Aravinda Babu', winnerVotes2024: 103167, runnerUp2024: 'YSRCP', margin2024: 19705, currentParty: 'TDP' },
  { acNo: 98, name: 'Sattenapalle', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kanna Lakshminaraya', winnerVotes2024: 117965, runnerUp2024: 'YSRCP', margin2024: 27836, currentParty: 'TDP' },
  { acNo: 99, name: 'Vinukonda', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'G. V. Anjaneyulu', winnerVotes2024: 131438, runnerUp2024: 'YSRCP', margin2024: 30267, currentParty: 'TDP' },
  { acNo: 100, name: 'Gurajala', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Yarapathineni Srinivasa Rao', winnerVotes2024: 128201, runnerUp2024: 'YSRCP', margin2024: 29486, currentParty: 'TDP' },
  { acNo: 101, name: 'Macherla', localName: 'మాచర్ల', district: 'Palnadu', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Julakanti Brahmananda Reddy', winnerVotes2024: 122413, runnerUp2024: 'YSRCP', margin2024: 33318, currentParty: 'TDP' },
  { acNo: 102, name: 'Yerragondapalem', localName: 'యర్రగొండపాలెం', district: 'Prakasam', type: 'SC', winner2024: 'YSRCP', winnerName2024: 'Tatiparthi Chandrasekhar', winnerVotes2024: 91741, runnerUp2024: 'TDP', margin2024: 5200, currentParty: 'YSRCP' },
  { acNo: 103, name: 'Darsi', localName: 'దర్శి', district: 'Prakasam', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Buchepalli Siva Prasad Reddy', winnerVotes2024: 101889, runnerUp2024: 'TDP', margin2024: 2456, currentParty: 'YSRCP' },
  { acNo: 104, name: 'Parchur', localName: 'పర్చూరు', district: 'Bapatla', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Yeluri Sambasiva Rao', winnerVotes2024: 110575, runnerUp2024: 'YSRCP', margin2024: 24013, currentParty: 'TDP' },
  { acNo: 105, name: 'Addanki', localName: 'అద్దంకి', district: 'Bapatla', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gottipati Ravikumar', winnerVotes2024: 116418, runnerUp2024: 'YSRCP', margin2024: 24890, currentParty: 'TDP' },
  { acNo: 106, name: 'Chirala', localName: 'చీరాల', district: 'Bapatla', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Madduluri Malakondaiah Yadav', winnerVotes2024: 72700, runnerUp2024: 'YSRCP', margin2024: 20984, currentParty: 'TDP' },
  { acNo: 107, name: 'Santhanuthalapadu', localName: 'సంతనూతలపాడు', district: 'Prakasam', type: 'SC', winner2024: 'TDP', winnerName2024: 'B. N. Vijay Kumar', winnerVotes2024: 105757, runnerUp2024: 'YSRCP', margin2024: 30385, currentParty: 'TDP' },
  { acNo: 108, name: 'Ongole', localName: 'ఒంగోలు', district: 'Prakasam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Damacharla Janardhana Rao', winnerVotes2024: 118800, runnerUp2024: 'YSRCP', margin2024: 34026, currentParty: 'TDP' },
  { acNo: 109, name: 'Kandukur', localName: 'కందుకూరు', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Inturi Nageswara Rao', winnerVotes2024: 109173, runnerUp2024: 'YSRCP', margin2024: 18558, currentParty: 'TDP' },
  { acNo: 110, name: 'Kondapi', district: 'Prakasam', type: 'SC', winner2024: 'TDP', winnerName2024: 'Dola Sree Bala Veeranjaneya Swamy', winnerVotes2024: 116674, runnerUp2024: 'YSRCP', margin2024: 24756, currentParty: 'TDP' },
  { acNo: 111, name: 'Markapuram', localName: 'మార్కాపురం', district: 'Prakasam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kandula Narayana Reddy', winnerVotes2024: 99005, runnerUp2024: 'YSRCP', margin2024: 13979, currentParty: 'TDP' },
  { acNo: 112, name: 'Giddalur', localName: 'గిద్దలూరు', district: 'Prakasam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Muthumula Ashok Reddy', winnerVotes2024: 98463, runnerUp2024: 'YSRCP', margin2024: 973, currentParty: 'TDP' },
  { acNo: 113, name: 'Kanigiri', localName: 'కనిగిరి', district: 'Prakasam', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Mukku Ugra Narasimha Reddy', winnerVotes2024: 107045, runnerUp2024: 'YSRCP', margin2024: 14604, currentParty: 'TDP' },
  { acNo: 114, name: 'Kavali', localName: 'కావలి', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Dagumati Venkata Krishna Reddy', winnerVotes2024: 106536, runnerUp2024: 'YSRCP', margin2024: 30948, currentParty: 'TDP' },
  { acNo: 115, name: 'Atmakur', localName: 'ఆత్మకూరు', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Anam Ramanarayana Reddy', winnerVotes2024: 91165, runnerUp2024: 'YSRCP', margin2024: 7576, currentParty: 'TDP' },
  { acNo: 116, name: 'Kovur', localName: 'కొవ్వూరు', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Vemireddy Prashanti Reddy', winnerVotes2024: 130623, runnerUp2024: 'YSRCP', margin2024: 54583, currentParty: 'TDP' },
  { acNo: 117, name: 'Nellore City', localName: 'నెల్లూరు సిటీ', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Ponguru Narayana', winnerVotes2024: 120551, runnerUp2024: 'YSRCP', margin2024: 72489, currentParty: 'TDP' },
  { acNo: 118, name: 'Nellore Rural', localName: 'నెల్లూరు రూరల్', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kotamreddy Sridhar Reddy', winnerVotes2024: 109975, runnerUp2024: 'YSRCP', margin2024: 34480, currentParty: 'TDP' },
  { acNo: 119, name: 'Sarvepalli', localName: 'సర్వేపల్లి', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Somireddy Chandra Mohan Reddy', winnerVotes2024: 103278, runnerUp2024: 'YSRCP', margin2024: 16288, currentParty: 'TDP' },
  { acNo: 120, name: 'Gudur', localName: 'గూడూరు', district: 'Tirupati', type: 'SC', winner2024: 'TDP', winnerName2024: 'Pasam Sunil Kumar', winnerVotes2024: 102675, runnerUp2024: 'YSRCP', margin2024: 21192, currentParty: 'TDP' },
  { acNo: 121, name: 'Sullurpeta', localName: 'సూళ్లూరుపేట', district: 'Tirupati', type: 'SC', winner2024: 'TDP', winnerName2024: 'Nelavala Vijayasree', winnerVotes2024: 111048, runnerUp2024: 'YSRCP', margin2024: 29115, currentParty: 'TDP' },
  { acNo: 122, name: 'Venkatagiri', localName: 'వెంకటగిరి', district: 'Tirupati', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kurugondla Ramakrishna', winnerVotes2024: 104398, runnerUp2024: 'YSRCP', margin2024: 16294, currentParty: 'TDP' },
  { acNo: 123, name: 'Udayagiri', localName: 'ఉదయగిరి', district: 'Nellore', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kakarla Suresh', winnerVotes2024: 101537, runnerUp2024: 'YSRCP', margin2024: 9621, currentParty: 'TDP' },
  { acNo: 124, name: 'Badvel', localName: 'బద్వేల్', district: 'Kadapa', type: 'SC', winner2024: 'YSRCP', winnerName2024: 'Dasari Sudha', winnerVotes2024: 90410, runnerUp2024: 'BJP', margin2024: 18567, currentParty: 'YSRCP' },
  { acNo: 125, name: 'Rajampet', localName: 'రాజంపేట', district: 'Annamayya', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Akepati Amarnath Reddy', winnerVotes2024: 92609, runnerUp2024: 'TDP', margin2024: 7016, currentParty: 'YSRCP' },
  { acNo: 126, name: 'Kadapa', localName: 'కడప', district: 'Kadapa', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Reddeppagari Madhavi', winnerVotes2024: 90988, runnerUp2024: 'YSRCP', margin2024: 18860, currentParty: 'TDP' },
  { acNo: 127, name: 'Kodur', localName: 'కోడూరు', district: 'Annamayya', type: 'SC', winner2024: 'JSP', winnerName2024: 'Arava Sreedhar', winnerVotes2024: 78594, runnerUp2024: 'YSRCP', margin2024: 11101, currentParty: 'JSP' },
  { acNo: 128, name: 'Rayachoti', district: 'Annamayya', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Mandipalli Ramprasad Reddy', winnerVotes2024: 95925, runnerUp2024: 'YSRCP', margin2024: 2495, currentParty: 'TDP' },
  { acNo: 129, name: 'Pulivendla', district: 'Kadapa', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Y. S. Jagan Mohan Reddy', winnerVotes2024: 116315, runnerUp2024: 'TDP', margin2024: 61687, currentParty: 'YSRCP' },
  { acNo: 130, name: 'Kamalapuram', localName: 'కమలాపురం', district: 'Kadapa', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Putha Krishna Chaitanya Reddy', winnerVotes2024: 95207, runnerUp2024: 'YSRCP', margin2024: 25357, currentParty: 'TDP' },
  { acNo: 131, name: 'Jammalamadugu', localName: 'జమ్మలమడుగు', district: 'Kadapa', type: 'GEN', winner2024: 'BJP', winnerName2024: 'C. Adinarayana Reddy', winnerVotes2024: 109640, runnerUp2024: 'YSRCP', margin2024: 17191, currentParty: 'BJP' },
  { acNo: 132, name: 'Proddatur', localName: 'ప్రొద్దుటూరు', district: 'Kadapa', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nandyala Varada Rajula Reddy', winnerVotes2024: 106712, runnerUp2024: 'YSRCP', margin2024: 22744, currentParty: 'TDP' },
  { acNo: 133, name: 'Mydukur', localName: 'మైదుకూరు', district: 'Kadapa', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Putta Sudhakar Yadav', winnerVotes2024: 96181, runnerUp2024: 'YSRCP', margin2024: 20950, currentParty: 'TDP' },
  { acNo: 134, name: 'Allagadda', localName: 'ఆళ్లగడ్డ', district: 'Nandyal', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bhuma Akhila Priya', winnerVotes2024: 98881, runnerUp2024: 'YSRCP', margin2024: 12037, currentParty: 'TDP' },
  { acNo: 135, name: 'Srisailam', localName: 'శ్రీశైలం', district: 'Nandyal', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Budda Raja Sekhara Reddy', winnerVotes2024: 81699, runnerUp2024: 'YSRCP', margin2024: 6385, currentParty: 'TDP' },
  { acNo: 136, name: 'Nandikotkur', localName: 'నందికొట్కూరు', district: 'Nandyal', type: 'SC', winner2024: 'TDP', winnerName2024: 'Githa Jayasurya', winnerVotes2024: 92004, runnerUp2024: 'YSRCP', margin2024: 9792, currentParty: 'TDP' },
  { acNo: 137, name: 'Kurnool', localName: 'కర్నూలు', district: 'Kurnool', type: 'GEN', winner2024: 'TDP', winnerName2024: 'T. G. Bharath', winnerVotes2024: 91690, runnerUp2024: 'YSRCP', margin2024: 18876, currentParty: 'TDP' },
  { acNo: 138, name: 'Panyam', localName: 'పాణ్యం', district: 'Kurnool', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gowru Charitha Reddy', winnerVotes2024: 141272, runnerUp2024: 'YSRCP', margin2024: 40591, currentParty: 'TDP' },
  { acNo: 139, name: 'Nandyal', localName: 'నంద్యాల', district: 'Nandyal', type: 'GEN', winner2024: 'TDP', winnerName2024: 'N. M. D. Farooq', winnerVotes2024: 103075, runnerUp2024: 'YSRCP', margin2024: 12333, currentParty: 'TDP' },
  { acNo: 140, name: 'Banaganapalle', localName: 'బనగానపల్లె', district: 'Nandyal', type: 'GEN', winner2024: 'TDP', winnerName2024: 'B. C. Janardhan Reddy', winnerVotes2024: 110603, runnerUp2024: 'YSRCP', margin2024: 25566, currentParty: 'TDP' },
  { acNo: 141, name: 'Dhone', localName: 'డోన్', district: 'Nandyal', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kotla Jayasurya Prakasha Reddy', winnerVotes2024: 93523, runnerUp2024: 'YSRCP', margin2024: 6049, currentParty: 'TDP' },
  { acNo: 142, name: 'Pattikonda', district: 'Kurnool', type: 'GEN', winner2024: 'TDP', winnerName2024: 'K. E. Shyam Babu', winnerVotes2024: 98849, runnerUp2024: 'YSRCP', margin2024: 14211, currentParty: 'TDP' },
  { acNo: 143, name: 'Kodumur', localName: 'కోడుమూరు', district: 'Kurnool', type: 'SC', winner2024: 'TDP', winnerName2024: 'Boggula Dastagiri', winnerVotes2024: 101703, runnerUp2024: 'YSRCP', margin2024: 21583, currentParty: 'TDP' },
  { acNo: 144, name: 'Yemmiganur', district: 'Kurnool', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Jaya Nageswara Reddy', winnerVotes2024: 103089, runnerUp2024: 'YSRCP', margin2024: 15837, currentParty: 'TDP' },
  { acNo: 145, name: 'Mantralayam', localName: 'మంత్రాలయం', district: 'Kurnool', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Y. Balanagi Reddy', winnerVotes2024: 87662, runnerUp2024: 'TDP', margin2024: 12805, currentParty: 'YSRCP' },
  { acNo: 146, name: 'Adoni', localName: 'ఆదోని', district: 'Kurnool', type: 'GEN', winner2024: 'BJP', winnerName2024: 'P. V. Parthasarathi', winnerVotes2024: 89929, runnerUp2024: 'YSRCP', margin2024: 18164, currentParty: 'BJP' },
  { acNo: 147, name: 'Alur', localName: 'ఆలూరు', district: 'Kurnool', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Busine Virupakshi', winnerVotes2024: 100264, runnerUp2024: 'TDP', margin2024: 2831, currentParty: 'YSRCP' },
  { acNo: 148, name: 'Rayadurg', localName: 'రాయదుర్గం', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kalava Srinivasulu', winnerVotes2024: 130309, runnerUp2024: 'YSRCP', margin2024: 41659, currentParty: 'TDP' },
  { acNo: 149, name: 'Uravakonda', localName: 'ఉరవకొండ', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Payyavula Keshav', winnerVotes2024: 102046, runnerUp2024: 'YSRCP', margin2024: 21704, currentParty: 'TDP' },
  { acNo: 150, name: 'Guntakal', localName: 'గుంతకల్లు', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gummanuru Jayaram', winnerVotes2024: 101700, runnerUp2024: 'YSRCP', margin2024: 6826, currentParty: 'TDP' },
  { acNo: 151, name: 'Tadipatri', localName: 'తాడిపత్రి', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'J. C. Ashmit Reddy', winnerVotes2024: 113755, runnerUp2024: 'YSRCP', margin2024: 27731, currentParty: 'TDP' },
  { acNo: 152, name: 'Singanamala', localName: 'శింగనమల', district: 'Anantapur', type: 'SC', winner2024: 'TDP', winnerName2024: 'Bandaru Sravani Sree', winnerVotes2024: 102957, runnerUp2024: 'YSRCP', margin2024: 8788, currentParty: 'TDP' },
  { acNo: 153, name: 'Anantapur Urban', localName: 'అనంతపురం అర్బన్', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Daggupati Venkateswara Prasad', winnerVotes2024: 103334, runnerUp2024: 'YSRCP', margin2024: 23023, currentParty: 'TDP' },
  { acNo: 154, name: 'Kalyandurg', localName: 'కల్యాణదుర్గం', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Amilineni Surendra Babu', winnerVotes2024: 118878, runnerUp2024: 'YSRCP', margin2024: 37734, currentParty: 'TDP' },
  { acNo: 155, name: 'Raptadu', localName: 'రాప్తాడు', district: 'Anantapur', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Paritala Sunitha', winnerVotes2024: 116140, runnerUp2024: 'YSRCP', margin2024: 23329, currentParty: 'TDP' },
  { acNo: 156, name: 'Madakasira', district: 'Sri Sathya Sai', type: 'SC', winner2024: 'TDP', winnerName2024: 'M. S. Raju', winnerVotes2024: 79983, runnerUp2024: 'YSRCP', margin2024: 351, currentParty: 'TDP' },
  { acNo: 157, name: 'Hindupur', localName: 'హిందూపురం', district: 'Sri Sathya Sai', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nandamuri Balakrishna', winnerVotes2024: 107250, runnerUp2024: 'YSRCP', margin2024: 32597, currentParty: 'TDP' },
  { acNo: 158, name: 'Penukonda', localName: 'పెనుకొండ', district: 'Sri Sathya Sai', type: 'GEN', winner2024: 'TDP', winnerName2024: 'S. Savitha', winnerVotes2024: 113832, runnerUp2024: 'YSRCP', margin2024: 33388, currentParty: 'TDP' },
  { acNo: 159, name: 'Puttaparthi', localName: 'పుట్టపర్తి', district: 'Sri Sathya Sai', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Palle Sindhura Reddy', winnerVotes2024: 91741, runnerUp2024: 'YSRCP', margin2024: 8760, currentParty: 'TDP' },
  { acNo: 160, name: 'Dharmavaram', localName: 'ధర్మవరం', district: 'Sri Sathya Sai', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Y. Satya Kumar Yadav', winnerVotes2024: 106544, runnerUp2024: 'YSRCP', margin2024: 3734, currentParty: 'BJP' },
  { acNo: 161, name: 'Kadiri', localName: 'కదిరి', district: 'Sri Sathya Sai', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Kandikunta Venkata Prasad', winnerVotes2024: 103610, runnerUp2024: 'YSRCP', margin2024: 6265, currentParty: 'TDP' },
  { acNo: 162, name: 'Thamballapalle', localName: 'తంబళ్లపల్లె', district: 'Annamayya', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Peddireddy Dwarkanatha Reddy', winnerVotes2024: 94136, runnerUp2024: 'TDP', margin2024: 10103, currentParty: 'YSRCP' },
  { acNo: 163, name: 'Pileru', localName: 'పీలేరు', district: 'Annamayya', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Nallari Kishore Kumar Reddy', winnerVotes2024: 105582, runnerUp2024: 'YSRCP', margin2024: 25081, currentParty: 'TDP' },
  { acNo: 164, name: 'Madanapalle', localName: 'మదనపల్లి', district: 'Annamayya', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Shahjahan Basha', winnerVotes2024: 97980, runnerUp2024: 'YSRCP', margin2024: 5509, currentParty: 'TDP' },
  { acNo: 165, name: 'Punganur', localName: 'పుంగనూరు', district: 'Chittoor', type: 'GEN', winner2024: 'YSRCP', winnerName2024: 'Peddireddy Ramachandra Reddy', winnerVotes2024: 100793, runnerUp2024: 'TDP', margin2024: 6095, currentParty: 'YSRCP' },
  { acNo: 166, name: 'Chandragiri', localName: 'చంద్రగిరి', district: 'Tirupati', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Pullivarthi Venkata Mani Prasad', winnerVotes2024: 143667, runnerUp2024: 'YSRCP', margin2024: 43852, currentParty: 'TDP' },
  { acNo: 167, name: 'Tirupati', localName: 'తిరుపతి', district: 'Tirupati', type: 'GEN', winner2024: 'JSP', winnerName2024: 'Arani Srinivasulu', winnerVotes2024: 124107, runnerUp2024: 'YSRCP', margin2024: 61956, currentParty: 'JSP' },
  { acNo: 168, name: 'Srikalahasti', localName: 'శ్రీకాళహస్తి', district: 'Tirupati', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Bojjala Venkata Sudhir Reddy', winnerVotes2024: 121565, runnerUp2024: 'YSRCP', margin2024: 43304, currentParty: 'TDP' },
  { acNo: 169, name: 'Sathyavedu', district: 'Tirupati', type: 'SC', winner2024: 'TDP', winnerName2024: 'Koneti Adimulam', winnerVotes2024: 85471, runnerUp2024: 'YSRCP', margin2024: 3739, currentParty: 'TDP' },
  { acNo: 170, name: 'Nagari', localName: 'నగరి', district: 'Chittoor', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gali Bhanu Prakash', winnerVotes2024: 107797, runnerUp2024: 'YSRCP', margin2024: 45004, currentParty: 'TDP' },
  { acNo: 171, name: 'Gangadhara Nellore', localName: 'గంగాధర నెల్లూరు', district: 'Chittoor', type: 'SC', winner2024: 'TDP', winnerName2024: 'V. M. Thomas', winnerVotes2024: 101176, runnerUp2024: 'YSRCP', margin2024: 26011, currentParty: 'TDP' },
  { acNo: 172, name: 'Chittoor', localName: 'చిత్తూరు', district: 'Chittoor', type: 'GEN', winner2024: 'TDP', winnerName2024: 'Gurajala Jagan Mohan', winnerVotes2024: 88066, runnerUp2024: 'YSRCP', margin2024: 14604, currentParty: 'TDP' },
  { acNo: 173, name: 'Puthalapattu', localName: 'పూతలపట్టు', district: 'Chittoor', type: 'SC', winner2024: 'TDP', winnerName2024: 'Kalikiri Murali Mohan', winnerVotes2024: 102137, runnerUp2024: 'YSRCP', margin2024: 15634, currentParty: 'TDP' },
  { acNo: 174, name: 'Palamaner', localName: 'పలమనేరు', district: 'Chittoor', type: 'GEN', winner2024: 'TDP', winnerName2024: 'N. Amarnath Reddy', winnerVotes2024: 123232, runnerUp2024: 'YSRCP', margin2024: 20122, currentParty: 'TDP' },
  { acNo: 175, name: 'Kuppam', localName: 'కుప్పం', district: 'Chittoor', type: 'GEN', winner2024: 'TDP', winnerName2024: 'N. Chandrababu Naidu', winnerVotes2024: 121929, runnerUp2024: 'YSRCP', margin2024: 48006, currentParty: 'TDP' },
];

/** Get constituency data by AC number */
export function getAPConstituency(acNo: number): APConstituencySeed | undefined {
  return AP_CONSTITUENCIES.find((c) => c.acNo === acNo);
}

/** Get all constituencies in a district */
export function getAPConstituenciesByDistrict(district: string): APConstituencySeed[] {
  return AP_CONSTITUENCIES.filter((c) => c.district.toLowerCase() === district.toLowerCase());
}

/** Get all constituencies won by a party */
export function getAPConstituenciesByParty(party: string): APConstituencySeed[] {
  return AP_CONSTITUENCIES.filter((c) => c.currentParty === party);
}
