/**
 * AR Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2019 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const AR_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 27401, totalVoters: 8918, turnout2023: 89.61, maleVoters: 4548, femaleVoters: 4370, literacy: 68.9, urbanPercent: 22.8, scPercent: 0, stPercent: 67.7, areaSqKm: 1562 },
  { acNo: 2, population: 29502, totalVoters: 9970, turnout2023: 76.46, maleVoters: 5085, femaleVoters: 4885, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 3, population: 30941, totalVoters: 7342, turnout2023: 82.87, maleVoters: 3722, femaleVoters: 3620, literacy: 64.3, urbanPercent: 22.8, scPercent: 0, stPercent: 67.7, areaSqKm: 1386 },
  { acNo: 4, population: 27765, totalVoters: 14020, turnout2023: 72, maleVoters: 6961, femaleVoters: 7059, literacy: 68, urbanPercent: 22.8, scPercent: 0, stPercent: 67.7, areaSqKm: 1469 },
  { acNo: 5, population: 32646, totalVoters: 9637, turnout2023: 87.09, maleVoters: 4881, femaleVoters: 4756, literacy: 68.9, urbanPercent: 26.2, scPercent: 0, stPercent: 67.7, areaSqKm: 1489 },
  { acNo: 6, population: 31490, totalVoters: 13166, turnout2023: 80, maleVoters: 6478, femaleVoters: 6688, literacy: 65.2, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1313 },
  { acNo: 7, population: 29204, totalVoters: 10062, turnout2023: 80.09, maleVoters: 5177, femaleVoters: 4885, literacy: 64.3, urbanPercent: 19.5, scPercent: 0, stPercent: 75.2, areaSqKm: 1553 },
  { acNo: 8, population: 31681, totalVoters: 11094, turnout2023: 88.1, maleVoters: 5675, femaleVoters: 5419, literacy: 64.3, urbanPercent: 21.7, scPercent: 0, stPercent: 75.2, areaSqKm: 1465 },
  { acNo: 9, population: 29502, totalVoters: 11878, turnout2023: 87.23, maleVoters: 6058, femaleVoters: 5820, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 10, population: 27800, totalVoters: 10328, turnout2023: 81.3, maleVoters: 5091, femaleVoters: 5237, literacy: 65.2, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1567 },
  { acNo: 11, population: 31480, totalVoters: 7291, turnout2023: 91.47, maleVoters: 3620, femaleVoters: 3671, literacy: 69.8, urbanPercent: 19.5, scPercent: 1, stPercent: 67.7, areaSqKm: 1337 },
  { acNo: 12, population: 29502, totalVoters: 7936, turnout2023: 86.69, maleVoters: 4047, femaleVoters: 3889, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 13, population: 28967, totalVoters: 61252, turnout2023: 44.82, maleVoters: 30810, femaleVoters: 30442, literacy: 64.3, urbanPercent: 19.5, scPercent: 0, stPercent: 67.7, areaSqKm: 1327 },
  { acNo: 14, population: 31594, totalVoters: 21938, turnout2023: 73.8, maleVoters: 10969, femaleVoters: 10969, literacy: 64.3, urbanPercent: 21.7, scPercent: 0, stPercent: 67.7, areaSqKm: 1631 },
  { acNo: 15, population: 29502, totalVoters: 12750, turnout2023: 85.43, maleVoters: 6503, femaleVoters: 6247, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 16, population: 28862, totalVoters: 15976, turnout2023: 71.6, maleVoters: 7908, femaleVoters: 8068, literacy: 65.2, urbanPercent: 26.2, scPercent: 0, stPercent: 67.7, areaSqKm: 1401 },
  { acNo: 17, population: 32542, totalVoters: 23349, turnout2023: 77.94, maleVoters: 11640, femaleVoters: 11709, literacy: 69.8, urbanPercent: 25.1, scPercent: 1, stPercent: 67.7, areaSqKm: 1562 },
  { acNo: 18, population: 26888, totalVoters: 14670, turnout2023: 86.82, maleVoters: 7203, femaleVoters: 7467, literacy: 65.2, urbanPercent: 22.8, scPercent: 0, stPercent: 67.7, areaSqKm: 1342 },
  { acNo: 19, population: 29366, totalVoters: 12825, turnout2023: 84.93, maleVoters: 6259, femaleVoters: 6566, literacy: 65.2, urbanPercent: 25.1, scPercent: 0, stPercent: 67.7, areaSqKm: 1646 },
  { acNo: 20, population: 25173, totalVoters: 13123, turnout2023: 83.55, maleVoters: 6535, femaleVoters: 6588, literacy: 69.8, urbanPercent: 26.2, scPercent: 1, stPercent: 67.7, areaSqKm: 1577 },
  { acNo: 21, population: 32506, totalVoters: 12690, turnout2023: 87.3, maleVoters: 6370, femaleVoters: 6320, literacy: 64.3, urbanPercent: 19.5, scPercent: 0, stPercent: 67.7, areaSqKm: 1465 },
  { acNo: 22, population: 34621, totalVoters: 10970, turnout2023: 86.29, maleVoters: 5600, femaleVoters: 5370, literacy: 68.9, urbanPercent: 21.7, scPercent: 0, stPercent: 67.7, areaSqKm: 1548 },
  { acNo: 23, population: 29003, totalVoters: 10377, turnout2023: 86.57, maleVoters: 5183, femaleVoters: 5194, literacy: 69.8, urbanPercent: 25.1, scPercent: 1, stPercent: 67.7, areaSqKm: 1425 },
  { acNo: 24, population: 34071, totalVoters: 16507, turnout2023: 74.96, maleVoters: 8171, femaleVoters: 8336, literacy: 68, urbanPercent: 23.9, scPercent: 0, stPercent: 67.7, areaSqKm: 1621 },
  { acNo: 25, population: 26748, totalVoters: 15441, turnout2023: 84.27, maleVoters: 7543, femaleVoters: 7898, literacy: 65.2, urbanPercent: 23.9, scPercent: 0, stPercent: 67.7, areaSqKm: 1631 },
  { acNo: 26, population: 25287, totalVoters: 11709, turnout2023: 84.04, maleVoters: 5873, femaleVoters: 5836, literacy: 64.3, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1479 },
  { acNo: 27, population: 29502, totalVoters: 12355, turnout2023: 87.08, maleVoters: 6301, femaleVoters: 6054, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 28, population: 29879, totalVoters: 11314, turnout2023: 85.65, maleVoters: 5713, femaleVoters: 5601, literacy: 64.3, urbanPercent: 25.1, scPercent: 0, stPercent: 67.7, areaSqKm: 1553 },
  { acNo: 29, population: 25375, totalVoters: 17467, turnout2023: 76.43, maleVoters: 8961, femaleVoters: 8506, literacy: 64.3, urbanPercent: 20.6, scPercent: 0, stPercent: 75.2, areaSqKm: 1313 },
  { acNo: 30, population: 34308, totalVoters: 13266, turnout2023: 87.85, maleVoters: 6719, femaleVoters: 6547, literacy: 68, urbanPercent: 23.9, scPercent: 0, stPercent: 75.2, areaSqKm: 1455 },
  { acNo: 31, population: 30629, totalVoters: 13322, turnout2023: 78.7, maleVoters: 6728, femaleVoters: 6594, literacy: 68, urbanPercent: 25.1, scPercent: 0, stPercent: 75.2, areaSqKm: 1607 },
  { acNo: 32, population: 34107, totalVoters: 11286, turnout2023: 89.85, maleVoters: 5547, femaleVoters: 5739, literacy: 65.2, urbanPercent: 21.7, scPercent: 0, stPercent: 67.7, areaSqKm: 1327 },
  { acNo: 33, population: 28454, totalVoters: 9501, turnout2023: 89.35, maleVoters: 4618, femaleVoters: 4883, literacy: 65.2, urbanPercent: 19.5, scPercent: 0, stPercent: 67.7, areaSqKm: 1420 },
  { acNo: 34, population: 25183, totalVoters: 12265, turnout2023: 84.53, maleVoters: 6052, femaleVoters: 6213, literacy: 65.2, urbanPercent: 19.5, scPercent: 0, stPercent: 67.7, areaSqKm: 1553 },
  { acNo: 35, population: 30568, totalVoters: 13045, turnout2023: 86.62, maleVoters: 6451, femaleVoters: 6594, literacy: 69.8, urbanPercent: 21.7, scPercent: 1, stPercent: 67.7, areaSqKm: 1504 },
  { acNo: 36, population: 25686, totalVoters: 7536, turnout2023: 88.61, maleVoters: 3667, femaleVoters: 3869, literacy: 65.2, urbanPercent: 26.2, scPercent: 0, stPercent: 67.7, areaSqKm: 1406 },
  { acNo: 37, population: 29502, totalVoters: 13322, turnout2023: 90.92, maleVoters: 6794, femaleVoters: 6528, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 38, population: 29376, totalVoters: 20842, turnout2023: 81.06, maleVoters: 10712, femaleVoters: 10130, literacy: 68.9, urbanPercent: 26.2, scPercent: 0, stPercent: 67.7, areaSqKm: 1621 },
  { acNo: 39, population: 34761, totalVoters: 10872, turnout2023: 94.03, maleVoters: 5599, femaleVoters: 5273, literacy: 65.2, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1572 },
  { acNo: 40, population: 31081, totalVoters: 10727, turnout2023: 94.26, maleVoters: 5487, femaleVoters: 5240, literacy: 68.9, urbanPercent: 21.7, scPercent: 0, stPercent: 67.7, areaSqKm: 1411 },
  { acNo: 41, population: 28001, totalVoters: 4287, turnout2023: 87.33, maleVoters: 2178, femaleVoters: 2109, literacy: 68, urbanPercent: 22.8, scPercent: 0, stPercent: 75.2, areaSqKm: 1303 },
  { acNo: 42, population: 30392, totalVoters: 11913, turnout2023: 89.9, maleVoters: 5879, femaleVoters: 6034, literacy: 68, urbanPercent: 25.1, scPercent: 0, stPercent: 67.7, areaSqKm: 1381 },
  { acNo: 43, population: 30428, totalVoters: 12238, turnout2023: 80.04, maleVoters: 5996, femaleVoters: 6242, literacy: 65.2, urbanPercent: 22.8, scPercent: 0, stPercent: 67.7, areaSqKm: 1479 },
  { acNo: 44, population: 32682, totalVoters: 18886, turnout2023: 86.31, maleVoters: 9499, femaleVoters: 9387, literacy: 66.1, urbanPercent: 23.9, scPercent: 0, stPercent: 67.7, areaSqKm: 1587 },
  { acNo: 45, population: 29502, totalVoters: 12275, turnout2023: 90.66, maleVoters: 6260, femaleVoters: 6015, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 46, population: 33019, totalVoters: 14084, turnout2023: 77.1, maleVoters: 6880, femaleVoters: 7204, literacy: 71.6, urbanPercent: 19.5, scPercent: 3, stPercent: 67.7, areaSqKm: 1371 },
  { acNo: 47, population: 28313, totalVoters: 22858, turnout2023: 83.95, maleVoters: 11703, femaleVoters: 11155, literacy: 68.9, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1396 },
  { acNo: 48, population: 26199, totalVoters: 18522, turnout2023: 86.25, maleVoters: 9326, femaleVoters: 9196, literacy: 64.3, urbanPercent: 26.2, scPercent: 0, stPercent: 67.7, areaSqKm: 1313 },
  { acNo: 49, population: 29502, totalVoters: 18509, turnout2023: 87.68, maleVoters: 9440, femaleVoters: 9069, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 50, population: 27261, totalVoters: 19974, turnout2023: 79.61, maleVoters: 10096, femaleVoters: 9878, literacy: 64.3, urbanPercent: 23.9, scPercent: 0, stPercent: 67.7, areaSqKm: 1538 },
  { acNo: 51, population: 29502, totalVoters: 8966, turnout2023: 88.2, maleVoters: 4573, femaleVoters: 4393, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 52, population: 30256, totalVoters: 5720, turnout2023: 90.42, maleVoters: 2806, femaleVoters: 2914, literacy: 68.9, urbanPercent: 23.9, scPercent: 0, stPercent: 75.2, areaSqKm: 1411 },
  { acNo: 53, population: 29502, totalVoters: 9468, turnout2023: 83.7, maleVoters: 4829, femaleVoters: 4639, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
  { acNo: 54, population: 31993, totalVoters: 9186, turnout2023: 77.31, maleVoters: 4717, femaleVoters: 4469, literacy: 68.9, urbanPercent: 19.5, scPercent: 0, stPercent: 67.7, areaSqKm: 1636 },
  { acNo: 55, population: 25147, totalVoters: 9438, turnout2023: 79.11, maleVoters: 4691, femaleVoters: 4747, literacy: 68, urbanPercent: 21.7, scPercent: 0, stPercent: 67.7, areaSqKm: 1455 },
  { acNo: 56, population: 28827, totalVoters: 10293, turnout2023: 94.17, maleVoters: 5131, femaleVoters: 5162, literacy: 68, urbanPercent: 20.6, scPercent: 0, stPercent: 67.7, areaSqKm: 1303 },
  { acNo: 57, population: 26576, totalVoters: 8218, turnout2023: 91.58, maleVoters: 4018, femaleVoters: 4200, literacy: 68.9, urbanPercent: 25.1, scPercent: 0, stPercent: 75.2, areaSqKm: 1562 },
  { acNo: 58, population: 26339, totalVoters: 11155, turnout2023: 91.21, maleVoters: 5667, femaleVoters: 5488, literacy: 68.9, urbanPercent: 25.1, scPercent: 0, stPercent: 67.7, areaSqKm: 1337 },
  { acNo: 59, population: 33558, totalVoters: 11683, turnout2023: 90.17, maleVoters: 5941, femaleVoters: 5742, literacy: 68.9, urbanPercent: 23.9, scPercent: 0, stPercent: 67.7, areaSqKm: 1322 },
  { acNo: 60, population: 29502, totalVoters: 13504, turnout2023: 92.48, maleVoters: 6887, femaleVoters: 6617, literacy: 67, urbanPercent: 22.7, scPercent: 0.2, stPercent: 68.8, areaSqKm: 1444 },
];

export function getARConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return AR_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
