/**
 * Arunachal Pradesh Assembly Constituencies — CURRENT assembly (2024) with 2019 history (60 seats)
 *
 * SOURCES:
 *   2019 result + numbering/district/reservation: TCPD "Lok Dhaba" (ECI). Official AC numbering.
 *   2024 winners (current): project data verified against ECI 2024 results.
 *   Auto-generated by scripts/build-current-seed.mjs — do not hand-edit.
 */

export interface ARConstituencySeed {
  acNo: number;
  name: string;
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2019: string;
  winnerName2019: string;
  winnerVotes2019: number;
  runnerUp2019: string;
  margin2019: number;
  winner2024: string;
  winnerName2024: string;
  currentParty: string;
}

export const AR_CONSTITUENCIES: ARConstituencySeed[] = [
  { acNo: 1, name: 'Lumla', localName: 'Lumla', district: 'Tawang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Jambey Tashi', winnerVotes2019: 4567, runnerUp2019: 'NPP', margin2019: 1288, winner2024: 'BJP', winnerName2024: 'Tsering Lhamu', currentParty: 'BJP' },
  { acNo: 2, name: 'Tawang', district: 'Tawang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tsering Tashi', winnerVotes2019: 5547, runnerUp2019: 'INC', margin2019: 3592, winner2024: 'NPP', winnerName2024: 'Namgey Tsering', currentParty: 'NPP' },
  { acNo: 3, name: 'Mukto', localName: 'Mukto', district: 'Tawang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Pema Khandu', winnerVotes2019: 4304, runnerUp2019: 'INC', margin2019: 2619, winner2024: 'BJP', winnerName2024: 'Pema Khandu', currentParty: 'BJP' },
  { acNo: 4, name: 'Dirang', localName: 'Dirang', district: 'West Kameng', type: 'ST', winner2019: 'BJP', winnerName2019: 'Shri Phurpa Tsering', winnerVotes2019: 0, runnerUp2019: 'NOTA', margin2019: 0, winner2024: 'BJP', winnerName2024: 'Phurpa Tsering', currentParty: 'BJP' },
  { acNo: 5, name: 'Kalaktang', localName: 'Kalaktang', district: 'West Kameng', type: 'ST', winner2019: 'JDU', winnerName2019: 'Shri Dorjee Wangdi Kharma', winnerVotes2019: 5026, runnerUp2019: 'BJP', margin2019: 1772, winner2024: 'BJP', winnerName2024: 'Tseten Chombay Kee', currentParty: 'BJP' },
  { acNo: 6, name: 'Thrizino-Buragaon', localName: 'Thrizino-Buragaon', district: 'West Kameng', type: 'ST', winner2019: 'BJP', winnerName2019: 'Kumsi Sidisow', winnerVotes2019: 8772, runnerUp2019: 'INC', margin2019: 7135, winner2024: 'IND', winnerName2024: 'Tenzin Nyima Glow', currentParty: 'IND' },
  { acNo: 7, name: 'Bomdila', localName: 'Bomdila', district: 'West Kameng', type: 'ST', winner2019: 'JDU', winnerName2019: 'Shri Dongru Siongju', winnerVotes2019: 2994, runnerUp2019: 'BJP', margin2019: 233, winner2024: 'BJP', winnerName2024: 'Dongru Siongju', currentParty: 'BJP' },
  { acNo: 8, name: 'Bameng', localName: 'Bameng', district: 'East Kameng', type: 'ST', winner2019: 'BJP', winnerName2019: 'Goruk Pordung', winnerVotes2019: 5043, runnerUp2019: 'NPP', margin2019: 393, winner2024: 'INC', winnerName2024: 'Kumar Waii', currentParty: 'INC' },
  { acNo: 9, name: 'Chayang Tajo', localName: 'Chyangtajo', district: 'East Kameng', type: 'ST', winner2019: 'JDU', winnerName2019: 'Hayeng Mangfi', winnerVotes2019: 5435, runnerUp2019: 'BJP', margin2019: 634, winner2024: 'BJP', winnerName2024: 'Hayeng Mangfi', currentParty: 'BJP' },
  { acNo: 10, name: 'Seppa East', localName: 'Seppa East', district: 'East Kameng', type: 'ST', winner2019: 'NPP', winnerName2019: 'Tapuk Taku', winnerVotes2019: 4184, runnerUp2019: 'BJP', margin2019: 29, winner2024: 'BJP', winnerName2024: 'Ealing Tallang', currentParty: 'BJP' },
  { acNo: 11, name: 'Seppa West', localName: 'Seppa West', district: 'East Kameng', type: 'ST', winner2019: 'BJP', winnerName2019: 'Mama Natung', winnerVotes2019: 4059, runnerUp2019: 'JDU', margin2019: 1554, winner2024: 'BJP', winnerName2024: 'Mama Natung', currentParty: 'BJP' },
  { acNo: 12, name: 'Pakke Kessang', localName: 'Pakke-Kasang', district: 'East Kameng', type: 'ST', winner2019: 'BJP', winnerName2019: 'Biyuram Wahge', winnerVotes2019: 4506, runnerUp2019: 'INC', margin2019: 2222, winner2024: 'BJP', winnerName2024: 'Biyuram Wahge', currentParty: 'BJP' },
  { acNo: 13, name: 'Itanagar', localName: 'Itanagar', district: 'Papum Pare', type: 'ST', winner2019: 'JDU', winnerName2019: 'Techi Kaso', winnerVotes2019: 12162, runnerUp2019: 'BJP', margin2019: 302, winner2024: 'BJP', winnerName2024: 'Techi Kaso', currentParty: 'BJP' },
  { acNo: 14, name: 'Doimukh', localName: 'Doimukh', district: 'Papum Pare', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tana Hali Tara', winnerVotes2019: 8403, runnerUp2019: 'NPP', margin2019: 2385, winner2024: 'PPA', winnerName2024: 'Nabam Vivek', currentParty: 'PPA' },
  { acNo: 15, name: 'Sagalee', district: 'Papum Pare', type: 'ST', winner2019: 'INC', winnerName2019: 'Nabam Tuki', winnerVotes2019: 4886, runnerUp2019: 'NPP', margin2019: 1321, winner2024: 'BJP', winnerName2024: 'Ratu Techi', currentParty: 'BJP' },
  { acNo: 16, name: 'Yachuli', localName: 'Yachuli', district: 'Lower Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Taba Tedir', winnerVotes2019: 0, runnerUp2019: 'NOTA', margin2019: 0, winner2024: 'NCP', winnerName2024: 'Toko Tatung', currentParty: 'NCP' },
  { acNo: 17, name: 'Ziro Hapoli', localName: 'Ziro-Hapoli', district: 'Lower Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tage Taki', winnerVotes2019: 9853, runnerUp2019: 'INC', margin2019: 1774, winner2024: 'BJP', winnerName2024: 'Hage Appa', currentParty: 'BJP' },
  { acNo: 18, name: 'Palin', localName: 'Palin', district: 'Kurung Kumey', type: 'ST', winner2019: 'BJP', winnerName2019: 'Balo Raja', winnerVotes2019: 5727, runnerUp2019: 'INC', margin2019: 730, winner2024: 'BJP', winnerName2024: 'Balo Raja', currentParty: 'BJP' },
  { acNo: 19, name: 'Nyapin', localName: 'Nyapin', district: 'Kurung Kumey', type: 'ST', winner2019: 'BJP', winnerName2019: 'Bamang Felix', winnerVotes2019: 5517, runnerUp2019: 'INC', margin2019: 154, winner2024: 'BJP', winnerName2024: 'Tai Nikio', currentParty: 'BJP' },
  { acNo: 20, name: 'Tali', localName: 'Tali', district: 'Kurung Kumey', type: 'ST', winner2019: 'JDU', winnerName2019: 'Jikke Tako', winnerVotes2019: 5518, runnerUp2019: 'BJP', margin2019: 105, winner2024: 'BJP', winnerName2024: 'Jikke Tako', currentParty: 'BJP' },
  { acNo: 21, name: 'Koloriang', localName: 'Koloriang', district: 'Kurung Kumey', type: 'ST', winner2019: 'BJP', winnerName2019: 'Lokam Tassar', winnerVotes2019: 5748, runnerUp2019: 'NPP', margin2019: 456, winner2024: 'BJP', winnerName2024: 'Pani Taram', currentParty: 'BJP' },
  { acNo: 22, name: 'Nacho', localName: 'Nacho', district: 'Upper Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Nakap Nalo', winnerVotes2019: 5053, runnerUp2019: 'INC', margin2019: 698, winner2024: 'BJP', winnerName2024: 'Nakap Nalo', currentParty: 'BJP' },
  { acNo: 23, name: 'Taliha', localName: 'Taliha', district: 'Upper Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Nyato Rigia', winnerVotes2019: 5024, runnerUp2019: 'NPP', margin2019: 1203, winner2024: 'BJP', winnerName2024: 'Nyato Dukam', currentParty: 'BJP' },
  { acNo: 24, name: 'Daporijo', localName: 'Daporijo', district: 'Upper Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Taniya Soki', winnerVotes2019: 6019, runnerUp2019: 'JDU', margin2019: 122, winner2024: 'BJP', winnerName2024: 'Taniya Soki', currentParty: 'BJP' },
  { acNo: 25, name: 'Raga', localName: 'Raga', district: 'Upper Subansiri', type: 'ST', winner2019: 'NPP', winnerName2019: 'Tarin Dakpe', winnerVotes2019: 3385, runnerUp2019: 'PPA', margin2019: 166, winner2024: 'BJP', winnerName2024: 'Rotom Tebin', currentParty: 'BJP' },
  { acNo: 26, name: 'Dumporijo', localName: 'Dumporijo', district: 'Upper Subansiri', type: 'ST', winner2019: 'BJP', winnerName2019: 'Rode Bui', winnerVotes2019: 4635, runnerUp2019: 'NPP', margin2019: 978, winner2024: 'BJP', winnerName2024: 'Rode Bui', currentParty: 'BJP' },
  { acNo: 27, name: 'Liromoba', district: 'West Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Nyamar Karbak', winnerVotes2019: 5616, runnerUp2019: 'NPP', margin2019: 746, winner2024: 'NPP', winnerName2024: 'Pesi Jilen', currentParty: 'NPP' },
  { acNo: 28, name: 'Likabali', localName: 'Likabali', district: 'West Siang', type: 'ST', winner2019: 'PPA', winnerName2019: 'Kardo Nyigyor', winnerVotes2019: 3714, runnerUp2019: 'BJP', margin2019: 178, winner2024: 'BJP', winnerName2024: 'Kardo Nyigyor', currentParty: 'BJP' },
  { acNo: 29, name: 'Basar', localName: 'Basar', district: 'West Siang', type: 'ST', winner2019: 'NPP', winnerName2019: 'Gokar Basar', winnerVotes2019: 6626, runnerUp2019: 'BJP', margin2019: 240, winner2024: 'BJP', winnerName2024: 'Nyabi Jini Dirchi', currentParty: 'BJP' },
  { acNo: 30, name: 'Along West', localName: 'Along West', district: 'West Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tumke Bagra', winnerVotes2019: 6000, runnerUp2019: 'JDU', margin2019: 966, winner2024: 'BJP', winnerName2024: 'Topin Ete', currentParty: 'BJP' },
  { acNo: 31, name: 'Along East', localName: 'Along East', district: 'West Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Kento Jini', winnerVotes2019: 0, runnerUp2019: 'NOTA', margin2019: 0, winner2024: 'BJP', winnerName2024: 'Kento Jini', currentParty: 'BJP' },
  { acNo: 32, name: 'Rumgong', localName: 'Rumgong', district: 'West Siang', type: 'ST', winner2019: 'JDU', winnerName2019: 'Talem Taboh', winnerVotes2019: 4949, runnerUp2019: 'BJP', margin2019: 85, winner2024: 'BJP', winnerName2024: 'Talem Taboh', currentParty: 'BJP' },
  { acNo: 33, name: 'Mechuka', localName: 'Mechuka', district: 'West Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Pasang Dorjee Sona', winnerVotes2019: 4261, runnerUp2019: 'NPP', margin2019: 68, winner2024: 'BJP', winnerName2024: 'Pasang Dorjee Sona', currentParty: 'BJP' },
  { acNo: 34, name: 'Tuting Yingkiong', localName: 'Tuting-Yingkiong', district: 'Upper Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Alo Libang', winnerVotes2019: 5800, runnerUp2019: 'JDS', margin2019: 1609, winner2024: 'BJP', winnerName2024: 'Alo Libang', currentParty: 'BJP' },
  { acNo: 35, name: 'Pangin', localName: 'Pangin', district: 'East Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Ojing Tasing', winnerVotes2019: 7647, runnerUp2019: 'INC', margin2019: 4052, winner2024: 'BJP', winnerName2024: 'Ojing Tasing', currentParty: 'BJP' },
  { acNo: 36, name: 'Nari-Koyu', localName: 'Nari-Koyu', district: 'East Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Kento Rina', winnerVotes2019: 2489, runnerUp2019: 'INC', margin2019: 216, winner2024: 'BJP', winnerName2024: 'Tojir Kadu', currentParty: 'BJP' },
  { acNo: 37, name: 'Pasighat West', district: 'East Siang', type: 'ST', winner2019: 'INC', winnerName2019: 'Ninong Ering', winnerVotes2019: 5210, runnerUp2019: 'BJP', margin2019: 571, winner2024: 'BJP', winnerName2024: 'Ninong Ering', currentParty: 'BJP' },
  { acNo: 38, name: 'Pasighat East', localName: 'Pasighat East', district: 'East Siang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Kaling Moyong', winnerVotes2019: 8851, runnerUp2019: 'INC', margin2019: 1242, winner2024: 'NPP', winnerName2024: 'Tapi Darang', currentParty: 'NPP' },
  { acNo: 39, name: 'Mebo', localName: 'Mebo', district: 'East Siang', type: 'ST', winner2019: 'INC', winnerName2019: 'Lombo Tayeng', winnerVotes2019: 5238, runnerUp2019: 'BJP', margin2019: 372, winner2024: 'PPA', winnerName2024: 'Oken Tayeng', currentParty: 'PPA' },
  { acNo: 40, name: 'Mariyang-Geku', localName: 'Mariyang-Geku', district: 'Upper Siang', type: 'ST', winner2019: 'JDU', winnerName2019: 'Kanggong Taku', winnerVotes2019: 5366, runnerUp2019: 'BJP', margin2019: 1260, winner2024: 'NPP', winnerName2024: 'Oni Panyang', currentParty: 'NPP' },
  { acNo: 41, name: 'Anini', localName: 'Anini', district: 'Dibang Valley', type: 'ST', winner2019: 'BJP', winnerName2019: 'Mopi Mihu', winnerVotes2019: 2416, runnerUp2019: 'INC', margin2019: 1134, winner2024: 'BJP', winnerName2024: 'Mopi Mihu', currentParty: 'BJP' },
  { acNo: 42, name: 'Dambuk', localName: 'Dambuk', district: 'Lower Dibang Valley', type: 'ST', winner2019: 'BJP', winnerName2019: 'Gum Tayeng', winnerVotes2019: 5584, runnerUp2019: 'NPP', margin2019: 873, winner2024: 'BJP', winnerName2024: 'Puinnyo Apum', currentParty: 'BJP' },
  { acNo: 43, name: 'Roing', localName: 'Roing', district: 'Lower Dibang Valley', type: 'ST', winner2019: 'NPP', winnerName2019: 'Mutchu Mithi', winnerVotes2019: 4950, runnerUp2019: 'BJP', margin2019: 400, winner2024: 'BJP', winnerName2024: 'Mutchu Mithi', currentParty: 'BJP' },
  { acNo: 44, name: 'Tezu', localName: 'Tezu', district: 'Lohit', type: 'ST', winner2019: 'IND', winnerName2019: 'Karikho Kri', winnerVotes2019: 7538, runnerUp2019: 'BJP', margin2019: 155, winner2024: 'BJP', winnerName2024: 'Dr. Mohesh Chai', currentParty: 'BJP' },
  { acNo: 45, name: 'Hayuliang', district: 'Anjaw', type: 'ST', winner2019: 'BJP', winnerName2019: 'Dasanglu Pul', winnerVotes2019: 6149, runnerUp2019: 'INC', margin2019: 1332, winner2024: 'BJP', winnerName2024: 'Dasanglu Pul', currentParty: 'BJP' },
  { acNo: 46, name: 'Chowkham', localName: 'Chowkham', district: 'Lohit', type: 'ST', winner2019: 'BJP', winnerName2019: 'Chowna Mein', winnerVotes2019: 8908, runnerUp2019: 'INC', margin2019: 7291, winner2024: 'BJP', winnerName2024: 'Chowna Mein', currentParty: 'BJP' },
  { acNo: 47, name: 'Namsai', localName: 'Namsai', district: 'Lohit', type: 'ST', winner2019: 'BJP', winnerName2019: 'Chau Zingnu Namchoom', winnerVotes2019: 13392, runnerUp2019: 'NPP', margin2019: 10755, winner2024: 'BJP', winnerName2024: 'Chau Zingnu Namchoom', currentParty: 'BJP' },
  { acNo: 48, name: 'Lekang', localName: 'Lekang', district: 'Lohit', type: 'ST', winner2019: 'BJP', winnerName2019: 'Jummum Ete Deori', winnerVotes2019: 8980, runnerUp2019: 'INC', margin2019: 5493, winner2024: 'NCP', winnerName2024: 'Likha Soni', currentParty: 'NCP' },
  { acNo: 49, name: 'Bordumsa - Diyun', localName: 'Bordumsa-Diyum', district: 'Changlang', type: 'GEN', winner2019: 'IND', winnerName2019: 'Somlung Mossang', winnerVotes2019: 6330, runnerUp2019: 'BJP', margin2019: 2379, winner2024: 'NCP', winnerName2024: 'Nikh Kamin', currentParty: 'NCP' },
  { acNo: 50, name: 'Miao', localName: 'Miao', district: 'Changlang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Kamlung Mosang', winnerVotes2019: 9760, runnerUp2019: 'INC', margin2019: 3856, winner2024: 'BJP', winnerName2024: 'Kamlung Mosang', currentParty: 'BJP' },
  { acNo: 51, name: 'Nampong', district: 'Changlang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Laisam Simai', winnerVotes2019: 3761, runnerUp2019: 'NPP', margin2019: 1510, winner2024: 'IND', winnerName2024: 'Laisam Simai', currentParty: 'IND' },
  { acNo: 52, name: 'Changlang South', localName: 'Changlang South', district: 'Changlang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Phosum Khimhun', winnerVotes2019: 2848, runnerUp2019: 'INC', margin2019: 583, winner2024: 'BJP', winnerName2024: 'Hamjong Tangha', currentParty: 'BJP' },
  { acNo: 53, name: 'Changlang North', district: 'Changlang', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tesam Pongte', winnerVotes2019: 5417, runnerUp2019: 'INC', margin2019: 3015, winner2024: 'BJP', winnerName2024: 'Tesam Pongte', currentParty: 'BJP' },
  { acNo: 54, name: 'Namsang', localName: 'Namsang', district: 'Tirap', type: 'ST', winner2019: 'BJP', winnerName2019: 'Wangki Lowang', winnerVotes2019: 3202, runnerUp2019: 'JDU', margin2019: 1682, winner2024: 'BJP', winnerName2024: 'Wangki Lowang', currentParty: 'BJP' },
  { acNo: 55, name: 'Khonsa East', localName: 'Khonsa East', district: 'Tirap', type: 'ST', winner2019: 'BJP', winnerName2019: 'Wanglam Sawin', winnerVotes2019: 5051, runnerUp2019: 'NPP', margin2019: 3381, winner2024: 'IND', winnerName2024: 'Wanglam Sawin', currentParty: 'IND' },
  { acNo: 56, name: 'Khonsa West', localName: 'Khonsa West', district: 'Tirap', type: 'ST', winner2019: 'NPP', winnerName2019: 'Tirong Aboh', winnerVotes2019: 5366, runnerUp2019: 'BJP', margin2019: 1055, winner2024: 'BJP', winnerName2024: 'Chakat Aboh', currentParty: 'BJP' },
  { acNo: 57, name: 'Borduria Bogapani', localName: 'Borduria-Bogapani', district: 'Tirap', type: 'ST', winner2019: 'INC', winnerName2019: 'Wanglin Lowangdong', winnerVotes2019: 2499, runnerUp2019: 'BJP', margin2019: 97, winner2024: 'BJP', winnerName2024: 'Wanglin Lowangdong', currentParty: 'BJP' },
  { acNo: 58, name: 'Kanubari', localName: 'Kanubari', district: 'Tirap', type: 'ST', winner2019: 'BJP', winnerName2019: 'Gabriel Denwang Wangsu', winnerVotes2019: 6707, runnerUp2019: 'INC', margin2019: 4236, winner2024: 'BJP', winnerName2024: 'Gabriel Denwang Wangsu', currentParty: 'BJP' },
  { acNo: 59, name: 'Longding Pumao', localName: 'Longding-Pumao', district: 'Tirap', type: 'ST', winner2019: 'BJP', winnerName2019: 'Tanpho Wangnaw', winnerVotes2019: 4463, runnerUp2019: 'NPP', margin2019: 695, winner2024: 'NPP', winnerName2024: 'Thangwang Wangham', currentParty: 'NPP' },
  { acNo: 60, name: 'Pongchau Wakka', localName: 'Pongchao-Wakka', district: 'Tirap', type: 'ST', winner2019: 'BJP', winnerName2019: 'Honchun Ngandam', winnerVotes2019: 6837, runnerUp2019: 'INC', margin2019: 3738, winner2024: 'BJP', winnerName2024: 'Honchun Ngandam', currentParty: 'BJP' },
];

export function getARConstituency(acNo: number): ARConstituencySeed | undefined {
  return AR_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
