/**
 * AR — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface ARElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const AR_ELECTION_HISTORY: ARElectionResult[] = [
  {
    year: 2024,
    partyResults: {
      'BJP': 46,
      'NPP': 5,
      'IND': 3,
      'NCP': 3,
      'PPA': 2,
      'INC': 1,
    },
    totalSeats: 60,
    rulingParty: 'BJP',
  },
  {
    year: 2019,
    partyResults: {
      'BJP': 41,
      'JDU': 7,
      'NPP': 5,
      'INC': 4,
      'IND': 2,
      'PPA': 1,
    },
    totalSeats: 60,
    rulingParty: 'BJP',
  },
];

export function getARElectionByYear(year: number) {
  return AR_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getARPartyTrend(party: string) {
  return AR_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
