/**
 * Jammu & Kashmir Assembly Constituencies — 2024 General Election (90 seats)
 *
 * SOURCE: English Wikipedia, "2024 Jammu and Kashmir Legislative Assembly
 *         election", section "Results by constituency" (ECI-sourced). Uses the
 *         official post-2022-delimitation AC numbering (1-90). Auto-generated by
 *         scripts/build-jk-seed.mjs — do not hand-edit.
 *
 * Winner/runner-up parties, vote counts and margins are from the ECI results as
 * compiled on Wikipedia. Reservation (GEN/SC/ST) is derived from the official
 * constituency-name suffix. Local-script names are carried over by name match.
 *
 * PARTY TALLY 2024: JKNC 42 | BJP 29 | IND 7 | INC 6 | JKPDP 3 | JKPC 1 | CPI(M) 1 | AAP 1 = 90
 */

export interface JKConstituencySeed {
  acNo: number; name: string; district: string; type: 'GEN' | 'SC' | 'ST';
  winner2024: string; winnerName2024: string; winnerVotes2024: number;
  runnerUp2024: string; margin2024: number; currentParty: string;
  /** Constituency name in local script */
  localName?: string;
}

export const JK_CONSTITUENCIES: JKConstituencySeed[] = [
  { acNo: 1, name: 'Karnah', localName: 'करनाह', district: 'Kupwara', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Javaid Ahmad Mirchal', winnerVotes2024: 14294, runnerUp2024: 'JKPC', margin2024: 6262, currentParty: 'JKNC' },
  { acNo: 2, name: 'Trehgam', localName: 'त्रेहगाम', district: 'Kupwara', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Saifullah Mir', winnerVotes2024: 18002, runnerUp2024: 'JKPC', margin2024: 3636, currentParty: 'JKNC' },
  { acNo: 3, name: 'Kupwara', localName: 'कुपवाड़ा', district: 'Kupwara', type: 'GEN', winner2024: 'JKPDP', winnerName2024: 'Mir Mohammad Fayaz', winnerVotes2024: 27773, runnerUp2024: 'JKNC', margin2024: 9797, currentParty: 'JKPDP' },
  { acNo: 4, name: 'Lolab', localName: 'लोलाब', district: 'Kupwara', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Qaysar Jamshaid Lone', winnerVotes2024: 19603, runnerUp2024: 'IND', margin2024: 7871, currentParty: 'JKNC' },
  { acNo: 5, name: 'Handwara', localName: 'हंदवाड़ा', district: 'Kupwara', type: 'GEN', winner2024: 'JKPC', winnerName2024: 'Sajad Gani Lone', winnerVotes2024: 29812, runnerUp2024: 'JKNC', margin2024: 662, currentParty: 'JKPC' },
  { acNo: 6, name: 'Langate', localName: 'लंगेट', district: 'Kupwara', type: 'GEN', winner2024: 'IND', winnerName2024: 'Khursheed Ahmed Sheikh', winnerVotes2024: 25984, runnerUp2024: 'JKPC', margin2024: 1602, currentParty: 'IND' },
  { acNo: 7, name: 'Sopore', localName: 'सोपोर', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Irshad Rasool Kar', winnerVotes2024: 26975, runnerUp2024: 'IND', margin2024: 20356, currentParty: 'JKNC' },
  { acNo: 8, name: 'Rafiabad', localName: 'रफियाबाद', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Javid Ahmad Dar', winnerVotes2024: 28783, runnerUp2024: 'OTH', margin2024: 9202, currentParty: 'JKNC' },
  { acNo: 9, name: 'Uri', localName: 'उरी', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Sajjad Safi', winnerVotes2024: 39713, runnerUp2024: 'IND', margin2024: 14469, currentParty: 'JKNC' },
  { acNo: 10, name: 'Baramulla', localName: 'बारामूला', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Javid Hassan Baig', winnerVotes2024: 22523, runnerUp2024: 'IND', margin2024: 11773, currentParty: 'JKNC' },
  { acNo: 11, name: 'Gulmarg', localName: 'गुलमार्ग', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Farooq Ahmed Shah', winnerVotes2024: 26984, runnerUp2024: 'OTH', margin2024: 4191, currentParty: 'JKNC' },
  { acNo: 12, name: 'Wagoora–Kreeri', localName: 'वागूरा - क्रीरी', district: 'Baramulla', type: 'GEN', winner2024: 'INC', winnerName2024: 'Irfan Hafiz Lone', winnerVotes2024: 17002, runnerUp2024: 'JKPDP', margin2024: 7751, currentParty: 'INC' },
  { acNo: 13, name: 'Pattan', localName: 'पट्टन', district: 'Baramulla', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Javaid Riyaz', winnerVotes2024: 29893, runnerUp2024: 'JKPC', margin2024: 603, currentParty: 'JKNC' },
  { acNo: 14, name: 'Sonawari', localName: 'सोनावारी', district: 'Bandipora', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Hilal Akbar Lone', winnerVotes2024: 31535, runnerUp2024: 'IND', margin2024: 13744, currentParty: 'JKNC' },
  { acNo: 15, name: 'Bandipora', localName: 'बांडीपोरा', district: 'Bandipora', type: 'GEN', winner2024: 'INC', winnerName2024: 'Nizam Uddin Bhat', winnerVotes2024: 20391, runnerUp2024: 'IND', margin2024: 811, currentParty: 'INC' },
  { acNo: 16, name: 'Gurez', localName: 'गुरेज़', district: 'Bandipora', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Nazir Ahmed Khan', winnerVotes2024: 8378, runnerUp2024: 'BJP', margin2024: 1132, currentParty: 'JKNC' },
  { acNo: 17, name: 'Kangan', localName: 'कंगन', district: 'Ganderbal', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Mian Mehar Ali', winnerVotes2024: 28907, runnerUp2024: 'JKPDP', margin2024: 3819, currentParty: 'JKNC' },
  { acNo: 18, name: 'Ganderbal', localName: 'गांदरबल', district: 'Ganderbal', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Omar Abdullah', winnerVotes2024: 32727, runnerUp2024: 'JKPDP', margin2024: 10574, currentParty: 'JKNC' },
  { acNo: 19, name: 'Hazratbal', localName: 'हज़रतबल', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Salman Sagar', winnerVotes2024: 18890, runnerUp2024: 'JKPDP', margin2024: 10295, currentParty: 'JKNC' },
  { acNo: 20, name: 'Khanyar', localName: 'खान्यार', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Ali Mohammad Sagar', winnerVotes2024: 14906, runnerUp2024: 'IND', margin2024: 9912, currentParty: 'JKNC' },
  { acNo: 21, name: 'Habba Kadal', localName: 'हब्बाकदल', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Shamim Firdous', winnerVotes2024: 12437, runnerUp2024: 'BJP', margin2024: 9538, currentParty: 'JKNC' },
  { acNo: 22, name: 'Lal Chowk', localName: 'लाल चौक', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Sheikh Ahsan Ahmed', winnerVotes2024: 16731, runnerUp2024: 'OTH', margin2024: 11765, currentParty: 'JKNC' },
  { acNo: 23, name: 'Chanapora', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Mushtaq Guroo', winnerVotes2024: 13717, runnerUp2024: 'OTH', margin2024: 5688, currentParty: 'JKNC' },
  { acNo: 24, name: 'Zadibal', localName: 'ज़दीबल', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Tanvir Sadiq', winnerVotes2024: 22189, runnerUp2024: 'JKPDP', margin2024: 16173, currentParty: 'JKNC' },
  { acNo: 25, name: 'Eidgah', district: 'Srinagar', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Mubarik Gul', winnerVotes2024: 7700, runnerUp2024: 'IND', margin2024: 1680, currentParty: 'JKNC' },
  { acNo: 26, name: 'Central Shalteng', localName: 'सेंट्रल शालतेंग', district: 'Srinagar', type: 'GEN', winner2024: 'INC', winnerName2024: 'Tariq Hameed Karra', winnerVotes2024: 18933, runnerUp2024: 'IND', margin2024: 14395, currentParty: 'INC' },
  { acNo: 27, name: 'Budgam', localName: 'बडगाम', district: 'Budgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Omar Abdullah', winnerVotes2024: 36010, runnerUp2024: 'JKPDP', margin2024: 18485, currentParty: 'JKNC' },
  { acNo: 28, name: 'Beerwah', localName: 'बीरवाह', district: 'Budgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Shafi Ahmad Wani', winnerVotes2024: 20118, runnerUp2024: 'IND', margin2024: 4161, currentParty: 'JKNC' },
  { acNo: 29, name: 'Khan Sahib', district: 'Budgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Saif Ud Din Bhat', winnerVotes2024: 33225, runnerUp2024: 'JKPDP', margin2024: 11614, currentParty: 'JKNC' },
  { acNo: 30, name: 'Charari Sharief', localName: 'चरार-ए-शरीफ', district: 'Budgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Abdul Rahim Rather', winnerVotes2024: 35957, runnerUp2024: 'JKPDP', margin2024: 11496, currentParty: 'JKNC' },
  { acNo: 31, name: 'Chadoora', localName: 'चादूरा', district: 'Budgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Ali Mohammad Dar', winnerVotes2024: 31991, runnerUp2024: 'JKPDP', margin2024: 17218, currentParty: 'JKNC' },
  { acNo: 32, name: 'Pampore', localName: 'पाम्पोर', district: 'Pulwama', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Hasnain Masoodi', winnerVotes2024: 15088, runnerUp2024: 'JKPDP', margin2024: 2763, currentParty: 'JKNC' },
  { acNo: 33, name: 'Tral', localName: 'त्राल', district: 'Pulwama', type: 'GEN', winner2024: 'JKPDP', winnerName2024: 'Rafiq Ahmad Naik', winnerVotes2024: 10710, runnerUp2024: 'INC', margin2024: 460, currentParty: 'JKPDP' },
  { acNo: 34, name: 'Pulwama', district: 'Pulwama', type: 'GEN', winner2024: 'JKPDP', winnerName2024: 'Waheed Ur Rehman Para', winnerVotes2024: 24716, runnerUp2024: 'JKNC', margin2024: 8148, currentParty: 'JKPDP' },
  { acNo: 35, name: 'Rajpora', localName: 'राजपोरा', district: 'Pulwama', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Ghulam Mohit Uddin Mir', winnerVotes2024: 25627, runnerUp2024: 'JKPDP', margin2024: 14313, currentParty: 'JKNC' },
  { acNo: 36, name: 'Zainapora', district: 'Shopian', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Showkat Hussain', winnerVotes2024: 28251, runnerUp2024: 'IND', margin2024: 13233, currentParty: 'JKNC' },
  { acNo: 37, name: 'Shopian', localName: 'शोपियां', district: 'Shopian', type: 'GEN', winner2024: 'IND', winnerName2024: 'Shabir Ahmad Kullay', winnerVotes2024: 14113, runnerUp2024: 'IND', margin2024: 1207, currentParty: 'IND' },
  { acNo: 38, name: 'DH Pora', localName: 'डी.एच. पोरा', district: 'Kulgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Sakeena Masood', winnerVotes2024: 36623, runnerUp2024: 'JKPDP', margin2024: 17449, currentParty: 'JKNC' },
  { acNo: 39, name: 'Kulgam', localName: 'कुलगाम', district: 'Kulgam', type: 'GEN', winner2024: 'CPI(M)', winnerName2024: 'Md Yusuf Tarigami', winnerVotes2024: 33634, runnerUp2024: 'IND', margin2024: 7838, currentParty: 'CPI(M)' },
  { acNo: 40, name: 'Devsar', localName: 'देवसर', district: 'Kulgam', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Peerzada Feroze Ahamad', winnerVotes2024: 18230, runnerUp2024: 'JKPDP', margin2024: 840, currentParty: 'JKNC' },
  { acNo: 41, name: 'Dooru', localName: 'दूरू', district: 'Anantnag', type: 'GEN', winner2024: 'INC', winnerName2024: 'Gulam Ahmad Mir', winnerVotes2024: 44270, runnerUp2024: 'JKPDP', margin2024: 29728, currentParty: 'INC' },
  { acNo: 42, name: 'Kokernag', localName: 'कोकरनाग', district: 'Anantnag', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Zafar Ali Khatana', winnerVotes2024: 17949, runnerUp2024: 'JKPDP', margin2024: 6162, currentParty: 'JKNC' },
  { acNo: 43, name: 'Anantnag West', localName: 'अनंतनाग पश्चिम', district: 'Anantnag', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Abdul Majeed Bhat', winnerVotes2024: 25135, runnerUp2024: 'JKPDP', margin2024: 10435, currentParty: 'JKNC' },
  { acNo: 44, name: 'Anantnag', localName: 'अनंतनाग', district: 'Anantnag', type: 'GEN', winner2024: 'INC', winnerName2024: 'Peerzada Mohammad Syed', winnerVotes2024: 6679, runnerUp2024: 'JKPDP', margin2024: 1686, currentParty: 'INC' },
  { acNo: 45, name: 'Srigufwara–Bijbehara', localName: 'श्रीगुफवारा - बिजबेहरा', district: 'Anantnag', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Bashir Ahmed Shah Veeri', winnerVotes2024: 33299, runnerUp2024: 'JKPDP', margin2024: 9770, currentParty: 'JKNC' },
  { acNo: 46, name: 'Shangus–Anantnag East', localName: 'शांगस-अनंतनाग पूर्व', district: 'Anantnag', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Reyaz Ahmad Khan', winnerVotes2024: 30345, runnerUp2024: 'JKPDP', margin2024: 14532, currentParty: 'JKNC' },
  { acNo: 47, name: 'Pahalgam', localName: 'पहलगाम', district: 'Anantnag', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Altaf Ahmad Wani', winnerVotes2024: 26210, runnerUp2024: 'OTH', margin2024: 13756, currentParty: 'JKNC' },
  { acNo: 48, name: 'Inderwal', district: 'Kishtwar', type: 'GEN', winner2024: 'IND', winnerName2024: 'Payare Lal Sharma', winnerVotes2024: 14195, runnerUp2024: 'IND', margin2024: 643, currentParty: 'IND' },
  { acNo: 49, name: 'Kishtwar', localName: 'किश्तवाड़', district: 'Kishtwar', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Shagun Parihar', winnerVotes2024: 29053, runnerUp2024: 'JKNC', margin2024: 521, currentParty: 'BJP' },
  { acNo: 50, name: 'Padder–Nagseni', localName: 'पाद्दर-नागसेनी', district: 'Kishtwar', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Sunil Kumar Sharma', winnerVotes2024: 17036, runnerUp2024: 'JKNC', margin2024: 1546, currentParty: 'BJP' },
  { acNo: 51, name: 'Bhadarwah', localName: 'भद्रवाह', district: 'Doda', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Daleep Singh', winnerVotes2024: 42128, runnerUp2024: 'JKNC', margin2024: 10130, currentParty: 'BJP' },
  { acNo: 52, name: 'Doda', localName: 'डोडा', district: 'Doda', type: 'GEN', winner2024: 'AAP', winnerName2024: 'Mehraj Malik', winnerVotes2024: 23228, runnerUp2024: 'BJP', margin2024: 4538, currentParty: 'AAP' },
  { acNo: 53, name: 'Doda West', localName: 'डोडा पश्चिम', district: 'Doda', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Shakti Raj Parihar', winnerVotes2024: 33964, runnerUp2024: 'INC', margin2024: 3453, currentParty: 'BJP' },
  { acNo: 54, name: 'Ramban', localName: 'रामबन', district: 'Ramban', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Arjun Singh Raju', winnerVotes2024: 28425, runnerUp2024: 'IND', margin2024: 9013, currentParty: 'JKNC' },
  { acNo: 55, name: 'Banihal', localName: 'बनिहाल', district: 'Ramban', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Sajad Shaheen', winnerVotes2024: 33128, runnerUp2024: 'JKPDP', margin2024: 6110, currentParty: 'JKNC' },
  { acNo: 56, name: 'Gulabgarh', localName: 'गुलाबगढ़', district: 'Reasi', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Khurshied Ahmed', winnerVotes2024: 30591, runnerUp2024: 'IND', margin2024: 6527, currentParty: 'JKNC' },
  { acNo: 57, name: 'Reasi', localName: 'रियासी', district: 'Reasi', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Kuldeep Raj Dubey', winnerVotes2024: 39647, runnerUp2024: 'INC', margin2024: 18815, currentParty: 'BJP' },
  { acNo: 58, name: 'Shri Mata Vaishno Devi', localName: 'श्री माता वैष्णो देवी', district: 'Reasi', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Baldev Raj Sharma', winnerVotes2024: 18199, runnerUp2024: 'IND', margin2024: 1995, currentParty: 'BJP' },
  { acNo: 59, name: 'Udhampur West', localName: 'उधमपुर पश्चिम', district: 'Udhampur', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Pawan Kumar Gupta', winnerVotes2024: 47164, runnerUp2024: 'INC', margin2024: 20752, currentParty: 'BJP' },
  { acNo: 60, name: 'Udhampur East', localName: 'उधमपुर पूर्व', district: 'Udhampur', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Ranbir Singh Pathania', winnerVotes2024: 32966, runnerUp2024: 'IND', margin2024: 2349, currentParty: 'BJP' },
  { acNo: 61, name: 'Chenani', localName: 'चेनानी', district: 'Udhampur', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Balwant Singh Mankotia', winnerVotes2024: 47990, runnerUp2024: 'JKNPP', margin2024: 15611, currentParty: 'BJP' },
  { acNo: 62, name: 'Ramnagar', localName: 'रामनगर', district: 'Udhampur', type: 'SC', winner2024: 'BJP', winnerName2024: 'Sunil Bhardwaj', winnerVotes2024: 34550, runnerUp2024: 'JKNPP', margin2024: 9306, currentParty: 'BJP' },
  { acNo: 63, name: 'Bani', localName: 'बानी', district: 'Kathua', type: 'GEN', winner2024: 'IND', winnerName2024: 'Rameshwar Singh', winnerVotes2024: 18672, runnerUp2024: 'BJP', margin2024: 2048, currentParty: 'IND' },
  { acNo: 64, name: 'Billawar', localName: 'बिलावर', district: 'Kathua', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Satish Kumar Sharma', winnerVotes2024: 44629, runnerUp2024: 'INC', margin2024: 21368, currentParty: 'BJP' },
  { acNo: 65, name: 'Basohli', district: 'Kathua', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Darshan Kumar', winnerVotes2024: 31874, runnerUp2024: 'INC', margin2024: 16034, currentParty: 'BJP' },
  { acNo: 66, name: 'Jasrota', localName: 'जसरोटा', district: 'Kathua', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Rajiv Jasrotia', winnerVotes2024: 34157, runnerUp2024: 'IND', margin2024: 12420, currentParty: 'BJP' },
  { acNo: 67, name: 'Kathua', localName: 'कठुआ', district: 'Kathua', type: 'SC', winner2024: 'BJP', winnerName2024: 'Bharat Bhushan', winnerVotes2024: 45944, runnerUp2024: 'OTH', margin2024: 12117, currentParty: 'BJP' },
  { acNo: 68, name: 'Hiranagar', localName: 'हीरानगर', district: 'Kathua', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Vijay Kumar', winnerVotes2024: 36737, runnerUp2024: 'INC', margin2024: 8610, currentParty: 'BJP' },
  { acNo: 69, name: 'Ramgarh', localName: 'रामगढ़', district: 'Samba', type: 'SC', winner2024: 'BJP', winnerName2024: 'Devinder Kumar Manyal', winnerVotes2024: 35672, runnerUp2024: 'INC', margin2024: 14202, currentParty: 'BJP' },
  { acNo: 70, name: 'Samba', district: 'Samba', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Surjeet Singh Slathia', winnerVotes2024: 43182, runnerUp2024: 'IND', margin2024: 30309, currentParty: 'BJP' },
  { acNo: 71, name: 'Vijaypur', localName: 'विजयपुर', district: 'Samba', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Chander Prakash Ganga', winnerVotes2024: 32859, runnerUp2024: 'JKNC', margin2024: 19040, currentParty: 'BJP' },
  { acNo: 72, name: 'Bishnah', localName: 'बिश्नाह', district: 'Jammu', type: 'SC', winner2024: 'BJP', winnerName2024: 'Rajeev Kumar', winnerVotes2024: 53435, runnerUp2024: 'INC', margin2024: 15627, currentParty: 'BJP' },
  { acNo: 73, name: 'Suchetgarh', localName: 'सुचेतगढ़', district: 'Jammu', type: 'SC', winner2024: 'BJP', winnerName2024: 'Gharu Ram Bhagat', winnerVotes2024: 39302, runnerUp2024: 'INC', margin2024: 11141, currentParty: 'BJP' },
  { acNo: 74, name: 'RS Pora–Jammu South', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Narinder Singh Raina', winnerVotes2024: 43317, runnerUp2024: 'INC', margin2024: 1966, currentParty: 'BJP' },
  { acNo: 75, name: 'Bahu', localName: 'बहू', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Vikram Randhawa', winnerVotes2024: 40385, runnerUp2024: 'INC', margin2024: 11251, currentParty: 'BJP' },
  { acNo: 76, name: 'Jammu East', localName: 'जम्मू पूर्व', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Yudhvir Sethi', winnerVotes2024: 42589, runnerUp2024: 'INC', margin2024: 18114, currentParty: 'BJP' },
  { acNo: 77, name: 'Nagrota', localName: 'नगरोटा', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Devender Singh Rana', winnerVotes2024: 48113, runnerUp2024: 'JKNC', margin2024: 30472, currentParty: 'BJP' },
  { acNo: 78, name: 'Jammu West', localName: 'जम्मू पश्चिम', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Arvind Gupta', winnerVotes2024: 41963, runnerUp2024: 'INC', margin2024: 22127, currentParty: 'BJP' },
  { acNo: 79, name: 'Jammu North', localName: 'जम्मू उत्तर', district: 'Jammu', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Sham Lal Sharma', winnerVotes2024: 47219, runnerUp2024: 'JKNC', margin2024: 27363, currentParty: 'BJP' },
  { acNo: 80, name: 'Marh', district: 'Jammu', type: 'SC', winner2024: 'BJP', winnerName2024: 'Surinder Kumar', winnerVotes2024: 42563, runnerUp2024: 'INC', margin2024: 23086, currentParty: 'BJP' },
  { acNo: 81, name: 'Akhnoor', localName: 'अखनूर', district: 'Jammu', type: 'SC', winner2024: 'BJP', winnerName2024: 'Mohan Lal', winnerVotes2024: 49927, runnerUp2024: 'INC', margin2024: 25248, currentParty: 'BJP' },
  { acNo: 82, name: 'Chhamb', localName: 'छम्ब', district: 'Jammu', type: 'GEN', winner2024: 'IND', winnerName2024: 'Satish Sharma', winnerVotes2024: 33985, runnerUp2024: 'BJP', margin2024: 6929, currentParty: 'IND' },
  { acNo: 83, name: 'Kalakote–Sunderbani', localName: 'कालाकोट - सुंदरबनी', district: 'Rajouri', type: 'GEN', winner2024: 'BJP', winnerName2024: 'Randhir Singh', winnerVotes2024: 35010, runnerUp2024: 'JKNC', margin2024: 14409, currentParty: 'BJP' },
  { acNo: 84, name: 'Nowshera', localName: 'नौशेरा', district: 'Rajouri', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Surinder Choudhary', winnerVotes2024: 35069, runnerUp2024: 'BJP', margin2024: 7819, currentParty: 'JKNC' },
  { acNo: 85, name: 'Rajouri', localName: 'राजौरी', district: 'Rajouri', type: 'ST', winner2024: 'INC', winnerName2024: 'Iftkar Ahmed', winnerVotes2024: 28293, runnerUp2024: 'BJP', margin2024: 1404, currentParty: 'INC' },
  { acNo: 86, name: 'Budhal', localName: 'बुधल', district: 'Rajouri', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Javaid Iqbal', winnerVotes2024: 42043, runnerUp2024: 'BJP', margin2024: 18908, currentParty: 'JKNC' },
  { acNo: 87, name: 'Thanamandi', district: 'Rajouri', type: 'ST', winner2024: 'IND', winnerName2024: 'Muzaffar Iqbal Khan', winnerVotes2024: 32645, runnerUp2024: 'BJP', margin2024: 6179, currentParty: 'IND' },
  { acNo: 88, name: 'Surankote', localName: 'सुरनकोट', district: 'Poonch', type: 'ST', winner2024: 'IND', winnerName2024: 'Choudhary Mohammed Akram', winnerVotes2024: 34201, runnerUp2024: 'INC', margin2024: 8551, currentParty: 'IND' },
  { acNo: 89, name: 'Poonch Haveli', localName: 'पुंछ हवेली', district: 'Poonch', type: 'GEN', winner2024: 'JKNC', winnerName2024: 'Ajaz Ahmed Jan', winnerVotes2024: 41807, runnerUp2024: 'BJP', margin2024: 20879, currentParty: 'JKNC' },
  { acNo: 90, name: 'Mendhar', localName: 'मेंढर', district: 'Poonch', type: 'ST', winner2024: 'JKNC', winnerName2024: 'Javed Ahmed Rana', winnerVotes2024: 32176, runnerUp2024: 'BJP', margin2024: 14906, currentParty: 'JKNC' },
];

/** Get constituency data by AC number */
export function getJKConstituency(acNo: number): JKConstituencySeed | undefined {
  return JK_CONSTITUENCIES.find((c) => c.acNo === acNo);
}

/** Get all constituencies in a district */
export function getJKConstituenciesByDistrict(district: string): JKConstituencySeed[] {
  return JK_CONSTITUENCIES.filter((c) => c.district.toLowerCase() === district.toLowerCase());
}

/** Get all constituencies won by a party */
export function getJKConstituenciesByParty(party: string): JKConstituencySeed[] {
  return JK_CONSTITUENCIES.filter((c) => c.currentParty === party);
}
