/**
 * MN — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface MNElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const MN_ELECTION_HISTORY: MNElectionResult[] = [
  {
    year: 2022,
    partyResults: {
      'BJP': 32,
      'NPP': 7,
      'JDU': 6,
      'INC': 5,
      'NPF': 5,
      'IND': 3,
      'KPA': 2,
    },
    totalSeats: 60,
    rulingParty: 'BJP',
  },
];

export function getMNElectionByYear(year: number) {
  return MN_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getMNPartyTrend(party: string) {
  return MN_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
