/**
 * Manipur Assembly Constituencies — 2022 General Election (60 seats)
 *
 * SOURCE: TCPD "Lok Dhaba" (Trivedi Centre for Political Data, Ashoka University),
 *         Manipur_AE dataset — ECI-sourced constituency results. Uses the
 *         official ECI AC numbering (1-60). Winner/runner-up parties,
 *         vote counts, and margins are the ECI 2022 results as compiled by TCPD.
 *         Reservation (GEN/SC/ST) and district are from the same dataset.
 *         Auto-generated by scripts/build-tcpd-seed.mjs — do not hand-edit.
 *
 * PARTY TALLY 2022: BJP 32 | NPP 7 | JDU 6 | INC 5 | NPF 5 | IND 3 | KPA 2 = 60
 */

export interface MNConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in local script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2022: string;
  winnerName2022: string;
  winnerVotes2022: number;
  runnerUp2022: string;
  margin2022: number;
  currentParty: string;
}

export const MN_CONSTITUENCIES: MNConstituencySeed[] = [
  { acNo: 1, name: 'Khundrakpam', district: 'Imphal East', type: 'GEN', winner2022: 'INC', winnerName2022: 'Thokchom Lokeshwar Singh', winnerVotes2022: 12211, runnerUp2022: 'BJP', margin2022: 215, currentParty: 'INC' },
  { acNo: 2, name: 'Heingang', localName: 'হেইংগাং', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Nongthombam Biren Singh', winnerVotes2022: 24814, runnerUp2022: 'INC', margin2022: 18271, currentParty: 'BJP' },
  { acNo: 3, name: 'Khurai', localName: 'খুরাই', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Leishangthem Susindro Meitei', winnerVotes2022: 11131, runnerUp2022: 'NPP', margin2022: 2237, currentParty: 'BJP' },
  { acNo: 4, name: 'Kshetrigao', district: 'Imphal East', type: 'GEN', winner2022: 'NPP', winnerName2022: 'Sheikh Noorul Hassan', winnerVotes2022: 13118, runnerUp2022: 'BJP', margin2022: 742, currentParty: 'NPP' },
  { acNo: 5, name: 'Thongju', localName: 'থোংজু', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Thongam Biswajit Singh', winnerVotes2022: 15338, runnerUp2022: 'INC', margin2022: 6689, currentParty: 'BJP' },
  { acNo: 6, name: 'Keirao', localName: 'কেইরাও', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Lourembam Rameshwor Meetei', winnerVotes2022: 17335, runnerUp2022: 'NPP', margin2022: 8209, currentParty: 'BJP' },
  { acNo: 7, name: 'Andro', localName: 'আন্দ্রো', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Thounaojam Shyamkumar', winnerVotes2022: 16739, runnerUp2022: 'NPP', margin2022: 1457, currentParty: 'BJP' },
  { acNo: 8, name: 'Lamlai', localName: 'লামলাই', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Khongbantabam Ibomcha', winnerVotes2022: 10105, runnerUp2022: 'JDU', margin2022: 121, currentParty: 'BJP' },
  { acNo: 9, name: 'Thangmeiband', localName: 'থাংমেইবন্দ', district: 'Imphal West', type: 'GEN', winner2022: 'JDU', winnerName2022: 'Khumukcham Joykisan Singh', winnerVotes2022: 13629, runnerUp2022: 'BJP', margin2022: 3773, currentParty: 'JDU' },
  { acNo: 10, name: 'Uripok', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Khwairakpam Raghumani Singh', winnerVotes2022: 8335, runnerUp2022: 'NPP', margin2022: 909, currentParty: 'BJP' },
  { acNo: 11, name: 'Sagolband', localName: 'সাগোলবন্দ', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Rajkumar Imo Singh', winnerVotes2022: 11054, runnerUp2022: 'JDU', margin2022: 2656, currentParty: 'BJP' },
  { acNo: 12, name: 'Keishamthong', district: 'Imphal West', type: 'GEN', winner2022: 'IND', winnerName2022: 'Sapam Nishikant Singh', winnerVotes2022: 8874, runnerUp2022: 'RPIA', margin2022: 187, currentParty: 'IND' },
  { acNo: 13, name: 'Singjamei', localName: 'শিংজামৈ', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Yumnam Khemchand Singh', winnerVotes2022: 8709, runnerUp2022: 'NPP', margin2022: 2295, currentParty: 'BJP' },
  { acNo: 14, name: 'Yaiskul', localName: 'য়াইস্কুল', district: 'Imphal East', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Thokchom Satyabrata Singh', winnerVotes2022: 9724, runnerUp2022: 'NPP', margin2022: 632, currentParty: 'BJP' },
  { acNo: 15, name: 'Wangkhei', localName: 'ওয়াংখৈ', district: 'Imphal East', type: 'GEN', winner2022: 'JDU', winnerName2022: 'Thangjam Arunkumar', winnerVotes2022: 11593, runnerUp2022: 'BJP', margin2022: 753, currentParty: 'JDU' },
  { acNo: 16, name: 'Sekmai', localName: 'সেকমাই', district: 'Imphal West', type: 'SC', winner2022: 'BJP', winnerName2022: 'Heikham Dingo Singh', winnerVotes2022: 10010, runnerUp2022: 'NPP', margin2022: 3333, currentParty: 'BJP' },
  { acNo: 17, name: 'Lamsang', localName: 'লামসাং', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Sorokhaibam Rajen Singh', winnerVotes2022: 15185, runnerUp2022: 'NPP', margin2022: 400, currentParty: 'BJP' },
  { acNo: 18, name: 'Konthoujam', localName: 'কোনথৌজাম', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Dr. Sapam Ranjan Singh', winnerVotes2022: 13432, runnerUp2022: 'NPP', margin2022: 394, currentParty: 'BJP' },
  { acNo: 19, name: 'Patsoi', localName: 'পাতসোই', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Sapam Kunjakeswor (Keba) Singh', winnerVotes2022: 12186, runnerUp2022: 'INC', margin2022: 687, currentParty: 'BJP' },
  { acNo: 20, name: 'Langthabal', localName: 'লাংথাবল', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Karam Shyam', winnerVotes2022: 10815, runnerUp2022: 'INC', margin2022: 2053, currentParty: 'BJP' },
  { acNo: 21, name: 'Naoriya Pakhanglakpa', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Sagolshem Kebi Devi', winnerVotes2022: 11058, runnerUp2022: 'NPP', margin2022: 531, currentParty: 'BJP' },
  { acNo: 22, name: 'Wangoi', localName: 'ওয়াঙ্গোই', district: 'Imphal West', type: 'GEN', winner2022: 'NPP', winnerName2022: 'Khuraijam Loken Singh', winnerVotes2022: 15606, runnerUp2022: 'BJP', margin2022: 3266, currentParty: 'NPP' },
  { acNo: 23, name: 'Mayang Imphal', district: 'Imphal West', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Kongkham Robindro Singh', winnerVotes2022: 14642, runnerUp2022: 'INC', margin2022: 6129, currentParty: 'BJP' },
  { acNo: 24, name: 'Nambol', localName: 'নাম্বোল', district: 'Bishnupur', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Thounaojam Basanta Kumar Singh', winnerVotes2022: 16885, runnerUp2022: 'INC', margin2022: 3060, currentParty: 'BJP' },
  { acNo: 25, name: 'Oinam', localName: 'ওইনাম', district: 'Bishnupur', type: 'GEN', winner2022: 'NPP', winnerName2022: 'Irengbam Nalini Devi', winnerVotes2022: 10808, runnerUp2022: 'BJP', margin2022: 442, currentParty: 'NPP' },
  { acNo: 26, name: 'Bishnupur', district: 'Bishnupur', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Konthoujam Govindas Singh', winnerVotes2022: 13611, runnerUp2022: 'JDU', margin2022: 1409, currentParty: 'BJP' },
  { acNo: 27, name: 'Moirang', localName: 'মইরাং', district: 'Bishnupur', type: 'GEN', winner2022: 'NPP', winnerName2022: 'Thongam Shanti Singh', winnerVotes2022: 14349, runnerUp2022: 'BJP', margin2022: 2231, currentParty: 'NPP' },
  { acNo: 28, name: 'Thanga', localName: 'থাঙ্গা', district: 'Bishnupur', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Tongbram Robindro Singh', winnerVotes2022: 13095, runnerUp2022: 'INC', margin2022: 5251, currentParty: 'BJP' },
  { acNo: 29, name: 'Kumbi', localName: 'কুম্বি', district: 'Bishnupur', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Sanasam Premchandra Singh', winnerVotes2022: 8513, runnerUp2022: 'JDU', margin2022: 372, currentParty: 'BJP' },
  { acNo: 30, name: 'Lilong', localName: 'লিলং', district: 'Thoubal', type: 'GEN', winner2022: 'JDU', winnerName2022: 'Mohd Abdul Nasir', winnerVotes2022: 16886, runnerUp2022: 'BJP', margin2022: 570, currentParty: 'JDU' },
  { acNo: 31, name: 'Thoubal', localName: 'থৌবাল', district: 'Thoubal', type: 'GEN', winner2022: 'INC', winnerName2022: 'Okram Ibobi Singh', winnerVotes2022: 15085, runnerUp2022: 'BJP', margin2022: 2543, currentParty: 'INC' },
  { acNo: 32, name: 'Wangkhem', localName: 'ওয়াংখেম', district: 'Thoubal', type: 'GEN', winner2022: 'INC', winnerName2022: 'Keisham Meghachandra Singh', winnerVotes2022: 8889, runnerUp2022: 'BJP', margin2022: 1292, currentParty: 'INC' },
  { acNo: 33, name: 'Heirok', localName: 'হৈরোক', district: 'Thoubal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Thokchom Radheshyam Singh', winnerVotes2022: 13589, runnerUp2022: 'INC', margin2022: 403, currentParty: 'BJP' },
  { acNo: 34, name: 'Wangjing Tentha', localName: 'ওয়াংজিং তেন্থা', district: 'Thoubal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Paonam Brojen Singh', winnerVotes2022: 15765, runnerUp2022: 'INC', margin2022: 1913, currentParty: 'BJP' },
  { acNo: 35, name: 'Khangabok', localName: 'খঙ্গাবোক', district: 'Thoubal', type: 'GEN', winner2022: 'INC', winnerName2022: 'Surjakumar Okram', winnerVotes2022: 17435, runnerUp2022: 'BJP', margin2022: 7803, currentParty: 'INC' },
  { acNo: 36, name: 'Wabgai', localName: 'ওয়াবগাই', district: 'Thoubal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Dr.Usham Deben Singh', winnerVotes2022: 9138, runnerUp2022: 'INC', margin2022: 50, currentParty: 'BJP' },
  { acNo: 37, name: 'Kakching', localName: 'কাকচিং', district: 'Thoubal', type: 'GEN', winner2022: 'NPP', winnerName2022: 'Mayanglambam Rameshwar Singh', winnerVotes2022: 8546, runnerUp2022: 'BJP', margin2022: 1205, currentParty: 'NPP' },
  { acNo: 38, name: 'Hiyanglam', district: 'Thoubal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Dr. Yumnam Radheshyam Singh', winnerVotes2022: 8613, runnerUp2022: 'INC', margin2022: 2029, currentParty: 'BJP' },
  { acNo: 39, name: 'Sugnu', district: 'Thoubal', type: 'GEN', winner2022: 'INC', winnerName2022: 'Kangujam Ranjit Singh', winnerVotes2022: 12673, runnerUp2022: 'BJP', margin2022: 1016, currentParty: 'INC' },
  { acNo: 40, name: 'Jiribam', localName: 'জিরিবাম', district: 'Imphal East', type: 'GEN', winner2022: 'JDU', winnerName2022: 'Md. Achab Uddin', winnerVotes2022: 12313, runnerUp2022: 'BJP', margin2022: 416, currentParty: 'JDU' },
  { acNo: 41, name: 'Chandel', localName: 'চান্দেল', district: 'Chandel', type: 'ST', winner2022: 'BJP', winnerName2022: 'Ss. Olish', winnerVotes2022: 37066, runnerUp2022: 'NPF', margin2022: 27341, currentParty: 'BJP' },
  { acNo: 42, name: 'Tengnoupal', localName: 'তেংনৌপাল', district: 'Chandel', type: 'ST', winner2022: 'BJP', winnerName2022: 'Letpao Haokip', winnerVotes2022: 21663, runnerUp2022: 'NPF', margin2022: 6411, currentParty: 'BJP' },
  { acNo: 43, name: 'Phungyar', localName: 'ফুংয়ার', district: 'Ukhrul', type: 'ST', winner2022: 'NPF', winnerName2022: 'Leishiyo Keishing', winnerVotes2022: 11642, runnerUp2022: 'BJP', margin2022: 779, currentParty: 'NPF' },
  { acNo: 44, name: 'Ukhrul', localName: 'উখরুল', district: 'Ukhrul', type: 'ST', winner2022: 'NPF', winnerName2022: 'Ram Muivah', winnerVotes2022: 15503, runnerUp2022: 'INC', margin2022: 942, currentParty: 'NPF' },
  { acNo: 45, name: 'Chingai', localName: 'চিঙাই', district: 'Ukhrul', type: 'ST', winner2022: 'NPF', winnerName2022: 'Khashim Vashum', winnerVotes2022: 12837, runnerUp2022: 'NPP', margin2022: 2336, currentParty: 'NPF' },
  { acNo: 46, name: 'Saikul', localName: 'সাইকুল', district: 'Senapati', type: 'ST', winner2022: 'KPA', winnerName2022: 'Kimneo Haokip Hangshing', winnerVotes2022: 6710, runnerUp2022: 'IND', margin2022: 1249, currentParty: 'KPA' },
  { acNo: 47, name: 'Karong', localName: 'কারং', district: 'Senapati', type: 'ST', winner2022: 'IND', winnerName2022: 'J Kumo Sha', winnerVotes2022: 17191, runnerUp2022: 'BJP', margin2022: 3542, currentParty: 'IND' },
  { acNo: 48, name: 'Mao', localName: 'মাও', district: 'Senapati', type: 'ST', winner2022: 'NPF', winnerName2022: 'Losii Dikho', winnerVotes2022: 29591, runnerUp2022: 'IND', margin2022: 8513, currentParty: 'NPF' },
  { acNo: 49, name: 'Tadubi', localName: 'তাদুবি', district: 'Senapati', type: 'ST', winner2022: 'NPP', winnerName2022: 'N. Kayisii', winnerVotes2022: 21601, runnerUp2022: 'NPF', margin2022: 549, currentParty: 'NPP' },
  { acNo: 50, name: 'Kangpokpi', localName: 'কাংপোকপি', district: 'Senapati', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Nemcha Kipgen', winnerVotes2022: 14412, runnerUp2022: 'JDU', margin2022: 5396, currentParty: 'BJP' },
  { acNo: 51, name: 'Saitu', localName: 'সাইতু', district: 'Senapati', type: 'ST', winner2022: 'IND', winnerName2022: 'Haokholet Kipgen', winnerVotes2022: 12456, runnerUp2022: 'BJP', margin2022: 2694, currentParty: 'IND' },
  { acNo: 52, name: 'Tamei', localName: 'তামৈ', district: 'Tamenglong', type: 'ST', winner2022: 'NPF', winnerName2022: 'Awangbow Newmai', winnerVotes2022: 19643, runnerUp2022: 'NPP', margin2022: 1698, currentParty: 'NPF' },
  { acNo: 53, name: 'Tamenglong', district: 'Tamenglong', type: 'ST', winner2022: 'NPP', winnerName2022: 'Janghemlung Panmei', winnerVotes2022: 10456, runnerUp2022: 'BJP', margin2022: 1309, currentParty: 'NPP' },
  { acNo: 54, name: 'Nungba', localName: 'নুংবা', district: 'Tamenglong', type: 'ST', winner2022: 'BJP', winnerName2022: 'Dinganglung Gangmei', winnerVotes2022: 14464, runnerUp2022: 'INC', margin2022: 3786, currentParty: 'BJP' },
  { acNo: 55, name: 'Tipaimukh', localName: 'তিপৈমুখ', district: 'Churachandpur', type: 'ST', winner2022: 'JDU', winnerName2022: 'Ngursanglur Sanate', winnerVotes2022: 6267, runnerUp2022: 'BJP', margin2022: 1249, currentParty: 'JDU' },
  { acNo: 56, name: 'Thanlon', localName: 'থানলোন', district: 'Churachandpur', type: 'ST', winner2022: 'BJP', winnerName2022: 'Vungzagin Valte', winnerVotes2022: 4863, runnerUp2022: 'NPP', margin2022: 751, currentParty: 'BJP' },
  { acNo: 57, name: 'Henglep', localName: 'হেঙ্গলেপ', district: 'Churachandpur', type: 'ST', winner2022: 'BJP', winnerName2022: 'Letzamang Haokip', winnerVotes2022: 13897, runnerUp2022: 'INC', margin2022: 7848, currentParty: 'BJP' },
  { acNo: 58, name: 'Churachandpur', localName: 'চুরাচাঁদপুর', district: 'Churachandpur', type: 'ST', winner2022: 'JDU', winnerName2022: 'L.M. Khaute', winnerVotes2022: 18231, runnerUp2022: 'BJP', margin2022: 624, currentParty: 'JDU' },
  { acNo: 59, name: 'Saikot', district: 'Churachandpur', type: 'ST', winner2022: 'BJP', winnerName2022: 'Paolienlal Haokip', winnerVotes2022: 18457, runnerUp2022: 'NPP', margin2022: 5871, currentParty: 'BJP' },
  { acNo: 60, name: 'Singhat', localName: 'সিংহাত', district: 'Churachandpur', type: 'ST', winner2022: 'KPA', winnerName2022: 'Chinlunthang', winnerVotes2022: 12098, runnerUp2022: 'BJP', margin2022: 1919, currentParty: 'KPA' },
];

export function getMNConstituency(acNo: number): MNConstituencySeed | undefined {
  return MN_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
