/**
 * MN Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2022 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const MN_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 61706, totalVoters: 27864, turnout2023: 89.4, maleVoters: 14211, femaleVoters: 13653, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 2, population: 46703, totalVoters: 34448, turnout2023: 91.72, maleVoters: 17259, femaleVoters: 17189, literacy: 82.9, urbanPercent: 14.8, scPercent: 0, stPercent: 30.8, areaSqKm: 76 },
  { acNo: 3, population: 51521, totalVoters: 36233, turnout2023: 91.38, maleVoters: 17916, femaleVoters: 18317, literacy: 84.9, urbanPercent: 18.3, scPercent: 0, stPercent: 26, areaSqKm: 166 },
  { acNo: 4, population: 61706, totalVoters: 37227, turnout2023: 91.6, maleVoters: 18986, femaleVoters: 18241, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 5, population: 73341, totalVoters: 32723, turnout2023: 90.18, maleVoters: 16770, femaleVoters: 15953, literacy: 84.9, urbanPercent: 35.7, scPercent: 0, stPercent: 46.5, areaSqKm: 37 },
  { acNo: 6, population: 39164, totalVoters: 30824, turnout2023: 91.17, maleVoters: 15119, femaleVoters: 15705, literacy: 79.9, urbanPercent: 25.2, scPercent: 0, stPercent: 26, areaSqKm: 139 },
  { acNo: 7, population: 48585, totalVoters: 36353, turnout2023: 91.94, maleVoters: 18123, femaleVoters: 18230, literacy: 82.9, urbanPercent: 11.3, scPercent: 0, stPercent: 30.8, areaSqKm: 74 },
  { acNo: 8, population: 43386, totalVoters: 30608, turnout2023: 93.65, maleVoters: 15595, femaleVoters: 15013, literacy: 80.9, urbanPercent: 21.8, scPercent: 0, stPercent: 26, areaSqKm: 137 },
  { acNo: 9, population: 52106, totalVoters: 28845, turnout2023: 84.25, maleVoters: 14798, femaleVoters: 14047, literacy: 79.9, urbanPercent: 39.2, scPercent: 0, stPercent: 46.5, areaSqKm: 39 },
  { acNo: 10, population: 61706, totalVoters: 26281, turnout2023: 87.67, maleVoters: 13403, femaleVoters: 12878, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 11, population: 56696, totalVoters: 23454, turnout2023: 86.31, maleVoters: 11938, femaleVoters: 11516, literacy: 70.9, urbanPercent: 47.9, scPercent: 0, stPercent: 35.6, areaSqKm: 226 },
  { acNo: 12, population: 61706, totalVoters: 28310, turnout2023: 89.55, maleVoters: 14438, femaleVoters: 13872, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 13, population: 53869, totalVoters: 21205, turnout2023: 89.67, maleVoters: 10390, femaleVoters: 10815, literacy: 68.9, urbanPercent: 51.4, scPercent: 0, stPercent: 35.6, areaSqKm: 284 },
  { acNo: 14, population: 45711, totalVoters: 27416, turnout2023: 88.11, maleVoters: 13626, femaleVoters: 13790, literacy: 79.9, urbanPercent: 4.4, scPercent: 0, stPercent: 47.7, areaSqKm: 75 },
  { acNo: 15, population: 67227, totalVoters: 37644, turnout2023: 86.23, maleVoters: 18878, femaleVoters: 18766, literacy: 73.9, urbanPercent: 49.6, scPercent: 6, stPercent: 44, areaSqKm: 248 },
  { acNo: 16, population: 59079, totalVoters: 30518, turnout2023: 89.13, maleVoters: 15397, femaleVoters: 15121, literacy: 69.9, urbanPercent: 54.8, scPercent: 0, stPercent: 35.6, areaSqKm: 282 },
  { acNo: 17, population: 53977, totalVoters: 34004, turnout2023: 93.43, maleVoters: 17342, femaleVoters: 16662, literacy: 80.9, urbanPercent: 20, scPercent: 0, stPercent: 26, areaSqKm: 146 },
  { acNo: 18, population: 46298, totalVoters: 30557, turnout2023: 92.94, maleVoters: 15126, femaleVoters: 15431, literacy: 84.9, urbanPercent: 28.7, scPercent: 0, stPercent: 26, areaSqKm: 174 },
  { acNo: 19, population: 61906, totalVoters: 38151, turnout2023: 91.31, maleVoters: 18809, femaleVoters: 19342, literacy: 71.9, urbanPercent: 51.4, scPercent: 2.7, stPercent: 35.6, areaSqKm: 224 },
  { acNo: 20, population: 45127, totalVoters: 28635, turnout2023: 91.73, maleVoters: 14617, femaleVoters: 14018, literacy: 80.9, urbanPercent: 18.3, scPercent: 0, stPercent: 26, areaSqKm: 155 },
  { acNo: 21, population: 61706, totalVoters: 35625, turnout2023: 92.53, maleVoters: 18169, femaleVoters: 17456, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 22, population: 56214, totalVoters: 29784, turnout2023: 94.76, maleVoters: 15055, femaleVoters: 14729, literacy: 81.9, urbanPercent: 6.1, scPercent: 0, stPercent: 47.7, areaSqKm: 78 },
  { acNo: 23, population: 61706, totalVoters: 32599, turnout2023: 94.11, maleVoters: 16625, femaleVoters: 15974, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 24, population: 93030, totalVoters: 33330, turnout2023: 92.51, maleVoters: 16665, femaleVoters: 16665, literacy: 82.9, urbanPercent: 44.4, scPercent: 6, stPercent: 33.7, areaSqKm: 449 },
  { acNo: 25, population: 96548, totalVoters: 29090, turnout2023: 91.58, maleVoters: 14458, femaleVoters: 14632, literacy: 84.9, urbanPercent: 51.4, scPercent: 12.7, stPercent: 33.7, areaSqKm: 429 },
  { acNo: 26, population: 61706, totalVoters: 32740, turnout2023: 90.28, maleVoters: 16697, femaleVoters: 16043, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 27, population: 82263, totalVoters: 39960, turnout2023: 90.33, maleVoters: 19641, femaleVoters: 20319, literacy: 77.9, urbanPercent: 46.1, scPercent: 0, stPercent: 33.7, areaSqKm: 447 },
  { acNo: 28, population: 90665, totalVoters: 23559, turnout2023: 89.71, maleVoters: 11449, femaleVoters: 12110, literacy: 83.9, urbanPercent: 72.3, scPercent: 0, stPercent: 52.7, areaSqKm: 213 },
  { acNo: 29, population: 57805, totalVoters: 28309, turnout2023: 92.15, maleVoters: 14027, femaleVoters: 14282, literacy: 84.9, urbanPercent: 27, scPercent: 0, stPercent: 26, areaSqKm: 142 },
  { acNo: 30, population: 49392, totalVoters: 36774, turnout2023: 92.37, maleVoters: 18791, femaleVoters: 17983, literacy: 80.9, urbanPercent: 28.7, scPercent: 0, stPercent: 26, areaSqKm: 164 },
  { acNo: 31, population: 64607, totalVoters: 33207, turnout2023: 89.08, maleVoters: 16686, femaleVoters: 16521, literacy: 73.9, urbanPercent: 49.6, scPercent: 6, stPercent: 44, areaSqKm: 239 },
  { acNo: 32, population: 63726, totalVoters: 33626, turnout2023: 90.04, maleVoters: 16324, femaleVoters: 17302, literacy: 79.9, urbanPercent: 7.8, scPercent: 0, stPercent: 47.7, areaSqKm: 78 },
  { acNo: 33, population: 55080, totalVoters: 34115, turnout2023: 93.06, maleVoters: 17109, femaleVoters: 17006, literacy: 82.9, urbanPercent: 13.1, scPercent: 0, stPercent: 30.8, areaSqKm: 80 },
  { acNo: 34, population: 64333, totalVoters: 33610, turnout2023: 90.74, maleVoters: 16805, femaleVoters: 16805, literacy: 73.9, urbanPercent: 51.4, scPercent: 6, stPercent: 27.9, areaSqKm: 236 },
  { acNo: 35, population: 57036, totalVoters: 38172, turnout2023: 91.78, maleVoters: 19104, femaleVoters: 19068, literacy: 87.9, urbanPercent: 13.1, scPercent: 2.7, stPercent: 25.1, areaSqKm: 71 },
  { acNo: 36, population: 77655, totalVoters: 32118, turnout2023: 91.39, maleVoters: 16348, femaleVoters: 15770, literacy: 78.9, urbanPercent: 44.4, scPercent: 22.7, stPercent: 44, areaSqKm: 206 },
  { acNo: 37, population: 39820, totalVoters: 30595, turnout2023: 88.69, maleVoters: 14960, femaleVoters: 15635, literacy: 79.9, urbanPercent: 18.3, scPercent: 0, stPercent: 26, areaSqKm: 154 },
  { acNo: 38, population: 61706, totalVoters: 28112, turnout2023: 93.42, maleVoters: 14337, femaleVoters: 13775, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 39, population: 61706, totalVoters: 27796, turnout2023: 90.05, maleVoters: 14176, femaleVoters: 13620, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 40, population: 45015, totalVoters: 29523, turnout2023: 90.26, maleVoters: 14629, femaleVoters: 14894, literacy: 79.9, urbanPercent: 25.2, scPercent: 0, stPercent: 22.2, areaSqKm: 141 },
  { acNo: 41, population: 61934, totalVoters: 49721, turnout2023: 94.29, maleVoters: 24836, femaleVoters: 24885, literacy: 82.9, urbanPercent: 7.8, scPercent: 0, stPercent: 30.8, areaSqKm: 84 },
  { acNo: 42, population: 80343, totalVoters: 44791, turnout2023: 93.55, maleVoters: 22776, femaleVoters: 22015, literacy: 88.9, urbanPercent: 74, scPercent: 9.3, stPercent: 52.7, areaSqKm: 211 },
  { acNo: 43, population: 69203, totalVoters: 34390, turnout2023: 89.67, maleVoters: 17230, femaleVoters: 17160, literacy: 75.9, urbanPercent: 49.6, scPercent: 16, stPercent: 35.6, areaSqKm: 225 },
  { acNo: 44, population: 84058, totalVoters: 51395, turnout2023: 77.97, maleVoters: 26082, femaleVoters: 25313, literacy: 78.9, urbanPercent: 46.1, scPercent: 22.7, stPercent: 44, areaSqKm: 194 },
  { acNo: 45, population: 56405, totalVoters: 48405, turnout2023: 84.49, maleVoters: 24203, femaleVoters: 24202, literacy: 82.9, urbanPercent: 6.1, scPercent: 0, stPercent: 30.8, areaSqKm: 88 },
  { acNo: 46, population: 63992, totalVoters: 28888, turnout2023: 91.51, maleVoters: 14054, femaleVoters: 14834, literacy: 74.9, urbanPercent: 46.1, scPercent: 12.7, stPercent: 35.6, areaSqKm: 227 },
  { acNo: 47, population: 42894, totalVoters: 58490, turnout2023: 84.39, maleVoters: 28660, femaleVoters: 29830, literacy: 79.9, urbanPercent: 27, scPercent: 0, stPercent: 26, areaSqKm: 171 },
  { acNo: 48, population: 100719, totalVoters: 55478, turnout2023: 91.88, maleVoters: 28486, femaleVoters: 26992, literacy: 81.9, urbanPercent: 47.9, scPercent: 2.7, stPercent: 33.7, areaSqKm: 446 },
  { acNo: 49, population: 68464, totalVoters: 51252, turnout2023: 88.15, maleVoters: 25934, femaleVoters: 25318, literacy: 76.9, urbanPercent: 47.9, scPercent: 19.3, stPercent: 35.6, areaSqKm: 286 },
  { acNo: 50, population: 42596, totalVoters: 27768, turnout2023: 90.46, maleVoters: 13593, femaleVoters: 14175, literacy: 79.9, urbanPercent: 28.7, scPercent: 0, stPercent: 26, areaSqKm: 162 },
  { acNo: 51, population: 51782, totalVoters: 44370, turnout2023: 89.05, maleVoters: 21941, femaleVoters: 22429, literacy: 69.9, urbanPercent: 56.6, scPercent: 0, stPercent: 35.6, areaSqKm: 228 },
  { acNo: 52, population: 47638, totalVoters: 42059, turnout2023: 91.88, maleVoters: 20798, femaleVoters: 21261, literacy: 89.9, urbanPercent: 7.8, scPercent: 9.3, stPercent: 25.1, areaSqKm: 75 },
  { acNo: 53, population: 61706, totalVoters: 37101, turnout2023: 82.62, maleVoters: 18922, femaleVoters: 18179, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 54, population: 85342, totalVoters: 30169, turnout2023: 83.53, maleVoters: 14738, femaleVoters: 15431, literacy: 79.9, urbanPercent: 53.1, scPercent: 0, stPercent: 33.7, areaSqKm: 428 },
  { acNo: 55, population: 88621, totalVoters: 18398, turnout2023: 69.18, maleVoters: 9273, femaleVoters: 9125, literacy: 73.9, urbanPercent: 47.9, scPercent: 6, stPercent: 44, areaSqKm: 193 },
  { acNo: 56, population: 77871, totalVoters: 17374, turnout2023: 76.78, maleVoters: 8626, femaleVoters: 8748, literacy: 79.9, urbanPercent: 37.4, scPercent: 0, stPercent: 46.5, areaSqKm: 39 },
  { acNo: 57, population: 59077, totalVoters: 31767, turnout2023: 86.87, maleVoters: 15947, femaleVoters: 15820, literacy: 82.9, urbanPercent: 11.3, scPercent: 0, stPercent: 30.8, areaSqKm: 85 },
  { acNo: 58, population: 57168, totalVoters: 65338, turnout2023: 72.96, maleVoters: 32700, femaleVoters: 32638, literacy: 82.9, urbanPercent: 16.5, scPercent: 0, stPercent: 30.8, areaSqKm: 71 },
  { acNo: 59, population: 61706, totalVoters: 62199, turnout2023: 84.55, maleVoters: 31721, femaleVoters: 30478, literacy: 80.2, urbanPercent: 32.5, scPercent: 3.7, stPercent: 35.1, areaSqKm: 170 },
  { acNo: 60, population: 66377, totalVoters: 27753, turnout2023: 85.15, maleVoters: 14223, femaleVoters: 13530, literacy: 73.9, urbanPercent: 53.1, scPercent: 9.3, stPercent: 35.6, areaSqKm: 283 },
];

export function getMNConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return MN_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
