/**
 * Meghalaya Assembly Constituencies — 2023 General Election (60 seats)
 *
 * SOURCE: TCPD "Lok Dhaba" (Trivedi Centre for Political Data, Ashoka University),
 *         Meghalaya_AE dataset — ECI-sourced constituency results. Uses the
 *         official ECI AC numbering (1-60). Winner/runner-up parties,
 *         vote counts, and margins are the ECI 2023 results as compiled by TCPD.
 *         Reservation (GEN/SC/ST) and district are from the same dataset.
 *         Auto-generated by scripts/build-tcpd-seed.mjs — do not hand-edit.
 *
 * PARTY TALLY 2023: NPP 26 | UDP 12 | INC 5 | AITC 5 | VPP 4 | BJP 2 | PDF 2 | HSPDP 2 | IND 2 = 60
 */

export interface MLConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in local script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2023: string;
  winnerName2023: string;
  winnerVotes2023: number;
  runnerUp2023: string;
  margin2023: number;
  currentParty: string;
}

export const ML_CONSTITUENCIES: MLConstituencySeed[] = [
  { acNo: 1, name: 'Nartiang', localName: 'Nartiang', district: 'West Jaintia Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Sniawbhalang Dhar', winnerVotes2023: 16969, runnerUp2023: 'INC', margin2023: 2123, currentParty: 'NPP' },
  { acNo: 2, name: 'Jowai', localName: 'Jowai', district: 'West Jaintia Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Wailadmiki Shylla', winnerVotes2023: 14079, runnerUp2023: 'AITC', margin2023: 2667, currentParty: 'NPP' },
  { acNo: 3, name: 'Raliang', localName: 'Raliang', district: 'West Jaintia Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Coming One Ymbon', winnerVotes2023: 13626, runnerUp2023: 'BJP', margin2023: 5337, currentParty: 'NPP' },
  { acNo: 4, name: 'Mowkaiaw', localName: 'Mowkaiaw', district: 'West Jaintia Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Nujorki Sungoh', winnerVotes2023: 14508, runnerUp2023: 'NPP', margin2023: 3901, currentParty: 'UDP' },
  { acNo: 5, name: 'Sutnga Saipung', district: 'East Jaintia Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Santa Mary Shylla', winnerVotes2023: 16974, runnerUp2023: 'INC', margin2023: 1828, currentParty: 'NPP' },
  { acNo: 6, name: 'Khliehriat', localName: 'Khliehriat', district: 'East Jaintia Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Kyrmen Shylla', winnerVotes2023: 23514, runnerUp2023: 'NPP', margin2023: 5606, currentParty: 'UDP' },
  { acNo: 7, name: 'Amlarem', localName: 'Amlarem', district: 'West Jaintia Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Lahkmen Rymbui', winnerVotes2023: 17803, runnerUp2023: 'NPP', margin2023: 57, currentParty: 'UDP' },
  { acNo: 8, name: 'Mawhati', localName: 'Mawhati', district: 'Ri Bhoi', type: 'ST', winner2023: 'INC', winnerName2023: 'Charles Marngar', winnerVotes2023: 13273, runnerUp2023: 'NPP', margin2023: 5244, currentParty: 'INC' },
  { acNo: 9, name: 'Nongpoh', localName: 'Nongpoh', district: 'Ri Bhoi', type: 'ST', winner2023: 'UDP', winnerName2023: 'Mayralborn Syiem', winnerVotes2023: 14940, runnerUp2023: 'INC', margin2023: 6686, currentParty: 'UDP' },
  { acNo: 10, name: 'Jirang', localName: 'Jirang', district: 'Ri Bhoi', type: 'ST', winner2023: 'NPP', winnerName2023: 'Sosthenes Sohtun', winnerVotes2023: 12690, runnerUp2023: 'INC', margin2023: 1623, currentParty: 'NPP' },
  { acNo: 11, name: 'Umsning', localName: 'Umsning', district: 'Ri Bhoi', type: 'ST', winner2023: 'INC', winnerName2023: 'Dr. Celestine Lyngdoh', winnerVotes2023: 9907, runnerUp2023: 'UDP', margin2023: 1164, currentParty: 'INC' },
  { acNo: 12, name: 'Umroi', localName: 'Umroi', district: 'Ri Bhoi', type: 'ST', winner2023: 'NPP', winnerName2023: 'Damanbait Lamare', winnerVotes2023: 14213, runnerUp2023: 'AITC', margin2023: 1686, currentParty: 'NPP' },
  { acNo: 13, name: 'Mawryngkneng', localName: 'Mawryngkneng', district: 'East Khasi Hills', type: 'ST', winner2023: 'VPP', winnerName2023: 'Heaving Stone Kharpran', winnerVotes2023: 11424, runnerUp2023: 'UDP', margin2023: 1242, currentParty: 'VPP' },
  { acNo: 14, name: 'Pynthorumkhrah', district: 'East Khasi Hills', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Alexander Laloo Hek', winnerVotes2023: 9321, runnerUp2023: 'INC', margin2023: 2538, currentParty: 'BJP' },
  { acNo: 15, name: 'Mawlai', localName: 'Mawlai', district: 'East Khasi Hills', type: 'ST', winner2023: 'VPP', winnerName2023: 'Brightstarwell Marbaniang', winnerVotes2023: 24262, runnerUp2023: 'NPP', margin2023: 15648, currentParty: 'VPP' },
  { acNo: 16, name: 'East Shillong', localName: 'East Shillong', district: 'East Khasi Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Dr. Mazel Ampareen Lyngdoh', winnerVotes2023: 6637, runnerUp2023: 'INC', margin2023: 1711, currentParty: 'NPP' },
  { acNo: 17, name: 'North Shillong', localName: 'North Shillong', district: 'East Khasi Hills', type: 'ST', winner2023: 'VPP', winnerName2023: 'Adelbert Nongrum', winnerVotes2023: 5583, runnerUp2023: 'BJP', margin2023: 1033, currentParty: 'VPP' },
  { acNo: 18, name: 'West Shillong', localName: 'West Shillong', district: 'East Khasi Hills', type: 'GEN', winner2023: 'UDP', winnerName2023: 'Paul Lyngdoh', winnerVotes2023: 7917, runnerUp2023: 'NPP', margin2023: 3485, currentParty: 'UDP' },
  { acNo: 19, name: 'South Shillong', localName: 'South Shillong', district: 'East Khasi Hills', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Sanbor Shullai', winnerVotes2023: 14213, runnerUp2023: 'VPP', margin2023: 11609, currentParty: 'BJP' },
  { acNo: 20, name: 'Mylliem', district: 'East Khasi Hills', type: 'ST', winner2023: 'INC', winnerName2023: 'Ronnie V. Lyngdoh', winnerVotes2023: 8904, runnerUp2023: 'VPP', margin2023: 38, currentParty: 'INC' },
  { acNo: 21, name: 'Nongthymmai', localName: 'Nongthymmai', district: 'East Khasi Hills', type: 'ST', winner2023: 'AITC', winnerName2023: 'Charles Pyngrope', winnerVotes2023: 7452, runnerUp2023: 'UDP', margin2023: 1199, currentParty: 'AITC' },
  { acNo: 22, name: 'Nongkrem', localName: 'Nongkrem', district: 'East Khasi Hills', type: 'ST', winner2023: 'VPP', winnerName2023: 'Ardent Miller Basaiawmoit', winnerVotes2023: 13286, runnerUp2023: 'UDP', margin2023: 4187, currentParty: 'VPP' },
  { acNo: 23, name: 'Sohiong', district: 'East Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Synshar Kupar Roy Lyngdoh Thabah', winnerVotes2023: 16679, runnerUp2023: 'NPP', margin2023: 3422, currentParty: 'UDP' },
  { acNo: 24, name: 'Mawphlang', localName: 'Mawphlang', district: 'East Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Matthew Beyondstar Kurbah', winnerVotes2023: 6690, runnerUp2023: 'PDF', margin2023: 104, currentParty: 'UDP' },
  { acNo: 25, name: 'Mawsynram', localName: 'Mawsynram', district: 'East Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Ollan Singh Suin', winnerVotes2023: 10987, runnerUp2023: 'BJP', margin2023: 955, currentParty: 'UDP' },
  { acNo: 26, name: 'Shella', localName: 'Shella', district: 'East Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Balajied Kupar Synrem', winnerVotes2023: 13274, runnerUp2023: 'NPP', margin2023: 434, currentParty: 'UDP' },
  { acNo: 27, name: 'Pynursla', localName: 'Pynursla', district: 'East Khasi Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Prestone Tynsong', winnerVotes2023: 13745, runnerUp2023: 'INC', margin2023: 8140, currentParty: 'NPP' },
  { acNo: 28, name: 'Sohra', localName: 'Sohra', district: 'East Khasi Hills', type: 'ST', winner2023: 'PDF', winnerName2023: 'Gavin Miguel Mylliem', winnerVotes2023: 11358, runnerUp2023: 'UDP', margin2023: 15, currentParty: 'PDF' },
  { acNo: 29, name: 'Mawkynrew', localName: 'Mawkynrew', district: 'East Khasi Hills', type: 'ST', winner2023: 'PDF', winnerName2023: 'Banteidor Lyngdoh', winnerVotes2023: 11789, runnerUp2023: 'HSPDP', margin2023: 4137, currentParty: 'PDF' },
  { acNo: 30, name: 'Mairang', localName: 'Mairang', district: 'West Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Metbah Lyngdoh', winnerVotes2023: 19066, runnerUp2023: 'INC', margin2023: 155, currentParty: 'UDP' },
  { acNo: 31, name: 'Mawthadraishan', localName: 'Mawthadraishan', district: 'West Khasi Hills', type: 'ST', winner2023: 'HSPDP', winnerName2023: 'Shakliar Warjri', winnerVotes2023: 17366, runnerUp2023: 'UDP', margin2023: 2353, currentParty: 'HSPDP' },
  { acNo: 32, name: 'Nongstoin', localName: 'Nongstoin', district: 'West Khasi Hills', type: 'ST', winner2023: 'INC', winnerName2023: 'Gabriel Wahlang', winnerVotes2023: 13847, runnerUp2023: 'NPP', margin2023: 2624, currentParty: 'INC' },
  { acNo: 33, name: 'Rambrai Jyrngam', localName: 'Rambrai Jyrngam', district: 'West Khasi Hills', type: 'ST', winner2023: 'IND', winnerName2023: 'Remington Gabil Momin', winnerVotes2023: 9057, runnerUp2023: 'HSPDP', margin2023: 110, currentParty: 'IND' },
  { acNo: 34, name: 'Mawshynrut', localName: 'Mawshynrut', district: 'West Khasi Hills', type: 'ST', winner2023: 'HSPDP', winnerName2023: 'Methodius Dkhar', winnerVotes2023: 19368, runnerUp2023: 'NPP', margin2023: 5187, currentParty: 'HSPDP' },
  { acNo: 35, name: 'Ranikor', localName: 'Ranikor', district: 'South West Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Pius Marwein', winnerVotes2023: 16502, runnerUp2023: 'BJP', margin2023: 5649, currentParty: 'UDP' },
  { acNo: 36, name: 'Mawkyrwat', district: 'South West Khasi Hills', type: 'ST', winner2023: 'UDP', winnerName2023: 'Renikton Lyngdoh Tongkhar', winnerVotes2023: 10678, runnerUp2023: 'INC', margin2023: 1272, currentParty: 'UDP' },
  { acNo: 37, name: 'Kharkutta', localName: 'Kharkutta', district: 'East Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Rupert Momin', winnerVotes2023: 17426, runnerUp2023: 'AITC', margin2023: 1530, currentParty: 'NPP' },
  { acNo: 38, name: 'Mendipathar', localName: 'Mendipathar', district: 'North Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Marthon J Sangma', winnerVotes2023: 9363, runnerUp2023: 'INC', margin2023: 3825, currentParty: 'NPP' },
  { acNo: 39, name: 'Resubelpara', localName: 'Resubelpara', district: 'North Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Timothy D. Shira', winnerVotes2023: 10948, runnerUp2023: 'AITC', margin2023: 3465, currentParty: 'NPP' },
  { acNo: 40, name: 'Bajengdoba', localName: 'Bajengdoba', district: 'North Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Pongseng Marak', winnerVotes2023: 9900, runnerUp2023: 'INC', margin2023: 2316, currentParty: 'NPP' },
  { acNo: 41, name: 'Songsak', localName: 'Songsak', district: 'East Garo Hills', type: 'ST', winner2023: 'AITC', winnerName2023: 'Dr. Mukul Sangma', winnerVotes2023: 12689, runnerUp2023: 'NPP', margin2023: 372, currentParty: 'AITC' },
  { acNo: 42, name: 'Rongjeng', localName: 'Rongjeng', district: 'East Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Jim M Sangma', winnerVotes2023: 8836, runnerUp2023: 'IND', margin2023: 128, currentParty: 'NPP' },
  { acNo: 43, name: 'William Nagar', localName: 'William Nagar', district: 'East Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Marcuise N Marak', winnerVotes2023: 10976, runnerUp2023: 'INC', margin2023: 3843, currentParty: 'NPP' },
  { acNo: 44, name: 'Raksamgre', localName: 'Raksamgre', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Limison D. Sangma', winnerVotes2023: 12184, runnerUp2023: 'BJP', margin2023: 2818, currentParty: 'NPP' },
  { acNo: 45, name: 'Tikrikila', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Jimmy D. Sangma', winnerVotes2023: 13218, runnerUp2023: 'AITC', margin2023: 5313, currentParty: 'NPP' },
  { acNo: 46, name: 'Phulbari', localName: 'Phulbari', district: 'West Garo Hills', type: 'GEN', winner2023: 'NPP', winnerName2023: 'Abu Taher Mondal', winnerVotes2023: 14969, runnerUp2023: 'AITC', margin2023: 3240, currentParty: 'NPP' },
  { acNo: 47, name: 'Rajabala', localName: 'Rajabala', district: 'West Garo Hills', type: 'GEN', winner2023: 'AITC', winnerName2023: 'Dr. Mizanur Rahman Kazi', winnerVotes2023: 12628, runnerUp2023: 'NPP', margin2023: 10, currentParty: 'AITC' },
  { acNo: 48, name: 'Selsella', localName: 'Selsella', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Arbinstone B Marak', winnerVotes2023: 16595, runnerUp2023: 'AITC', margin2023: 8741, currentParty: 'NPP' },
  { acNo: 49, name: 'Dadenggre', localName: 'Dadenggre', district: 'West Garo Hills', type: 'ST', winner2023: 'AITC', winnerName2023: 'Rupa M. Marak', winnerVotes2023: 15702, runnerUp2023: 'NPP', margin2023: 18, currentParty: 'AITC' },
  { acNo: 50, name: 'North Tura', localName: 'North Tura', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Thomas A. Sangma', winnerVotes2023: 11385, runnerUp2023: 'BJP', margin2023: 3885, currentParty: 'NPP' },
  { acNo: 51, name: 'South Tura', localName: 'South Tura', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Conrad Kongkal Sangma', winnerVotes2023: 13342, runnerUp2023: 'BJP', margin2023: 5016, currentParty: 'NPP' },
  { acNo: 52, name: 'Rangsakona', localName: 'Rangsakona', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Subir Marak', winnerVotes2023: 13605, runnerUp2023: 'AITC', margin2023: 788, currentParty: 'NPP' },
  { acNo: 53, name: 'Ampati', localName: 'Ampati', district: 'South West Garo Hills', type: 'ST', winner2023: 'AITC', winnerName2023: 'Miani D. Shira', winnerVotes2023: 13446, runnerUp2023: 'NPP', margin2023: 2277, currentParty: 'AITC' },
  { acNo: 54, name: 'Mahendraganj', localName: 'Mahendraganj', district: 'South West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Sanjay A. Sangma', winnerVotes2023: 13560, runnerUp2023: 'AITC', margin2023: 1718, currentParty: 'NPP' },
  { acNo: 55, name: 'Salmanpara', localName: 'Salmanpara', district: 'South West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Ian Botham K. Sangma', winnerVotes2023: 11352, runnerUp2023: 'AITC', margin2023: 5238, currentParty: 'NPP' },
  { acNo: 56, name: 'Gambegre', localName: 'Gambegre', district: 'West Garo Hills', type: 'ST', winner2023: 'INC', winnerName2023: 'Saleng A. Sangma', winnerVotes2023: 11252, runnerUp2023: 'AITC', margin2023: 2871, currentParty: 'INC' },
  { acNo: 57, name: 'Dalu', localName: 'Dalu', district: 'West Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Brening A. Sangma', winnerVotes2023: 5834, runnerUp2023: 'BJP', margin2023: 527, currentParty: 'NPP' },
  { acNo: 58, name: 'Rongara Siju', district: 'South Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Rakkam A. Sangma', winnerVotes2023: 11569, runnerUp2023: 'INC', margin2023: 3258, currentParty: 'NPP' },
  { acNo: 59, name: 'Chokpot', localName: 'Chokpot', district: 'South Garo Hills', type: 'ST', winner2023: 'NPP', winnerName2023: 'Sengchim N. Sangma', winnerVotes2023: 9503, runnerUp2023: 'GNC', margin2023: 353, currentParty: 'NPP' },
  { acNo: 60, name: 'Baghmara', localName: 'Baghmara', district: 'South Garo Hills', type: 'ST', winner2023: 'IND', winnerName2023: 'Kartush R. Marak', winnerVotes2023: 9013, runnerUp2023: 'BJP', margin2023: 2225, currentParty: 'IND' },
];

export function getMLConstituency(acNo: number): MLConstituencySeed | undefined {
  return ML_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
