/**
 * ML — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface MLElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const ML_ELECTION_HISTORY: MLElectionResult[] = [
  {
    year: 2023,
    partyResults: {
      'NPP': 26,
      'UDP': 12,
      'INC': 5,
      'AITC': 5,
      'VPP': 4,
      'BJP': 2,
      'PDF': 2,
      'HSPDP': 2,
      'IND': 2,
    },
    totalSeats: 60,
    rulingParty: 'NPP',
  },
];

export function getMLElectionByYear(year: number) {
  return ML_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getMLPartyTrend(party: string) {
  return ML_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
