/**
 * ML Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2023 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const ML_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 61429, totalVoters: 45118, turnout2023: 90.49, maleVoters: 22176, femaleVoters: 22942, literacy: 73.5, urbanPercent: 19, scPercent: 0, stPercent: 86.9, areaSqKm: 352 },
  { acNo: 2, population: 60211, totalVoters: 42718, turnout2023: 85.95, maleVoters: 21680, femaleVoters: 21038, literacy: 80.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 89 },
  { acNo: 3, population: 82323, totalVoters: 40033, turnout2023: 88.58, maleVoters: 20217, femaleVoters: 19816, literacy: 79.5, urbanPercent: 17.7, scPercent: 3.6, stPercent: 86.9, areaSqKm: 239 },
  { acNo: 4, population: 54631, totalVoters: 39628, turnout2023: 92.73, maleVoters: 19259, femaleVoters: 20369, literacy: 75.5, urbanPercent: 20.4, scPercent: 0, stPercent: 86.9, areaSqKm: 332 },
  { acNo: 5, population: 62221, totalVoters: 47812, turnout2023: 90.8, maleVoters: 24384, femaleVoters: 23428, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 6, population: 55481, totalVoters: 47158, turnout2023: 90.75, maleVoters: 23344, femaleVoters: 23814, literacy: 84.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 85 },
  { acNo: 7, population: 68714, totalVoters: 36597, turnout2023: 98.98, maleVoters: 18774, femaleVoters: 17823, literacy: 76.5, urbanPercent: 27.1, scPercent: 3.6, stPercent: 86.9, areaSqKm: 455 },
  { acNo: 8, population: 78150, totalVoters: 39634, turnout2023: 89.6, maleVoters: 19956, femaleVoters: 19678, literacy: 71.5, urbanPercent: 16.3, scPercent: 0, stPercent: 86.9, areaSqKm: 351 },
  { acNo: 9, population: 59461, totalVoters: 38473, turnout2023: 85.45, maleVoters: 19410, femaleVoters: 19063, literacy: 74.5, urbanPercent: 16.3, scPercent: 0, stPercent: 86.9, areaSqKm: 373 },
  { acNo: 10, population: 58292, totalVoters: 39739, turnout2023: 87.7, maleVoters: 19989, femaleVoters: 19750, literacy: 83.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 87 },
  { acNo: 11, population: 54066, totalVoters: 39621, turnout2023: 85.32, maleVoters: 20287, femaleVoters: 19334, literacy: 73.5, urbanPercent: 37.9, scPercent: 0, stPercent: 86.9, areaSqKm: 327 },
  { acNo: 12, population: 66315, totalVoters: 32896, turnout2023: 86.76, maleVoters: 16250, femaleVoters: 16646, literacy: 71.5, urbanPercent: 39.3, scPercent: 0, stPercent: 86.9, areaSqKm: 326 },
  { acNo: 13, population: 52753, totalVoters: 40528, turnout2023: 85.19, maleVoters: 20142, femaleVoters: 20386, literacy: 77.5, urbanPercent: 20.4, scPercent: 0.6, stPercent: 76.4, areaSqKm: 317 },
  { acNo: 14, population: 62221, totalVoters: 35614, turnout2023: 73.31, maleVoters: 18163, femaleVoters: 17451, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 15, population: 52669, totalVoters: 51579, turnout2023: 79, maleVoters: 26537, femaleVoters: 25042, literacy: 76.5, urbanPercent: 13.6, scPercent: 0, stPercent: 86.9, areaSqKm: 391 },
  { acNo: 16, population: 60052, totalVoters: 26335, turnout2023: 64.69, maleVoters: 13036, femaleVoters: 13299, literacy: 79.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 86 },
  { acNo: 17, population: 65456, totalVoters: 29170, turnout2023: 64.99, maleVoters: 15008, femaleVoters: 14162, literacy: 78.5, urbanPercent: 5.5, scPercent: 0, stPercent: 86.9, areaSqKm: 5 },
  { acNo: 18, population: 61213, totalVoters: 27371, turnout2023: 68.64, maleVoters: 13727, femaleVoters: 13644, literacy: 71.5, urbanPercent: 36.6, scPercent: 0, stPercent: 86.9, areaSqKm: 312 },
  { acNo: 19, population: 54492, totalVoters: 34817, turnout2023: 62.1, maleVoters: 17495, femaleVoters: 17322, literacy: 76.5, urbanPercent: 36.6, scPercent: 1.6, stPercent: 78.1, areaSqKm: 316 },
  { acNo: 20, population: 62221, totalVoters: 38226, turnout2023: 81.2, maleVoters: 19495, femaleVoters: 18731, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 21, population: 56603, totalVoters: 37505, turnout2023: 66.72, maleVoters: 18190, femaleVoters: 19315, literacy: 70.5, urbanPercent: 13.6, scPercent: 0, stPercent: 86.9, areaSqKm: 318 },
  { acNo: 22, population: 53155, totalVoters: 38931, turnout2023: 83.7, maleVoters: 19350, femaleVoters: 19581, literacy: 71.5, urbanPercent: 17.7, scPercent: 0, stPercent: 86.9, areaSqKm: 372 },
  { acNo: 23, population: 45717, totalVoters: 30173, turnout2023: 89.92, maleVoters: 15116, femaleVoters: 15057, literacy: 74.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 15 },
  { acNo: 24, population: 59467, totalVoters: 35951, turnout2023: 86.95, maleVoters: 17670, femaleVoters: 18281, literacy: 70.5, urbanPercent: 21.7, scPercent: 0, stPercent: 76.4, areaSqKm: 393 },
  { acNo: 25, population: 56826, totalVoters: 37635, turnout2023: 87.85, maleVoters: 18743, femaleVoters: 18892, literacy: 76.5, urbanPercent: 15, scPercent: 0, stPercent: 86.9, areaSqKm: 385 },
  { acNo: 26, population: 52004, totalVoters: 35082, turnout2023: 87.27, maleVoters: 17663, femaleVoters: 17419, literacy: 73.5, urbanPercent: 40.6, scPercent: 0, stPercent: 86.9, areaSqKm: 281 },
  { acNo: 27, population: 60423, totalVoters: 39244, turnout2023: 88.59, maleVoters: 19721, femaleVoters: 19523, literacy: 77.5, urbanPercent: 1.5, scPercent: 0, stPercent: 86.9, areaSqKm: 5 },
  { acNo: 28, population: 59442, totalVoters: 30340, turnout2023: 88.49, maleVoters: 14957, femaleVoters: 15383, literacy: 71.5, urbanPercent: 39.3, scPercent: 0, stPercent: 86.9, areaSqKm: 266 },
  { acNo: 29, population: 64320, totalVoters: 37358, turnout2023: 89.55, maleVoters: 19014, femaleVoters: 18344, literacy: 78.5, urbanPercent: 15, scPercent: 1.6, stPercent: 86.9, areaSqKm: 371 },
  { acNo: 30, population: 53961, totalVoters: 43201, turnout2023: 90.93, maleVoters: 21427, femaleVoters: 21774, literacy: 77.5, urbanPercent: 17.7, scPercent: 0.6, stPercent: 76.4, areaSqKm: 349 },
  { acNo: 31, population: 59485, totalVoters: 44618, turnout2023: 91.3, maleVoters: 22465, femaleVoters: 22153, literacy: 74.5, urbanPercent: 13.6, scPercent: 0, stPercent: 86.9, areaSqKm: 406 },
  { acNo: 32, population: 63372, totalVoters: 44727, turnout2023: 88.02, maleVoters: 22812, femaleVoters: 21915, literacy: 72.5, urbanPercent: 15, scPercent: 0, stPercent: 86.9, areaSqKm: 394 },
  { acNo: 33, population: 66100, totalVoters: 39879, turnout2023: 85.39, maleVoters: 20099, femaleVoters: 19780, literacy: 70.5, urbanPercent: 5.5, scPercent: 0, stPercent: 86.9, areaSqKm: 76 },
  { acNo: 34, population: 64061, totalVoters: 41652, turnout2023: 88.57, maleVoters: 20514, femaleVoters: 21138, literacy: 78.5, urbanPercent: 16.3, scPercent: 1.6, stPercent: 86.9, areaSqKm: 365 },
  { acNo: 35, population: 78706, totalVoters: 36286, turnout2023: 89.63, maleVoters: 18215, femaleVoters: 18071, literacy: 82.5, urbanPercent: 31.2, scPercent: 7.6, stPercent: 86.9, areaSqKm: 289 },
  { acNo: 36, population: 62221, totalVoters: 38806, turnout2023: 88.39, maleVoters: 19791, femaleVoters: 19015, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 37, population: 60032, totalVoters: 43626, turnout2023: 84.93, maleVoters: 21246, femaleVoters: 22380, literacy: 80.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 85 },
  { acNo: 38, population: 53042, totalVoters: 29887, turnout2023: 83.42, maleVoters: 15212, femaleVoters: 14675, literacy: 72.5, urbanPercent: 21.7, scPercent: 0, stPercent: 86.9, areaSqKm: 330 },
  { acNo: 39, population: 75544, totalVoters: 31126, turnout2023: 85.17, maleVoters: 15423, femaleVoters: 15703, literacy: 78.5, urbanPercent: 27.1, scPercent: 3.6, stPercent: 86.9, areaSqKm: 265 },
  { acNo: 40, population: 71057, totalVoters: 33481, turnout2023: 86.39, maleVoters: 17109, femaleVoters: 16372, literacy: 80.5, urbanPercent: 23.1, scPercent: 7.6, stPercent: 86.9, areaSqKm: 392 },
  { acNo: 41, population: 66587, totalVoters: 31997, turnout2023: 89.09, maleVoters: 16414, femaleVoters: 15583, literacy: 69.5, urbanPercent: 37.9, scPercent: 0, stPercent: 78.1, areaSqKm: 331 },
  { acNo: 42, population: 48480, totalVoters: 35575, turnout2023: 84.72, maleVoters: 17253, femaleVoters: 18322, literacy: 72.5, urbanPercent: 6.9, scPercent: 0, stPercent: 86.9, areaSqKm: 75 },
  { acNo: 43, population: 50650, totalVoters: 38506, turnout2023: 77.26, maleVoters: 19388, femaleVoters: 19118, literacy: 80.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 16 },
  { acNo: 44, population: 72476, totalVoters: 31226, turnout2023: 88.56, maleVoters: 15332, femaleVoters: 15894, literacy: 82.5, urbanPercent: 19, scPercent: 6.6, stPercent: 86.9, areaSqKm: 216 },
  { acNo: 45, population: 62221, totalVoters: 36168, turnout2023: 88.24, maleVoters: 18446, femaleVoters: 17722, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 46, population: 67768, totalVoters: 32702, turnout2023: 90.39, maleVoters: 16253, femaleVoters: 16449, literacy: 79.5, urbanPercent: 2.8, scPercent: 0, stPercent: 86.9, areaSqKm: 5 },
  { acNo: 47, population: 63109, totalVoters: 35965, turnout2023: 92.66, maleVoters: 18341, femaleVoters: 17624, literacy: 80.5, urbanPercent: 1.4, scPercent: 0, stPercent: 86.9, areaSqKm: 5 },
  { acNo: 48, population: 58342, totalVoters: 36294, turnout2023: 91.71, maleVoters: 17875, femaleVoters: 18419, literacy: 72.5, urbanPercent: 4.2, scPercent: 0, stPercent: 86.9, areaSqKm: 72 },
  { acNo: 49, population: 71452, totalVoters: 36484, turnout2023: 90.23, maleVoters: 18407, femaleVoters: 18077, literacy: 69.5, urbanPercent: 36.6, scPercent: 0, stPercent: 86.9, areaSqKm: 300 },
  { acNo: 50, population: 67603, totalVoters: 35391, turnout2023: 75.98, maleVoters: 17395, femaleVoters: 17996, literacy: 72.5, urbanPercent: 4.2, scPercent: 0, stPercent: 86.9, areaSqKm: 5 },
  { acNo: 51, population: 61485, totalVoters: 34811, turnout2023: 73.65, maleVoters: 17127, femaleVoters: 17684, literacy: 74.5, urbanPercent: 35.2, scPercent: 0, stPercent: 86.9, areaSqKm: 301 },
  { acNo: 52, population: 68945, totalVoters: 37948, turnout2023: 85.95, maleVoters: 18765, femaleVoters: 19183, literacy: 79.5, urbanPercent: 32.5, scPercent: 4.6, stPercent: 86.9, areaSqKm: 288 },
  { acNo: 53, population: 76906, totalVoters: 33429, turnout2023: 90, maleVoters: 17149, femaleVoters: 16280, literacy: 73.5, urbanPercent: 25.8, scPercent: 0.6, stPercent: 86.9, areaSqKm: 390 },
  { acNo: 54, population: 62376, totalVoters: 36937, turnout2023: 88.99, maleVoters: 18118, femaleVoters: 18819, literacy: 70.5, urbanPercent: 19, scPercent: 0, stPercent: 86.9, areaSqKm: 329 },
  { acNo: 55, population: 53902, totalVoters: 30173, turnout2023: 89.92, maleVoters: 15176, femaleVoters: 14997, literacy: 65.5, urbanPercent: 5.5, scPercent: 0, stPercent: 86.9, areaSqKm: 75 },
  { acNo: 56, population: 55965, totalVoters: 31607, turnout2023: 89.96, maleVoters: 15361, femaleVoters: 16246, literacy: 79.5, urbanPercent: 1.5, scPercent: 0, stPercent: 86.9, areaSqKm: 14 },
  { acNo: 57, population: 73399, totalVoters: 22296, turnout2023: 84.95, maleVoters: 11393, femaleVoters: 10903, literacy: 80.5, urbanPercent: 19, scPercent: 7.6, stPercent: 86.9, areaSqKm: 419 },
  { acNo: 58, population: 62221, totalVoters: 34855, turnout2023: 84.44, maleVoters: 17776, femaleVoters: 17079, literacy: 76, urbanPercent: 20.1, scPercent: 1, stPercent: 86.1, areaSqKm: 254 },
  { acNo: 59, population: 86819, totalVoters: 32413, turnout2023: 87.96, maleVoters: 16352, femaleVoters: 16061, literacy: 72.5, urbanPercent: 37.9, scPercent: 2.6, stPercent: 86.9, areaSqKm: 269 },
  { acNo: 60, population: 62865, totalVoters: 33805, turnout2023: 86.3, maleVoters: 17274, femaleVoters: 16531, literacy: 74.5, urbanPercent: 24.4, scPercent: 1.6, stPercent: 86.9, areaSqKm: 458 },
];

export function getMLConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return ML_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
