/**
 * Mizoram Assembly Constituencies — CURRENT assembly (2023) with 2018 history (40 seats)
 *
 * SOURCES:
 *   2018 result + numbering/district/reservation: TCPD "Lok Dhaba" (ECI). Official AC numbering.
 *   2023 winners (current): project data verified against ECI 2023 results.
 *   Auto-generated by scripts/build-current-seed.mjs — do not hand-edit.
 */

export interface MZConstituencySeed {
  acNo: number;
  name: string;
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2018: string;
  winnerName2018: string;
  winnerVotes2018: number;
  runnerUp2018: string;
  margin2018: number;
  winner2023: string;
  winnerName2023: string;
  currentParty: string;
}

export const MZ_CONSTITUENCIES: MZConstituencySeed[] = [
  { acNo: 1, name: 'Hachhek', localName: 'Hachhek', district: 'Mamit', type: 'ST', winner2018: 'INC', winnerName2018: 'Lalrindika Ralte', winnerVotes2018: 6202, runnerUp2018: 'MNF', margin2018: 366, winner2023: 'MNF', winnerName2023: 'Robert Romawia Royte', currentParty: 'MNF' },
  { acNo: 2, name: 'Dampa', localName: 'Dampa', district: 'Mamit', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalrintluanga Sailo', winnerVotes2018: 5840, runnerUp2018: 'INC', margin2018: 1657, winner2023: 'MNF', winnerName2023: 'Lalrintluanga Sailo', currentParty: 'MNF' },
  { acNo: 3, name: 'Mamit', localName: 'Mamit', district: 'Mamit', type: 'ST', winner2018: 'MNF', winnerName2018: 'H. Lalzirliana', winnerVotes2018: 6874, runnerUp2018: 'INC', margin2018: 407, winner2023: 'MNF', winnerName2023: 'H. Lalzirliana', currentParty: 'MNF' },
  { acNo: 4, name: 'Tuirial', localName: 'Tuirial', district: 'Kolasib', type: 'ST', winner2018: 'IND', winnerName2018: 'Andrew H. Thangliana', winnerVotes2018: 4387, runnerUp2018: 'MNF', margin2018: 204, winner2023: 'MNF', winnerName2023: 'K. Laldawngliana', currentParty: 'MNF' },
  { acNo: 5, name: 'Kolasib', localName: 'Kolasib', district: 'Kolasib', type: 'ST', winner2018: 'MNF', winnerName2018: 'K. Lalrinliana', winnerVotes2018: 5940, runnerUp2018: 'IND', margin2018: 279, winner2023: 'ZPM', winnerName2023: 'Lalfamkima', currentParty: 'ZPM' },
  { acNo: 6, name: 'Serlui', localName: 'Serlui', district: 'Kolasib', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalrinsanga Ralte', winnerVotes2018: 6128, runnerUp2018: 'INC', margin2018: 927, winner2023: 'MNF', winnerName2023: 'Lalrinsanga Ralte', currentParty: 'MNF' },
  { acNo: 7, name: 'Tuivawl', localName: 'Tuivawl', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalchhandama Ralte', winnerVotes2018: 5207, runnerUp2018: 'INC', margin2018: 3, winner2023: 'MNF', winnerName2023: 'Lalchhandama Ralte', currentParty: 'MNF' },
  { acNo: 8, name: 'Chalfilh', localName: 'Chalfilh', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalrinliana Sailo', winnerVotes2018: 5541, runnerUp2018: 'IND', margin2018: 1007, winner2023: 'ZPM', winnerName2023: 'Lalbiakzama', currentParty: 'ZPM' },
  { acNo: 9, name: 'Tawi', localName: 'Tawi', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'R.Lalzirliana', winnerVotes2018: 4940, runnerUp2018: 'IND', margin2018: 184, winner2023: 'ZPM', winnerName2023: 'Prof. Lalnilawma', currentParty: 'ZPM' },
  { acNo: 10, name: 'Aizawl North - I', localName: 'Aizawl North-I', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'Vanlalhlana', winnerVotes2018: 7094, runnerUp2018: 'MNF', margin2018: 1165, winner2023: 'ZPM', winnerName2023: 'Vanlalhlana', currentParty: 'ZPM' },
  { acNo: 11, name: 'Aizawl North - Ii', localName: 'Aizawl North-Ii', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'Vanlalthlana', winnerVotes2018: 7775, runnerUp2018: 'MNF', margin2018: 1801, winner2023: 'ZPM', winnerName2023: 'Dr. Vanlalthlana', currentParty: 'ZPM' },
  { acNo: 12, name: 'Aizawl North-Iii', localName: 'Aizawl North-Iii', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'C Lalmuanpuia', winnerVotes2018: 5166, runnerUp2018: 'INC', margin2018: 434, winner2023: 'ZPM', winnerName2023: 'K. Sapdanga', currentParty: 'ZPM' },
  { acNo: 13, name: 'Aizawl East - I', localName: 'Aizawl East-I', district: 'Tuivawl', type: 'GEN', winner2018: 'MNF', winnerName2018: 'Zoramthanga', winnerVotes2018: 8358, runnerUp2018: 'IND', margin2018: 2504, winner2023: 'ZPM', winnerName2023: 'Lalthansanga', currentParty: 'ZPM' },
  { acNo: 14, name: 'Aizawl East Ii', localName: 'Aizawl East-Ii', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'Robert Romawia Royte', winnerVotes2018: 5869, runnerUp2018: 'IND', margin2018: 1492, winner2023: 'ZPM', winnerName2023: 'B. Lalchhanzova', currentParty: 'ZPM' },
  { acNo: 15, name: 'Aizawl West I', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'Lalduhoma', winnerVotes2018: 7889, runnerUp2018: 'MNF', margin2018: 1060, winner2023: 'ZPM', winnerName2023: 'TBC Lalvenchhunga', currentParty: 'ZPM' },
  { acNo: 16, name: 'Aizawl West Ii', localName: 'Aizawl West-Ii', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalruatkima', winnerVotes2018: 7626, runnerUp2018: 'INC', margin2018: 2720, winner2023: 'ZPM', winnerName2023: 'Lalnghinglova Hmar', currentParty: 'ZPM' },
  { acNo: 17, name: 'Aizawl West Iii', localName: 'Aizawl West-Iii', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'V.L. Zaithanzama', winnerVotes2018: 6934, runnerUp2018: 'MNF', margin2018: 1026, winner2023: 'ZPM', winnerName2023: 'V. L. Zaithanzama', currentParty: 'ZPM' },
  { acNo: 18, name: 'Aizawl South I', localName: 'Aizawl South-I', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'C. Lalsawivunga', winnerVotes2018: 6808, runnerUp2018: 'MNF', margin2018: 1049, winner2023: 'ZPM', winnerName2023: 'C. Lalsawivunga', currentParty: 'ZPM' },
  { acNo: 19, name: 'Aizawl South Ii', localName: 'Aizawl South-Ii', district: 'Tuivawl', type: 'ST', winner2018: 'IND', winnerName2018: 'Lalchhuanthanga', winnerVotes2018: 7294, runnerUp2018: 'MNF', margin2018: 179, winner2023: 'ZPM', winnerName2023: 'Lalchhuanthanga', currentParty: 'ZPM' },
  { acNo: 20, name: 'Aizawl South-Iii', localName: 'Aizawl South-Iii', district: 'Tuivawl', type: 'ST', winner2018: 'MNF', winnerName2018: 'F. Lalnunmawia', winnerVotes2018: 7558, runnerUp2018: 'INC', margin2018: 2088, winner2023: 'ZPM', winnerName2023: 'Baryl Vanneihsangi', currentParty: 'ZPM' },
  { acNo: 21, name: 'Lengteng', district: 'Champhai', type: 'ST', winner2018: 'MNF', winnerName2018: 'L.Thangmawia', winnerVotes2018: 6430, runnerUp2018: 'INC', margin2018: 1772, winner2023: 'ZPM', winnerName2023: 'F. Rodingliana', currentParty: 'ZPM' },
  { acNo: 22, name: 'Tuichang', localName: 'Tuichang', district: 'Champhai', type: 'ST', winner2018: 'MNF', winnerName2018: 'Tawnluia', winnerVotes2018: 5146, runnerUp2018: 'IND', margin2018: 739, winner2023: 'ZPM', winnerName2023: 'W Chhuanawma', currentParty: 'ZPM' },
  { acNo: 23, name: 'Champhai North', localName: 'Champhai North', district: 'Champhai', type: 'ST', winner2018: 'MNF', winnerName2018: 'Dr Zr.Thiamsanga', winnerVotes2018: 6057, runnerUp2018: 'INC', margin2018: 1093, winner2023: 'ZPM', winnerName2023: 'H. Ginzalala', currentParty: 'ZPM' },
  { acNo: 24, name: 'Champhai South', localName: 'Champhai South', district: 'Champhai', type: 'ST', winner2018: 'MNF', winnerName2018: 'T.J Lalnuntluanga', winnerVotes2018: 5212, runnerUp2018: 'INC', margin2018: 1049, winner2023: 'ZPM', winnerName2023: 'Lt Col. Clement Lalhmingthanga', currentParty: 'ZPM' },
  { acNo: 25, name: 'East Tuipui', localName: 'East Tuipui', district: 'Champhai', type: 'ST', winner2018: 'MNF', winnerName2018: 'Ramthanmawia', winnerVotes2018: 4384, runnerUp2018: 'IND', margin2018: 587, winner2023: 'MNF', winnerName2023: 'Ramthanmawia', currentParty: 'MNF' },
  { acNo: 26, name: 'Serchhip', localName: 'Serchhip', district: 'Serchhip', type: 'ST', winner2018: 'IND', winnerName2018: 'Lalduhoma', winnerVotes2018: 5481, runnerUp2018: 'INC', margin2018: 410, winner2023: 'ZPM', winnerName2023: 'Lalduhoma', currentParty: 'ZPM' },
  { acNo: 27, name: 'Tuikum', district: 'Serchhip', type: 'ST', winner2018: 'MNF', winnerName2018: 'Er. Lalrinawma', winnerVotes2018: 5439, runnerUp2018: 'INC', margin2018: 1397, winner2023: 'ZPM', winnerName2023: 'P.C. Vanlalruata', currentParty: 'ZPM' },
  { acNo: 28, name: 'Hrangturzo', district: 'Serchhip', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lalchamliana', winnerVotes2018: 4572, runnerUp2018: 'INC', margin2018: 757, winner2023: 'ZPM', winnerName2023: 'Lalmuanpuia Punte', currentParty: 'ZPM' },
  { acNo: 29, name: 'South Tuipui', localName: 'South Tuipui', district: 'Lunglei', type: 'ST', winner2018: 'MNF', winnerName2018: 'Dr R Lalthangliana', winnerVotes2018: 6126, runnerUp2018: 'INC', margin2018: 1469, winner2023: 'ZPM', winnerName2023: 'Jeje Lalpekhlua', currentParty: 'ZPM' },
  { acNo: 30, name: 'Lunglei North', localName: 'Lunglei North', district: 'Lunglei', type: 'ST', winner2018: 'MNF', winnerName2018: 'Vanlaltanpuia', winnerVotes2018: 5022, runnerUp2018: 'IND', margin2018: 395, winner2023: 'ZPM', winnerName2023: 'V. Malsawmtluanga', currentParty: 'ZPM' },
  { acNo: 31, name: 'Lunglei East', localName: 'Lunglei East', district: 'Lunglei', type: 'ST', winner2018: 'MNF', winnerName2018: 'Lawmawma Tochhawng', winnerVotes2018: 4063, runnerUp2018: 'IND', margin2018: 72, winner2023: 'ZPM', winnerName2023: 'Lalrinpuii', currentParty: 'ZPM' },
  { acNo: 32, name: 'Lunglei West', localName: 'Lunglei West', district: 'Lunglei', type: 'ST', winner2018: 'MNF', winnerName2018: 'C.Lalrinsanga', winnerVotes2018: 4093, runnerUp2018: 'INC', margin2018: 77, winner2023: 'ZPM', winnerName2023: 'T. Lalhlimpuia', currentParty: 'ZPM' },
  { acNo: 33, name: 'Lunglei South', localName: 'Lunglei South', district: 'Lunglei', type: 'ST', winner2018: 'MNF', winnerName2018: 'K Pachhunga', winnerVotes2018: 6245, runnerUp2018: 'INC', margin2018: 2441, winner2023: 'ZPM', winnerName2023: 'Lalramliana Papuia', currentParty: 'ZPM' },
  { acNo: 34, name: 'Thorang', localName: 'Thorang', district: 'Lunglei', type: 'ST', winner2018: 'INC', winnerName2018: 'Zodintluanga Ralte', winnerVotes2018: 4499, runnerUp2018: 'MNF', margin2018: 1240, winner2023: 'MNF', winnerName2023: 'R. Rohmingliana', currentParty: 'MNF' },
  { acNo: 35, name: 'West Tuipui', localName: 'West Tuipui', district: 'Lunglei', type: 'ST', winner2018: 'INC', winnerName2018: 'Nihar Kanti Chakma', winnerVotes2018: 5943, runnerUp2018: 'BJP', margin2018: 2385, winner2023: 'MNF', winnerName2023: 'Prova Chakma', currentParty: 'MNF' },
  { acNo: 36, name: 'Tuichawng', localName: 'Tuichawng', district: 'Lawngtlai', type: 'ST', winner2018: 'BJP', winnerName2018: 'Buddha Dhan Chakma', winnerVotes2018: 11419, runnerUp2018: 'MNF', margin2018: 1594, winner2023: 'MNF', winnerName2023: 'Rasik Mohan Chakma', currentParty: 'MNF' },
  { acNo: 37, name: 'Lawngtlai West', localName: 'Lawngtlai West', district: 'Lawngtlai', type: 'ST', winner2018: 'INC', winnerName2018: 'C. Ngunlianchunga', winnerVotes2018: 10678, runnerUp2018: 'MNF', margin2018: 795, winner2023: 'INC', winnerName2023: 'C. Ngunlianchunga', currentParty: 'INC' },
  { acNo: 38, name: 'Lawngtlai East', localName: 'Lawngtlai East', district: 'Lawngtlai', type: 'ST', winner2018: 'MNF', winnerName2018: 'H. Biakzaua', winnerVotes2018: 8656, runnerUp2018: 'INC', margin2018: 944, winner2023: 'ZPM', winnerName2023: 'Dr. Lorrain Lalpekliana Chinzah', currentParty: 'ZPM' },
  { acNo: 39, name: 'Saiha', localName: 'Saiha', district: 'Saiha', type: 'ST', winner2018: 'MNF', winnerName2018: 'Dr. K. Beichhua', winnerVotes2018: 8109, runnerUp2018: 'INC', margin2018: 2468, winner2023: 'BJP', winnerName2023: 'Dr. K. Beichhua', currentParty: 'BJP' },
  { acNo: 40, name: 'Palak', district: 'Saiha', type: 'ST', winner2018: 'INC', winnerName2018: 'K.T. Rokhaw', winnerVotes2018: 5492, runnerUp2018: 'MNF', margin2018: 844, winner2023: 'BJP', winnerName2023: 'K. Hrahmo', currentParty: 'BJP' },
];

export function getMZConstituency(acNo: number): MZConstituencySeed | undefined {
  return MZ_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
