/**
 * MZ — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface MZElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const MZ_ELECTION_HISTORY: MZElectionResult[] = [
  {
    year: 2023,
    partyResults: {
      'ZPM': 27,
      'MNF': 10,
      'BJP': 2,
      'INC': 1,
    },
    totalSeats: 40,
    rulingParty: 'ZPM',
  },
  {
    year: 2018,
    partyResults: {
      'MNF': 26,
      'IND': 8,
      'INC': 5,
      'BJP': 1,
    },
    totalSeats: 40,
    rulingParty: 'MNF',
  },
];

export function getMZElectionByYear(year: number) {
  return MZ_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getMZPartyTrend(party: string) {
  return MZ_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
