/**
 * NL Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2023 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const NL_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 35303, totalVoters: 25173, turnout2023: 79, maleVoters: 12559, femaleVoters: 12614, literacy: 84.2, urbanPercent: 5.8, scPercent: 0, stPercent: 86.6, areaSqKm: 103 },
  { acNo: 2, population: 37429, totalVoters: 59520, turnout2023: 75.36, maleVoters: 30650, femaleVoters: 28870, literacy: 80.1, urbanPercent: 12.8, scPercent: 0, stPercent: 86.6, areaSqKm: 128 },
  { acNo: 3, population: 42546, totalVoters: 38824, turnout2023: 82.1, maleVoters: 19412, femaleVoters: 19412, literacy: 78.1, urbanPercent: 37.5, scPercent: 0, stPercent: 86.6, areaSqKm: 159 },
  { acNo: 4, population: 22897, totalVoters: 76063, turnout2023: 75.28, maleVoters: 39144, femaleVoters: 36919, literacy: 85.2, urbanPercent: 10.5, scPercent: 0, stPercent: 86.6, areaSqKm: 123 },
  { acNo: 5, population: 28161, totalVoters: 30029, turnout2023: 81.72, maleVoters: 15016, femaleVoters: 15013, literacy: 81.1, urbanPercent: 9.3, scPercent: 0, stPercent: 86.6, areaSqKm: 117 },
  { acNo: 6, population: 44540, totalVoters: 27621, turnout2023: 82.97, maleVoters: 14072, femaleVoters: 13549, literacy: 84.2, urbanPercent: 21, scPercent: 0, stPercent: 86.6, areaSqKm: 192 },
  { acNo: 7, population: 41692, totalVoters: 32826, turnout2023: 75.98, maleVoters: 16725, femaleVoters: 16101, literacy: 80.1, urbanPercent: 48.1, scPercent: 0, stPercent: 86.6, areaSqKm: 160 },
  { acNo: 8, population: 40057, totalVoters: 18243, turnout2023: 78, maleVoters: 9113, femaleVoters: 9130, literacy: 77.1, urbanPercent: 31.6, scPercent: 1, stPercent: 86.6, areaSqKm: 174 },
  { acNo: 9, population: 34246, totalVoters: 29209, turnout2023: 68, maleVoters: 14853, femaleVoters: 14356, literacy: 77.1, urbanPercent: 30.4, scPercent: 5, stPercent: 86.6, areaSqKm: 343 },
  { acNo: 10, population: 45942, totalVoters: 18246, turnout2023: 75.8, maleVoters: 9087, femaleVoters: 9159, literacy: 80.1, urbanPercent: 42.2, scPercent: 0, stPercent: 86.6, areaSqKm: 169 },
  { acNo: 11, population: 51893, totalVoters: 23300, turnout2023: 78.77, maleVoters: 11406, femaleVoters: 11894, literacy: 87.2, urbanPercent: 49.3, scPercent: 7, stPercent: 86.6, areaSqKm: 160 },
  { acNo: 12, population: 37001, totalVoters: 24703, turnout2023: 91.29, maleVoters: 12673, femaleVoters: 12030, literacy: 86.2, urbanPercent: 24.6, scPercent: 0, stPercent: 86.6, areaSqKm: 241 },
  { acNo: 13, population: 25739, totalVoters: 16056, turnout2023: 92.11, maleVoters: 7843, femaleVoters: 8213, literacy: 75.1, urbanPercent: 10.5, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
  { acNo: 14, population: 49744, totalVoters: 15112, turnout2023: 87, maleVoters: 7420, femaleVoters: 7692, literacy: 74, urbanPercent: 30.4, scPercent: 0, stPercent: 86.6, areaSqKm: 212 },
  { acNo: 15, population: 55800, totalVoters: 18586, turnout2023: 87.1, maleVoters: 9117, femaleVoters: 9469, literacy: 77.1, urbanPercent: 37.5, scPercent: 2, stPercent: 86.6, areaSqKm: 224 },
  { acNo: 16, population: 55916, totalVoters: 21848, turnout2023: 87, maleVoters: 10946, femaleVoters: 10902, literacy: 86.2, urbanPercent: 44.6, scPercent: 6, stPercent: 86.6, areaSqKm: 174 },
  { acNo: 17, population: 27645, totalVoters: 19042, turnout2023: 86, maleVoters: 9236, femaleVoters: 9806, literacy: 84.2, urbanPercent: 6.9, scPercent: 0, stPercent: 86.6, areaSqKm: 103 },
  { acNo: 18, population: 44256, totalVoters: 26497, turnout2023: 87, maleVoters: 13513, femaleVoters: 12984, literacy: 84.2, urbanPercent: 9.3, scPercent: 0, stPercent: 86.6, areaSqKm: 106 },
  { acNo: 19, population: 17073, totalVoters: 22544, turnout2023: 86, maleVoters: 11463, femaleVoters: 11081, literacy: 74, urbanPercent: 11.6, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
  { acNo: 20, population: 42538, totalVoters: 21172, turnout2023: 91.6, maleVoters: 10417, femaleVoters: 10755, literacy: 84.2, urbanPercent: 49.3, scPercent: 4, stPercent: 86.6, areaSqKm: 156 },
  { acNo: 21, population: 28443, totalVoters: 18614, turnout2023: 94.8, maleVoters: 9400, femaleVoters: 9214, literacy: 76.1, urbanPercent: 30.4, scPercent: 2, stPercent: 86.6, areaSqKm: 264 },
  { acNo: 22, population: 49736, totalVoters: 18701, turnout2023: 94.07, maleVoters: 9566, femaleVoters: 9135, literacy: 85.2, urbanPercent: 43.4, scPercent: 0, stPercent: 86.6, areaSqKm: 168 },
  { acNo: 23, population: 33103, totalVoters: 13820, turnout2023: 91.06, maleVoters: 7028, femaleVoters: 6792, literacy: 71, urbanPercent: 23.4, scPercent: 0, stPercent: 86.6, areaSqKm: 289 },
  { acNo: 24, population: 45687, totalVoters: 18483, turnout2023: 85.13, maleVoters: 8983, femaleVoters: 9500, literacy: 88.2, urbanPercent: 37.5, scPercent: 2, stPercent: 86.6, areaSqKm: 258 },
  { acNo: 25, population: 44240, totalVoters: 17950, turnout2023: 90.63, maleVoters: 8885, femaleVoters: 9065, literacy: 82.2, urbanPercent: 45.7, scPercent: 2, stPercent: 86.6, areaSqKm: 185 },
  { acNo: 26, population: 56422, totalVoters: 11910, turnout2023: 82.22, maleVoters: 6098, femaleVoters: 5812, literacy: 82.2, urbanPercent: 44.6, scPercent: 0, stPercent: 86.6, areaSqKm: 158 },
  { acNo: 27, population: 54441, totalVoters: 8650, turnout2023: 78.16, maleVoters: 4355, femaleVoters: 4295, literacy: 84.2, urbanPercent: 46.9, scPercent: 4, stPercent: 86.6, areaSqKm: 194 },
  { acNo: 28, population: 40147, totalVoters: 22177, turnout2023: 86.33, maleVoters: 11321, femaleVoters: 10856, literacy: 79.1, urbanPercent: 29.3, scPercent: 7, stPercent: 86.6, areaSqKm: 291 },
  { acNo: 29, population: 43373, totalVoters: 12883, turnout2023: 87.42, maleVoters: 6570, femaleVoters: 6313, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 30, population: 115247, totalVoters: 16139, turnout2023: 91.94, maleVoters: 8207, femaleVoters: 7932, literacy: 84.2, urbanPercent: 38.7, scPercent: 0, stPercent: 86.6, areaSqKm: 257 },
  { acNo: 31, population: 58824, totalVoters: 10014, turnout2023: 82.1, maleVoters: 5012, femaleVoters: 5002, literacy: 89.2, urbanPercent: 39.9, scPercent: 3, stPercent: 86.6, areaSqKm: 256 },
  { acNo: 32, population: 27641, totalVoters: 16988, turnout2023: 94.2, maleVoters: 8392, femaleVoters: 8596, literacy: 79.1, urbanPercent: 10.5, scPercent: 0, stPercent: 86.6, areaSqKm: 112 },
  { acNo: 33, population: 43373, totalVoters: 16429, turnout2023: 83.92, maleVoters: 8379, femaleVoters: 8050, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 34, population: 90182, totalVoters: 16087, turnout2023: 85.2, maleVoters: 7891, femaleVoters: 8196, literacy: 89.2, urbanPercent: 41, scPercent: 3, stPercent: 86.6, areaSqKm: 270 },
  { acNo: 35, population: 36324, totalVoters: 23460, turnout2023: 84.79, maleVoters: 11836, femaleVoters: 11624, literacy: 73, urbanPercent: 29.3, scPercent: 0, stPercent: 86.6, areaSqKm: 185 },
  { acNo: 36, population: 35545, totalVoters: 19371, turnout2023: 84.86, maleVoters: 9957, femaleVoters: 9414, literacy: 81.1, urbanPercent: 15.2, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
  { acNo: 37, population: 49165, totalVoters: 26246, turnout2023: 93.48, maleVoters: 13018, femaleVoters: 13228, literacy: 80.1, urbanPercent: 26.9, scPercent: 6, stPercent: 86.6, areaSqKm: 232 },
  { acNo: 38, population: 45284, totalVoters: 32032, turnout2023: 91.12, maleVoters: 16112, femaleVoters: 15920, literacy: 73, urbanPercent: 30.4, scPercent: 0, stPercent: 86.6, areaSqKm: 175 },
  { acNo: 39, population: 24374, totalVoters: 23968, turnout2023: 95.53, maleVoters: 12116, femaleVoters: 11852, literacy: 76.1, urbanPercent: 16.3, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
  { acNo: 40, population: 43373, totalVoters: 30875, turnout2023: 83, maleVoters: 15746, femaleVoters: 15129, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 41, population: 40881, totalVoters: 21072, turnout2023: 93.39, maleVoters: 10452, femaleVoters: 10620, literacy: 85.2, urbanPercent: 26.9, scPercent: 0, stPercent: 86.6, areaSqKm: 217 },
  { acNo: 42, population: 48803, totalVoters: 16500, turnout2023: 94.85, maleVoters: 8217, femaleVoters: 8283, literacy: 77.1, urbanPercent: 32.8, scPercent: 1, stPercent: 86.6, areaSqKm: 164 },
  { acNo: 43, population: 44003, totalVoters: 15459, turnout2023: 94.5, maleVoters: 7699, femaleVoters: 7760, literacy: 78.1, urbanPercent: 21, scPercent: 0, stPercent: 86.6, areaSqKm: 241 },
  { acNo: 44, population: 43373, totalVoters: 17588, turnout2023: 95.95, maleVoters: 8970, femaleVoters: 8618, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 45, population: 39106, totalVoters: 12451, turnout2023: 94.39, maleVoters: 6238, femaleVoters: 6213, literacy: 79.1, urbanPercent: 22.2, scPercent: 0, stPercent: 86.6, areaSqKm: 238 },
  { acNo: 46, population: 43373, totalVoters: 20987, turnout2023: 91.33, maleVoters: 10703, femaleVoters: 10284, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 47, population: 38766, totalVoters: 13647, turnout2023: 93.98, maleVoters: 7001, femaleVoters: 6646, literacy: 85.2, urbanPercent: 42.2, scPercent: 0, stPercent: 80, areaSqKm: 188 },
  { acNo: 48, population: 48490, totalVoters: 18199, turnout2023: 96, maleVoters: 9354, femaleVoters: 8845, literacy: 82.2, urbanPercent: 48.1, scPercent: 2, stPercent: 86.6, areaSqKm: 193 },
  { acNo: 49, population: 53838, totalVoters: 18637, turnout2023: 90.7, maleVoters: 9487, femaleVoters: 9150, literacy: 77.1, urbanPercent: 34, scPercent: 2, stPercent: 86.6, areaSqKm: 175 },
  { acNo: 50, population: 32079, totalVoters: 32449, turnout2023: 90, maleVoters: 16289, femaleVoters: 16160, literacy: 77.1, urbanPercent: 24.6, scPercent: 5, stPercent: 86.6, areaSqKm: 301 },
  { acNo: 51, population: 56143, totalVoters: 13012, turnout2023: 78.03, maleVoters: 6590, femaleVoters: 6422, literacy: 82.2, urbanPercent: 43.4, scPercent: 2, stPercent: 86.6, areaSqKm: 177 },
  { acNo: 52, population: 34158, totalVoters: 22302, turnout2023: 90.75, maleVoters: 11384, femaleVoters: 10918, literacy: 76.1, urbanPercent: 28.1, scPercent: 4, stPercent: 86.6, areaSqKm: 346 },
  { acNo: 53, population: 43373, totalVoters: 24576, turnout2023: 81.24, maleVoters: 12534, femaleVoters: 12042, literacy: 80.1, urbanPercent: 28.9, scPercent: 1.3, stPercent: 86.5, areaSqKm: 173 },
  { acNo: 54, population: 42434, totalVoters: 17718, turnout2023: 86, maleVoters: 8699, femaleVoters: 9019, literacy: 82.2, urbanPercent: 23.4, scPercent: 0, stPercent: 86.6, areaSqKm: 196 },
  { acNo: 55, population: 46315, totalVoters: 22322, turnout2023: 93, maleVoters: 11262, femaleVoters: 11060, literacy: 81.1, urbanPercent: 25.7, scPercent: 0, stPercent: 86.6, areaSqKm: 229 },
  { acNo: 56, population: 50191, totalVoters: 18735, turnout2023: 86.76, maleVoters: 9115, femaleVoters: 9620, literacy: 80.1, urbanPercent: 44.6, scPercent: 0, stPercent: 86.6, areaSqKm: 176 },
  { acNo: 57, population: 50195, totalVoters: 20661, turnout2023: 90.32, maleVoters: 10072, femaleVoters: 10589, literacy: 80.1, urbanPercent: 28.1, scPercent: 0, stPercent: 86.6, areaSqKm: 204 },
  { acNo: 58, population: 43690, totalVoters: 18739, turnout2023: 86, maleVoters: 9210, femaleVoters: 9529, literacy: 71, urbanPercent: 31.6, scPercent: 0, stPercent: 86.6, areaSqKm: 201 },
  { acNo: 59, population: 29350, totalVoters: 24638, turnout2023: 93.46, maleVoters: 12171, femaleVoters: 12467, literacy: 73, urbanPercent: 14, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
  { acNo: 60, population: 24892, totalVoters: 33298, turnout2023: 90.21, maleVoters: 16551, femaleVoters: 16747, literacy: 80.1, urbanPercent: 9.3, scPercent: 0, stPercent: 86.6, areaSqKm: 5 },
];

export function getNLConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return NL_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
