/**
 * Nagaland Assembly Constituencies — 2023 General Election (60 seats)
 *
 * SOURCE: TCPD "Lok Dhaba" (Trivedi Centre for Political Data, Ashoka University),
 *         Nagaland_AE dataset — ECI-sourced constituency results. Uses the
 *         official ECI AC numbering (1-60). Winner/runner-up parties,
 *         vote counts, and margins are the ECI 2023 results as compiled by TCPD.
 *         Reservation (GEN/SC/ST) and district are from the same dataset.
 *         Auto-generated by scripts/build-tcpd-seed.mjs — do not hand-edit.
 *
 * PARTY TALLY 2023: NDPP 25 | BJP 12 | NCP 7 | NPP 5 | IND 4 | LJPRV 2 | NPF 2 | RPIA 2 | JDU 1 = 60
 */

export interface NLConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in local script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2023: string;
  winnerName2023: string;
  winnerVotes2023: number;
  runnerUp2023: string;
  margin2023: number;
  currentParty: string;
}

export const NL_CONSTITUENCIES: NLConstituencySeed[] = [
  { acNo: 1, name: 'Dimapur-I', localName: 'Dimapur-I', district: 'Dimapur', type: 'GEN', winner2023: 'BJP', winnerName2023: 'H. Tovihoto Ayemi', winnerVotes2023: 13325, runnerUp2023: 'INC', margin2023: 6959, currentParty: 'BJP' },
  { acNo: 2, name: 'Dimapur-Ii', localName: 'Dimapur-Ii', district: 'Dimapur', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Moatoshi Longkumer', winnerVotes2023: 23856, runnerUp2023: 'LJPRV', margin2023: 5147, currentParty: 'NDPP' },
  { acNo: 3, name: 'Dimapur-Iii', localName: 'Dimapur-Iii', district: 'Dimapur', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Hekani Jakhalu', winnerVotes2023: 14395, runnerUp2023: 'LJPRV', margin2023: 1536, currentParty: 'NDPP' },
  { acNo: 4, name: 'Ghaspani-I', localName: 'Ghaspani-I', district: 'Dimapur', type: 'ST', winner2023: 'BJP', winnerName2023: 'N. Jacob Zhimomi', winnerVotes2023: 32037, runnerUp2023: 'IND', margin2023: 20096, currentParty: 'BJP' },
  { acNo: 5, name: 'Ghaspani-Ii', localName: 'Ghaspani-Ii', district: 'Dimapur', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Zhaleo Rio', winnerVotes2023: 11405, runnerUp2023: 'RPIA', margin2023: 4175, currentParty: 'NDPP' },
  { acNo: 6, name: 'Tenning', localName: 'Tenning', district: 'Peren', type: 'ST', winner2023: 'NCP', winnerName2023: 'Namri Nchang', winnerVotes2023: 6736, runnerUp2023: 'NDPP', margin2023: 337, currentParty: 'NCP' },
  { acNo: 7, name: 'Peren', localName: 'Peren', district: 'Peren', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Taditui Rangkau Zeliang', winnerVotes2023: 16800, runnerUp2023: 'NPF', margin2023: 9915, currentParty: 'NDPP' },
  { acNo: 8, name: 'Western Angami', localName: 'Western Angami', district: 'Kohima', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Salhoutuonuo Kruse', winnerVotes2023: 7078, runnerUp2023: 'IND', margin2023: 7, currentParty: 'NDPP' },
  { acNo: 9, name: 'Kohima Town', localName: 'Kohima Town', district: 'Kohima', type: 'ST', winner2023: 'NPP', winnerName2023: 'Dr Tseilhoutuo Rhutso (Dr Ato)', winnerVotes2023: 9844, runnerUp2023: 'NDPP', margin2023: 1342, currentParty: 'NPP' },
  { acNo: 10, name: 'Northern Angami-I', localName: 'Northern Angami-I', district: 'Kohima', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Dr.Kekhrielhoulie Yhome', winnerVotes2023: 7724, runnerUp2023: 'NPF', margin2023: 1690, currentParty: 'NDPP' },
  { acNo: 11, name: 'Northern Angami-Ii', localName: 'Northern Angami-Ii', district: 'Kohima', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Neiphiu Rio', winnerVotes2023: 17045, runnerUp2023: 'INC', margin2023: 15824, currentParty: 'NDPP' },
  { acNo: 12, name: 'Tseminyu', localName: 'Tseminyu', district: 'Kohima', type: 'ST', winner2023: 'JDU', winnerName2023: 'Jwenga Seb', winnerVotes2023: 8096, runnerUp2023: 'RPIA', margin2023: 2563, currentParty: 'JDU' },
  { acNo: 13, name: 'Pughoboto', localName: 'Pughoboto', district: 'Pughoboto', type: 'ST', winner2023: 'LJPRV', winnerName2023: 'Dr Sukhato A Sema', winnerVotes2023: 7808, runnerUp2023: 'NDPP', margin2023: 850, currentParty: 'LJPRV' },
  { acNo: 14, name: 'Southern Angami-I', localName: 'Southern Angami-I', district: 'Kohima', type: 'ST', winner2023: 'IND', winnerName2023: 'Kevipodi Sophie', winnerVotes2023: 6643, runnerUp2023: 'NDPP', margin2023: 177, currentParty: 'IND' },
  { acNo: 15, name: 'Southern Angami-Ii', localName: 'Southern Angami-Ii', district: 'Kohima', type: 'ST', winner2023: 'BJP', winnerName2023: 'Kropol Vitsu', winnerVotes2023: 5985, runnerUp2023: 'NCP', margin2023: 450, currentParty: 'BJP' },
  { acNo: 16, name: 'Pfutsero', localName: 'Pfutsero', district: 'Phek', type: 'ST', winner2023: 'IND', winnerName2023: 'Dr.Neisatuo Mero', winnerVotes2023: 7995, runnerUp2023: 'NDPP', margin2023: 104, currentParty: 'IND' },
  { acNo: 17, name: 'Chizami', localName: 'Chizami', district: 'Phek', type: 'ST', winner2023: 'NDPP', winnerName2023: 'K. G Kenye', winnerVotes2023: 7088, runnerUp2023: 'LJPRV', margin2023: 1279, currentParty: 'NDPP' },
  { acNo: 18, name: 'Chazouba', localName: 'Chazouba', district: 'Phek', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Kudecho Khamo', winnerVotes2023: 9485, runnerUp2023: 'LJPRV', margin2023: 2238, currentParty: 'NDPP' },
  { acNo: 19, name: 'Phek', localName: 'Phek', district: 'Phek', type: 'ST', winner2023: 'NPF', winnerName2023: 'Kuzholuzo Nienu', winnerVotes2023: 9485, runnerUp2023: 'NDPP', margin2023: 48, currentParty: 'NPF' },
  { acNo: 20, name: 'Meluri', localName: 'Meluri', district: 'Phek', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Z.Nyusietho Nyuthe', winnerVotes2023: 11256, runnerUp2023: 'LJPRV', margin2023: 3580, currentParty: 'NDPP' },
  { acNo: 21, name: 'Tuli', localName: 'Tuli', district: 'Mokokchung', type: 'ST', winner2023: 'BJP', winnerName2023: 'A. Pangjung Jamir', winnerVotes2023: 10319, runnerUp2023: 'NCP', margin2023: 3029, currentParty: 'BJP' },
  { acNo: 22, name: 'Arkakong', localName: 'Arkakong', district: 'Mokokchung', type: 'ST', winner2023: 'NPP', winnerName2023: 'Nuklutoshi', winnerVotes2023: 9387, runnerUp2023: 'NDPP', margin2023: 1203, currentParty: 'NPP' },
  { acNo: 23, name: 'Impur', localName: 'Impur', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'T N Mannen', winnerVotes2023: 6825, runnerUp2023: 'INC', margin2023: 1095, currentParty: 'NDPP' },
  { acNo: 24, name: 'Angetyongpang', localName: 'Angetyongpang', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Tongpang Ozukum', winnerVotes2023: 8046, runnerUp2023: 'IND', margin2023: 2220, currentParty: 'NDPP' },
  { acNo: 25, name: 'Mongoya', localName: 'Mongoya', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Imkongmar', winnerVotes2023: 6818, runnerUp2023: 'INC', margin2023: 1042, currentParty: 'NDPP' },
  { acNo: 26, name: 'Aonglenden', localName: 'Aonglenden', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Sharingain Longkumer', winnerVotes2023: 7074, runnerUp2023: 'INC', margin2023: 4390, currentParty: 'NDPP' },
  { acNo: 27, name: 'Mokokchung Town', localName: 'Mokokchung Town', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Metsubo Jamir', winnerVotes2023: 5318, runnerUp2023: 'INC', margin2023: 3911, currentParty: 'NDPP' },
  { acNo: 28, name: 'Koridang', localName: 'Koridang', district: 'Mokokchung', type: 'ST', winner2023: 'BJP', winnerName2023: 'Imkong L. Imchen', winnerVotes2023: 8340, runnerUp2023: 'NPF', margin2023: 410, currentParty: 'BJP' },
  { acNo: 29, name: 'Jangpetkong', district: 'Mokokchung', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Temjenmenba', winnerVotes2023: 6238, runnerUp2023: 'NPF', margin2023: 2001, currentParty: 'NDPP' },
  { acNo: 30, name: 'Alongtaki', localName: 'Alongtaki', district: 'Mokokchung', type: 'ST', winner2023: 'BJP', winnerName2023: 'Temjen Imna Along', winnerVotes2023: 9274, runnerUp2023: 'JDU', margin2023: 3748, currentParty: 'BJP' },
  { acNo: 31, name: 'Akuluto', localName: 'Akuluto', district: 'Zunheboto', type: 'ST', winner2023: 'BJP', winnerName2023: 'Kazheto', winnerVotes2023: 0, runnerUp2023: '', margin2023: 0, currentParty: 'BJP' },
  { acNo: 32, name: 'Atoizu', localName: 'Atoizu', district: 'Zunheboto', type: 'ST', winner2023: 'NCP', winnerName2023: 'Picto', winnerVotes2023: 8294, runnerUp2023: 'BJP', margin2023: 602, currentParty: 'NCP' },
  { acNo: 33, name: 'Suruhoto', district: 'Zunheboto', type: 'ST', winner2023: 'NCP', winnerName2023: 'S. Toiho Yeptho', winnerVotes2023: 6919, runnerUp2023: 'BJP', margin2023: 69, currentParty: 'NCP' },
  { acNo: 34, name: 'Aghunato', localName: 'Aghunato', district: 'Zunheboto', type: 'ST', winner2023: 'NDPP', winnerName2023: 'G Ikuto Zhimomi', winnerVotes2023: 7133, runnerUp2023: 'LJPRV', margin2023: 592, currentParty: 'NDPP' },
  { acNo: 35, name: 'Zunheboto', localName: 'Zunheboto', district: 'Zunheboto', type: 'ST', winner2023: 'NDPP', winnerName2023: 'K Tokugha Sukhalu', winnerVotes2023: 15921, runnerUp2023: 'NPF', margin2023: 12028, currentParty: 'NDPP' },
  { acNo: 36, name: 'Satakha', localName: 'Satakha', district: 'Zunheboto', type: 'ST', winner2023: 'NDPP', winnerName2023: 'G. Kaito Aye', winnerVotes2023: 8875, runnerUp2023: 'LJPRV', margin2023: 1351, currentParty: 'NDPP' },
  { acNo: 37, name: 'Tyui', localName: 'Tyui', district: 'Wokha', type: 'ST', winner2023: 'BJP', winnerName2023: 'Yanthungo Patton', winnerVotes2023: 16641, runnerUp2023: 'JDU', margin2023: 8841, currentParty: 'BJP' },
  { acNo: 38, name: 'Wokha', localName: 'Wokha', district: 'Wokha', type: 'ST', winner2023: 'NCP', winnerName2023: 'Y Mhonbemo Humtsoe', winnerVotes2023: 15949, runnerUp2023: 'BJP', margin2023: 3061, currentParty: 'NCP' },
  { acNo: 39, name: 'Sanis', localName: 'Sanis', district: 'Wokha', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Mhathung Yanthan', winnerVotes2023: 15076, runnerUp2023: 'RJD', margin2023: 9513, currentParty: 'NDPP' },
  { acNo: 40, name: 'Bhandari', district: 'Wokha', type: 'ST', winner2023: 'NPF', winnerName2023: 'Achumbemo Kikon', winnerVotes2023: 13867, runnerUp2023: 'BJP', margin2023: 3589, currentParty: 'NPF' },
  { acNo: 41, name: 'Tizit', localName: 'Tizit', district: 'Mon', type: 'ST', winner2023: 'BJP', winnerName2023: 'P. Paiwang Konyak', winnerVotes2023: 10428, runnerUp2023: 'INC', margin2023: 4603, currentParty: 'BJP' },
  { acNo: 42, name: 'Wakching', localName: 'Wakching', district: 'Mon', type: 'ST', winner2023: 'NDPP', winnerName2023: 'W Chingang Konyak', winnerVotes2023: 9166, runnerUp2023: 'NPP', margin2023: 2733, currentParty: 'NDPP' },
  { acNo: 43, name: 'Tapi', localName: 'Tapi', district: 'Mon', type: 'ST', winner2023: 'NDPP', winnerName2023: 'Noke Wangnao', winnerVotes2023: 5864, runnerUp2023: 'NPF', margin2023: 82, currentParty: 'NDPP' },
  { acNo: 44, name: 'Phomching', district: 'Mon', type: 'ST', winner2023: 'BJP', winnerName2023: 'K Konngam Konyak', winnerVotes2023: 9803, runnerUp2023: 'NCP', margin2023: 2877, currentParty: 'BJP' },
  { acNo: 45, name: 'Tehok', localName: 'Tehok', district: 'Mon', type: 'ST', winner2023: 'NDPP', winnerName2023: 'C.L John', winnerVotes2023: 9232, runnerUp2023: 'NPF', margin2023: 7070, currentParty: 'NDPP' },
  { acNo: 46, name: 'Mon Town', district: 'Mon', type: 'ST', winner2023: 'NCP', winnerName2023: 'Y Mankhao Konyak', winnerVotes2023: 10870, runnerUp2023: 'BJP', margin2023: 2611, currentParty: 'NCP' },
  { acNo: 47, name: 'Aboi', localName: 'Aboi', district: 'Mon', type: 'ST', winner2023: 'IND', winnerName2023: 'C. Manpon Konyak', winnerVotes2023: 6771, runnerUp2023: 'RPIA', margin2023: 3524, currentParty: 'IND' },
  { acNo: 48, name: 'Moka', localName: 'Moka', district: 'Mon', type: 'ST', winner2023: 'NPP', winnerName2023: 'A Nyamnyei Konyak', winnerVotes2023: 8857, runnerUp2023: 'NDPP', margin2023: 556, currentParty: 'NPP' },
  { acNo: 49, name: 'Tamlu', localName: 'Tamlu', district: 'Longleng', type: 'ST', winner2023: 'IND', winnerName2023: 'B. Bangtick Phom', winnerVotes2023: 8646, runnerUp2023: 'NDPP', margin2023: 694, currentParty: 'IND' },
  { acNo: 50, name: 'Longleng', localName: 'Longleng', district: 'Longleng', type: 'ST', winner2023: 'NCP', winnerName2023: 'A Pongshi Phom', winnerVotes2023: 16908, runnerUp2023: 'BJP', margin2023: 5270, currentParty: 'NCP' },
  { acNo: 51, name: 'Noksen', localName: 'Noksen', district: 'Tuensang', type: 'ST', winner2023: 'RPIA', winnerName2023: 'Y. Lima Onen Chang', winnerVotes2023: 5151, runnerUp2023: 'NDPP', margin2023: 188, currentParty: 'RPIA' },
  { acNo: 52, name: 'Longkhim Chare', localName: 'Longkhim Chare', district: 'Tuensang', type: 'ST', winner2023: 'BJP', winnerName2023: 'Sethronkyu', winnerVotes2023: 10187, runnerUp2023: 'NCP', margin2023: 1623, currentParty: 'BJP' },
  { acNo: 53, name: 'Tuensang Sadar-I', district: 'Tuensang', type: 'ST', winner2023: 'BJP', winnerName2023: 'P. Bashangmongba Chang', winnerVotes2023: 12638, runnerUp2023: 'NCP', margin2023: 5644, currentParty: 'BJP' },
  { acNo: 54, name: 'Tuensang Sadar-Ii', localName: 'Tuensang Sadar-Ii', district: 'Tuensang', type: 'ST', winner2023: 'RPIA', winnerName2023: 'Imtichoba', winnerVotes2023: 5514, runnerUp2023: 'NDPP', margin2023: 400, currentParty: 'RPIA' },
  { acNo: 55, name: 'Tobu', localName: 'Tobu', district: 'Mon', type: 'ST', winner2023: 'LJPRV', winnerName2023: 'Naiba Konyak', winnerVotes2023: 10622, runnerUp2023: 'NDPP', margin2023: 506, currentParty: 'LJPRV' },
  { acNo: 56, name: 'Noklak', localName: 'Noklak', district: 'Tuensang', type: 'ST', winner2023: 'NCP', winnerName2023: 'P Longon', winnerVotes2023: 8482, runnerUp2023: 'BJP', margin2023: 734, currentParty: 'NCP' },
  { acNo: 57, name: 'Thonoknyu', localName: 'Thonoknyu', district: 'Tuensang', type: 'ST', winner2023: 'NPP', winnerName2023: 'Benei M Lamthiu', winnerVotes2023: 10462, runnerUp2023: 'NDPP', margin2023: 2325, currentParty: 'NPP' },
  { acNo: 58, name: 'Shamator Chessore', localName: 'Shamator Chessore', district: 'Tuensang', type: 'ST', winner2023: 'NDPP', winnerName2023: 'S Keoshu Yimchunger', winnerVotes2023: 9065, runnerUp2023: 'LJPRV', margin2023: 2295, currentParty: 'NDPP' },
  { acNo: 59, name: 'Seyochung Sitimi', localName: 'Seyochung Sitimi', district: 'Kiphire', type: 'ST', winner2023: 'NPP', winnerName2023: 'C. Kipili Sangtam', winnerVotes2023: 11936, runnerUp2023: 'BJP', margin2023: 930, currentParty: 'NPP' },
  { acNo: 60, name: 'Pungro Kiphire', localName: 'Pungro Kiphire', district: 'Kiphire', type: 'ST', winner2023: 'NDPP', winnerName2023: 'S. Kiusumew Yimchunger', winnerVotes2023: 16098, runnerUp2023: 'RPIA', margin2023: 2291, currentParty: 'NDPP' },
];

export function getNLConstituency(acNo: number): NLConstituencySeed | undefined {
  return NL_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
