/**
 * NL — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface NLElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const NL_ELECTION_HISTORY: NLElectionResult[] = [
  {
    year: 2023,
    partyResults: {
      'NDPP': 25,
      'BJP': 12,
      'NCP': 7,
      'NPP': 5,
      'IND': 4,
      'LJPRV': 2,
      'NPF': 2,
      'RPIA': 2,
      'JDU': 1,
    },
    totalSeats: 60,
    rulingParty: 'NDPP',
  },
];

export function getNLElectionByYear(year: number) {
  return NL_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getNLPartyTrend(party: string) {
  return NL_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
