/**
 * PY — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface PYElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const PY_ELECTION_HISTORY: PYElectionResult[] = [
  {
    year: 2026,
    partyResults: {
      'AINRC': 12,
      'DMK': 5,
      'BJP': 4,
      'IND': 3,
      'TVK': 2,
      'INC': 1,
      'LJK': 1,
      'AIADMK': 1,
      'NMK': 1,
    },
    totalSeats: 30,
    rulingParty: 'AINRC',
  },
  {
    year: 2021,
    partyResults: {
      'AINRC': 10,
      'BJP': 6,
      'IND': 6,
      'DMK': 6,
      'INC': 2,
    },
    totalSeats: 30,
    rulingParty: 'AINRC',
  },
];

export function getPYElectionByYear(year: number) {
  return PY_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getPYPartyTrend(party: string) {
  return PY_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
