/**
 * Puducherry Assembly Constituencies — CURRENT 7th Assembly (2026 General Election, 30 seats)
 *
 * SOURCES:
 *   2026 result (current): ECI ResultAcGenMay2026 / CEO Puducherry Form-21C (04-05-2026),
 *     cross-checked with Indian Express & News18 constituency-wise winners lists.
 *   2021 result (history): TCPD "Lok Dhaba" (ECI-sourced). Official ECI AC numbering (1-30).
 *   localName (Tamil) and most 2026 candidate names retained from the project's prior data.
 *   Auto-generated by scripts/build-py-2026.mjs — do not hand-edit.
 *
 * 2026 PARTY TALLY: AINRC 12 | BJP 4 | DMK 5 | TVK 2 | INC 1 | LJK 1 | AIADMK 1 | NMK 1 | IND 3 = 30   (NDA: AINRC+BJP+AIADMK+LJK = 18)
 */

export interface PYConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in Tamil script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2021: string;
  winnerName2021: string;
  winnerVotes2021: number;
  runnerUp2021: string;
  margin2021: number;
  winner2026: string;
  winnerName2026: string;
  winnerVotes2026: number;
  runnerUp2026: string;
  margin2026: number;
  currentParty: string;
}

export const PY_CONSTITUENCIES: PYConstituencySeed[] = [
  { acNo: 1, name: 'Mannadipet', localName: 'மண்ணாடிப்பட்டு', district: 'Puducherry', type: 'GEN', winner2021: 'BJP', winnerName2021: 'A. Namassivayam', winnerVotes2021: 14939, runnerUp2021: 'DMK', margin2021: 2750, winner2026: 'BJP', winnerName2026: 'A. Namassivayam', winnerVotes2026: 17020, runnerUp2026: 'DMK', margin2026: 1021, currentParty: 'BJP' },
  { acNo: 2, name: 'Thirubhuvanai', district: 'Puducherry', type: 'SC', winner2021: 'IND', winnerName2021: 'P. Angalane', winnerVotes2021: 10597, runnerUp2021: 'AINRC', margin2021: 2359, winner2026: 'TVK', winnerName2026: 'AK Sai J Saravanan Kumar', winnerVotes2026: 0, runnerUp2026: '', margin2026: 0, currentParty: 'TVK' },
  { acNo: 3, name: 'Oussudu', localName: 'ஒசுடு', district: 'Puducherry', type: 'SC', winner2021: 'BJP', winnerName2021: 'Ak Sai J Saravanan Kumar', winnerVotes2021: 14121, runnerUp2021: 'INC', margin2021: 1880, winner2026: 'INC', winnerName2026: 'P. Karthikeyan', winnerVotes2026: 10548, runnerUp2026: 'AINRC', margin2026: 1477, currentParty: 'INC' },
  { acNo: 4, name: 'Mangalam', localName: 'மங்கலம்', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'Djeacoumar .C', winnerVotes2021: 16972, runnerUp2021: 'DMK', margin2021: 2751, winner2026: 'AINRC', winnerName2026: 'N. Rangasamy', winnerVotes2026: 16108, runnerUp2026: 'AINRC', margin2026: 1289, currentParty: 'AINRC' },
  { acNo: 5, name: 'Villianur', localName: 'வில்லியனூர்', district: 'Puducherry', type: 'GEN', winner2021: 'DMK', winnerName2021: 'R. Siva', winnerVotes2021: 19653, runnerUp2021: 'AINRC', margin2021: 6950, winner2026: 'AINRC', winnerName2026: 'B.Ravicoumar', winnerVotes2026: 10518, runnerUp2026: 'AINRC', margin2026: 1473, currentParty: 'AINRC' },
  { acNo: 6, name: 'Ozhukarai', localName: 'உழவர்கரை', district: 'Puducherry', type: 'GEN', winner2021: 'IND', winnerName2021: 'M. Sivasankar', winnerVotes2021: 11940, runnerUp2021: 'AINRC', margin2021: 819, winner2026: 'AINRC', winnerName2026: 'K.Narayanasamy Alias Nithyanandam', winnerVotes2026: 12018, runnerUp2026: 'AINRC', margin2026: 2163, currentParty: 'AINRC' },
  { acNo: 7, name: 'Kadirgamam', localName: 'கதிர்காமம்', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'K.S.P @ S. Ramesh', winnerVotes2021: 17775, runnerUp2021: 'INC', margin2021: 12246, winner2026: 'IND', winnerName2026: 'Azhagu Alias Azhaganantham', winnerVotes2026: 11460, runnerUp2026: 'AINRC', margin2026: 1604, currentParty: 'IND' },
  { acNo: 8, name: 'Indira Nagar', localName: 'இந்திரா நகர்', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'V. Aroumougame @ Akd', winnerVotes2021: 21841, runnerUp2021: 'INC', margin2021: 18531, winner2026: 'AINRC', winnerName2026: 'P.V. Aroumougame Alias Akd', winnerVotes2026: 11044, runnerUp2026: 'AINRC', margin2026: 884, currentParty: 'AINRC' },
  { acNo: 9, name: 'Thattanchavady', localName: 'தட்டாஞ்சாவடி', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'N. Rangasamy', winnerVotes2021: 12978, runnerUp2021: 'CPI', margin2021: 5456, winner2026: 'AINRC', winnerName2026: 'N. Rangasamy', winnerVotes2026: 15144, runnerUp2026: 'AINRC', margin2026: 1212, currentParty: 'AINRC' },
  { acNo: 10, name: 'Kamaraj Nagar', localName: 'காமராஜ் நகர்', district: 'Puducherry', type: 'GEN', winner2021: 'BJP', winnerName2021: 'A. Johnkumar', winnerVotes2021: 16687, runnerUp2021: 'INC', margin2021: 7229, winner2026: 'LJK', winnerName2026: 'Jose Charles Martin', winnerVotes2026: 12478, runnerUp2026: 'DMK', margin2026: 998, currentParty: 'LJK' },
  { acNo: 11, name: 'Lawspet', localName: 'லாஸ்பேட்டை', district: 'Puducherry', type: 'GEN', winner2021: 'INC', winnerName2021: 'M. Vaithianathan', winnerVotes2021: 14592, runnerUp2021: 'BJP', margin2021: 5701, winner2026: 'AINRC', winnerName2026: 'V.P. Sivakolundhu', winnerVotes2026: 13744, runnerUp2026: 'AINRC', margin2026: 2474, currentParty: 'AINRC' },
  { acNo: 12, name: 'Kalapet', localName: 'காலாப்பட்டு', district: 'Puducherry', type: 'GEN', winner2021: 'BJP', winnerName2021: 'P.M.L. Kalyanasundaram', winnerVotes2021: 13277, runnerUp2021: 'IND', margin2021: 3508, winner2026: 'DMK', winnerName2026: 'Senthil Alias Ramesh', winnerVotes2026: 11938, runnerUp2026: 'AINRC', margin2026: 1671, currentParty: 'DMK' },
  { acNo: 13, name: 'Muthialpet', localName: 'முத்தியால்பேட்டை', district: 'Puducherry', type: 'GEN', winner2021: 'IND', winnerName2021: 'J. Prakash Kumar', winnerVotes2021: 8778, runnerUp2021: 'AIADMK', margin2021: 934, winner2026: 'AINRC', winnerName2026: 'Vaiyapuri Manikandan', winnerVotes2026: 11030, runnerUp2026: 'AINRC', margin2026: 441, currentParty: 'AINRC' },
  { acNo: 14, name: 'Raj Bhavan', localName: 'ராஜ் பவன்', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'K. Lakshminarayanan', winnerVotes2021: 10096, runnerUp2021: 'DMK', margin2021: 3732, winner2026: 'DMK', winnerName2026: 'Vignesh Kannan', winnerVotes2026: 13550, runnerUp2026: 'AINRC', margin2026: 2168, currentParty: 'DMK' },
  { acNo: 15, name: 'Oupalam', localName: 'உப்பளம்', district: 'Puducherry', type: 'GEN', winner2021: 'DMK', winnerName2021: 'Annibal Kennedy', winnerVotes2021: 13433, runnerUp2021: 'AIADMK', margin2021: 4780, winner2026: 'AIADMK', winnerName2026: 'A Anbalagan', winnerVotes2026: 17140, runnerUp2026: 'DMK', margin2026: 686, currentParty: 'AIADMK' },
  { acNo: 16, name: 'Orleampeth', localName: 'உருளையன்பேட்டை', district: 'Puducherry', type: 'GEN', winner2021: 'IND', winnerName2021: 'G. Nehru @ Kuppusamy', winnerVotes2021: 9580, runnerUp2021: 'DMK', margin2021: 2093, winner2026: 'NMK', winnerName2026: 'G. Nehru Alias Couppoussamy', winnerVotes2026: 15794, runnerUp2026: 'AINRC', margin2026: 1264, currentParty: 'NMK' },
  { acNo: 17, name: 'Nellithope', district: 'Puducherry', type: 'GEN', winner2021: 'BJP', winnerName2021: 'Richards Johnkumar', winnerVotes2021: 11757, runnerUp2021: 'DMK', margin2021: 496, winner2026: 'DMK', winnerName2026: 'V. Cartigueyane', winnerVotes2026: 0, runnerUp2026: '', margin2026: 850, currentParty: 'DMK' },
  { acNo: 18, name: 'Mudaliarpet', localName: 'முதலியார்பேட்டை', district: 'Puducherry', type: 'GEN', winner2021: 'DMK', winnerName2021: 'L. Sambath', winnerVotes2021: 15151, runnerUp2021: 'AIADMK', margin2021: 4179, winner2026: 'BJP', winnerName2026: 'A. Johnkumar', winnerVotes2026: 17994, runnerUp2026: 'DMK', margin2026: 3239, currentParty: 'BJP' },
  { acNo: 19, name: 'Ariankuppam', localName: 'அரியாங்குப்பம்', district: 'Puducherry', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'R. Baskar @ Datchanamourtty', winnerVotes2021: 17858, runnerUp2021: 'INC', margin2021: 6418, winner2026: 'AINRC', winnerName2026: 'C. Aiyappan Alias Mouttayappan', winnerVotes2026: 10168, runnerUp2026: 'AINRC', margin2026: 1424, currentParty: 'AINRC' },
  { acNo: 20, name: 'Manavely', localName: 'மணவெளி', district: 'Puducherry', type: 'GEN', winner2021: 'BJP', winnerName2021: 'Embalam Selvam @ R.Selvam', winnerVotes2021: 17225, runnerUp2021: 'INC', margin2021: 8132, winner2026: 'TVK', winnerName2026: 'B.Ramu', winnerVotes2026: 15258, runnerUp2026: 'AINRC', margin2026: 610, currentParty: 'TVK' },
  { acNo: 21, name: 'Embalam', localName: 'ஏம்பலம்', district: 'Puducherry', type: 'SC', winner2021: 'AINRC', winnerName2021: 'U Lakshmikandhan', winnerVotes2021: 15624, runnerUp2021: 'INC', margin2021: 2240, winner2026: 'AINRC', winnerName2026: 'E. Mohandoss', winnerVotes2026: 10690, runnerUp2026: 'AINRC', margin2026: 1710, currentParty: 'AINRC' },
  { acNo: 22, name: 'Nettapakkam', localName: 'நெட்டப்பாக்கம்', district: 'Puducherry', type: 'SC', winner2021: 'AINRC', winnerName2021: 'P Rajavelu', winnerVotes2021: 15978, runnerUp2021: 'INC', margin2021: 6638, winner2026: 'AINRC', winnerName2026: 'P. Rajavelu', winnerVotes2026: 14510, runnerUp2026: 'AINRC', margin2026: 871, currentParty: 'AINRC' },
  { acNo: 23, name: 'Bahour', localName: 'பாகூர்', district: 'Puducherry', type: 'GEN', winner2021: 'DMK', winnerName2021: 'R Senthilkumar', winnerVotes2021: 11789, runnerUp2021: 'AINRC', margin2021: 211, winner2026: 'DMK', winnerName2026: 'R. Senthil Kumar', winnerVotes2026: 10398, runnerUp2026: 'AINRC', margin2026: 1872, currentParty: 'DMK' },
  { acNo: 24, name: 'Nedungadu', localName: 'நெடுங்காடு', district: 'Karaikal', type: 'SC', winner2021: 'AINRC', winnerName2021: 'Chandira Priyanga', winnerVotes2021: 10774, runnerUp2021: 'INC', margin2021: 2214, winner2026: 'IND', winnerName2026: 'Dr. V. Vigneswaran', winnerVotes2026: 12128, runnerUp2026: 'AINRC', margin2026: 485, currentParty: 'IND' },
  { acNo: 25, name: 'Thirunallar', localName: 'திருநள்ளாறு', district: 'Karaikal', type: 'GEN', winner2021: 'IND', winnerName2021: 'Pr. Siva', winnerVotes2021: 9796, runnerUp2021: 'BJP', margin2021: 1380, winner2026: 'BJP', winnerName2026: 'G.N.S. Rajasekaran', winnerVotes2026: 16800, runnerUp2026: 'DMK', margin2026: 2352, currentParty: 'BJP' },
  { acNo: 26, name: 'Karaikal North', localName: 'காரைக்கால் வடக்கு', district: 'Karaikal', type: 'GEN', winner2021: 'AINRC', winnerName2021: 'P.R.N. Thirumurugan', winnerVotes2021: 12704, runnerUp2021: 'INC', margin2021: 135, winner2026: 'AINRC', winnerName2026: 'P.R.N. Thirumurugan', winnerVotes2026: 13080, runnerUp2026: 'AINRC', margin2026: 2093, currentParty: 'AINRC' },
  { acNo: 27, name: 'Karaikal South', district: 'Karaikal', type: 'GEN', winner2021: 'DMK', winnerName2021: 'A.M.H. Nazim', winnerVotes2021: 17401, runnerUp2021: 'AIADMK', margin2021: 12034, winner2026: 'DMK', winnerName2026: 'A.M.H. Nazeem', winnerVotes2026: 0, runnerUp2026: '', margin2026: 5862, currentParty: 'DMK' },
  { acNo: 28, name: 'Neravy T.R. Pattinam', localName: 'நெரவி-டி.ஆர்.பட்டினம்', district: 'Karaikal', type: 'GEN', winner2021: 'DMK', winnerName2021: 'M.Nagathiyagarajan', winnerVotes2021: 14496, runnerUp2021: 'BJP', margin2021: 5511, winner2026: 'BJP', winnerName2026: 'Tksm Meenatchisundaram', winnerVotes2026: 13288, runnerUp2026: 'DMK', margin2026: 2392, currentParty: 'BJP' },
  { acNo: 29, name: 'Mahe', localName: 'மாஹே', district: 'Mahe', type: 'GEN', winner2021: 'INC', winnerName2021: 'Ramesh Parambath', winnerVotes2021: 9744, runnerUp2021: 'IND', margin2021: 300, winner2026: 'IND', winnerName2026: 'T Ashok Kumar', winnerVotes2026: 14470, runnerUp2026: 'AINRC', margin2026: 2026, currentParty: 'IND' },
  { acNo: 30, name: 'Yanam', localName: 'யானம்', district: 'Yanam', type: 'GEN', winner2021: 'IND', winnerName2021: 'Gollapalli Srinivas Ashok', winnerVotes2021: 17132, runnerUp2021: 'AINRC', margin2021: 655, winner2026: 'AINRC', winnerName2026: 'Malladi Krishna Rao', winnerVotes2026: 12298, runnerUp2026: 'AINRC', margin2026: 984, currentParty: 'AINRC' },
];

export function getPYConstituency(acNo: number): PYConstituencySeed | undefined {
  return PY_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
