/**
 * PY Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2021 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const PY_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 46035, totalVoters: 32843, turnout2023: 87.78, maleVoters: 16438, femaleVoters: 16405, literacy: 86.1, urbanPercent: 71.3, scPercent: 15.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 2, population: 53319, totalVoters: 33284, turnout2023: 86.55, maleVoters: 16975, femaleVoters: 16309, literacy: 86.6, urbanPercent: 68, scPercent: 15.7, stPercent: 0.1, areaSqKm: 5 },
  { acNo: 3, population: 53279, totalVoters: 32723, turnout2023: 88.46, maleVoters: 16018, femaleVoters: 16705, literacy: 86.1, urbanPercent: 68.3, scPercent: 26.9, stPercent: 0, areaSqKm: 5 },
  { acNo: 4, population: 53364, totalVoters: 38656, turnout2023: 86.28, maleVoters: 19753, femaleVoters: 18903, literacy: 84, urbanPercent: 72.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 5, population: 55445, totalVoters: 43297, turnout2023: 81.45, maleVoters: 21670, femaleVoters: 21627, literacy: 90.3, urbanPercent: 61.3, scPercent: 11.1, stPercent: 0, areaSqKm: 5 },
  { acNo: 6, population: 54431, totalVoters: 42960, turnout2023: 76.14, maleVoters: 21974, femaleVoters: 20986, literacy: 84, urbanPercent: 67.3, scPercent: 24.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 7, population: 65602, totalVoters: 35383, turnout2023: 76.32, maleVoters: 17920, femaleVoters: 17463, literacy: 88.2, urbanPercent: 67.3, scPercent: 17.2, stPercent: 0, areaSqKm: 5 },
  { acNo: 8, population: 58570, totalVoters: 36519, turnout2023: 79.99, maleVoters: 17767, femaleVoters: 18752, literacy: 86.1, urbanPercent: 68.3, scPercent: 15.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 9, population: 48955, totalVoters: 31410, turnout2023: 75.09, maleVoters: 15564, femaleVoters: 15846, literacy: 85.1, urbanPercent: 56.3, scPercent: 14.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 10, population: 53639, totalVoters: 38735, turnout2023: 76.78, maleVoters: 18961, femaleVoters: 19774, literacy: 84, urbanPercent: 72.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 11, population: 49372, totalVoters: 33225, turnout2023: 78.99, maleVoters: 16645, femaleVoters: 16580, literacy: 84, urbanPercent: 70.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 12, population: 65091, totalVoters: 35220, turnout2023: 84.47, maleVoters: 17540, femaleVoters: 17680, literacy: 86.1, urbanPercent: 73.3, scPercent: 15.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 13, population: 52950, totalVoters: 30383, turnout2023: 77.09, maleVoters: 15617, femaleVoters: 14766, literacy: 81.9, urbanPercent: 69.3, scPercent: 12, stPercent: 0, areaSqKm: 5 },
  { acNo: 14, population: 45602, totalVoters: 26783, turnout2023: 72.68, maleVoters: 13472, femaleVoters: 13311, literacy: 81.9, urbanPercent: 73.3, scPercent: 12, stPercent: 0, areaSqKm: 5 },
  { acNo: 15, population: 53261, totalVoters: 28335, turnout2023: 83.7, maleVoters: 14168, femaleVoters: 14167, literacy: 84, urbanPercent: 69.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 16, population: 60411, totalVoters: 25151, turnout2023: 80.54, maleVoters: 12739, femaleVoters: 12412, literacy: 81.9, urbanPercent: 72.3, scPercent: 12, stPercent: 0, areaSqKm: 5 },
  { acNo: 17, population: 53319, totalVoters: 34210, turnout2023: 81.33, maleVoters: 17447, femaleVoters: 16763, literacy: 86.6, urbanPercent: 68, scPercent: 15.7, stPercent: 0.1, areaSqKm: 5 },
  { acNo: 18, population: 46731, totalVoters: 36401, turnout2023: 81.14, maleVoters: 17909, femaleVoters: 18492, literacy: 84, urbanPercent: 70.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 19, population: 49977, totalVoters: 39871, turnout2023: 82.45, maleVoters: 20495, femaleVoters: 19376, literacy: 88.2, urbanPercent: 71.3, scPercent: 17.2, stPercent: 0, areaSqKm: 5 },
  { acNo: 20, population: 50341, totalVoters: 35152, turnout2023: 85.16, maleVoters: 17190, femaleVoters: 17962, literacy: 86.1, urbanPercent: 73.3, scPercent: 15.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 21, population: 49580, totalVoters: 35164, turnout2023: 87.37, maleVoters: 17405, femaleVoters: 17759, literacy: 88.2, urbanPercent: 69.3, scPercent: 29.4, stPercent: 0, areaSqKm: 5 },
  { acNo: 22, population: 55153, totalVoters: 32786, turnout2023: 85.77, maleVoters: 15951, femaleVoters: 16835, literacy: 89.2, urbanPercent: 73.3, scPercent: 18.1, stPercent: 0, areaSqKm: 5 },
  { acNo: 23, population: 56197, totalVoters: 30097, turnout2023: 87.9, maleVoters: 15153, femaleVoters: 14944, literacy: 90.3, urbanPercent: 70.3, scPercent: 31.8, stPercent: 0, areaSqKm: 5 },
  { acNo: 24, population: 42707, totalVoters: 32310, turnout2023: 82.94, maleVoters: 16269, femaleVoters: 16041, literacy: 84, urbanPercent: 68.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 25, population: 48536, totalVoters: 32034, turnout2023: 83.89, maleVoters: 15985, femaleVoters: 16049, literacy: 90.3, urbanPercent: 55.3, scPercent: 11.1, stPercent: 0, areaSqKm: 5 },
  { acNo: 26, population: 55332, totalVoters: 36594, turnout2023: 77.4, maleVoters: 18644, femaleVoters: 17950, literacy: 86.1, urbanPercent: 71.3, scPercent: 15.5, stPercent: 0, areaSqKm: 5 },
  { acNo: 27, population: 53319, totalVoters: 32568, turnout2023: 75.09, maleVoters: 16610, femaleVoters: 15958, literacy: 86.6, urbanPercent: 68, scPercent: 15.7, stPercent: 0.1, areaSqKm: 5 },
  { acNo: 28, population: 51833, totalVoters: 31928, turnout2023: 81.45, maleVoters: 15804, femaleVoters: 16124, literacy: 81.9, urbanPercent: 67.3, scPercent: 12, stPercent: 0, areaSqKm: 5 },
  { acNo: 29, population: 58689, totalVoters: 31830, turnout2023: 73.54, maleVoters: 15899, femaleVoters: 15931, literacy: 84, urbanPercent: 67.3, scPercent: 13.7, stPercent: 0, areaSqKm: 5 },
  { acNo: 30, population: 49345, totalVoters: 38383, turnout2023: 90.95, maleVoters: 19268, femaleVoters: 19115, literacy: 90.3, urbanPercent: 60.3, scPercent: 11.1, stPercent: 0, areaSqKm: 5 },
];

export function getPYConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return PY_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
