/**
 * Sikkim Assembly Constituencies — CURRENT assembly (2024) with 2019 history (32 seats)
 *
 * SOURCES:
 *   2019 result + numbering/district/reservation: TCPD "Lok Dhaba" (ECI). Official AC numbering.
 *   2024 winners (current): project data verified against ECI 2024 results.
 *   Auto-generated by scripts/build-current-seed.mjs — do not hand-edit.
 */

export interface SKConstituencySeed {
  acNo: number;
  name: string;
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2019: string;
  winnerName2019: string;
  winnerVotes2019: number;
  runnerUp2019: string;
  margin2019: number;
  winner2024: string;
  winnerName2024: string;
  currentParty: string;
}

export const SK_CONSTITUENCIES: SKConstituencySeed[] = [
  { acNo: 1, name: 'Yoksam-Tashiding', localName: 'योक्सम-ताशिदिङ', district: 'West', type: 'ST', winner2019: 'SKM', winnerName2019: 'Sangay Lepcha', winnerVotes2019: 5686, runnerUp2019: 'SDF', margin2019: 79, winner2024: 'SKM', winnerName2024: 'Tshering Thendup Bhutia', currentParty: 'SKM' },
  { acNo: 2, name: 'Yangthang', localName: 'याङ्थाङ', district: 'West', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Bhim Hang Limboo', winnerVotes2019: 5184, runnerUp2019: 'SDF', margin2019: 47, winner2024: 'SKM', winnerName2024: 'Bhim Hang Limboo', currentParty: 'SKM' },
  { acNo: 3, name: 'Maneybung-Dentam', localName: 'मानेबुङ-देन्ताम', district: 'West', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Narendra Kumar Subba', winnerVotes2019: 7134, runnerUp2019: 'SKM', margin2019: 1504, winner2024: 'SKM', winnerName2024: 'Sudesh Kumar Subba', currentParty: 'SKM' },
  { acNo: 4, name: 'Gyalshing-Barnyak', localName: 'ग्याल्सिङ-बर्नयाक', district: 'West', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Lok Nath Sharma', winnerVotes2019: 5862, runnerUp2019: 'SDF', margin2019: 1814, winner2024: 'SKM', winnerName2024: 'Lok Nath Sharma', currentParty: 'SKM' },
  { acNo: 5, name: 'Rinchenpong', localName: 'रिन्चेनपोङ', district: 'West', type: 'ST', winner2019: 'SDF', winnerName2019: 'Karma Sonam Lepcha', winnerVotes2019: 6582, runnerUp2019: 'SKM', margin2019: 1069, winner2024: 'SKM', winnerName2024: 'Erung Tenzing Lepcha', currentParty: 'SKM' },
  { acNo: 6, name: 'Daramdin', localName: 'दरामदिन', district: 'West', type: 'ST', winner2019: 'SKM', winnerName2019: 'Mingma Norbu Sherpa', winnerVotes2019: 6219, runnerUp2019: 'SDF', margin2019: 336, winner2024: 'SKM', winnerName2024: 'Mingma Norbu Sherpa', currentParty: 'SKM' },
  { acNo: 7, name: 'Soreong-Chakung', localName: 'सोरेङ-चाकुङ', district: 'West', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Aditya Golay (Tamang)', winnerVotes2019: 6580, runnerUp2019: 'SDF', margin2019: 208, winner2024: 'SKM', winnerName2024: 'P S Tamang', currentParty: 'SKM' },
  { acNo: 8, name: 'Salghari-Zoo', localName: 'सालघारी-जूम', district: 'West', type: 'SC', winner2019: 'SKM', winnerName2019: 'Sunita Gajmer', winnerVotes2019: 4400, runnerUp2019: 'SDF', margin2019: 93, winner2024: 'SKM', winnerName2024: 'Madan Cintury', currentParty: 'SKM' },
  { acNo: 9, name: 'Barfung', localName: 'बरफुङ', district: 'South', type: 'ST', winner2019: 'SDF', winnerName2019: 'Tashi Thendup Bhutia', winnerVotes2019: 5936, runnerUp2019: 'SKM', margin2019: 97, winner2024: 'SKM', winnerName2024: 'Rikshal Dorjee Bhutia', currentParty: 'SKM' },
  { acNo: 10, name: 'Poklok-Kamrang', district: 'South', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Pawan Chamling', winnerVotes2019: 7731, runnerUp2019: 'SKM', margin2019: 2899, winner2024: 'SKM', winnerName2024: 'Bhoj Raj Rai', currentParty: 'SKM' },
  { acNo: 11, name: 'Namchi-Singhithang', localName: 'नाम्ची-सिङ्गीथाङ', district: 'South', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Pawan Chamling', winnerVotes2019: 5054, runnerUp2019: 'SKM', margin2019: 377, winner2024: 'SKM', winnerName2024: 'Krishna Kumari Rai', currentParty: 'SKM' },
  { acNo: 12, name: 'Melli', localName: 'मेल्ली', district: 'South', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Farwanti Tamang', winnerVotes2019: 6354, runnerUp2019: 'SKM', margin2019: 865, winner2024: 'SKM', winnerName2024: 'Nar Bahadur Pradhan', currentParty: 'SKM' },
  { acNo: 13, name: 'Namthang-Rateypani', localName: 'नामथाङ-रातेपानी', district: 'South', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Sanjeet Kharel', winnerVotes2019: 6848, runnerUp2019: 'SDF', margin2019: 1305, winner2024: 'SKM', winnerName2024: 'Sanjeet Kharel', currentParty: 'SKM' },
  { acNo: 14, name: 'Temi-Namphing', localName: 'तेमी-नाम्फिङ', district: 'South', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Bedu Singh Panth', winnerVotes2019: 6084, runnerUp2019: 'SDF', margin2019: 770, winner2024: 'SKM', winnerName2024: 'Bedu Singh Panth', currentParty: 'SKM' },
  { acNo: 15, name: 'Rangang-Yangang', localName: 'राङ्गाङ-याङ्गाङ', district: 'South', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Raj Kumari Thapa', winnerVotes2019: 6146, runnerUp2019: 'SKM', margin2019: 1525, winner2024: 'SKM', winnerName2024: 'Raj Kumari Thapa', currentParty: 'SKM' },
  { acNo: 16, name: 'Tumen-Lingi', district: 'South', type: 'ST', winner2019: 'SDF', winnerName2019: 'Ugen T. Gyatso Bhutia', winnerVotes2019: 6615, runnerUp2019: 'SKM', margin2019: 320, winner2024: 'SKM', winnerName2024: 'Samdup Tshering Bhutia', currentParty: 'SKM' },
  { acNo: 17, name: 'Khamdong-Singtam', localName: 'खम्दोङ-सिङताम', district: 'East', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Mani Kumar Sharma', winnerVotes2019: 5347, runnerUp2019: 'SDF', margin2019: 873, winner2024: 'SKM', winnerName2024: 'Nar Bahadur Dahal', currentParty: 'SKM' },
  { acNo: 18, name: 'West Penda', localName: 'पश्चिम पेन्डाम', district: 'East', type: 'SC', winner2019: 'SKM', winnerName2019: 'L .B Das', winnerVotes2019: 5799, runnerUp2019: 'SDF', margin2019: 898, winner2024: 'SKM', winnerName2024: 'Lall Bahadur Das', currentParty: 'SKM' },
  { acNo: 19, name: 'Rhenock', localName: 'रिनक', district: 'East', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Bishnu Kumar Sharma', winnerVotes2019: 8039, runnerUp2019: 'SDF', margin2019: 3086, winner2024: 'SKM', winnerName2024: 'P S Tamang', currentParty: 'SKM' },
  { acNo: 20, name: 'Chujachen', localName: 'छुजाचेन', district: 'East', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Krishna Bahadur Rai', winnerVotes2019: 7266, runnerUp2019: 'SKM', margin2019: 1327, winner2024: 'SKM', winnerName2024: 'Puran Kr. Gurung', currentParty: 'SKM' },
  { acNo: 21, name: 'Gnathang-Machong', localName: 'नथाङ-माचोङ', district: 'East', type: 'ST', winner2019: 'SDF', winnerName2019: 'Dorjee Tshering Lepcha', winnerVotes2019: 6380, runnerUp2019: 'SKM', margin2019: 2920, winner2024: 'SKM', winnerName2024: 'Pamin Lepcha', currentParty: 'SKM' },
  { acNo: 22, name: 'Namcheybung', localName: 'नामचेबुङ', district: 'East', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Em Prasad Sharma', winnerVotes2019: 6141, runnerUp2019: 'SKM', margin2019: 971, winner2024: 'SKM', winnerName2024: 'Raju Basnet', currentParty: 'SKM' },
  { acNo: 23, name: 'Shyari', localName: 'श्यारी', district: 'East', type: 'ST', winner2019: 'SKM', winnerName2019: 'Kunga Nima Lepcha', winnerVotes2019: 6638, runnerUp2019: 'SDF', margin2019: 1356, winner2024: 'SDF', winnerName2024: 'Tenzing Norbu Lamtha', currentParty: 'SDF' },
  { acNo: 24, name: 'Martam-Rumtek', localName: 'मार्ताम-रुमटेक', district: 'East', type: 'ST', winner2019: 'SDF', winnerName2019: 'Dorjee Tshering Lepcha', winnerVotes2019: 6244, runnerUp2019: 'SKM', margin2019: 73, winner2024: 'SKM', winnerName2024: 'Sonam Tsh. Venchungpa', currentParty: 'SKM' },
  { acNo: 25, name: 'Upper Tadong', localName: 'माथिल्लो तादोङ', district: 'East', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Gay Tshering Dhungel', winnerVotes2019: 3844, runnerUp2019: 'SKM', margin2019: 416, winner2024: 'SKM', winnerName2024: 'G.T. Dhungel', currentParty: 'SKM' },
  { acNo: 26, name: 'Arithang', localName: 'अरिथाङ', district: 'East', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Arun Kumar Upreti', winnerVotes2019: 3150, runnerUp2019: 'IND', margin2019: 474, winner2024: 'SKM', winnerName2024: 'Arun Kumar Upreti', currentParty: 'SKM' },
  { acNo: 27, name: 'Gangtok', localName: 'गान्तोक', district: 'East', type: 'ST', winner2019: 'SKM', winnerName2019: 'Kunga Nima Lepcha', winnerVotes2019: 3838, runnerUp2019: 'SDF', margin2019: 888, winner2024: 'SKM', winnerName2024: 'Delay Namgyal Barfungpa', currentParty: 'SKM' },
  { acNo: 28, name: 'Upper Burtuk', localName: 'माथिल्लो बुर्तुक', district: 'East', type: 'GEN', winner2019: 'SDF', winnerName2019: 'Dilli Ram Thapa', winnerVotes2019: 6107, runnerUp2019: 'SKM', margin2019: 757, winner2024: 'SKM', winnerName2024: 'Kala Rai', currentParty: 'SKM' },
  { acNo: 29, name: 'Kabi Lungchuk', district: 'North', type: 'ST', winner2019: 'SKM', winnerName2019: 'Karma Loday Bhutia', winnerVotes2019: 5705, runnerUp2019: 'SDF', margin2019: 1437, winner2024: 'SKM', winnerName2024: 'Thenlay Tshering Bhutia', currentParty: 'SKM' },
  { acNo: 30, name: 'Djongu', localName: 'जोङु', district: 'North', type: 'ST', winner2019: 'SDF', winnerName2019: 'Pintso Namgyal Lepcha', winnerVotes2019: 5613, runnerUp2019: 'SKM', margin2019: 3001, winner2024: 'SKM', winnerName2024: 'Pintso Namgyal Lepcha', currentParty: 'SKM' },
  { acNo: 31, name: 'Lachen Mangan', localName: 'लाचेन-मङ्गन', district: 'North', type: 'ST', winner2019: 'SKM', winnerName2019: 'Samdup Lepcha', winnerVotes2019: 3615, runnerUp2019: 'SDF', margin2019: 584, winner2024: 'SKM', winnerName2024: 'Samdup Lepcha', currentParty: 'SKM' },
  { acNo: 32, name: 'Sangha', localName: 'सङ्घ', district: 'Sangha', type: 'GEN', winner2019: 'SKM', winnerName2019: 'Sonam Lama', winnerVotes2019: 1488, runnerUp2019: 'SDF', margin2019: 630, winner2024: 'SKM', winnerName2024: 'Sonam Lama', currentParty: 'SKM' },
];

export function getSKConstituency(acNo: number): SKConstituencySeed | undefined {
  return SK_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
