/**
 * SK — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface SKElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const SK_ELECTION_HISTORY: SKElectionResult[] = [
  {
    year: 2024,
    partyResults: {
      'SKM': 31,
      'SDF': 1,
    },
    totalSeats: 32,
    rulingParty: 'SKM',
  },
  {
    year: 2019,
    partyResults: {
      'SKM': 17,
      'SDF': 15,
    },
    totalSeats: 32,
    rulingParty: 'SKM',
  },
];

export function getSKElectionByYear(year: number) {
  return SK_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getSKPartyTrend(party: string) {
  return SK_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
