/**
 * SK Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2019 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const SK_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 21683, totalVoters: 13808, turnout2023: 84.88, maleVoters: 7042, femaleVoters: 6766, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 2, population: 16673, totalVoters: 12952, turnout2023: 82.58, maleVoters: 6612, femaleVoters: 6340, literacy: 82.6, urbanPercent: 32.7, scPercent: 13.6, stPercent: 46.1, areaSqKm: 176 },
  { acNo: 3, population: 21683, totalVoters: 15174, turnout2023: 85.25, maleVoters: 7739, femaleVoters: 7435, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 4, population: 18830, totalVoters: 12406, turnout2023: 82.81, maleVoters: 6215, femaleVoters: 6191, literacy: 85.8, urbanPercent: 43.7, scPercent: 17.9, stPercent: 41.7, areaSqKm: 193 },
  { acNo: 5, population: 25835, totalVoters: 14756, turnout2023: 85.38, maleVoters: 7341, femaleVoters: 7415, literacy: 77.4, urbanPercent: 21.8, scPercent: 3.7, stPercent: 31.7, areaSqKm: 229 },
  { acNo: 6, population: 22365, totalVoters: 15269, turnout2023: 82.99, maleVoters: 7650, femaleVoters: 7619, literacy: 81.6, urbanPercent: 30.9, scPercent: 9.4, stPercent: 36.1, areaSqKm: 191 },
  { acNo: 7, population: 21683, totalVoters: 15589, turnout2023: 84.29, maleVoters: 7950, femaleVoters: 7639, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 8, population: 21683, totalVoters: 10942, turnout2023: 81.62, maleVoters: 5580, femaleVoters: 5362, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 9, population: 24464, totalVoters: 14875, turnout2023: 81.23, maleVoters: 7378, femaleVoters: 7497, literacy: 76.4, urbanPercent: 21.8, scPercent: 2.3, stPercent: 36.1, areaSqKm: 190 },
  { acNo: 10, population: 21683, totalVoters: 15595, turnout2023: 83.89, maleVoters: 7953, femaleVoters: 7642, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 11, population: 15150, totalVoters: 12689, turnout2023: 79.17, maleVoters: 6224, femaleVoters: 6465, literacy: 88.9, urbanPercent: 20, scPercent: 0, stPercent: 32.8, areaSqKm: 100 },
  { acNo: 12, population: 16595, totalVoters: 15479, turnout2023: 81.69, maleVoters: 7600, femaleVoters: 7879, literacy: 83.7, urbanPercent: 23.7, scPercent: 0, stPercent: 32.8, areaSqKm: 105 },
  { acNo: 13, population: 17173, totalVoters: 15451, turnout2023: 82.71, maleVoters: 7795, femaleVoters: 7656, literacy: 88.9, urbanPercent: 18.2, scPercent: 0, stPercent: 32.8, areaSqKm: 100 },
  { acNo: 14, population: 14290, totalVoters: 14225, turnout2023: 82.73, maleVoters: 7326, femaleVoters: 6899, literacy: 83.7, urbanPercent: 12.7, scPercent: 0, stPercent: 32.8, areaSqKm: 100 },
  { acNo: 15, population: 19196, totalVoters: 13919, turnout2023: 82.58, maleVoters: 6820, femaleVoters: 7099, literacy: 84.7, urbanPercent: 16.4, scPercent: 0, stPercent: 32.8, areaSqKm: 96 },
  { acNo: 16, population: 21683, totalVoters: 15888, turnout2023: 83.46, maleVoters: 8103, femaleVoters: 7785, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 17, population: 28360, totalVoters: 13067, turnout2023: 81.2, maleVoters: 6664, femaleVoters: 6403, literacy: 74.3, urbanPercent: 34.6, scPercent: 0, stPercent: 31.7, areaSqKm: 180 },
  { acNo: 18, population: 21683, totalVoters: 14984, turnout2023: 77.97, maleVoters: 7642, femaleVoters: 7342, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 19, population: 16902, totalVoters: 17396, turnout2023: 81.88, maleVoters: 8620, femaleVoters: 8776, literacy: 82.6, urbanPercent: 1.8, scPercent: 2.3, stPercent: 26.2, areaSqKm: 5 },
  { acNo: 20, population: 14509, totalVoters: 17776, turnout2023: 79.96, maleVoters: 8799, femaleVoters: 8977, literacy: 77.4, urbanPercent: 7.3, scPercent: 0, stPercent: 27.3, areaSqKm: 5 },
  { acNo: 21, population: 23256, totalVoters: 12048, turnout2023: 84.1, maleVoters: 6115, femaleVoters: 5933, literacy: 77.4, urbanPercent: 25.5, scPercent: 3.7, stPercent: 36.1, areaSqKm: 227 },
  { acNo: 22, population: 19908, totalVoters: 15095, turnout2023: 82.15, maleVoters: 7427, femaleVoters: 7668, literacy: 79.5, urbanPercent: 7.3, scPercent: 0, stPercent: 26.2, areaSqKm: 5 },
  { acNo: 23, population: 22600, totalVoters: 15732, turnout2023: 77.69, maleVoters: 7732, femaleVoters: 8000, literacy: 81.6, urbanPercent: 25.5, scPercent: 9.4, stPercent: 31.7, areaSqKm: 191 },
  { acNo: 24, population: 29267, totalVoters: 16975, turnout2023: 81.02, maleVoters: 8716, femaleVoters: 8259, literacy: 76.4, urbanPercent: 21.8, scPercent: 2.3, stPercent: 31.7, areaSqKm: 236 },
  { acNo: 25, population: 24133, totalVoters: 10334, turnout2023: 72.92, maleVoters: 5239, femaleVoters: 5095, literacy: 78.5, urbanPercent: 43.7, scPercent: 3.7, stPercent: 28.4, areaSqKm: 179 },
  { acNo: 26, population: 28823, totalVoters: 11408, turnout2023: 69, maleVoters: 5761, femaleVoters: 5647, literacy: 82.6, urbanPercent: 36.4, scPercent: 9.4, stPercent: 31.7, areaSqKm: 185 },
  { acNo: 27, population: 28598, totalVoters: 11649, turnout2023: 63.76, maleVoters: 5871, femaleVoters: 5778, literacy: 81.6, urbanPercent: 27.3, scPercent: 9.4, stPercent: 36.1, areaSqKm: 204 },
  { acNo: 28, population: 29576, totalVoters: 15231, turnout2023: 77.45, maleVoters: 7600, femaleVoters: 7631, literacy: 74.3, urbanPercent: 32.7, scPercent: 0, stPercent: 28.4, areaSqKm: 178 },
  { acNo: 29, population: 21683, totalVoters: 12661, turnout2023: 81.83, maleVoters: 6457, femaleVoters: 6204, literacy: 82.2, urbanPercent: 25, scPercent: 4.6, stPercent: 33.8, areaSqKm: 153 },
  { acNo: 30, population: 25482, totalVoters: 9595, turnout2023: 88.41, maleVoters: 4821, femaleVoters: 4774, literacy: 81.6, urbanPercent: 29.1, scPercent: 9.4, stPercent: 36.1, areaSqKm: 226 },
  { acNo: 31, population: 23035, totalVoters: 7867, turnout2023: 85.41, maleVoters: 4000, femaleVoters: 3867, literacy: 80.6, urbanPercent: 25.5, scPercent: 8, stPercent: 31.7, areaSqKm: 234 },
  { acNo: 32, population: 21227, totalVoters: 3293, turnout2023: 72.15, maleVoters: 1669, femaleVoters: 1624, literacy: 84.7, urbanPercent: 40, scPercent: 2.3, stPercent: 37.2, areaSqKm: 176 },
];

export function getSKConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return SK_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
