/**
 * TR — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface TRElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const TR_ELECTION_HISTORY: TRElectionResult[] = [
  {
    year: 2023,
    partyResults: {
      'BJP': 32,
      'TMP': 13,
      'CPIM': 11,
      'INC': 3,
      'IPFT': 1,
    },
    totalSeats: 60,
    rulingParty: 'BJP',
  },
];

export function getTRElectionByYear(year: number) {
  return TR_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getTRPartyTrend(party: string) {
  return TR_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
