/**
 * Tripura Assembly Constituencies — 2023 General Election (60 seats)
 *
 * SOURCE: TCPD "Lok Dhaba" (Trivedi Centre for Political Data, Ashoka University),
 *         Tripura_AE dataset — ECI-sourced constituency results. Uses the
 *         official ECI AC numbering (1-60). Winner/runner-up parties,
 *         vote counts, and margins are the ECI 2023 results as compiled by TCPD.
 *         Reservation (GEN/SC/ST) and district are from the same dataset.
 *         Auto-generated by scripts/build-tcpd-seed.mjs — do not hand-edit.
 *
 * PARTY TALLY 2023: BJP 32 | TMP 13 | CPIM 11 | INC 3 | IPFT 1 = 60
 */

export interface TRConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in local script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2023: string;
  winnerName2023: string;
  winnerVotes2023: number;
  runnerUp2023: string;
  margin2023: number;
  currentParty: string;
}

export const TR_CONSTITUENCIES: TRConstituencySeed[] = [
  { acNo: 1, name: 'Simna', localName: 'সিমনা', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Brishaketu Debbarma', winnerVotes2023: 22757, runnerUp2023: 'CPIM', margin2023: 16946, currentParty: 'TMP' },
  { acNo: 2, name: 'Mohanpur', localName: 'মোহনপুর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Ratan Lal Nath', winnerVotes2023: 19663, runnerUp2023: 'TMP', margin2023: 7385, currentParty: 'BJP' },
  { acNo: 3, name: 'Bamutia', district: 'West Tripura', type: 'SC', winner2023: 'CPIM', winnerName2023: 'Nayan Sarkar', winnerVotes2023: 20119, runnerUp2023: 'BJP', margin2023: 2026, currentParty: 'CPIM' },
  { acNo: 4, name: 'Barjala', localName: 'বড়জলা', district: 'West Tripura', type: 'SC', winner2023: 'CPIM', winnerName2023: 'Sudip Sarkar', winnerVotes2023: 21486, runnerUp2023: 'BJP', margin2023: 1789, currentParty: 'CPIM' },
  { acNo: 5, name: 'Khayerpur', localName: 'খায়েরপুর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Ratan Chakraborty', winnerVotes2023: 22453, runnerUp2023: 'CPIM', margin2023: 4110, currentParty: 'BJP' },
  { acNo: 6, name: 'Agartala', localName: 'আগরতলা', district: 'West Tripura', type: 'GEN', winner2023: 'INC', winnerName2023: 'Sudip Roy Barman', winnerVotes2023: 26435, runnerUp2023: 'BJP', margin2023: 8162, currentParty: 'INC' },
  { acNo: 7, name: 'Ramnagar', localName: 'রামনগর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Surajit Datta', winnerVotes2023: 17455, runnerUp2023: 'IND', margin2023: 897, currentParty: 'BJP' },
  { acNo: 8, name: 'Town Bordowali', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Manik Saha', winnerVotes2023: 19586, runnerUp2023: 'INC', margin2023: 1257, currentParty: 'BJP' },
  { acNo: 9, name: 'Banamalipur', localName: 'বনমালীপুর', district: 'West Tripura', type: 'GEN', winner2023: 'INC', winnerName2023: 'Gopal Chandra Roy', winnerVotes2023: 17128, runnerUp2023: 'BJP', margin2023: 1369, currentParty: 'INC' },
  { acNo: 10, name: 'Majlishpur', localName: 'মজলিশপুর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Sushanta Chowdhury', winnerVotes2023: 21349, runnerUp2023: 'CPIM', margin2023: 5172, currentParty: 'BJP' },
  { acNo: 11, name: 'Mandaibazar', localName: 'মান্দাইবাজার', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Swapna Debbarma', winnerVotes2023: 28726, runnerUp2023: 'CPIM', margin2023: 21649, currentParty: 'TMP' },
  { acNo: 12, name: 'Takarjala', localName: 'টাকারজলা', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Biswajit Kalai', winnerVotes2023: 34717, runnerUp2023: 'IPFT', margin2023: 32455, currentParty: 'TMP' },
  { acNo: 13, name: 'Pratapgarh', localName: 'প্রতাপগড়', district: 'West Tripura', type: 'SC', winner2023: 'CPIM', winnerName2023: 'Ramu Das', winnerVotes2023: 26422, runnerUp2023: 'BJP', margin2023: 2086, currentParty: 'CPIM' },
  { acNo: 14, name: 'Badharghat', localName: 'বাধারঘাট', district: 'West Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Mina Rani Sarkar', winnerVotes2023: 27427, runnerUp2023: 'AIFB', margin2023: 1289, currentParty: 'BJP' },
  { acNo: 15, name: 'Kamalasagar', localName: 'কমলাসাগর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Antara Sarkar Deb', winnerVotes2023: 19052, runnerUp2023: 'CPIM', margin2023: 1744, currentParty: 'BJP' },
  { acNo: 16, name: 'Bishalgarh', localName: 'বিশালগড়', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Sushanta Deb', winnerVotes2023: 22314, runnerUp2023: 'CPIM', margin2023: 1326, currentParty: 'BJP' },
  { acNo: 17, name: 'Golaghati', localName: 'গোলাঘাটি', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Manab Debbarma', winnerVotes2023: 19800, runnerUp2023: 'BJP', margin2023: 9198, currentParty: 'TMP' },
  { acNo: 18, name: 'Suryamaninagar', localName: 'সূর্যমণিনগর', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Ram Prasad Paul', winnerVotes2023: 24991, runnerUp2023: 'INC', margin2023: 1908, currentParty: 'BJP' },
  { acNo: 19, name: 'Charilam', localName: 'চড়িলাম', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Subodh Deb Barma', winnerVotes2023: 13657, runnerUp2023: 'BJP', margin2023: 858, currentParty: 'TMP' },
  { acNo: 20, name: 'Boxanagar', localName: 'বক্সনগর', district: 'West Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Samsul Haque', winnerVotes2023: 19404, runnerUp2023: 'BJP', margin2023: 4849, currentParty: 'BJP' },
  { acNo: 21, name: 'Nalchar', localName: 'নলচর', district: 'West Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Kishor Barman', winnerVotes2023: 20836, runnerUp2023: 'CPIM', margin2023: 2384, currentParty: 'BJP' },
  { acNo: 22, name: 'Sonamura', localName: 'সোনামুড়া', district: 'West Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Shyamal Chakraborty', winnerVotes2023: 20039, runnerUp2023: 'BJP', margin2023: 2415, currentParty: 'CPIM' },
  { acNo: 23, name: 'Dhanpur', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Pratima Bhoumik', winnerVotes2023: 19148, runnerUp2023: 'CPIM', margin2023: 3500, currentParty: 'BJP' },
  { acNo: 24, name: 'Ramchandraghat', localName: 'রামচন্দ্রঘাট', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Ranjit Debbarma', winnerVotes2023: 23143, runnerUp2023: 'CPIM', margin2023: 16202, currentParty: 'TMP' },
  { acNo: 25, name: 'Khowai', district: 'West Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Nirmal Biswas', winnerVotes2023: 19696, runnerUp2023: 'BJP', margin2023: 1040, currentParty: 'CPIM' },
  { acNo: 26, name: 'Asharambari', localName: 'আশারামবাড়ি', district: 'West Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Animesh Debbarma', winnerVotes2023: 23838, runnerUp2023: 'IPFT', margin2023: 18328, currentParty: 'TMP' },
  { acNo: 27, name: 'Kalyanpur-Pramodenagar', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Pinaki Das Chowdhury', winnerVotes2023: 17903, runnerUp2023: 'TMP', margin2023: 6613, currentParty: 'BJP' },
  { acNo: 28, name: 'Teliamura', localName: 'তেলিয়ামুড়া', district: 'West Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Kalyani Saha Roy', winnerVotes2023: 16755, runnerUp2023: 'INC', margin2023: 4152, currentParty: 'BJP' },
  { acNo: 29, name: 'Krishnapur', localName: 'কৃষ্ণপুর', district: 'West Tripura', type: 'ST', winner2023: 'BJP', winnerName2023: 'Bikash Debbarma', winnerVotes2023: 13800, runnerUp2023: 'TMP', margin2023: 2638, currentParty: 'BJP' },
  { acNo: 30, name: 'Bagma', localName: 'বাগমা', district: 'South Tripura', type: 'ST', winner2023: 'BJP', winnerName2023: 'Ram Pada Jamatia', winnerVotes2023: 19482, runnerUp2023: 'TMP', margin2023: 2083, currentParty: 'BJP' },
  { acNo: 31, name: 'Radhakishorepur', district: 'South Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Pranajit Singha Roy', winnerVotes2023: 24421, runnerUp2023: 'RSP', margin2023: 7414, currentParty: 'BJP' },
  { acNo: 32, name: 'Matarbari', localName: 'মাতারবাড়ি', district: 'South Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Abhishek Debroy', winnerVotes2023: 25494, runnerUp2023: 'INC', margin2023: 9041, currentParty: 'BJP' },
  { acNo: 33, name: 'Kakraban-Salgarah', district: 'South Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Jitendra Majumder', winnerVotes2023: 23625, runnerUp2023: 'CPIM', margin2023: 5051, currentParty: 'BJP' },
  { acNo: 34, name: 'Rajnagar', localName: 'রাজনগর', district: 'South Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Swapna Majumder', winnerVotes2023: 20849, runnerUp2023: 'CPIM', margin2023: 1335, currentParty: 'BJP' },
  { acNo: 35, name: 'Belonia', localName: 'বিলোনিয়া', district: 'South Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Dipankar Sen', winnerVotes2023: 20016, runnerUp2023: 'BJP', margin2023: 403, currentParty: 'CPIM' },
  { acNo: 36, name: 'Santirbazar', district: 'South Tripura', type: 'ST', winner2023: 'BJP', winnerName2023: 'Pramod Reang', winnerVotes2023: 18709, runnerUp2023: 'TMP', margin2023: 4094, currentParty: 'BJP' },
  { acNo: 37, name: 'Hrishyamukh', localName: 'ঋষ্যমুখ', district: 'South Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Asoke Ch. Mitra', winnerVotes2023: 19986, runnerUp2023: 'BJP', margin2023: 1418, currentParty: 'CPIM' },
  { acNo: 38, name: 'Jolaibari', localName: 'জোলাইবাড়ি', district: 'South Tripura', type: 'ST', winner2023: 'IPFT', winnerName2023: 'Sukla Charan Noatia', winnerVotes2023: 17621, runnerUp2023: 'CPIM', margin2023: 375, currentParty: 'IPFT' },
  { acNo: 39, name: 'Manu', localName: 'মনু', district: 'South Tripura', type: 'ST', winner2023: 'BJP', winnerName2023: 'Mailafru Mog', winnerVotes2023: 15469, runnerUp2023: 'CPIM', margin2023: 547, currentParty: 'BJP' },
  { acNo: 40, name: 'Sabroom', localName: 'সাব্রুম', district: 'South Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Jitendra Chaudhury', winnerVotes2023: 21801, runnerUp2023: 'BJP', margin2023: 396, currentParty: 'CPIM' },
  { acNo: 41, name: 'Ampinagar', localName: 'অম্পিনগর', district: 'South Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Pathan Lal Jamatia', winnerVotes2023: 21525, runnerUp2023: 'BJP', margin2023: 12186, currentParty: 'TMP' },
  { acNo: 42, name: 'Amarpur', localName: 'অমরপুর', district: 'South Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Ranjit Das', winnerVotes2023: 17989, runnerUp2023: 'CPIM', margin2023: 4594, currentParty: 'BJP' },
  { acNo: 43, name: 'Karbook', localName: 'করবুক', district: 'South Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Sanjoy Manik Tripura', winnerVotes2023: 16647, runnerUp2023: 'BJP', margin2023: 4447, currentParty: 'TMP' },
  { acNo: 44, name: 'Raima Valley', localName: 'রাইমা ভ্যালি', district: 'Dhalai', type: 'ST', winner2023: 'TMP', winnerName2023: 'Nandita Debbarma(Reang)', winnerVotes2023: 19269, runnerUp2023: 'BJP', margin2023: 3442, currentParty: 'TMP' },
  { acNo: 45, name: 'Kamalpur', localName: 'কামালপুর', district: 'Dhalai', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Manoj Kanti Deb', winnerVotes2023: 18287, runnerUp2023: 'INC', margin2023: 5260, currentParty: 'BJP' },
  { acNo: 46, name: 'Surma', localName: 'সুরমা', district: 'Dhalai', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Swapna Das Paul', winnerVotes2023: 17313, runnerUp2023: 'CPIM', margin2023: 4838, currentParty: 'BJP' },
  { acNo: 47, name: 'Ambassa', localName: 'আমবাসা', district: 'Dhalai', type: 'ST', winner2023: 'TMP', winnerName2023: 'Chitta Ranjan Debbarma', winnerVotes2023: 15317, runnerUp2023: 'BJP', margin2023: 493, currentParty: 'TMP' },
  { acNo: 48, name: 'Karamchhara', district: 'Dhalai', type: 'ST', winner2023: 'TMP', winnerName2023: 'Paul Dangshu', winnerVotes2023: 20496, runnerUp2023: 'BJP', margin2023: 10595, currentParty: 'TMP' },
  { acNo: 49, name: 'Chhawmanu', district: 'Dhalai', type: 'ST', winner2023: 'BJP', winnerName2023: 'Sambhu Lal Chakma', winnerVotes2023: 16644, runnerUp2023: 'TMP', margin2023: 2899, currentParty: 'BJP' },
  { acNo: 50, name: 'Pabiachhara', district: 'North Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Bhagaban Chandra Das', winnerVotes2023: 19542, runnerUp2023: 'INC', margin2023: 408, currentParty: 'BJP' },
  { acNo: 51, name: 'Fatikroy', localName: 'ফটিকরায়', district: 'North Tripura', type: 'SC', winner2023: 'BJP', winnerName2023: 'Sudhangshu Das', winnerVotes2023: 19570, runnerUp2023: 'CPIM', margin2023: 5112, currentParty: 'BJP' },
  { acNo: 52, name: 'Chandipur', localName: 'চণ্ডীপুর', district: 'North Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Tinku Roy', winnerVotes2023: 17395, runnerUp2023: 'CPIM', margin2023: 577, currentParty: 'BJP' },
  { acNo: 53, name: 'Kailasahar', district: 'North Tripura', type: 'GEN', winner2023: 'INC', winnerName2023: 'Birajit Sinha', winnerVotes2023: 25300, runnerUp2023: 'BJP', margin2023: 9686, currentParty: 'INC' },
  { acNo: 54, name: 'Kadamtala - Kurti', localName: 'কদমতলা-কুর্তি', district: 'North Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Islam Uddin', winnerVotes2023: 20012, runnerUp2023: 'BJP', margin2023: 1892, currentParty: 'CPIM' },
  { acNo: 55, name: 'Bagbassa', localName: 'বাগবাসা', district: 'North Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Jadab Lal Debnath', winnerVotes2023: 18905, runnerUp2023: 'CPIM', margin2023: 1461, currentParty: 'BJP' },
  { acNo: 56, name: 'Dharmanagar', localName: 'ধর্মনগর', district: 'North Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Biswa Bandhu Sen', winnerVotes2023: 18684, runnerUp2023: 'INC', margin2023: 1098, currentParty: 'BJP' },
  { acNo: 57, name: 'Jubarajnagar', localName: 'যুবরাজনগর', district: 'North Tripura', type: 'GEN', winner2023: 'CPIM', winnerName2023: 'Sailendra Chandra Nath', winnerVotes2023: 19386, runnerUp2023: 'BJP', margin2023: 296, currentParty: 'CPIM' },
  { acNo: 58, name: 'Panisagar', district: 'North Tripura', type: 'GEN', winner2023: 'BJP', winnerName2023: 'Binay Bhushan Das', winnerVotes2023: 15745, runnerUp2023: 'CPIM', margin2023: 2498, currentParty: 'BJP' },
  { acNo: 59, name: 'Pencharthal', district: 'North Tripura', type: 'ST', winner2023: 'BJP', winnerName2023: 'Santana Chakma', winnerVotes2023: 17781, runnerUp2023: 'CPIM', margin2023: 7973, currentParty: 'BJP' },
  { acNo: 60, name: 'Kanchanpur', localName: 'কাঞ্চনপুর', district: 'North Tripura', type: 'ST', winner2023: 'TMP', winnerName2023: 'Philip Kumar Reang', winnerVotes2023: 15413, runnerUp2023: 'CPIM', margin2023: 4891, currentParty: 'TMP' },
];

export function getTRConstituency(acNo: number): TRConstituencySeed | undefined {
  return TR_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
