/**
 * TR Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2023 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const TR_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 66980, totalVoters: 39362, turnout2023: 89.1, maleVoters: 20094, femaleVoters: 19268, literacy: 91.1, urbanPercent: 13.4, scPercent: 8.3, stPercent: 30, areaSqKm: 51 },
  { acNo: 2, population: 72365, totalVoters: 48071, turnout2023: 90.21, maleVoters: 24252, femaleVoters: 23819, literacy: 85.9, urbanPercent: 35.1, scPercent: 11.1, stPercent: 26.4, areaSqKm: 166 },
  { acNo: 3, population: 77669, totalVoters: 47896, turnout2023: 90.54, maleVoters: 24427, femaleVoters: 23469, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 4, population: 76382, totalVoters: 47931, turnout2023: 88.01, maleVoters: 24254, femaleVoters: 23677, literacy: 89, urbanPercent: 19.2, scPercent: 21.5, stPercent: 32.4, areaSqKm: 123 },
  { acNo: 5, population: 75788, totalVoters: 52426, turnout2023: 90.21, maleVoters: 25532, femaleVoters: 26894, literacy: 92.2, urbanPercent: 43.8, scPercent: 16.8, stPercent: 26.4, areaSqKm: 162 },
  { acNo: 6, population: 71249, totalVoters: 54496, turnout2023: 84.58, maleVoters: 27575, femaleVoters: 26921, literacy: 84.9, urbanPercent: 19.2, scPercent: 17.7, stPercent: 43.4, areaSqKm: 130 },
  { acNo: 7, population: 75171, totalVoters: 47240, turnout2023: 79.98, maleVoters: 24139, femaleVoters: 23101, literacy: 95.3, urbanPercent: 6.1, scPercent: 12, stPercent: 17.8, areaSqKm: 53 },
  { acNo: 8, population: 77669, totalVoters: 49225, turnout2023: 79.94, maleVoters: 25105, femaleVoters: 24120, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 9, population: 70301, totalVoters: 42912, turnout2023: 80.51, maleVoters: 21949, femaleVoters: 20963, literacy: 87, urbanPercent: 27.9, scPercent: 19.6, stPercent: 28.1, areaSqKm: 113 },
  { acNo: 10, population: 83897, totalVoters: 50412, turnout2023: 90.5, maleVoters: 25358, femaleVoters: 25054, literacy: 90.1, urbanPercent: 40.9, scPercent: 26.4, stPercent: 26.4, areaSqKm: 164 },
  { acNo: 11, population: 73930, totalVoters: 48858, turnout2023: 88.61, maleVoters: 24966, femaleVoters: 23892, literacy: 89, urbanPercent: 39.5, scPercent: 25.1, stPercent: 26.4, areaSqKm: 164 },
  { acNo: 12, population: 92096, totalVoters: 45712, turnout2023: 87.49, maleVoters: 22948, femaleVoters: 22764, literacy: 89, urbanPercent: 29.3, scPercent: 15.8, stPercent: 21.3, areaSqKm: 204 },
  { acNo: 13, population: 67633, totalVoters: 58839, turnout2023: 90.51, maleVoters: 29596, femaleVoters: 29243, literacy: 84.9, urbanPercent: 36.6, scPercent: 10.2, stPercent: 41.2, areaSqKm: 201 },
  { acNo: 14, population: 82570, totalVoters: 63905, turnout2023: 87.7, maleVoters: 32783, femaleVoters: 31122, literacy: 89, urbanPercent: 22.1, scPercent: 21.5, stPercent: 28.1, areaSqKm: 146 },
  { acNo: 15, population: 79929, totalVoters: 44508, turnout2023: 90.32, maleVoters: 22655, femaleVoters: 21853, literacy: 88, urbanPercent: 23.5, scPercent: 20.5, stPercent: 49, areaSqKm: 133 },
  { acNo: 16, population: 87907, totalVoters: 51135, turnout2023: 89.93, maleVoters: 26309, femaleVoters: 24826, literacy: 85.9, urbanPercent: 26.4, scPercent: 18.6, stPercent: 49, areaSqKm: 138 },
  { acNo: 17, population: 77611, totalVoters: 43404, turnout2023: 89.81, maleVoters: 21680, femaleVoters: 21724, literacy: 87, urbanPercent: 26.4, scPercent: 19.6, stPercent: 49, areaSqKm: 134 },
  { acNo: 18, population: 82323, totalVoters: 55325, turnout2023: 90.49, maleVoters: 27331, femaleVoters: 27994, literacy: 90.1, urbanPercent: 30.8, scPercent: 29.1, stPercent: 21.3, areaSqKm: 203 },
  { acNo: 19, population: 67436, totalVoters: 40949, turnout2023: 89.33, maleVoters: 21007, femaleVoters: 19942, literacy: 83.9, urbanPercent: 22.1, scPercent: 16.8, stPercent: 32.4, areaSqKm: 139 },
  { acNo: 20, population: 89150, totalVoters: 43909, turnout2023: 87.78, maleVoters: 22152, femaleVoters: 21757, literacy: 87, urbanPercent: 25, scPercent: 33, stPercent: 32.4, areaSqKm: 125 },
  { acNo: 21, population: 75468, totalVoters: 46040, turnout2023: 90.6, maleVoters: 23595, femaleVoters: 22445, literacy: 84.9, urbanPercent: 43.8, scPercent: 10.2, stPercent: 41.2, areaSqKm: 167 },
  { acNo: 22, population: 69465, totalVoters: 45599, turnout2023: 87.07, maleVoters: 22525, femaleVoters: 23074, literacy: 91.1, urbanPercent: 11.9, scPercent: 8.3, stPercent: 30, areaSqKm: 51 },
  { acNo: 23, population: 77669, totalVoters: 51168, turnout2023: 88.57, maleVoters: 26096, femaleVoters: 25072, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 24, population: 71297, totalVoters: 42555, turnout2023: 89.34, maleVoters: 21064, femaleVoters: 21491, literacy: 99, urbanPercent: 7.5, scPercent: 15.8, stPercent: 17.8, areaSqKm: 56 },
  { acNo: 25, population: 77669, totalVoters: 43436, turnout2023: 91.19, maleVoters: 22152, femaleVoters: 21284, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 26, population: 83270, totalVoters: 40589, turnout2023: 88.24, maleVoters: 19990, femaleVoters: 20599, literacy: 88, urbanPercent: 23.5, scPercent: 20.5, stPercent: 28.1, areaSqKm: 125 },
  { acNo: 27, population: 77669, totalVoters: 45741, turnout2023: 89.8, maleVoters: 23328, femaleVoters: 22413, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 28, population: 78848, totalVoters: 45836, turnout2023: 86.83, maleVoters: 23377, femaleVoters: 22459, literacy: 88, urbanPercent: 27.9, scPercent: 14.9, stPercent: 21.3, areaSqKm: 204 },
  { acNo: 29, population: 84855, totalVoters: 38814, turnout2023: 88.95, maleVoters: 19212, femaleVoters: 19602, literacy: 91.1, urbanPercent: 42.4, scPercent: 15.8, stPercent: 26.4, areaSqKm: 163 },
  { acNo: 30, population: 86323, totalVoters: 56617, turnout2023: 88.82, maleVoters: 27798, femaleVoters: 28819, literacy: 85.9, urbanPercent: 19.2, scPercent: 18.6, stPercent: 28.1, areaSqKm: 126 },
  { acNo: 31, population: 77669, totalVoters: 50020, turnout2023: 87.07, maleVoters: 25510, femaleVoters: 24510, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 32, population: 78098, totalVoters: 56004, turnout2023: 89.16, maleVoters: 27807, femaleVoters: 28197, literacy: 87, urbanPercent: 36.6, scPercent: 12, stPercent: 41.2, areaSqKm: 165 },
  { acNo: 33, population: 77669, totalVoters: 55372, turnout2023: 88.58, maleVoters: 28240, femaleVoters: 27132, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 34, population: 81730, totalVoters: 48794, turnout2023: 88.88, maleVoters: 24958, femaleVoters: 23836, literacy: 99, urbanPercent: 9, scPercent: 15.8, stPercent: 30, areaSqKm: 56 },
  { acNo: 35, population: 78559, totalVoters: 45926, turnout2023: 90.29, maleVoters: 22780, femaleVoters: 23146, literacy: 80.7, urbanPercent: 27.9, scPercent: 13.9, stPercent: 49, areaSqKm: 145 },
  { acNo: 36, population: 77669, totalVoters: 51545, turnout2023: 90.64, maleVoters: 26288, femaleVoters: 25257, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 37, population: 74582, totalVoters: 47761, turnout2023: 90.25, maleVoters: 24549, femaleVoters: 23212, literacy: 88, urbanPercent: 22.1, scPercent: 20.5, stPercent: 32.4, areaSqKm: 124 },
  { acNo: 38, population: 83930, totalVoters: 49809, turnout2023: 91.79, maleVoters: 25004, femaleVoters: 24805, literacy: 83.9, urbanPercent: 20.6, scPercent: 29.1, stPercent: 32.4, areaSqKm: 117 },
  { acNo: 39, population: 69585, totalVoters: 48697, turnout2023: 92.07, maleVoters: 23789, femaleVoters: 24908, literacy: 88, urbanPercent: 38, scPercent: 13, stPercent: 26.4, areaSqKm: 165 },
  { acNo: 40, population: 79595, totalVoters: 49069, turnout2023: 90.63, maleVoters: 24265, femaleVoters: 24804, literacy: 95.3, urbanPercent: 4.6, scPercent: 12, stPercent: 30, areaSqKm: 53 },
  { acNo: 41, population: 73922, totalVoters: 42905, turnout2023: 87.97, maleVoters: 21645, femaleVoters: 21260, literacy: 82.8, urbanPercent: 25, scPercent: 27.8, stPercent: 28.1, areaSqKm: 132 },
  { acNo: 42, population: 80597, totalVoters: 44975, turnout2023: 90.48, maleVoters: 22307, femaleVoters: 22668, literacy: 85.9, urbanPercent: 27.9, scPercent: 18.6, stPercent: 28.1, areaSqKm: 117 },
  { acNo: 43, population: 85783, totalVoters: 41408, turnout2023: 89.57, maleVoters: 21097, femaleVoters: 20311, literacy: 93.2, urbanPercent: 35.1, scPercent: 17.7, stPercent: 41.2, areaSqKm: 162 },
  { acNo: 44, population: 62739, totalVoters: 53942, turnout2023: 87.86, maleVoters: 26351, femaleVoters: 27591, literacy: 92.2, urbanPercent: 43.8, scPercent: 16.8, stPercent: 41.2, areaSqKm: 155 },
  { acNo: 45, population: 69305, totalVoters: 47056, turnout2023: 86.06, maleVoters: 23481, femaleVoters: 23575, literacy: 89, urbanPercent: 22.1, scPercent: 21.5, stPercent: 32.4, areaSqKm: 120 },
  { acNo: 46, population: 75970, totalVoters: 49613, turnout2023: 86.6, maleVoters: 24112, femaleVoters: 25501, literacy: 91.1, urbanPercent: 22.1, scPercent: 30.4, stPercent: 21.3, areaSqKm: 202 },
  { acNo: 47, population: 72570, totalVoters: 52533, turnout2023: 87.65, maleVoters: 27028, femaleVoters: 25505, literacy: 81.8, urbanPercent: 26.4, scPercent: 26.4, stPercent: 28.1, areaSqKm: 145 },
  { acNo: 48, population: 77669, totalVoters: 44207, turnout2023: 87.93, maleVoters: 22546, femaleVoters: 21661, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 49, population: 77669, totalVoters: 45847, turnout2023: 86.75, maleVoters: 23382, femaleVoters: 22465, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 50, population: 77669, totalVoters: 50140, turnout2023: 87.66, maleVoters: 25571, femaleVoters: 24569, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 51, population: 83826, totalVoters: 44787, turnout2023: 87.46, maleVoters: 22909, femaleVoters: 21878, literacy: 81.8, urbanPercent: 27.9, scPercent: 14.9, stPercent: 32.4, areaSqKm: 141 },
  { acNo: 52, population: 96826, totalVoters: 47358, turnout2023: 86.07, maleVoters: 23324, femaleVoters: 24034, literacy: 82.8, urbanPercent: 23.5, scPercent: 27.8, stPercent: 32.4, areaSqKm: 118 },
  { acNo: 53, population: 77669, totalVoters: 52040, turnout2023: 81.54, maleVoters: 26540, femaleVoters: 25500, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 54, population: 77527, totalVoters: 47619, turnout2023: 84.65, maleVoters: 24405, femaleVoters: 23214, literacy: 85.9, urbanPercent: 27.9, scPercent: 18.6, stPercent: 32.4, areaSqKm: 125 },
  { acNo: 55, population: 76976, totalVoters: 47965, turnout2023: 83.14, maleVoters: 24126, femaleVoters: 23839, literacy: 80.7, urbanPercent: 20.6, scPercent: 13.9, stPercent: 28.1, areaSqKm: 133 },
  { acNo: 56, population: 84286, totalVoters: 45310, turnout2023: 83.56, maleVoters: 22247, femaleVoters: 23063, literacy: 80.7, urbanPercent: 19.2, scPercent: 13.9, stPercent: 49, areaSqKm: 120 },
  { acNo: 57, population: 69089, totalVoters: 45331, turnout2023: 86.76, maleVoters: 22303, femaleVoters: 23028, literacy: 84.9, urbanPercent: 19.2, scPercent: 17.7, stPercent: 32.4, areaSqKm: 139 },
  { acNo: 58, population: 77669, totalVoters: 45278, turnout2023: 83.58, maleVoters: 23092, femaleVoters: 22186, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 59, population: 77669, totalVoters: 46373, turnout2023: 84.27, maleVoters: 23650, femaleVoters: 22723, literacy: 87.7, urbanPercent: 26.2, scPercent: 17.8, stPercent: 31.8, areaSqKm: 147 },
  { acNo: 60, population: 73634, totalVoters: 52075, turnout2023: 81.22, maleVoters: 25465, femaleVoters: 26610, literacy: 80.7, urbanPercent: 20.6, scPercent: 13.9, stPercent: 32.4, areaSqKm: 141 },
];

export function getTRConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return TR_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
