/**
 * Uttarakhand Assembly Constituencies — 2022 General Election (70 seats)
 *
 * SOURCE: TCPD "Lok Dhaba" (Trivedi Centre for Political Data, Ashoka University),
 *         Uttarakhand_AE dataset — ECI-sourced constituency results. Uses the
 *         official ECI AC numbering (1-70). Winner/runner-up parties,
 *         vote counts, and margins are the ECI 2022 results as compiled by TCPD.
 *         Reservation (GEN/SC/ST) and district are from the same dataset.
 *         Auto-generated by scripts/build-tcpd-seed.mjs — do not hand-edit.
 *
 * PARTY TALLY 2022: BJP 47 | INC 19 | IND 2 | BSP 2 = 70
 */

export interface UKConstituencySeed {
  acNo: number;
  name: string;
  /** Constituency name in local script */
  localName?: string;
  district: string;
  type: 'GEN' | 'SC' | 'ST';
  winner2022: string;
  winnerName2022: string;
  winnerVotes2022: number;
  runnerUp2022: string;
  margin2022: number;
  currentParty: string;
}

export const UK_CONSTITUENCIES: UKConstituencySeed[] = [
  { acNo: 1, name: 'Purola', localName: 'पुरोला', district: 'Uttarkashi', type: 'SC', winner2022: 'BJP', winnerName2022: 'Durgeshwar Lal', winnerVotes2022: 27856, runnerUp2022: 'INC', margin2022: 6296, currentParty: 'BJP' },
  { acNo: 2, name: 'Yamunotri', localName: 'यमुनोत्री', district: 'Uttarkashi', type: 'GEN', winner2022: 'IND', winnerName2022: 'Sanjay Dobhal', winnerVotes2022: 22952, runnerUp2022: 'INC', margin2022: 6639, currentParty: 'IND' },
  { acNo: 3, name: 'Gangotri', localName: 'गंगोत्री', district: 'Uttarkashi', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Suresh Singh Chauhan', winnerVotes2022: 29619, runnerUp2022: 'INC', margin2022: 8029, currentParty: 'BJP' },
  { acNo: 4, name: 'Badrinath', localName: 'बद्रीनाथ', district: 'Chamoli', type: 'GEN', winner2022: 'INC', winnerName2022: 'Rajendra Singh Bhandari', winnerVotes2022: 32661, runnerUp2022: 'BJP', margin2022: 2066, currentParty: 'INC' },
  { acNo: 5, name: 'Tharali', localName: 'थराली', district: 'Chamoli', type: 'SC', winner2022: 'BJP', winnerName2022: 'Bhupal Ram Tamta', winnerVotes2022: 32852, runnerUp2022: 'INC', margin2022: 8302, currentParty: 'BJP' },
  { acNo: 6, name: 'Karnprayag', district: 'Chamoli', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Anil Nautiyal', winnerVotes2022: 28911, runnerUp2022: 'INC', margin2022: 6715, currentParty: 'BJP' },
  { acNo: 7, name: 'Kedarnath', localName: 'केदारनाथ', district: 'Rudraprayag', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Shaila Rani Rawat', winnerVotes2022: 21886, runnerUp2022: 'IND', margin2022: 8463, currentParty: 'BJP' },
  { acNo: 8, name: 'Rudraprayag', localName: 'रुद्रप्रयाग', district: 'Rudraprayag', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Bharat Singh Chaudhary', winnerVotes2022: 29660, runnerUp2022: 'INC', margin2022: 9802, currentParty: 'BJP' },
  { acNo: 9, name: 'Ghanshali', localName: 'घनसाली', district: 'Tehri Garhwal', type: 'SC', winner2022: 'BJP', winnerName2022: 'Shakti Lal Shah', winnerVotes2022: 20949, runnerUp2022: 'INC', margin2022: 10285, currentParty: 'BJP' },
  { acNo: 10, name: 'Deoprayag', district: 'Tehri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Vinod Kandari', winnerVotes2022: 17330, runnerUp2022: 'UKD', margin2022: 2588, currentParty: 'BJP' },
  { acNo: 11, name: 'Narendranagar', localName: 'नरेन्द्रनगर', district: 'Tehri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Subodh Uniyal', winnerVotes2022: 27430, runnerUp2022: 'INC', margin2022: 1798, currentParty: 'BJP' },
  { acNo: 12, name: 'Pratapnagar', localName: 'प्रतापनगर', district: 'Tehri Garhwal', type: 'GEN', winner2022: 'INC', winnerName2022: 'Vikram Singh Negi', winnerVotes2022: 19131, runnerUp2022: 'BJP', margin2022: 2341, currentParty: 'INC' },
  { acNo: 13, name: 'Tehri', localName: 'टिहरी', district: 'Tehri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Kishore Upadhyay', winnerVotes2022: 19802, runnerUp2022: 'UJP', margin2022: 951, currentParty: 'BJP' },
  { acNo: 14, name: 'Dhanolti', localName: 'धनौल्टी', district: 'Tehri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Pritam Singh Panwar', winnerVotes2022: 22827, runnerUp2022: 'INC', margin2022: 4684, currentParty: 'BJP' },
  { acNo: 15, name: 'Chakrata', localName: 'चकराता', district: 'Dehradun', type: 'ST', winner2022: 'INC', winnerName2022: 'Pritam Singh', winnerVotes2022: 36853, runnerUp2022: 'BJP', margin2022: 9436, currentParty: 'INC' },
  { acNo: 16, name: 'Vikasnagar', localName: 'विकासनगर', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Munna Singh Chauhan', winnerVotes2022: 40819, runnerUp2022: 'INC', margin2022: 5193, currentParty: 'BJP' },
  { acNo: 17, name: 'Sahaspur', localName: 'सहसपुर', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Sahdev Singh Pundir', winnerVotes2022: 64008, runnerUp2022: 'INC', margin2022: 8355, currentParty: 'BJP' },
  { acNo: 18, name: 'Dharampur', localName: 'धरमपुर', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Vinod Chamoli', winnerVotes2022: 58538, runnerUp2022: 'INC', margin2022: 10090, currentParty: 'BJP' },
  { acNo: 19, name: 'Raipur', localName: 'रायपुर', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Umesh Sharma Kau', winnerVotes2022: 65756, runnerUp2022: 'INC', margin2022: 30052, currentParty: 'BJP' },
  { acNo: 20, name: 'Rajpur Road', district: 'Dehradun', type: 'SC', winner2022: 'BJP', winnerName2022: 'Khajan Dass', winnerVotes2022: 37027, runnerUp2022: 'INC', margin2022: 11163, currentParty: 'BJP' },
  { acNo: 21, name: 'Dehradun Cantt.', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Savita Kapoor', winnerVotes2022: 45492, runnerUp2022: 'INC', margin2022: 20938, currentParty: 'BJP' },
  { acNo: 22, name: 'Mussoorie', localName: 'मसूरी', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Ganesh Joshi', winnerVotes2022: 44847, runnerUp2022: 'INC', margin2022: 15325, currentParty: 'BJP' },
  { acNo: 23, name: 'Doiwala', localName: 'डोईवाला', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Brij Bhushan Gairola', winnerVotes2022: 64946, runnerUp2022: 'INC', margin2022: 29021, currentParty: 'BJP' },
  { acNo: 24, name: 'Rishikesh', localName: 'ऋषिकेश', district: 'Dehradun', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Prem Chand Aggarwal', winnerVotes2022: 52460, runnerUp2022: 'INC', margin2022: 19057, currentParty: 'BJP' },
  { acNo: 25, name: 'Hardwar', district: 'Haridwar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Madan Kaushik', winnerVotes2022: 53147, runnerUp2022: 'INC', margin2022: 15237, currentParty: 'BJP' },
  { acNo: 26, name: 'B.H.E.L. Ranipur', localName: 'भेल रानीपुर', district: 'Haridwar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Adesh Chauhan', winnerVotes2022: 57544, runnerUp2022: 'INC', margin2022: 13862, currentParty: 'BJP' },
  { acNo: 27, name: 'Jwalapur', localName: 'ज्वालापुर', district: 'Haridwar', type: 'SC', winner2022: 'INC', winnerName2022: 'Er. Ravi Bahadur', winnerVotes2022: 42372, runnerUp2022: 'BJP', margin2022: 13343, currentParty: 'INC' },
  { acNo: 28, name: 'Bhagwanpur', localName: 'भगवानपुर', district: 'Haridwar', type: 'SC', winner2022: 'INC', winnerName2022: 'Mamta Rakesh', winnerVotes2022: 44808, runnerUp2022: 'BSP', margin2022: 4811, currentParty: 'INC' },
  { acNo: 29, name: 'Jhabrera', localName: 'झबरेड़ा', district: 'Haridwar', type: 'SC', winner2022: 'INC', winnerName2022: 'Virendra Kumar', winnerVotes2022: 39652, runnerUp2022: 'BJP', margin2022: 8216, currentParty: 'INC' },
  { acNo: 30, name: 'Pirankaliyar', localName: 'पिरान कलियर', district: 'Haridwar', type: 'GEN', winner2022: 'INC', winnerName2022: 'Furkan Ahmad', winnerVotes2022: 43539, runnerUp2022: 'BJP', margin2022: 15743, currentParty: 'INC' },
  { acNo: 31, name: 'Roorkee', localName: 'रुड़की', district: 'Haridwar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Pradeep Batra', winnerVotes2022: 36986, runnerUp2022: 'INC', margin2022: 2277, currentParty: 'BJP' },
  { acNo: 32, name: 'Khanpur', localName: 'खानपुर', district: 'Haridwar', type: 'GEN', winner2022: 'IND', winnerName2022: 'Umesh Kumar', winnerVotes2022: 38767, runnerUp2022: 'BSP', margin2022: 6852, currentParty: 'IND' },
  { acNo: 33, name: 'Manglore', localName: 'मंगलौर', district: 'Haridwar', type: 'GEN', winner2022: 'BSP', winnerName2022: 'Sarwat Kareem Ansari', winnerVotes2022: 32660, runnerUp2022: 'INC', margin2022: 598, currentParty: 'BSP' },
  { acNo: 34, name: 'Laksar', localName: 'लक्सर', district: 'Haridwar', type: 'GEN', winner2022: 'BSP', winnerName2022: 'Shahzad', winnerVotes2022: 34899, runnerUp2022: 'BJP', margin2022: 10440, currentParty: 'BSP' },
  { acNo: 35, name: 'Hardwar Rural', district: 'Haridwar', type: 'GEN', winner2022: 'INC', winnerName2022: 'Anupama Rawat', winnerVotes2022: 50028, runnerUp2022: 'BJP', margin2022: 4472, currentParty: 'INC' },
  { acNo: 36, name: 'Yamkeshwar', localName: 'यमकेश्वर', district: 'Pauri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Renu Bisht', winnerVotes2022: 28390, runnerUp2022: 'INC', margin2022: 10410, currentParty: 'BJP' },
  { acNo: 37, name: 'Pauri', localName: 'पौड़ी', district: 'Pauri Garhwal', type: 'SC', winner2022: 'BJP', winnerName2022: 'Rajkumar Pori', winnerVotes2022: 25865, runnerUp2022: 'INC', margin2022: 5738, currentParty: 'BJP' },
  { acNo: 38, name: 'Srinagar', localName: 'श्रीनगर', district: 'Pauri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: '(Dr) Dhan Singh Rawat', winnerVotes2022: 29618, runnerUp2022: 'INC', margin2022: 587, currentParty: 'BJP' },
  { acNo: 39, name: 'Chaubattakhal', localName: 'चौबट्टाखाल', district: 'Pauri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Satpal Maharaj', winnerVotes2022: 24927, runnerUp2022: 'INC', margin2022: 11430, currentParty: 'BJP' },
  { acNo: 40, name: 'Lansdowne', localName: 'लैंसडाउन', district: 'Pauri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Daleep Singh Rawat', winnerVotes2022: 24504, runnerUp2022: 'INC', margin2022: 9868, currentParty: 'BJP' },
  { acNo: 41, name: 'Kotdwar', localName: 'कोटद्वार', district: 'Pauri Garhwal', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Ritu Khanduri Bhushan', winnerVotes2022: 32103, runnerUp2022: 'INC', margin2022: 3687, currentParty: 'BJP' },
  { acNo: 42, name: 'Dharchula', localName: 'धारचूला', district: 'Pithoragarh', type: 'GEN', winner2022: 'INC', winnerName2022: 'Harish Singh Dhami', winnerVotes2022: 27007, runnerUp2022: 'BJP', margin2022: 1118, currentParty: 'INC' },
  { acNo: 43, name: 'Didihat', localName: 'डीडीहाट', district: 'Pithoragarh', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Vishan Singh', winnerVotes2022: 20594, runnerUp2022: 'IND', margin2022: 3226, currentParty: 'BJP' },
  { acNo: 44, name: 'Pithoragarh', localName: 'पिथौरागढ़', district: 'Pithoragarh', type: 'GEN', winner2022: 'INC', winnerName2022: 'Mayukh Mahar', winnerVotes2022: 33269, runnerUp2022: 'BJP', margin2022: 6054, currentParty: 'INC' },
  { acNo: 45, name: 'Gangolihat', localName: 'गंगोलीहाट', district: 'Pithoragarh', type: 'SC', winner2022: 'BJP', winnerName2022: 'Fakeer Ram', winnerVotes2022: 32296, runnerUp2022: 'INC', margin2022: 10053, currentParty: 'BJP' },
  { acNo: 46, name: 'Kapkote', localName: 'कपकोट', district: 'Bageshwar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Suresh Gariya', winnerVotes2022: 31275, runnerUp2022: 'INC', margin2022: 4046, currentParty: 'BJP' },
  { acNo: 47, name: 'Bageshwar', localName: 'बागेश्वर', district: 'Bageshwar', type: 'SC', winner2022: 'BJP', winnerName2022: 'Chandan Ram Dass', winnerVotes2022: 32211, runnerUp2022: 'INC', margin2022: 12141, currentParty: 'BJP' },
  { acNo: 48, name: 'Dwarahat', district: 'Almora', type: 'GEN', winner2022: 'INC', winnerName2022: 'Madan Singh Bisht', winnerVotes2022: 17766, runnerUp2022: 'BJP', margin2022: 182, currentParty: 'INC' },
  { acNo: 49, name: 'Salt', localName: 'सल्ट', district: 'Almora', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Mahesh Jeena', winnerVotes2022: 22393, runnerUp2022: 'INC', margin2022: 3688, currentParty: 'BJP' },
  { acNo: 50, name: 'Ranikhet', localName: 'रानीखेत', district: 'Almora', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Pramod Nainwal', winnerVotes2022: 21047, runnerUp2022: 'INC', margin2022: 2584, currentParty: 'BJP' },
  { acNo: 51, name: 'Someshwar', localName: 'सोमेश्वर', district: 'Almora', type: 'SC', winner2022: 'BJP', winnerName2022: 'Rekha Arya', winnerVotes2022: 26161, runnerUp2022: 'INC', margin2022: 5293, currentParty: 'BJP' },
  { acNo: 52, name: 'Almora', localName: 'अल्मोड़ा', district: 'Almora', type: 'GEN', winner2022: 'INC', winnerName2022: 'Manoj Tewari', winnerVotes2022: 24439, runnerUp2022: 'BJP', margin2022: 127, currentParty: 'INC' },
  { acNo: 53, name: 'Jageshwar', localName: 'जागेश्वर', district: 'Almora', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Mohan Singh', winnerVotes2022: 27530, runnerUp2022: 'INC', margin2022: 5883, currentParty: 'BJP' },
  { acNo: 54, name: 'Lohaghat', localName: 'लोहाघाट', district: 'Champawat', type: 'GEN', winner2022: 'INC', winnerName2022: 'Khushal Singh Adhikari', winnerVotes2022: 32950, runnerUp2022: 'BJP', margin2022: 6038, currentParty: 'INC' },
  { acNo: 55, name: 'Champawat', district: 'Champawat', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Kailash Chandra Gahtori', winnerVotes2022: 32547, runnerUp2022: 'INC', margin2022: 5304, currentParty: 'BJP' },
  { acNo: 56, name: 'Lalkuwa', district: 'Nainital', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Dr. Mohan Singh Bisht', winnerVotes2022: 46307, runnerUp2022: 'INC', margin2022: 17527, currentParty: 'BJP' },
  { acNo: 57, name: 'Bhimtal', localName: 'भीमताल', district: 'Nainital', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Ram Singh Kaira', winnerVotes2022: 25632, runnerUp2022: 'INC', margin2022: 9844, currentParty: 'BJP' },
  { acNo: 58, name: 'Nainital', district: 'Nainital', type: 'SC', winner2022: 'BJP', winnerName2022: 'Sarita Arya', winnerVotes2022: 31770, runnerUp2022: 'INC', margin2022: 7881, currentParty: 'BJP' },
  { acNo: 59, name: 'Haldwani', localName: 'हल्द्वानी', district: 'Nainital', type: 'GEN', winner2022: 'INC', winnerName2022: 'Sumit Hridayesh', winnerVotes2022: 50116, runnerUp2022: 'BJP', margin2022: 7814, currentParty: 'INC' },
  { acNo: 60, name: 'Kaladhungi', localName: 'कालाढूँगी', district: 'Nainital', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Banshidhar Bhagat', winnerVotes2022: 67847, runnerUp2022: 'INC', margin2022: 23931, currentParty: 'BJP' },
  { acNo: 61, name: 'Ramnagar', localName: 'रामनगर', district: 'Nainital', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Diwan Singh Bisht', winnerVotes2022: 31094, runnerUp2022: 'INC', margin2022: 4745, currentParty: 'BJP' },
  { acNo: 62, name: 'Jaspur', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'INC', winnerName2022: 'Adesh Singh Chauhan', winnerVotes2022: 42886, runnerUp2022: 'BJP', margin2022: 4172, currentParty: 'INC' },
  { acNo: 63, name: 'Kashipur', localName: 'काशीपुर', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Trilok Singh Cheema', winnerVotes2022: 48508, runnerUp2022: 'INC', margin2022: 16335, currentParty: 'BJP' },
  { acNo: 64, name: 'Bajpur', localName: 'बाजपुर', district: 'Udham Singh Nagar', type: 'SC', winner2022: 'INC', winnerName2022: 'Yashpal Arya', winnerVotes2022: 40252, runnerUp2022: 'BJP', margin2022: 1611, currentParty: 'INC' },
  { acNo: 65, name: 'Gadarpur', localName: 'गदरपुर', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Arvind Pandey', winnerVotes2022: 52841, runnerUp2022: 'INC', margin2022: 1120, currentParty: 'BJP' },
  { acNo: 66, name: 'Rudrapur', localName: 'रुद्रपुर', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Shiv Arora', winnerVotes2022: 60602, runnerUp2022: 'INC', margin2022: 19750, currentParty: 'BJP' },
  { acNo: 67, name: 'Kichha', localName: 'किच्छा', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'INC', winnerName2022: 'Tilak Raj Behar', winnerVotes2022: 49552, runnerUp2022: 'BJP', margin2022: 10077, currentParty: 'INC' },
  { acNo: 68, name: 'Sitarganj', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'BJP', winnerName2022: 'Saurabh Bahuguna', winnerVotes2022: 43354, runnerUp2022: 'INC', margin2022: 10938, currentParty: 'BJP' },
  { acNo: 69, name: 'Nanak Matta', localName: 'नानकमत्ता', district: 'Udham Singh Nagar', type: 'ST', winner2022: 'INC', winnerName2022: 'Gopal Singh Rana', winnerVotes2022: 48746, runnerUp2022: 'BJP', margin2022: 13020, currentParty: 'INC' },
  { acNo: 70, name: 'Khatima', district: 'Udham Singh Nagar', type: 'GEN', winner2022: 'INC', winnerName2022: 'Bhuwan Chandra Kapri', winnerVotes2022: 48177, runnerUp2022: 'BJP', margin2022: 6579, currentParty: 'INC' },
];

export function getUKConstituency(acNo: number): UKConstituencySeed | undefined {
  return UK_CONSTITUENCIES.find((c) => c.acNo === acNo);
}
