/**
 * UK Constituency Demographics — keyed by OFFICIAL ECI acNo.
 *
 * REAL DATA: totalVoters (electorate) and turnout2023 are real ECI/TCPD figures
 *   from the 2022 Assembly election (the latest per-constituency electorate data
 *   available offline). maleVoters/femaleVoters are scaled to the real electorate.
 * ESTIMATES: population, literacy, urbanPercent, scPercent, stPercent, areaSqKm are
 *   Census-2011 district-proportional ESTIMATES (per-AC census not available offline).
 * Auto-generated by scripts/build-demographics.mjs — do not hand-edit.
 */

import type { ConstituencyDemographics } from './telangana-demographics';

export const UK_DEMOGRAPHICS: ConstituencyDemographics[] = [
  { acNo: 1, population: 186142, totalVoters: 75364, turnout2023: 68.51, maleVoters: 37795, femaleVoters: 37569, literacy: 87.3, urbanPercent: 40.6, scPercent: 37.8, stPercent: 2.9, areaSqKm: 643 },
  { acNo: 2, population: 268832, totalVoters: 77770, turnout2023: 67.06, maleVoters: 39585, femaleVoters: 38185, literacy: 77.2, urbanPercent: 53.2, scPercent: 18.4, stPercent: 9.9, areaSqKm: 427 },
  { acNo: 3, population: 272642, totalVoters: 89522, turnout2023: 66.63, maleVoters: 45298, femaleVoters: 44224, literacy: 77.2, urbanPercent: 2.8, scPercent: 18.4, stPercent: 0, areaSqKm: 96 },
  { acNo: 4, population: 137717, totalVoters: 106330, turnout2023: 64.15, maleVoters: 53645, femaleVoters: 52685, literacy: 89.3, urbanPercent: 6.6, scPercent: 14.3, stPercent: 0, areaSqKm: 24 },
  { acNo: 5, population: 264171, totalVoters: 106895, turnout2023: 59.49, maleVoters: 52860, femaleVoters: 54035, literacy: 81.3, urbanPercent: 25.5, scPercent: 13.2, stPercent: 0, areaSqKm: 16 },
  { acNo: 6, population: 196890, totalVoters: 97893, turnout2023: 60.28, maleVoters: 49925, femaleVoters: 47968, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 7, population: 202990, totalVoters: 93376, turnout2023: 65.03, maleVoters: 46968, femaleVoters: 46408, literacy: 80.2, urbanPercent: 49.4, scPercent: 11.2, stPercent: 0, areaSqKm: 574 },
  { acNo: 8, population: 144512, totalVoters: 107017, turnout2023: 59.24, maleVoters: 54418, femaleVoters: 52599, literacy: 74.2, urbanPercent: 4, scPercent: 12.2, stPercent: 0, areaSqKm: 300 },
  { acNo: 9, population: 183239, totalVoters: 100076, turnout2023: 49.73, maleVoters: 49539, femaleVoters: 50537, literacy: 76.2, urbanPercent: 1.3, scPercent: 30.5, stPercent: 0, areaSqKm: 88 },
  { acNo: 10, population: 196890, totalVoters: 88764, turnout2023: 54.07, maleVoters: 45270, femaleVoters: 43494, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 11, population: 139453, totalVoters: 93383, turnout2023: 61.41, maleVoters: 45478, femaleVoters: 47905, literacy: 76.2, urbanPercent: 43.1, scPercent: 21.5, stPercent: 3.9, areaSqKm: 560 },
  { acNo: 12, population: 155452, totalVoters: 86985, turnout2023: 49.23, maleVoters: 42710, femaleVoters: 44275, literacy: 86.3, urbanPercent: 41.9, scPercent: 21.5, stPercent: 2.9, areaSqKm: 517 },
  { acNo: 13, population: 231264, totalVoters: 86668, turnout2023: 54, maleVoters: 43810, femaleVoters: 42858, literacy: 82.3, urbanPercent: 29.2, scPercent: 14.3, stPercent: 0, areaSqKm: 17 },
  { acNo: 14, population: 191625, totalVoters: 86846, turnout2023: 65.35, maleVoters: 42729, femaleVoters: 44117, literacy: 85.3, urbanPercent: 38.1, scPercent: 18.4, stPercent: 5.9, areaSqKm: 639 },
  { acNo: 15, population: 182828, totalVoters: 107574, turnout2023: 67.65, maleVoters: 54486, femaleVoters: 53088, literacy: 76.2, urbanPercent: 25.5, scPercent: 20.5, stPercent: 0.9, areaSqKm: 911 },
  { acNo: 16, population: 182620, totalVoters: 108512, turnout2023: 75.18, maleVoters: 53823, femaleVoters: 54689, literacy: 81.3, urbanPercent: 24.2, scPercent: 13.2, stPercent: 0, areaSqKm: 17 },
  { acNo: 17, population: 148656, totalVoters: 173514, turnout2023: 72.53, maleVoters: 88666, femaleVoters: 84848, literacy: 85.3, urbanPercent: 14.1, scPercent: 11.2, stPercent: 0, areaSqKm: 184 },
  { acNo: 18, population: 215758, totalVoters: 209869, turnout2023: 56.63, maleVoters: 104516, femaleVoters: 105353, literacy: 79.2, urbanPercent: 36.8, scPercent: 12.2, stPercent: 5.9, areaSqKm: 675 },
  { acNo: 19, population: 143191, totalVoters: 179944, turnout2023: 60.75, maleVoters: 87272, femaleVoters: 92672, literacy: 76.2, urbanPercent: 4, scPercent: 14.3, stPercent: 0, areaSqKm: 261 },
  { acNo: 20, population: 196890, totalVoters: 120938, turnout2023: 57.1, maleVoters: 61678, femaleVoters: 59260, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 21, population: 196890, totalVoters: 136405, turnout2023: 56.37, maleVoters: 69567, femaleVoters: 66838, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 22, population: 215507, totalVoters: 133265, turnout2023: 59.57, maleVoters: 65699, femaleVoters: 67566, literacy: 70.2, urbanPercent: 39.3, scPercent: 16.3, stPercent: 3.9, areaSqKm: 731 },
  { acNo: 23, population: 164412, totalVoters: 168173, turnout2023: 67.49, maleVoters: 84001, femaleVoters: 84172, literacy: 72.2, urbanPercent: 6.6, scPercent: 13.2, stPercent: 0, areaSqKm: 111 },
  { acNo: 24, population: 135238, totalVoters: 169175, turnout2023: 61.97, maleVoters: 86110, femaleVoters: 83065, literacy: 69.2, urbanPercent: 1.3, scPercent: 16, stPercent: 0, areaSqKm: 242 },
  { acNo: 25, population: 196890, totalVoters: 148889, turnout2023: 64.37, maleVoters: 75933, femaleVoters: 72956, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 26, population: 121156, totalVoters: 166352, turnout2023: 68.35, maleVoters: 85670, femaleVoters: 80682, literacy: 87.3, urbanPercent: 1.3, scPercent: 12.2, stPercent: 0, areaSqKm: 24 },
  { acNo: 27, population: 252048, totalVoters: 117488, turnout2023: 78.95, maleVoters: 59214, femaleVoters: 58274, literacy: 80.2, urbanPercent: 49.4, scPercent: 11.2, stPercent: 0, areaSqKm: 554 },
  { acNo: 28, population: 222499, totalVoters: 123927, turnout2023: 79.71, maleVoters: 60415, femaleVoters: 63512, literacy: 88.3, urbanPercent: 36.8, scPercent: 16.3, stPercent: 0, areaSqKm: 623 },
  { acNo: 29, population: 225589, totalVoters: 122287, turnout2023: 78.04, maleVoters: 61449, femaleVoters: 60838, literacy: 80.2, urbanPercent: 50.7, scPercent: 11.2, stPercent: 0, areaSqKm: 525 },
  { acNo: 30, population: 179201, totalVoters: 127927, turnout2023: 77.07, maleVoters: 62428, femaleVoters: 65499, literacy: 76.2, urbanPercent: 40.6, scPercent: 21.5, stPercent: 3.9, areaSqKm: 631 },
  { acNo: 31, population: 140535, totalVoters: 122722, turnout2023: 62.51, maleVoters: 60686, femaleVoters: 62036, literacy: 74.2, urbanPercent: 5.3, scPercent: 12.2, stPercent: 0, areaSqKm: 299 },
  { acNo: 32, population: 224668, totalVoters: 148281, turnout2023: 76.5, maleVoters: 74808, femaleVoters: 73473, literacy: 80.2, urbanPercent: 48.2, scPercent: 11.2, stPercent: 0, areaSqKm: 468 },
  { acNo: 33, population: 159525, totalVoters: 115966, turnout2023: 75.75, maleVoters: 56359, femaleVoters: 59607, literacy: 72.2, urbanPercent: 43.1, scPercent: 18.4, stPercent: 3.9, areaSqKm: 830 },
  { acNo: 34, population: 199286, totalVoters: 102914, turnout2023: 79.28, maleVoters: 52589, femaleVoters: 50325, literacy: 85.3, urbanPercent: 44.4, scPercent: 16.3, stPercent: 0, areaSqKm: 526 },
  { acNo: 35, population: 196890, totalVoters: 131529, turnout2023: 81.64, maleVoters: 67080, femaleVoters: 64449, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 36, population: 200653, totalVoters: 89876, turnout2023: 53.56, maleVoters: 44084, femaleVoters: 45792, literacy: 84.3, urbanPercent: 45.6, scPercent: 25.7, stPercent: 9.9, areaSqKm: 426 },
  { acNo: 37, population: 159327, totalVoters: 95949, turnout2023: 51.25, maleVoters: 46775, femaleVoters: 49174, literacy: 76.2, urbanPercent: 41.9, scPercent: 21.5, stPercent: 3.9, areaSqKm: 595 },
  { acNo: 38, population: 167948, totalVoters: 109578, turnout2023: 59.34, maleVoters: 55008, femaleVoters: 54570, literacy: 86.3, urbanPercent: 21.7, scPercent: 32, stPercent: 0, areaSqKm: 17 },
  { acNo: 39, population: 224171, totalVoters: 94284, turnout2023: 45.02, maleVoters: 48415, femaleVoters: 45869, literacy: 83.3, urbanPercent: 39.3, scPercent: 29.1, stPercent: 4.9, areaSqKm: 685 },
  { acNo: 40, population: 176250, totalVoters: 86698, turnout2023: 47.76, maleVoters: 43392, femaleVoters: 43306, literacy: 74.2, urbanPercent: 45.6, scPercent: 34.9, stPercent: 3.9, areaSqKm: 578 },
  { acNo: 41, population: 210409, totalVoters: 117808, turnout2023: 65.53, maleVoters: 60024, femaleVoters: 57784, literacy: 85.3, urbanPercent: 45.6, scPercent: 16.3, stPercent: 0, areaSqKm: 498 },
  { acNo: 42, population: 174394, totalVoters: 90351, turnout2023: 62.34, maleVoters: 45718, femaleVoters: 44633, literacy: 78.2, urbanPercent: 35.6, scPercent: 11.2, stPercent: 5.9, areaSqKm: 677 },
  { acNo: 43, population: 162991, totalVoters: 86048, turnout2023: 63.5, maleVoters: 42680, femaleVoters: 43368, literacy: 76.2, urbanPercent: 1.3, scPercent: 17.4, stPercent: 18, areaSqKm: 111 },
  { acNo: 44, population: 160188, totalVoters: 114213, turnout2023: 61.35, maleVoters: 55793, femaleVoters: 58420, literacy: 76.2, urbanPercent: 48.2, scPercent: 36.3, stPercent: 3.9, areaSqKm: 466 },
  { acNo: 45, population: 317983, totalVoters: 105724, turnout2023: 54.89, maleVoters: 53126, femaleVoters: 52598, literacy: 72.2, urbanPercent: 4, scPercent: 13.2, stPercent: 0, areaSqKm: 96 },
  { acNo: 46, population: 187768, totalVoters: 102598, turnout2023: 62.43, maleVoters: 52222, femaleVoters: 50376, literacy: 85.3, urbanPercent: 46.9, scPercent: 29.1, stPercent: 0, areaSqKm: 449 },
  { acNo: 47, population: 218911, totalVoters: 122854, turnout2023: 60.78, maleVoters: 59830, femaleVoters: 63024, literacy: 77.2, urbanPercent: 50.7, scPercent: 18.4, stPercent: 9.9, areaSqKm: 407 },
  { acNo: 48, population: 196890, totalVoters: 94506, turnout2023: 51.95, maleVoters: 48198, femaleVoters: 46308, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 49, population: 182438, totalVoters: 99036, turnout2023: 45.54, maleVoters: 49419, femaleVoters: 49617, literacy: 86.3, urbanPercent: 24.2, scPercent: 18.4, stPercent: 0, areaSqKm: 15 },
  { acNo: 50, population: 129963, totalVoters: 82345, turnout2023: 51.07, maleVoters: 40761, femaleVoters: 41584, literacy: 69.2, urbanPercent: 1.3, scPercent: 7, stPercent: 0, areaSqKm: 241 },
  { acNo: 51, population: 154226, totalVoters: 89257, turnout2023: 56.27, maleVoters: 44674, femaleVoters: 44583, literacy: 86.3, urbanPercent: 22.9, scPercent: 18.4, stPercent: 0, areaSqKm: 16 },
  { acNo: 52, population: 149542, totalVoters: 92753, turnout2023: 58.68, maleVoters: 45728, femaleVoters: 47025, literacy: 89.3, urbanPercent: 1.3, scPercent: 26.2, stPercent: 0, areaSqKm: 26 },
  { acNo: 53, population: 256326, totalVoters: 95378, turnout2023: 55.46, maleVoters: 47975, femaleVoters: 47403, literacy: 72.2, urbanPercent: 2.8, scPercent: 13.2, stPercent: 0, areaSqKm: 105 },
  { acNo: 54, population: 199673, totalVoters: 109772, turnout2023: 58.12, maleVoters: 55820, femaleVoters: 53952, literacy: 73.2, urbanPercent: 44.4, scPercent: 19.4, stPercent: 3.9, areaSqKm: 580 },
  { acNo: 55, population: 196890, totalVoters: 98113, turnout2023: 66, maleVoters: 50038, femaleVoters: 48075, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 56, population: 196890, totalVoters: 120409, turnout2023: 72.25, maleVoters: 61409, femaleVoters: 59000, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 57, population: 225004, totalVoters: 101789, turnout2023: 65.09, maleVoters: 51505, femaleVoters: 50284, literacy: 76.2, urbanPercent: 26.7, scPercent: 20.5, stPercent: 0.9, areaSqKm: 861 },
  { acNo: 58, population: 196890, totalVoters: 110846, turnout2023: 54.92, maleVoters: 56531, femaleVoters: 54315, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 59, population: 206674, totalVoters: 152634, turnout2023: 65.43, maleVoters: 75784, femaleVoters: 76850, literacy: 76.2, urbanPercent: 6.6, scPercent: 17.4, stPercent: 0, areaSqKm: 94 },
  { acNo: 60, population: 203855, totalVoters: 174353, turnout2023: 67.86, maleVoters: 88484, femaleVoters: 85869, literacy: 85.3, urbanPercent: 48.2, scPercent: 29.1, stPercent: 0, areaSqKm: 556 },
  { acNo: 61, population: 150055, totalVoters: 120529, turnout2023: 68.91, maleVoters: 60144, femaleVoters: 60385, literacy: 76.2, urbanPercent: 2.8, scPercent: 14.3, stPercent: 0, areaSqKm: 262 },
  { acNo: 62, population: 196890, totalVoters: 132431, turnout2023: 73.92, maleVoters: 67540, femaleVoters: 64891, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 63, population: 193829, totalVoters: 177429, turnout2023: 63.89, maleVoters: 88980, femaleVoters: 88449, literacy: 80.2, urbanPercent: 50.7, scPercent: 11.2, stPercent: 0, areaSqKm: 545 },
  { acNo: 64, population: 196474, totalVoters: 152581, turnout2023: 71.77, maleVoters: 77512, femaleVoters: 75069, literacy: 88.3, urbanPercent: 38.1, scPercent: 29.1, stPercent: 0, areaSqKm: 658 },
  { acNo: 65, population: 262900, totalVoters: 144481, turnout2023: 75.42, maleVoters: 72384, femaleVoters: 72097, literacy: 72.2, urbanPercent: 5.3, scPercent: 13.2, stPercent: 0, areaSqKm: 90 },
  { acNo: 66, population: 166321, totalVoters: 195621, turnout2023: 67.81, maleVoters: 98299, femaleVoters: 97322, literacy: 80.2, urbanPercent: 15.4, scPercent: 6, stPercent: 0, areaSqKm: 183 },
  { acNo: 67, population: 187697, totalVoters: 140830, turnout2023: 71.07, maleVoters: 71542, femaleVoters: 69288, literacy: 85.3, urbanPercent: 46.9, scPercent: 16.3, stPercent: 0, areaSqKm: 469 },
  { acNo: 68, population: 196890, totalVoters: 123384, turnout2023: 78.42, maleVoters: 62926, femaleVoters: 60458, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
  { acNo: 69, population: 178497, totalVoters: 124627, turnout2023: 73.88, maleVoters: 62189, femaleVoters: 62438, literacy: 73.2, urbanPercent: 38.1, scPercent: 19.4, stPercent: 3.9, areaSqKm: 773 },
  { acNo: 70, population: 196890, totalVoters: 121978, turnout2023: 76.12, maleVoters: 62209, femaleVoters: 59769, literacy: 79.6, urbanPercent: 30.2, scPercent: 18.8, stPercent: 2.8, areaSqKm: 396 },
];

export function getUKConstituencyDemographics(acNo: number): ConstituencyDemographics | undefined {
  return UK_DEMOGRAPHICS.find((d) => d.acNo === acNo);
}
