/**
 * UK — Election History Summary (party seat tallies per Assembly election).
 * Auto-generated by scripts/build-election-history.mjs from the authoritative seed
 * (TCPD/ECI). Totals match the constituency map exactly.
 */

export interface UKElectionResult {
  year: number;
  partyResults: Record<string, number>;
  totalSeats: number;
  rulingParty: string;
}

export const UK_ELECTION_HISTORY: UKElectionResult[] = [
  {
    year: 2022,
    partyResults: {
      'BJP': 47,
      'INC': 19,
      'IND': 2,
      'BSP': 2,
    },
    totalSeats: 70,
    rulingParty: 'BJP',
  },
];

export function getUKElectionByYear(year: number) {
  return UK_ELECTION_HISTORY.find((e) => e.year === year);
}

export function getUKPartyTrend(party: string) {
  return UK_ELECTION_HISTORY.map((e) => ({ year: e.year, seats: e.partyResults[party] || 0 }));
}
